### ISSUE TITLE
Uncaught TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by shadyb** [tulios/kafkajs#1000]
I have used browserify to enable me to use this module in Firefox.

When utilising it in my extension I get the exception in the title of this report. A quick look at the code and the culprit seems to be the following line of code:

File: kafkajs/src/errors.js
line:6
`Error.captureStackTrace(this, this.constructor)`

It appears firefox does not recognise the function, although having dug around the MDN it looks like there is a reference to it, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error 
There are no docs for it however, so one can only assume it's still in the works.

I think a quick fix would be to check whether the function is defined before using it to avert this issue, something like:

```
if (Error.captureStackTrace !== undefined) {
   Error.captureStackTrace(this, this.constructor);
}
```
Let me know whether it's viable fix or might pose other problems.

**Comment by Nevon** [comment]
KafkaJS is a NodeJS library that will not work in a browser context. Even if you browserify it, there's no way to have raw TCP sockets in a browser, which would be required for KafkaJS to work. See for example #36.
