### ISSUE TITLE
download compiled kafkajs 

### ISSUE THREAD

**Issue by vaskovasilev** [tulios/kafkajs#1003]
Hello dear all, 
I want to ask if I can use kafkajs from a website, not from node?
Is there any compiled, minified version of the kafkajs admin?

thank you !

**Comment by ankon** [comment]
KafkaJS will not work in a browser, see https://kafka.js.org/docs/next/faq#can-kafkajs-be-used-in-a-browser

**Comment by ankon** [comment]
You will have to do your Kafka interaction (topic consumption, producing messages, admin functions) on your backend, and expose a suitable API towards your frontend. If I understand correctly you have a PHP backend with some Java code -- so it probably would be best to find a Kafka client for either of those. Given that Kafka itself comes with a Java client, I would suggest you start there.
