### ISSUE TITLE
How can I check if the consumer group is initialised? 

### ISSUE THREAD

**Issue by lzhuor** [tulios/kafkajs#1006]
Hi folks,

I would like to perform a certain action when Consumer group is not initialized. Which function/variable could I use to obtain such information?

**Comment by Nevon** [comment]
I don't understand your question. What do you mean by a consumer group not being initialized? Could you show an example to show what you want to achieve and how you are trying to achieve it?

**Comment by lzhuor** [comment]
Hi @Nevon ,

After we invoke `consumer.disconnect()`, if we try to invoke `consumer.resume()`, Kafkajs will throw an error `KafkaJSNonRetriableError: Consumer group was not initialized, consumer#run must be called first`.

Therefore, I would like to find a way to check if I can check if the consumer is initialised before calling `consumer.resume`.

**Comment by tulios** [comment]
@lzhuor you are not using `resume` and `disconnect` in the right way, from what I can see you want to pause and resume the consumer, not disconnect and resume. When calling disconnect you shutdown the consumer completely, so you would have to initialize it again subscribing to topics, calling `consumer.run`, etc.

**Comment by lzhuor** [comment]
Thanks @tulios . Nope, I clearly understand the difference between `resume`, `pause` and `disconnect`  and I am using them in the right way.

I am asking if there is a way to check if a consumer has been `disconnected` or not for my usage.

**Comment by tulios** [comment]
@lzhuor there is no such param in place as of now, but you can keep track of that on your side by listening to the `DISCONNECT` instrumentation event
