### ISSUE TITLE
messageProducer.js error

### ISSUE THREAD

**Issue by zhengrz** [tulios/kafkajs#1007]
**Describe the bug**
Normal connection, abnormal sending message, error:
KafkaJSNonRetriableError: Invalid message without value for topic "demo": -1

**Expected behavior**
Normal sending message

**Environment:**
 - OS: [ Mac OS 10.15.3]
 - KafkaJS version [1.15.0]
 - Kafka version [2.7.0]
 - NodeJS version [10.23.0]

**Comment by zhengrz** [comment]
const messageWithoutValue = messages.find(message => message.value === undefined)

**Comment by tulios** [comment]
@zhengrz, can you add more context to the issue? Maybe add a snippet of the code you are using
