### ISSUE TITLE
Is it possible to search a kafka topic given a query ?

### ISSUE THREAD

**Issue by valavanisleonidas** [tulios/kafkajs#1018]
Hey,

I have a kafka topic where I store a JSON object. I would like to search for all the objects with a specific property in the topic. Is it possible using KafkaJS ?

thanks

**Comment by ankon** [comment]
It is "possible", in the sense that could get the data, and then "search" through it.

But there is no "kafka.search('myPropertyValue')" functionality, and that is out of the scope for KafkaJS as a Kafka client library.

**Comment by valavanisleonidas** [comment]
ok thanks for the answer
