### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

### ISSUE THREAD

**Issue by mkj-git** [tulios/kafkajs#1019]
I am using 

 ```
 producer.send({
                topic: 'test-channel-data-topic',
                messages: [
                  { value: new Buffer.from(data.body, "utf-8")}
                ],
              });  
```

`data.body` is like `{"msg":"Hello !!"}`

I am getting following error:

`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object`

**Comment by Nevon** [comment]
Well, exactly like the error says, `Buffer.from` expects a string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object, but you gave it an Object.

Probably what you meant to do was `Buffer.from(JSON.stringify(data.body))`.

Note that you're also using the `new` keyword on something that's not a constructor. It's just `Buffer.from()`, not `new Buffer.from()`.

**Comment by tulios** [comment]
@mkj-git you can also just just send the string `JSON.stringify(data.body)`, kafkajs will make the conversion for you.

**Comment by mkj-git** [comment]
{ value: Buffer.from(JSON.stringify(data.body))}

solved it

**Comment by Gatvik** [comment]
The name of the directory where my project was located contained parentheses. I removed them and everything worked.

**Comment by GitAlison** [comment]
you can do to `Buffer.from(await file.arrayBuffer())`
file from FormData
