### ISSUE TITLE
DescribeConfigs v1 response isn't being decoded correctly

### ISSUE THREAD

**Issue by sOfekS** [tulios/kafkajs#1022]
**Describe the bug**
DescribeConfigs v1 response isn't being decoded correctly

**To Reproduce**
Call the DescribeConfigs function for any topic.

**Expected behavior**
isDefault (boolean) was changed from v0 to configSource (Int8) in v1. It's expected to use readInt8() instead of the previous readBoolean().

**Observed behavior**
The v1 response decoding still uses readBoolean() into isDefault, thus causing default configs to have a "isDefault: false" value, and vice versa.

**Environment:**
 - OS: Windows 10 Enterprise v1703
 - KafkaJS version: 1.15.0
 - Kafka version: 2.5.0
 - NodeJS version: 12.14.0

**Comment by Nevon** [comment]
Thanks for reporting the issue. I've put up a PR that should fix it. #1023

**Comment by Nevon** [comment]
A fix for this will be out in 1.16.0-beta.8, which will be out shortly.
