### ISSUE TITLE
Issues reading header

### ISSUE THREAD

**Issue by robertbarron** [tulios/kafkajs#1024]
**Describe the bug**
This might not be a bug but rater a lack of understanding on how to read kafka headers.

**To Reproduce**
Please provide either a link to a:
1.- I am using the eachMessage loop:

`eachMessage: async ({ topic, partition, message }) => {`

2.- Inside the loop  I am able to parse message.value without an issue:
`JSON.parse(message.value);`

3.- But when I try to do the same with message.headers, it gets an error:
`SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)`

4.- I was able to look into the data and the format is something like this:
`
{
    "someKey": {
        "type": "Buffer",
        "data": [131,123123,1313,1231,3123,13]
    },
    "someOtherKey": {
        "type": "Buffer",
        "data": [131,123123,1313,1231,3123,13]
    },
}
`

5.- I tried using something like JSON.parse(message.headers.somekey), but got no luck.

**Expected behavior**
I should be able to get headers object from message as the value from the message, they both have the same format from origin (JSON).

**Environment:**
 - AWS container
 - KafkaJS 1.12.0
 - Kafka 2.2.1]
 - NodeJS 12.x

**Additional context**

Thank you!

**Comment by tulios** [comment]
The header value is a `Buffer`, so you have to convert it to a string if you want to use `JSON.parse`, take a look at the example for more information.

https://github.com/tulios/kafkajs/blob/76ec563efe03d98156132fcb43105d3e693e1e56/examples/consumer.js#L47
