### ISSUE TITLE
What is the default partition number when topic is created by send() and how to change it?

### ISSUE THREAD

**Issue by 300LiterPropofol** [tulios/kafkajs#1028]
Hello,

I am using kafkajs as the producer of my AWS MSK kafka cluster. The topic is created by setting 
`<const producer = kafka.producer({ allowAutoTopicCreation: true });>` in my code 
and 
`<auto.create.topics.enable = true>` in AWS MSK cluster configuration.
So I don't explicitly create a topic but whenever I run
```
const producerRun = async (payloads) => {
    await producer.connect();
    await producer.send({
        topic: kafkaTopic,
        messages: payloads,
    });
    await producer.disconnect();
}
```
kafkaTopic is automatically created on AWS MSK. 
However, I found the topics created in this way only have partition number == 1, what I want to know are:
1. Is the default topic partition number set to 1 in kafkajs?
2. Where can I change this number if I want to create topic using auto way during sending?

Thank you for your help!

**Comment by ankon** [comment]
You would configure that on the broker: https://docs.aws.amazon.com/msk/latest/developerguide/msk-default-configuration.html , look for `num.partitions`.

**Comment by 300LiterPropofol** [comment]
Oh thank you a lot! I kept trying to find ways to do this from kafkajs side. So kafkajs cannot change or override this setting, the corr
ect and only way is to leave it to the MSK side?

**Comment by Nevon** [comment]
Not unless you create the topics from KafkaJS. The configuration property is read-only from the client side, so it's something that has to be updated in the broker configuration if you want to change it.
