### ISSUE TITLE
Two topics subscription should not block each other

### ISSUE THREAD

**Issue by yjhmelody** [tulios/kafkajs#1043]
**Describe the bug**
I subscribe two topics, but the first topic need to wait for the second topic data. So when I get the first topic data, I make it sleep. But I find the second topic cannot be gained from kafka, If the first topic `eachMessage` is blocking. 

**Environment:**
 - OS: Window10
 - KafkaJS version 1.15
 - Kafka version 2.13-2.7.0
 - NodeJS version 15.3.0

**Comment by Nevon** [comment]
That's not really how Kafka works. There's no ordering guarantees between topics, so if you first produce a message to topic A and then one to topic B, you can't expect that it will necessarily be consumed first from topic A and then topic B.

KafkaJS allows you to process multiple partitions in parallel [using partition-aware concurrency](https://kafka.js.org/docs/consuming#a-name-concurrent-processing-a-partition-aware-concurrency), so you can indeed process multiple partitions from different topics in parallel.

**Comment by t-d-d** [comment]
> If the first topic eachMessage is blocking

Yes, if you 'block' then the fetch loop is blocked and no more messaged
will be read.  You will need to find a way to return from eachMessage so
the fetch loop can continue.

You might want to look at kafka-streams and a table*table join.  But that
is Java.  (Or other stream processing solutions.)
