### ISSUE TITLE
Addition of Alter & Describe Client Quotas

### ISSUE THREAD

**Issue by ronfarkash** [tulios/kafkajs#1045]
**Feature Description**
Allow KafkaJS to suppport the DescribeClientQuotas and AlterClientQuotas protocol requests.

**Solution**
Nowadays Kafka version 2.6.0 Admin API supports these two protocol requests:
KIP - https://cwiki.apache.org/confluence/display/KAFKA/KIP-546%3A+Add+Client+Quota+APIs+to+the+Admin+Client
As described, I will add the mentioned protocol requests to KafkaJS and make them accessible throught the admin interface, allowing authenticated users to alter and describe the quotation set to them.

**Additional context**
Just to add a bit of context, I was the person in the Slack channel who successfully developed privately (after a very long research with the help of @Nevon, @tulios and some Kafka developers) the following requests into KafkaJS:

- **DescribeClientQuotas**
- **AlterClientQuotas** 
- DescribeUserScramCredentials*
- AlterUserScramCredentials*

The requests marked by * were added at Kafka version 2.7.0 which supports a very "heavy" change to the way protocol requests work called tag buffers and more size efficient data types.
KIP - https://cwiki.apache.org/confluence/display/KAFKA/KIP-482%3A+The+Kafka+Protocol+should+Support+Optional+Tagged+Fields

I intend to contribute my code to the public repository and save a lot of effort diving into the tag buffer, as this is my first time contributing to any open-source project I have quite a few challenges ahead of me such as: writing code that will be used by many people, writing unit tests, testing with jest using docker and more.

I have already forked the project and started working on the Client Quotas requests, I hope we will have a great time reviewing this together.

Link to my branch: https://github.com/ronfarkash/kafkajs/tree/client_quota_support

**Comment by Nevon** [comment]
> I intend to contribute my code to the public repository and save a lot of effort diving into the tag buffer

That would be great! Thanks for making the effort of upstreaming your changes.

If I could make a request, it would be to see if it would be possible to split your changes into several smaller pull requests (wherever there is a logical split), rather than dropping a single huge pull request. That will make it easier to provide fast feedback.

**Comment by ronfarkash** [comment]
> If I could make a request, it would be to see if it would be possible to split your changes into several smaller pull requests (wherever there is a logical split), rather than dropping a single huge pull request. That will make it easier to provide fast feedback.

Sure, that makes it easier for me as well.
I will start by adding encoder/decoder support & tests for new data types.

> If you have specific feedback on things we should document better for new contributors, please do make a note of them. We haven't really put in a lot of effort in this regard, but you can at least find some stuff under the "Developing KafkaJS" section of the website: https://kafka.js.org/docs/contribution-guide

I will reflect on my work after the first pull and throw some ideas for the contribution guide.

I guess since this issue is no longer relevant  I will close it.
