### ISSUE TITLE
encoder/decoder support for float64 (double), unsigned varint, compact data types (bytes, strings, arrays)

### ISSUE THREAD

**Issue by ronfarkash** [tulios/kafkajs#1048]
**Current State**
New protocol requests/versions require data types that are not supported by the current encoder.js/decoder.js, without these data types the library will be unable to support newer Kafka protocol requests/versions.

**Desired Solution**
Add read/write functions for the following data types using Kafka's protocol guide convention:
https://kafka.apache.org/protocol#protocol_types

- FLOAT_64 (double)
- UNSIGNED_VARINT
  - COMPACT_BYTES
  - COMPACT_STRING
  - COMPACT_ARRAY

Link to relevant KIP for compact data types - https://cwiki.apache.org/confluence/display/KAFKA/KIP-546%3A+Add+Client+Quota+APIs+to+the+Admin+Client

**Comment by Nevon** [comment]
Fixed by #1061
