### ISSUE TITLE
question: Best practices for resetting offsets?

### ISSUE THREAD

**Issue by brianbegy** [tulios/kafkajs#1049]
First off, thanks for taking the initiative and building this.  

I couldn't find a good explanation of what I need to do in the docs:  

Assuming I have a `mytopic` with 3 partitions.  

I start up 5 pods in k8s to process this topic.  The first three pods join `mygroup` and start consuming.  The rest remain idle (correct?).

I deploy my code, let it run for a couple days and discover a bug in a downstream system.  I fix the bug, but now I need to reprocess all messages since Tuesday.  

I can get the topic offsets per partition with the admin client, but I need to actually reset my consumers.  

- If I new up a client and connect a consumer to the topic, can I use `consumer.seek`  to reset all partitions in the group?  
- Does the fact that all partitions already have consumers attached mean anything?  
- Do I need to tell only connected consumers to `seek` on their partition?  

Assuming we get an answer here, I'm happy to open a docs PR if it would help the next person.  

Thanks!

**Comment by t-d-d** [comment]
Yes, you need to do the third option.  seek() will only work on partitions that are assigned to that group member.

In Kafka operations it's quite normal to completely stop consumer groups, use an offsets reset tool and then restart the group. The kafkajs admin client has a [reset function](https://kafka.js.org/docs/admin#a-name-reset-offsets-a-reset-consumer-group-offsets).  Although I think you should be able to get your third option to work if you signal each pod in the group.

>The first three pods join mygroup and start consuming. The rest remain idle (correct?).

They will join the group but won't be assigned any partitions.  On a rebalance (maybe a pod crashes or is terminated by k8s, or another pod is added) then they may be assigned partition(s).

**Comment by brianbegy** [comment]
Thanks for getting back to me.  

We need to tell each consumer to completely stop, then we can issue an administrative reset, right?  so `consumer.stop` right?  

A question:  because we have to communicate with each consumer anyway, why not use pause and seek?  Is there something about administrative reset that's better?

Implementation detail:  What's the best practice for communicating with consumers?  I can't see them directly for network reasons, so is the best some kind of `control topic` approach where I publish a message to each telling it to shut down?  Or should we maintain a list of consumers and their ideal state in redis or something?  

Thanks again for taking up my questions.

**Comment by t-d-d** [comment]
In a k8s environment, we stop the consumer group by deleting the deployment.  Then we reset the group offsets (or just delete the consumer group) and then re-apply the deployment (re-run our deployment.)  This is obviously a privileged and manual operation.

The  ```control topic``` approach should work.  But you need to be aware that each pod would need to receive every message from the control topic, so each would need a separate group id.  If you don't commit offsets and use ```fromBeginning: false``` you would have something similar to using redis pub/sub.

Of course sending a command via kafka or redis you still have to generate and post the command somehow.  This would normally still be a privileged operation.

**Comment by brianbegy** [comment]
I'm leaning towards your first solution: scale the `kafka-sinks` workload to 0 pods.  Wait a minute.  Use an admin api call to tell the admin client to reset the offsets for the group.  

While I like the idea of making this easy, for the moment, resetting offsets on a consumer in production probably is a "don't do this unless you know what you are doing" situation.  Thanks for the suggestions.

**Comment by Nevon** [comment]
I'm going to close this issue, since it seems you have been given some recommendations. Feel free to re-open it if you still have issues.
