### ISSUE TITLE
Consumer.run never reach EachMessage or EachBatch function

### ISSUE THREAD

**Issue by lucho42** [tulios/kafkajs#1059]
Sometimes when I start a Consumer.run(), it never reach eachMessage function().
I add log in every ConsumerEvents and I can see an infinite loop with FETCH_START, FETCH, REQUEST and HEARTBEAT.
Please, do you have an idea why I have this comportment ?

NB : The consumer is initialize with a group-id and the consumer subscribe an existing topic

Thanks for advance for help

**Comment by Nevon** [comment]
It means that there are no messages to process for the assigned partitions. I'm guessing that you produced the messages to the topic and subsequently subscribed your consumers to the topic, which by default means that they will start to consume any messages produced _from that point_. If you want consumers to default to consuming from the earliest available offset instead, subscribe using `fromBeginning: true`: https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning
