### ISSUE TITLE
Error was swallowed by barrier unlockWithError

### ISSUE THREAD

**Issue by thynson** [tulios/kafkajs#1064]
**Describe the bug**
I want to handle uncaught exceptions but found that they are swallowed by kafkajs.

In
https://github.com/tulios/kafkajs/blob/9566ca8afe234e4f34a85a8acf807d1f3b80d2ad/src/consumer/barrier.js#L7
Why `unlockWithError` is not initialized to `reject`?

Meanwhile in runner.js
https://github.com/tulios/kafkajs/blob/9566ca8afe234e4f34a85a8acf807d1f3b80d2ad/src/consumer/runner.js#L363
It's expected that the unlock would throw an exception.

It would be good if the runner provides an exception handler.

**Comment by t-d-d** [comment]
As you point out, the error is still getting thrown, so it isn't swallowed (at least the first error - subsequent errors may get swallowed.)

The consumer does take a retry parameter where you can set a restartOnFailure function (e -> Promise<boolean>)  That maybe what you are looking for.
