### ISSUE TITLE
Rebalancing event emitted at consumer level

### ISSUE THREAD

**Issue by benbirt97** [tulios/kafkajs#1066]
We have an application which is tracking some partition specific metrics including the consumer lag. We currently set this metric by using the offset lag value we get from the batch and tracking the partition as a label. We have an issue where when the application rebalances and the application loses a partition, we will no longer receive any batches for that particular partition and therefore the metric will be stuck at whatever the lag was last set as.

It would be helpful if the consumer emitted an event whenever KafkaJS rebalances so that we can then trigger a reset on our metrics, setting them back to 0. If we received a memberId from the event we could even use describeGroup to work out which partitions we should be tracking and which partitions we shouldn't be after the rebalance.

Happy to make a PR for this to help out! 😄 

(I do realise we can do this other ways such as running describeGroup every few seconds to check if the partitions have changed, but they feel a little dirty when we could just have  an event every time theres a rebalance)

**Comment by benbirt97** [comment]
Closing as above PR has now been merged

**Comment by Nevon** [comment]
This is now available in the pre-release version 1.16.0-beta.12

**Comment by benbirt97** [comment]
Going to look at changing this a little @Nevon. Was messing with it yesterday and it's a little awkward that it happens just before the rebalance happens. Going to see if I can change it to emit the event straight after a rebalance finishes.

For example we reset our metrics as soon as we get the event in our app but then we get a message on the partition straight after the event but just before the rebalance happens, adding the metric back in.

It will also give us the benefit of passing back the member assignment if we do it afterwards which might be useful for people to see what the new partitions are 😁

**Comment by solanoepalacio** [comment]
Hey there! 
So good to see that this feature is on it's way!
With my team we need this really bad.
Any word on when 1.16.0 will be released?
