### ISSUE TITLE
Add instrumentation events for connect/disconnect and consumer stop

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#107]
New proposed events:

`consumer.events.CONNECTED`
`consumer.events.DISCONNECTED`
`consumer.events.STOPPED`

`producer.events.CONNECTED`
`producer.events.DISCONNECTED`

`admin.events.CONNECTED`
`admin.events.DISCONNECTED`

**Comment by Nevon** [comment]
All the existing events are in present tense (`group_join`), so I would align these with that:

`CONNECT`, `DISCONNECT`, `STOP`
