### ISSUE TITLE
kafkajs Retry options on kafkaConfig vs ProducerConfig

### ISSUE THREAD

**Issue by LakhsmiC** [tulios/kafkajs#1073]
hello All

I would like to know if there is any difference between the KafkaConfig interface retry option vs ProducerConfig interface retry options. 

```ts
ProducerConfig {
  createPartitioner?: ICustomPartitioner
  retry?: RetryOptions
  metadataMaxAge?: number
  allowAutoTopicCreation?: boolean
  idempotent?: boolean
  transactionalId?: string
  transactionTimeout?: number
  maxInFlightRequests?: number
}

KafkaConfig {
  brokers: string[]
  ssl?: tls.ConnectionOptions | boolean
  sasl?: SASLOptions
  clientId?: string
  connectionTimeout?: number
  authenticationTimeout?: number
  reauthenticationThreshold?: number
  requestTimeout?: number
  enforceRequestTimeout?: boolean
  retry?: RetryOptions
}
```

On the  kafka producer failure if I give retry options while creating the Kafka connection vs ProducerConfig, will the library re-post the failed request to the kafka brokers again ?

```ts
kafka = await new Kafka({
      brokers: kafkaBrokerList,
        requestTimeout: requestTimeout,
      retry: {
        initialRetryTime: initialRetryTime,
        maxRetryTime: initialMaxRetryTime,
        retries: retries,
      },
```

Or we should provide the retry options as part of the ProducerConfig as shown below:

```ts
  const producerConfiguration: ProducerConfig = {
    metadataMaxAge: metadataMaxAgeTimeout,
    retry: {
        initialRetryTime: initialRetryTime,
        maxRetryTime: initialMaxRetryTime,
        retries: retries,
      },
  };
  producer = await kafka.producer(producerConfiguration );
```
Ack =1 in my code. 

Can you please share your thoughts on the above two retry declarations .

Lakshmi

**Comment by Nevon** [comment]
The type is the same, and the retry options are inherited by the producer when you create it from a client. The reason for the producer taking a retry config is so that you can override the one it inherits from the client:

https://github.com/tulios/kafkajs/blob/d8fd93e7ce8e4675e3bb9b13d7a1e55a1e0f6bbf/src/index.js#L108

This can be useful in case you, for example, have multiple producers that should behave differently.

> On the kafka producer failure if I give retry options while creating the Kafka connection vs ProducerConfig, will the library re-post the failed request to the kafka brokers again ?

Yes, it will retry the operation according to your retry configuration.

**Comment by LakhsmiC** [comment]
Thank you  so much for your quick response Nevon.
