### ISSUE TITLE
Document Typescript usage

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#1080]
**Is your feature request related to a problem? Please describe.**
Our search analytics show that "Typescript" is a common search query in our documentation that yields no results. Since we do support Typescript, we should make sure that at the very least there is some search result that tells you that KafkaJS works with Typescript and shows a minimal example.

**Describe the solution you'd like**

Under the "Examples" section, I'd like to have a page called "Typescript" that shows a small example of initializing the client in Typescript, just to assure people that we provide types.

**Comment by panzerama** [comment]
My team and I have some examples to share. I'll add an example shortly.
