### ISSUE TITLE
Does kafkajs support auto.register.schemas config?

### ISSUE THREAD

**Issue by 300LiterPropofol** [tulios/kafkajs#1081]
Hi!

I am using `kafkajs` and `@kafkajs/confluent-schema-registry` to write a producer which produces messages following AVRO schema to my confluent cloud topic.
However, I found that after I started the producer, the schema will be automatically updated to a newer version, which I don't want.

I know for example in python client there is an option to set `auto.register.schemas=False` in AvroSerialzer config. I wonder is there a similar config feature I can use in kafkajs? If there is, how should I write it? I searched the kafkajs documents and ctrl+F the repo, I couldn't find example pr explanation about this auto.register.schemas config.

Thank you a lot for help!

**Comment by herculesgabriel** [comment]
@300LiterPropofol, did you figure that out? I have the same question!
