### ISSUE TITLE
Long running eachMessage functions

### ISSUE THREAD

**Issue by gbarton** [tulios/kafkajs#1083]
All,
  I have a particular consumer that is performing some compute heavy work that can easily take 10-15 minutes to complete.  I am using await for my call out to complete during that operation.  What is happening is when the op finishes the consumer has been marked bad and rejoins the group and processes the same message over again.

Few questions:
Does the heartbeat get run in its own loop or does my async usage in eachMessage block the heartbeat from running?
Can I set session.timeout.ms for this consumer group to say 20 minutes on the consumer config somehow?  Is this what requestTimeout is, it doesn't feel like that's the right param though.

How should I approach this general pattern?  Have I exceeded what can be done in eachMessage?  If I moved to eachBatch, how would I then await on the op at the same time as send out heartbeats?

Thank you all!

**Comment by Nevon** [comment]
> Does the heartbeat get run in its own loop or does my async usage in eachMessage block the heartbeat from running?

In the `eachMessage` interface the heartbeating happens in between messages. So if processing a single message takes longer than the session timeout, the consumer will never be able to progress.

> Can I set session.timeout.ms for this consumer group to say 20 minutes on the consumer config somehow? 

It's called `sessionTimeout` in KafkaJS (https://kafka.js.org/docs/consuming#a-name-options-a-options), but yes, you could do that. The downside is that it will take 20 minutes before the cluster notices that a consumer has become unhealthy, so recovering from errors can take a very long time. I wouldn't recommend this option.

> If I moved to eachBatch, how would I then await on the op at the same time as send out heartbeats?

You would need to architect your application in such a way that you can continue to heartbeat while processing your message. In the `eachBatch` interface you have access to the `heartbeat` function, so you can call it continuously as long as your consumer is making progress on its work. How you implement this is up to you. A simple `setInterval` will work, but you'll need a way to propagate errors from the heatbeat call back to `eachBatch`, so you can interrupt your ongoing work in case the consumer group needs to rebalance.

**Comment by gbarton** [comment]
Thank you for the reply!  That is the direction I am looking at too.  I did look at the sessionTimeout but you are right, id have a very long window of downtime if one of the consumers in the group went bad.

I'll look to implement some kinda interruptible await, maybe I can start a setInterval in a promise above the work call and let the surrounding try/catch pickup a heartbeat error.  Thanks again for the advice.

**Comment by senseluo** [comment]
> > Does the heartbeat get run in its own loop or does my async usage in eachMessage block the heartbeat from running?
> 
> In the `eachMessage` interface the heartbeating happens in between messages. So if processing a single message takes longer than the session timeout, the consumer will never be able to progress.
> 
> > Can I set session.timeout.ms for this consumer group to say 20 minutes on the consumer config somehow?
> 
> It's called `sessionTimeout` in KafkaJS (https://kafka.js.org/docs/consuming#a-name-options-a-options), but yes, you could do that. The downside is that it will take 20 minutes before the cluster notices that a consumer has become unhealthy, so recovering from errors can take a very long time. I wouldn't recommend this option.
> 
> > If I moved to eachBatch, how would I then await on the op at the same time as send out heartbeats?
> 
> You would need to architect your application in such a way that you can continue to heartbeat while processing your message. In the `eachBatch` interface you have access to the `heartbeat` function, so you can call it continuously as long as your consumer is making progress on its work. How you implement this is up to you. A simple `setInterval` will work, but you'll need a way to propagate errors from the heatbeat call back to `eachBatch`, so you can interrupt your ongoing work in case the consumer group needs to rebalance.

thanks for pointing it out, solved my problem as well~ haha~

**Comment by harshagarwal00** [comment]
i liked this solution using heartbeats...:
https://github.com/tulios/kafkajs/issues/808
