### ISSUE TITLE
Fatal Error FATAL w/ JavaScript heap out of memory

### ISSUE THREAD

**Issue by bschena** [tulios/kafkajs#1085]
Hi Team, 

I have a tricky situation and I was hoping you could give me some pointers:

What would typically be the cause of this? Suppose we had quotas enabled would that have any impact?

The application is connecting to Confluent Cloud, I don't have a lot of logging but see these two messages seem most prominent:

```
Th: / memory leak detected. 11 confluent.cloud:9092-longpolling-ready listeners added to [KafkaClient]. Use emitter.setMaxListeners() to increase limit

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
this.consumerGroup = new kafka.ConsumerGroup({
kafkaHost: kafkaConfigs.kafkaBrokerUrl,
...kafkaConfigs.isConfluent && {
ssl : true,
sslOptions: {
rejectUnauthorized: true
}
},
groupId: kafkaConfigs.groupId,
protocol: ['roundrobin'],
fetchMaxBytes: kafkaConfigs.fetchMaxBytes,
fromOffset: 'earliest',
outOfRangeOffset: 'earliest',
...this.mechanism && this.username && this.password && {
sasl: { mechanism: this.mechanism, username: this.username, password: this.password }
}
}, kafkaConfigs.kafkaTopic);
const kafkaConfigs = {
kafkaBrokerUrl: process.env['KAFKA_BROKER_URL'] || 'localhost:9092',
kafkaTopic: process.env['KAFKA_TOPIC'] || 'XXXX.XXXXX',
kafkaConsumerName: process.env['KAFKA_CONSUMER_NAME'] || 'XXXXXXXX',
kafkaOffsetCollection: process.env['KAFKA_OFFSET_COLLECTION'] || 'kafkaOffset',
autoCommit: true,
autoCommitIntervalMs: 5000,
fetchMaxWaitMs: 100,
fetchMinBytes: 1,
fetchMaxBytes: 10 * 1024 * 1024, // 10 MB,
groupId: process.env['KAFKA_CONSUMER_GROUP'] || 'XXXXXXX',
fromOffset: false,
encoding: 'utf8',
keyEncoding: 'utf8',
connectionTimeout: 8000,
msgQueueMaxSize: parseInt(process.env['KAFKA_MAX_QUEUE_SIZE'] || '4', 10),
maxParallelHandles: parseInt(process.env['KAFKA_MAX_HANDLES'] || '4', 10),
mechanism: process.env['XXXX_KAFKA_SASL_MECHANISM'],
username: process.env['XXXX_KAFKA_SASL_USERNAME'],
password: process.env['XXXX_KAFKA_SASL_PASSWORD'],
isConfluent: getBoolean(process.env.XX_KAFKA_IS_CONFLUENT) || false
};
```

**Comment by AustinHunt** [comment]
Please properly format this.

**Comment by Nevon** [comment]
Since you haven't shared any usage of KafkaJS, it's impossible to say exactly what's wrong, but my suspicion is that you haven't implemented backpressure correctly in your message handler, so your consumer is consuming more messages before it has finished processing the previous ones.

The easiest way to cause this is by not awaiting some asynchronous action within your message processing. In this example, `processAsync` is an asynchronous function that resolves after 30 seconds, but since we aren't awaiting it in the `eachMessage` handler, the `eachMessage` function will resolve very quickly and the consumer will start processing the next message. Over time, the number of messages being processed concurrently will grow until you run out of memory.

```js
const processAsync = value => new Promise((resolve) => {
  setTimeout(() => {
    resolve(value * 2)
  }, 30000)
})

consumer.run({
  eachMessage: async ({ message }) => {
    processAsync(Number(message.value))
  }
})
```

**Comment by danielrhodes** [comment]
@Nevon I'm seeing the same thing, but using your example I am awaiting the the `processAsync` and also awaiting the heartbeat. Node 16.10, super basic local setup (I'm just trying out the library), nothing fancy. I also tried using `eachBatch`, copying the example in the docs and the same thing happens - the memory grows and grows until the process gets killed.

What can I do to help you understand where the leak is?

**Comment by Nevon** [comment]
There are many ways to diagnose a memory leak. If you have some APM available, they usually come with tools that do this automatically for you, but if not, the good old [Three Snapshots Technique](https://docs.google.com/presentation/d/1wUVmf78gG-ra5aOxvTfYdiLkdGaR9OhXRnOlIcEmu2s/pub?start=false&loop=false&delayms=3000&slide=id.g31ec7af_0_58) is a simple way to do it. TL;DR: Take a heap snapshot, do whatever action you think leaks memory, take a second snapshot, repeat the same action, take a third snapshot, then filter for objects that were allocated between snapshot 1 and 2 that are still present in the third snapshot. Chrome's devtools is easy to use for this.
