### ISSUE TITLE
How to gracefully handle process exit/SIGINT/uncaughtException/SIGTERM/etc?

### ISSUE THREAD

**Issue by antoooooooooooonie** [tulios/kafkajs#1091]
Hello!

I currently have this code for handling process exits, to make sure consumers properly disconnect in order for rebalancing to happen quickly afterwards:

```
 ['exit', 'SIGINT', 'SIGUSR1', 'SIGUSR2', 'uncaughtException', 'SIGTERM'].forEach(
    (eventType: NodeJS.Signals) => {
      process.on(eventType, (event: NodeJS.Signals) => {
        callbackify(() => kafka.disconnect())((error) => {
          if (error) {
            process.exit(1);
          }
          process.exit(0);
        });
      });
    },
  );
```

(`callbackify` is just a [NodeJS utility](https://nodejs.org/api/util.html#util_util_callbackify_original) for turning Promises into callbacks, as process.on does not handle async functions)

My main question is, is this the best/idiomatic way to do so? I couldn't find any documentation on this.

**Comment by Nevon** [comment]
This question isn't really KafkaJS specific, but rather a general NodeJS issue. From KafkaJS' perspective, what matters is that you `disconnect` your producers/consumers before shutting down, if possible.

Your solution I would say is as close to idiomatic as there is in NodeJS. You can get some more context here: https://github.com/nodejs/node/discussions/29480

**Comment by antoooooooooooonie** [comment]
Awesome, thanks for the reply @Nevon! Didn't think to broaden my search to NodeJS signalling in general.
