### ISSUE TITLE
Does the consumer api supports `auto.offset.reset`

### ISSUE THREAD

**Issue by krvajal** [tulios/kafkajs#1103]
How can I set this value `auto.offset.reset` https://docs.confluent.io/platform/current/clients/consumer.html#offset-management when consuming events

**Comment by Nevon** [comment]
`auto.offset.reset` is a Java client and/or librdkafka configuration option. The equivalent option in KafkaJS is called `fromBeginning` and [is documented here](https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning).
