### ISSUE TITLE
Re-connect attempt sometimes successfully connects to 127.0.0.1:9092

### ISSUE THREAD

**Issue by woodcockjosh** [tulios/kafkajs#1107]
**Describe the bug**
When client disconnects and re-connects it sometimes tries to connect to 127.0.0.1:9092 instead of the original list of brokers. 

**To Reproduce**
1. Have 2 hosts available
- 127.0.0.1:9092 (with no authentication)
- some-seed-broker:some-port (with no authentication)
2. Connect to an unreliable connection (some-seed-broker:some-port)
3. See that sometimes 127.0.0.1 is used as a seed broker when re-connecting/retrying and a connection is established
4. See that topics from some-seed-broker are somehow copied to the cluster running on 127.0.0.1:9092

**Expected behavior**
It only tries to re-connect to the list of seed brokers. 

**Observed behavior**
When client disconnects and attempts to re-connect it sometimes, about 10% of the time tries to connect to 127.0.0.1:9092 instead of the original list of seed brokers. This is really problematic especially when it succeeds at connecting to 127.0.0.1:9092 when it shouldn't. 

**Environment:**
 - OS: Mac 11.2.3
 - KafkaJS version 1.15.0
 - Kafka version various versions
 - NodeJS version 12.18.3

**Comment by ujjwalbe** [comment]
I'm also having same problem, KafkaJs is trying to connect Localhost instead of specified broker.

**Comment by ujjwalbe** [comment]
Did you found any way how to resolve the issue?

**Comment by illnr** [comment]
I was facing this issue on a NestJS application, but found that my client configuration was incorrect. But I got no error, instead it was trying to connect to localhost...

Another option, it is related to this: https://github.com/tulios/kafkajs/issues/529

**Comment by Nevon** [comment]
I'm going to close this as it is not due to a bug in KafkaJS. The brokers provide the list of addresses to connect to, and that's the only information the client has, other than the static list of brokers provided when you instantiate the client. So in this case, it's either that the client is misconfigured or that the brokers are misconfigured to return localhost as an advertised hostname (as in #529)
