### ISSUE TITLE
Does `partitionsConsumedConcurrently` option really enable parallel processing?

### ISSUE THREAD

**Issue by yossisp** [tulios/kafkajs#1115]
In the [docs](https://kafka.js.org/docs/consuming#a-name-concurrent-processing-a-partition-aware-concurrency) it says:

> Messages in the same partition are still guaranteed to be processed in order, but messages from multiple partitions can be processed at the same time. 

> Given partitionsConsumedConcurrently > 1, you will be able to process multiple batches concurrently.

> Depending on whether or not your workload is CPU bound, it may also not benefit you to set it to a higher number than the number of logical CPU cores.

Although the word "parallel" is not explicitly mentioned in the docs, CPU cores are mentioned which implies truly parallel processing (e.g. OS-level threads/nodejs worker_threads). In addition there's a comment of one of the contributors from one of the [issues](https://github.com/tulios/kafkajs/issues/1043#issuecomment-797314862):

> KafkaJS allows you to process multiple partitions in parallel using partition-aware concurrency, so you can indeed process multiple partitions from different topics in parallel.

I analyzed the kafkajs [file](https://github.com/tulios/kafkajs/blob/d8fd93e7ce8e4675e3bb9b13d7a1e55a1e0f6bbf/src/utils/concurrency.js#L49) responsible for implementing the parallel processing and as far as I understand there's a queue onto which processing requests are pushed (the requests being callbacks). Once the callback is pushed and provided the amount of callbacks in the queue is not greater than `partitionsConsumedConcurrently` the callback is executed and `await`ed.

But it's not really parallel processing as far as I understand because the callbacks are executed on the main thread. So the processing maybe concurrent in the sense that `Promise.all` is concurrent but it's not really parallel (no threads are opened per processing request). 

Am I right that truly parallel processing is not offered by the library?

**Comment by Nevon** [comment]
No, it is not parallel processing. It's concurrent processing, as the name implies. If it says parallel anywhere in the docs, that's a bug. Unless you use worker threads, you don't have the ability to do true parallel processing in node. Worker threads come with a lot of tradeoffs in terms of ergonomics, and unless your workload is CPU bound, you're unlikely to see any performance gains.

**Comment by yossisp** [comment]
As a follow-up question: having `n` partitions on a topic and having `n` consumers subscribed to the topic (within the same consumer group) and given that consumers work is CPU bound, this setup will not result in performance improvement in a single-threaded environment like nodejs as opposed to a single partition and single consumer right?
