### ISSUE TITLE
add EARLIEST_OFFSET and LATEST_OFFSET to typescript definition file

### ISSUE THREAD

**Issue by john-livelyvideo** [tulios/kafkajs#1120]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please include links to other clients' solutions and/or KIPs for Kafka features if applicable.

**Additional context**

**Comment by Nevon** [comment]
`EARLIEST_OFFSET` and `LATEST_OFFSET` are not exposed to the user in any way, so there wouldn't be any reason to include it among the types.
