### ISSUE TITLE
Connect with SSL keystore and truststore

### ISSUE THREAD

**Issue by prabhatmishra-metro** [tulios/kafkajs#1127]
Dear @tulios @Nevon @meister @Dieken @pihentagy 

Thanks for such a wonderful library, could you please help me in knowing, how can I use this library with SSL Keystore/Truststore. I have received these encrypted files but i am not sure how shall i use these file with this library.

**Comment by prashanthrelekar** [comment]
any sample code?

**Comment by Nevon** [comment]
NodeJS does not use external keystore/truststores. Instead, you can configure the trusted certificates via the `ssl` property, which takes the standard options from Node's `tls.createSecureContext` - see the linked resources below. You'll need to convert your keystore to a pem file and using that for `ssl.ca`.

* [KafkaJS client SSL configuration](https://kafka.js.org/docs/configuration#ssl)
* [NodeJS `createSecureContext`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options)

None of this is KafkaJS specific, but the standard way TLS works in NodeJS, so there should be plenty of resources on the internet.
