### ISSUE TITLE
partitionsConsumedConcurrently not processing events for the same partition in parallell

### ISSUE THREAD

**Issue by krvajal** [tulios/kafkajs#1139]
**Describe the bug**

`partitionsConsumedConcurrently` claims that it will keep the ordering processing of messages if they belong to the same partition, but I have found that this is not actually the case

**To Reproduce**
The producer is producing events with the same key and they are sent to kafka in the same order. In the consumer side, when enabling `partitionsConsumedConcurrently` events from the same partition are being consumed in parallel, instead of being consumed in order

**Expected behavior**
They are consumed in order

**Observed behavior**
They are consumed in parallel and out of order

**Events**
```json
{"topic":"bot_engine.conversation_flow.transitions","timestamp":1625076949362,"partition":145,"offset":571280,"key":"3052#LIVE#ca6160c0-7735-4d04-b929-c8fc6a226b5a#55e728cf-4273-4ea0-99d7-0d8c7a55cc0e","value":{"_v":0,"from":{"type":"INTENT","id":"nao"},"to":{"type":"DIALOG_STATE","id":"feff2713-5e01-4764-b391-25a49010dccc","role":null,"dialogStateType":"NAVIGATION","messagesCount":0},"timestamp":1625076839315,"meta":{"botId":"3052","channelType":"web","conversationId":"55e728cf-4273-4ea0-99d7-0d8c7a55cc0e","language":"pt","userId":"ca6160c0-7735-4d04-b929-c8fc6a226b5a","version":"LIVE"},"key":"3052#LIVE#ca6160c0-7735-4d04-b929-c8fc6a226b5a#55e728cf-4273-4ea0-99d7-0d8c7a55cc0e"}}
{"topic":"bot_engine.conversation_flow.transitions","timestamp":1625076949362,"partition":145,"offset":571279,"key":"3052#LIVE#ca6160c0-7735-4d04-b929-c8fc6a226b5a#55e728cf-4273-4ea0-99d7-0d8c7a55cc0e","value":{"_v":0,"from":{"type":"INTENT","id":"nao"},"to":{"type":"DIALOG_STATE","id":"4c0d4ba5-faa2-4ada-90df-3ffc1e2c5e53","role":null,"dialogStateType":"ACTION","messagesCount":0},"timestamp":1625076839314,"meta":{"botId":"3052","channelType":"web","conversationId":"55e728cf-4273-4ea0-99d7-0d8c7a55cc0e","language":"pt","userId":"ca6160c0-7735-4d04-b929-c8fc6a226b5a","version":"LIVE"},"key":"3052#LIVE#ca6160c0-7735-4d04-b929-c8fc6a226b5a#55e728cf-4273-4ea0-99d7-0d8c7a55cc0e"}}

```

**Logs**
![Image 2021-06-30 at 8 45 09 PM](https://user-images.githubusercontent.com/5899385/124015353-db4d9e00-d9e4-11eb-892f-15f426626c7d.jpg)

Loglines in the logs are ordered in descending manner (newer events on top)

**Environment:**
 - OS: alpine
 - KafkaJS version 1.15.0
 - Kafka version 2.7
 - NodeJS version 12.20.0

**Additional context**

**Comment by dhessler** [comment]
I know this is an old issue, but very concerning since [the docs](https://kafka.js.org/docs/consuming#a-name-concurrent-processing-a-partition-aware-concurrency) clearly state:
> Messages in the same partition are still guaranteed to be processed in order, but messages from multiple partitions can be processed at the same time.

Any updates from the team here?

**Comment by Nevon** [comment]
Please understand that it's not "the team"'s (i.e. me) job to do the leg work to reproduce other people's issues. The original report didn't come with a way to reproduce the issue and no one else has reported the same thing. If you are concerned about this, then please just write a script that produces the same result and then we have something to work from. There are [example consumers](https://github.com/tulios/kafkajs/blob/master/examples/consumer.js) and [producers](https://github.com/tulios/kafkajs/blob/master/examples/producer.js) in the repo that you could use as a starting point. Or you could [write a test](https://github.com/tulios/kafkajs/blob/c8748c4e56d16f77c28424c3be5525ac22b934ec/src/consumer/__tests__/consumeMessages.spec.js#L110-L152) that validates whether messages in a partition are consumed in the order they are produced.

**Comment by krvajal** [comment]
Hi Nevon, 
I understand you completely. It is really hard to reproduce for me as well. I tried unsuccessfully to create a test to reproduce it. Maybe with the new changes in version 2 the issue is now resolved. I will close this for now as I don't have a way to reproduce it.
