### ISSUE TITLE
Seek - Doc Clerification

### ISSUE THREAD

**Issue by stavalfi** [tulios/kafkajs#1149]
https://kafka.js.org/docs/consuming#a-name-concurrent-processing-a-partition-aware-concurrency

```
await consumer.connect()
await consumer.subscribe({ topic: 'example' })

// you don't need to await consumer#run
consumer.run({ eachMessage: async ({ topic, message }) => true })
consumer.seek({ topic: 'example', partition: 0, offset: 12384 })
```

In this example, you don't `await` for `consumer.run` to finish.

I do want to wait until the `run` is successfully started and there are no errrors. 

1. Can I safely do:

```
await consumer.connect()
await consumer.subscribe({ topic: 'example' })

// you don't need to await consumer#run
const p = consumer.run({ eachMessage: async ({ topic, message }) => true })
consumer.seek({ topic: 'example', partition: 0, offset: 12384 })
await p
```

2. What if I have 10 partitions. can I safely call `seek` 10 times and only then run `await p`?
---

I wasn't sure if the comment: `you don't need to await consumer#run` was related to this specific `seek` example or it's just a comment about `run`.

Thanks!

**Comment by tulios** [comment]
Hey @stavalfi, what you are doing is correct. The `seek` command will create an in-memory map that will trigger the seek command once the consumer is online. That's why we say that you don't need to wait for consumer#run.

> What if I have 10 partitions. can I safely call seek 10 times and only then run await p?

Yes. The `seek` command is sync and will not generate any network calls. All will be resolved once the consumer gets online.

**Comment by tulios** [comment]
Feel free to re-open the issue in case of other questions.

**Comment by stavalfi** [comment]
@tulios Thanks! :)
