### ISSUE TITLE
Bump up dependecies

### ISSUE THREAD

**Issue by mohanadkaleia** [tulios/kafkajs#1150]
Hey friends! 

There are few stale pull requests to update dependencies, wonder if there is any plan to merge them soon? 

Here is an example:  https://github.com/tulios/kafkajs/pull/1063

Preferably looking to have the following dependencies updated:
```
y18n
ws
lodash
minimist
glob-parent
hosted=git-info
```

Thank you!

**Comment by tulios** [comment]
Hey @mohanadkaleia KafkaJS has no dependencies, so dependabot is updating the dev dependencies of the documentation website. This is not critical for the KafkaJS usage in any way.
