### ISSUE TITLE
JavaCompatiblePartitioner has different results than rdkafka

### ISSUE THREAD

**Issue by Themesaul** [tulios/kafkajs#1154]
**Describe the bug**

Partitions generated with JavaCompatiblePartitioner are different from those published with kafkacat or node-rdkafka (both use rdkafka 1.5.0 or higher).

**To Reproduce**
1- Use JavaCompatiblePartitioner in the producer
2- Post a message with the key "TT0124".

**Expected behavior**
The partition will be 9 as for rdkafka

**Observed behavior**
Partition is 10 making correct data processing incompatible.

**More information**

The topic has a total of 15 partitions

**Comment by t-d-d** [comment]
How many partitions does the topic have?

**Comment by Nevon** [comment]
The default partitioner in librdkafka (and I'm assuming kafkacat/node-rdkafka) is `consistent_random`: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties

If you want to be consistent with the Java partitioner, you'd need to use `murmur2_random`:

> `murmur2_random` - Java Producer compatible Murmur2 hash of key (NULL keys are randomly partitioned. This is functionally equivalent to the default partitioner in the Java Producer.)

If we compare kafkajs' JavaCompatiblePartitioner with murmur2_random from librdkafka, we can see that we get the exact same results.

https://github.com/edenhill/librdkafka/blob/55ad6101ac80a9ba09b802eab1c4dbf484245004/tests/0048-partitioner.c#L268-L274

```js
const murmur2 = require('./murmur2')
const toPositive = x => x & 0x7fffffff

const actual = toPositive(murmur2('this is another string with more length to it perhaps'))
// 1333199834

`0x${actual.toString(16)}`
// 0x4f7703da same as https://github.com/edenhill/librdkafka/blob/55ad6101ac80a9ba09b802eab1c4dbf484245004/tests/0048-partitioner.c#L272
```
