### ISSUE TITLE
Support retriable REPLICA_NOT_AVAILABLE error

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#1155]
**Is your feature request related to a problem? Please describe.**
In apache/kafka#8979 they changed the behavior of the brokers so that when a request intended for a leader or follower ends up going to another broker due to reassignment, a NOT_LEADER_OR_FOLLOWER error would be returned instead. This NOT_LEADER_OR_FOLLOWER error is actually the old NOT_LEADER_FOR_PARTITION error that has been renamed.

In the same change, they also changed REPLICA_NOT_AVAILABLE to be retriable.

**Describe the solution you'd like**
* NOT_LEADER_FOR_PARTITION should be renamed to NOT_LEADER_OR_FOLLOWER in order to be consistent with the Kafka docs.
* REPLICA_NOT_AVAILABLE should be a retriable error.

**Additional context**
I'm not sure what implications changing REPLICA_NOT_AVAILABLE to be a retriable error has for older cluster versions. Worst case, I suppose it just means that we'd be retrying an operation that isn't retriable, but I don't understand how this could be a backwards compatible change from the broker perspective, unless it was always supposed to be retriable and just wasn't marked as such for some reason.

**Comment by Nevon** [comment]
Checked with the author of the change in Kafka, and they verified that REPLICA_NOT_AVAILABLE was a transient error before and should have been retriable, even though it wasn't marked as such. Therefore this should be a safe change to make.

**Comment by rodrigolourenco** [comment]
Hi @Nevon,

Is it possible to patch this change on version 1.16.0?

**Comment by Nevon** [comment]
Re-opening as #1351 just makes `REPLICA_NOT_AVAILABLE` retriable, but doesn't address NOT_LEADER_FOR_PARTITION/NOT_LEADER_OR_FOLLOWER.

**Comment by Nevon** [comment]
No, we don't maintain multiple supported parallel versions. It will be available in [2.1.0-beta.1](https://www.npmjs.com/package/kafkajs/v/2.1.0-beta.1) soon though, and [the migration from 1.16.0 to 2.0.0 is very easy](https://kafka.js.org/docs/migration-guide-v2.0.0)

**Comment by macobo** [comment]
@Nevon is there a branch showing changes for 2.1.0? :)
