### ISSUE TITLE
Kafka SSL error: Connection error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by drstil** [tulios/kafkajs#1158]
I'm trying to get a ssl conntection to my kafka docker container. Certificates were created like here: [https://github.com/trastle/docker-kafka-ssl](https://github.com/trastle/docker-kafka-ssl). I'm using the following configuration, (and also tried the different cert files (cert.pem, key.pem, cert-signed, docker.kafka.server.keystore.pem) for `cert` and `ca` but always got the following error:

```
options.ssl = {
    rejectUnauthrorized: false,
    cert: cert.pem,
    key: key.pem,
    ca: "differentFiles",
    passphrase: "x"
}
```

> Error: Client network socket disconnected before secure TLS connection was established

Which files do I have to use for `cert` and `ca`?

I have the truststore configured for kafka. But those files are only available as .jks-files. Do I have to convert them and add to `ca` configuration? 

See also https://github.com/tulios/kafkajs/issues/1127.

**Comment by drstil** [comment]
The error was in Kafka configuration: I used `KAFKA_LISTENERS: SSL://localhost:9092`. It is working with `KAFKA_LISTENERS: SSL://:9092` or `KAFKA_LISTENERS: SSL://0.0.0.0:9092`.

**Comment by achmadshobari** [comment]
hello sir, may I know how you solved this problem?
i experience the same error and still get stuck

**Comment by JunaidOfficialNow** [comment]
> hello sir, may I know how you solved this problem? i experience the same error and still get stuck

Got the same issue for me... tried increasing connectionTimeout and working fine...
