### ISSUE TITLE
Can we please enable github discussions?

### ISSUE THREAD

**Issue by john-livelyvideo** [tulios/kafkajs#1165]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please include links to other clients' solutions and/or KIPs for Kafka features if applicable.

**Additional context**

**Comment by tulios** [comment]
Hey @john-livelyvideo, we have a Slack channel, is there anything that you are missing with that?

**Comment by john-livelyvideo** [comment]
I think slack kinda creates a barrier to entry.  What if most people are too lazy to join it?

**Comment by Nevon** [comment]
I'm not _necessarily_ against enabling Github Discussions, but it'd need to have a clear purpose. We already use Issues to discuss features and bugs and such, and Slack for more informal chatting. I'm going to close this for now. If there comes a time where we have lots of discussion going on in issues that doesn't belong there, we can reconsider.

**Comment by john-livelyvideo** [comment]
It's a signal/noise issue, @Nevon should I really be asking random questions in the issues section?  And if I actually ask a good question in Discussions, it can then be promoted to an issue, right?  I get the Slack channel argument, but is everyone on Slack?  Does google search index slack channels?  Don't we get more global search "reach" with discussions? @tulios

**Comment by john-livelyvideo** [comment]
Such a trivial thing, how could it hurt anything?
