### ISSUE TITLE
Producer is stuck in DISCONNECTING state if inflight request is timed out during disconnect procedure

### ISSUE THREAD

**Issue by Igor-Kuzmin** [tulios/kafkajs#1167]
**Describe the bug**
Scenario:
1. enforceRequestTimeout=true
2. Producer has inflight request
3. producer.disconnect() is called. RequestQueue::waitForPendingRequests wait's for queue to be empty.
4. Inflight request is failed due to timeout
In this case producer is stuck in DISCONNECTING state if inflight request is timed out during disconnect procedure.

**To Reproduce**
1. Set enforceRequestTimeout=true
2. Run a producer that continuously produces messages to a topic
3. Block port Kafka port (9092 by default) to simulate connection drop with broker:
    `sudo iptables -A OUTPUT -p tcp --sport 9092 -j DROP && sudo iptables -A INPUT -p tcp --dport 9092 -j DROP`
4. Stop producer from producing requests and call producer.disconnect(). Producer should have at least one inflight request.
5. Wait for all inflight requests to be timed out.

**Expected behavior**
Producer is moved to DISCONNECTED state and corresponding promise is resolved.

**Observed behavior**
Producer is stuck in DISCONNECTING state and corresponding promise isn't resolved.

**Environment:**
    OS: CentOS 7
    KafkaJS version 1.15.0
    Kafka version 2.7.0
    NodeJS version v15.14.0

**Additional context**
Problem in this code: https://github.com/tulios/kafkajs/blob/6f490be0f9a186539d6e5a3c572bddc3640f58f8/src/network/requestQueue/index.js#L144
If there is no pending requests, only inflight, this[PRIVATE.EMIT_REQUEST_QUEUE_EMPTY] isn't called and this promise is never resolved: https://github.com/tulios/kafkajs/blob/6f490be0f9a186539d6e5a3c572bddc3640f58f8/src/network/requestQueue/index.js#L243)

**Comment by julienvincent** [comment]
Seeing as the PR was merged, can this be closed? Or is this still partially relevant?

**Comment by Nevon** [comment]
Fixed by #1208
