### ISSUE TITLE
KIP-455: Implement alterPartitionReassignments/listPartitionReassignments admin methods

### ISSUE THREAD

**Issue by adalbert-homa** [tulios/kafkajs#1181]
These methods allow for Kafka partition managements.

I can take a look at implementing this.

**Comment by Nevon** [comment]
If anyone wants to pick this up, I think it should be a nice and simple first issue:

* [KIP-455](https://cwiki.apache.org/confluence/display/KAFKA/KIP-455%3A+Create+an+Administrative+API+for+Replica+Reassignment)
* [ListPartitionReassignments protocol definition](https://kafka.apache.org/protocol.html#The_Messages_ListPartitionReassignments)
* [AlterPartitionReassignments protocol definition](https://kafka.apache.org/protocol.html#The_Messages_AlterPartitionReassignments)

**Comment by Nevon** [comment]
This is now available in [kafkajs@2.2.0-beta.2 ](https://www.npmjs.com/package/kafkajs/v/2.2.0-beta.2) thanks to @jonathanhaviv
