### ISSUE TITLE
what's the config to matching this `max.poll.interval.ms`?

### ISSUE THREAD

**Issue by sylarwang** [tulios/kafkajs#1182]
found this in the kafka's document: https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_max.poll.interval.ms, but didn't see this in this lib, can you anyone guide me how can I can configure this?

**Comment by t-d-d** [comment]
There isn't a direct equivalent in kafkajs.  Heartbeats and the sessionTimeout are used to detect 'dead' clients.

The Java client has the mx.poll.interval.ms setting as it is using a separate thread to send heartbeats (see answer and comments here https://stackoverflow.com/a/39759329)

Kafkajs is operating in a single threaded environment.  Heartbeats are sent while processing the messages - by the library if using eachMessage or also from client code if using eachBatch.

If message processing is too slow and the consumer is hitting the sessionTimeout, then you can either raise the timeout (but server will take longer to notice dead consumers) or call the heartBeat() more regularly from within the processing code.

**Comment by yunnysunny** [comment]
When the time between consumer poll the next message is larger than  `max.poll.interval.ms`, the kafka server will rebalance the consumer group, even if heartbeat run properly.
https://kafka.apache.org/41/configuration/consumer-configs/#consumerconfigs_max.poll.interval.ms

**Comment by yulianovdey** [comment]
@yunnysunny I was also looking into this but I think that's consumer configuration, and if it's not implemented it doesn't actually apply. Also for consumers that do implement it there might still be cases where the rebalance doesn't apply (see [max.poll.interval.ms](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#max-poll-interval-ms)):

> For consumers using a non-null group.instance.id which reach this timeout, partitions will not be immediately reassigned. Instead, the consumer will stop sending heartbeats and partitions will be reassigned after expiration of the session timeout
