### ISSUE TITLE
Unable to use CooperativeStickyAssignor

### ISSUE THREAD

**Issue by sethddigitile** [tulios/kafkajs#1189]
**Describe the bug**
I am unable to use CooperativeStickyAssignor as my partitionAssigners value in setting my consumer configs

**To Reproduce**
const consumer = kafka.consumer({ groupId: process.env.KAFKA_GROUP_CONSUMER_ID, partitionAssigners: [PartitionAssigners.CooperativeStickyAssignor] });

**Expected behavior**
I expect to be able to set the CooperativeStickyAssignor as my partitionAssigner

**Comment by Nevon** [comment]
This is a very strange way to pose a feature request. The only assigner KafkaJS provides out of the box is the RoundRobinAssigner. A cooperative assigner is just one part of implementing [KIP-429](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol).

Closing as a duplicate of #922

**Comment by kagai** [comment]
lets learn to be kind when doing feature requests, this are open source libraries and people invest time for free . Lets be respectful.

**Comment by RohanDoshi21** [comment]
I have created an implementation and raised an PR. https://github.com/tulios/kafkajs/pull/1770

@Nevon @kagai Can you please take a look at this?
