### ISSUE TITLE
this is undefined

### ISSUE THREAD

**Issue by delcaos** [tulios/kafkajs#1194]
Boys, `this` line is problematic

https://github.com/tulios/kafkajs/blob/9b5ef7f7961fdb6716e2e90634b36abb81d24af9/src/protocol/requests/index.js#L86

Correct should be:

``` const bestImplementedVersion = Math.max.apply(Math, availableVersions)```

or if yall support sexiness:

``` const bestImplementedVersion = Math.max(...availableVersions)```

**Comment by Nevon** [comment]
Closed by #1195
