### ISSUE TITLE
one group bind many topics problem

### ISSUE THREAD

**Issue by 759325100** [tulios/kafkajs#1209]
**Describe the bug**
I have two programs using the same group id.
Two programs subscribe to different topics, such as topicA and topicB.
I found that only one of the programs can consume the topics.
When I use two different group id, the program works normally
What kind of question is this, and I hope to answer!!!

**To Reproduce**
ProgramA-Code
```ts
import { Kafka, Producer, ConsumerGroup, Consumer } from 'kafkajs'
const topic = "topicA"
function async start(){
  const client = new Kafka({
          clientId: `delay-api-${process.pid}-${Math.floor(Math.random() * 10000000)}`,
          brokers: _.split(host, ','),
          connectionTimeout: 10000,
          requestTimeout: 5000
        })
  const consumer = this.client.consumer({ groupId: "group-id" })
  consumer.on('consumer.connect', () => logger.info(`${topic} Consumer Is Connect`))
  consumer.on('consumer.disconnect', err => logger.info(`${topic} Consumer Is Disconnect`, err))
  consumer.on('consumer.crash', err => logger.info(`${topic} Consumer Is Crash`, err))
  consumer.on('consumer.stop', err => logger.info(`${topic} Consumer Is Stop`, err))
  await consumer.connect()
  await consumer.subscribe({ topic:topic, fromBeginning: false })
  consumer.run({
    eachMessage:({message})=>{
       console.log(message)
    }
  })
}
```

ProgramB-Code
```ts
import { Kafka, Producer, ConsumerGroup, Consumer } from 'kafkajs'
const topic = "topicB"
function async start(){
  const client = new Kafka({
          clientId: `delay-api-${process.pid}-${Math.floor(Math.random() * 10000000)}`,
          brokers: _.split(host, ','),
          connectionTimeout: 10000,
          requestTimeout: 5000
        })
  const consumer = this.client.consumer({ groupId: "group-id" })
  consumer.on('consumer.connect', () => logger.info(`${topic} Consumer Is Connect`))
  consumer.on('consumer.disconnect', err => logger.info(`${topic} Consumer Is Disconnect`, err))
  consumer.on('consumer.crash', err => logger.info(`${topic} Consumer Is Crash`, err))
  consumer.on('consumer.stop', err => logger.info(`${topic} Consumer Is Stop`, err))
  await consumer.connect()
  await consumer.subscribe({ topic:topic, fromBeginning: false })
  consumer.run({
    eachMessage:({message})=>{
       console.log(message)
    }
  })
}
```

** Logger:**
ProgramA
```json
{"level":"WARN","timestamp":"2021-10-19T06:52:13.524Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer group received unsubscribed topics","groupId":"delaygroup_dev","generationId":83,"memberId":"delay-api-52386-5344417-2d9403ff-5b58-41ce-9ecd-d595407aff31","assignedTopics":["SQLRunningDev"],"topicsSubscribed":["TaskRunningDev"],"topicsNotSubscribed":["SQLRunningDev"],"helpUrl":"https://kafka.js.org/docs/faq#why-am-i-receiving-messages-for-topics-i-m-not-subscribed-to"}
{"level":"INFO","timestamp":"2021-10-19T06:52:13.524Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"delaygroup_dev","memberId":"delay-api-52386-5344417-2d9403ff-5b58-41ce-9ecd-d595407aff31","leaderId":"delay-api-52387-8377299-2ec6bfc6-9c17-47b0-93ad-e7af4a146760","isLeader":false,"memberAssignment":{},"groupProtocol":"RoundRobinAssigner","duration":9237}
```

ProgramB
```json
{"level":"INFO","timestamp":"2021-10-19T06:52:13.504Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"delaygroup_dev","memberId":"delay-api-52387-8377299-2ec6bfc6-9c17-47b0-93ad-e7af4a146760","leaderId":"delay-api-52387-8377299-2ec6bfc6-9c17-47b0-93ad-e7af4a146760","isLeader":true,"memberAssignment":{"SQLRunningDev":[12,15,2,3,4,5,6,9]},"groupProtocol":"RoundRobinAssigner","duration":9236}
```

**Environment:**
 - OS: Mac OS 11.2.3
 - KafkaJS version 1.15.0
 - Kafka version 0.10.2
 - NodeJS version 14.x

**Additional context**

**Comment by Nevon** [comment]
You cannot have the same groupId subscribing to different topics. The whole point of the group id is to identify consumers as being part of the same consumer group.

> A consumer group is a set of consumers which cooperate to consume data from some topics. The partitions of all the topics are divided among the consumers in the group.

https://docs.confluent.io/platform/current/clients/consumer.html#consumer-groups

**Comment by sempasha** [comment]
@Nevon would you, please, clarify, what is wrong with [stackoverflow question](https://stackoverflow.com/questions/57753211/kafka-use-common-consumer-group-to-access-multiple-topics) and [answer](https://stackoverflow.com/questions/57753211/kafka-use-common-consumer-group-to-access-multiple-topics/58445425#58445425).

**Comment by Nevon** [comment]
"radai" already explained it [in the comments](https://stackoverflow.com/questions/57753211/kafka-use-common-consumer-group-to-access-multiple-topics/58445425#comment103414744_58445425):

>  i dont think anyone claimed they would see records from topics they dont own. to complete your experiment, try and force a rebalance by adding partitions to one of the topics and you will see ALL consumers (even those that dont care about that topic) stop to rebalance.

Partitions will still be assigned to all members of the consumer group. It's just that if a consumer isn't subscribed to a topic that it receives assignments for, it'll ignore them. This is client-side behavior, not server side behavior.

When I say "You cannot have the same groupid subscribing to different topics" I don't mean it's literally impossible to do. There's just absolutely no benefit to doing it, and is a misunderstanding of what the purpose of a consumer group is.
