### ISSUE TITLE
Fetch the specific offset logs

### ISSUE THREAD

**Issue by blockchain-app12** [tulios/kafkajs#1210]
Hi,
I have a doubt in **kafkajs** library, How to fetch the **specific offset logs** in kafka consumer ??
Now I hereby using the cli cmd only.
CLI cmd : 
kafka-console-consumer --topic example-topic --bootstrap-server broker:9092 \
 --property print.key=true \
 --property key.separator="-" \
 --partition 1 \
 --offset 6
 
 I need it as programatically to do in kafkajs consumer.
 Kindly let me know, if any queries you have regards this issue.

**Comment by Nevon** [comment]
There's no API in KafkaJS for doing that. You _could_ create a new consumer, seek to the desired offset, store the fetched message and then shut down, but it's very unergonomic compared to using a client that is built around that type of consumption pattern.
