### ISSUE TITLE
use broker default instead of 1 for replicationFactor in ITopicConfig

### ISSUE THREAD

**Issue by FrVaBe** [tulios/kafkajs#1216]
We need to createTopics with the AdminClient and want the replicationFactor to be the same as the default replication factor of the Kafka cluster (which we do not know, when creating the topic).

Unfortunately kafkajs uses "1" as default and it does not seem to be possible to fall back on the cluser default value.

**Describe the solution you'd like**
When omitting the replicationFactor in ITopicConfig, the cluster default value should be used (as it is also done in the Kafka _kafka-topics_ commandline tool)

**Additional context**
If there is any other solution to fall back to the cluster default value this would be great to know.

**Comment by Nevon** [comment]
Fixed in #1305 and is available in 1.17.0-beta.2
