### ISSUE TITLE
[docs] Please clarify the Brief Intro to Kafka on Partitions

### ISSUE THREAD

**Issue by futpib** [tulios/kafkajs#1218]
https://github.com/tulios/kafkajs/blob/e99be62c1bfeee5dd92ade6e3a2bdbca0a20d834/docs/KafkaIntro.md#L17

> only one **instance** can read from a particular partition at a time

What exactly is an instance?

Could be:
* instance of a `Kafka` class
* node js process
* kafka broker
* kafka consumer group
* kafka consumer

I'm not sure myself but I'd bet on both of "kafka broker" and "kafka consumer group"

**Comment by Nevon** [comment]
The answer is "member in a consumer group". Multiple Kafka consumers can read from the same partition if they are part of different consumer groups, but only one member in a given consumer group is allowed to commit offsets for a particular partition at any given time.
