### ISSUE TITLE
RequestReply approach with kafkajs

### ISSUE THREAD

**Issue by artemitcraft** [tulios/kafkajs#1223]
Hi, I know it's not completely related to the subject but I have an issue and cannot resolve it by myself so asking for help. So I am going to implement sync request-reply pattern based on kafka. here is a short prototype: [gist link](https://gist.github.com/artemitcraft/5f04fea00fdee1f33078eee31aa5ee32)

I am faced with the problem on the second iteration (start), eventEmitter uses old object and promise cannot be resolved. Will be grateful for any thoughts.

**Comment by tacyarg** [comment]
Event streaming systems are not designed for this sort of architectural pattern.

**You would be better suited using some form of RPC as it would be more performant and easier to implement for direct sync calls.**

https://en.wikipedia.org/wiki/Two_Generals%27_Problem

You can however simulate this behavior using a two topic per service solution: `serviceA.requests`, `serviceA.responses`. You would then map promises using the message key for each, returning a unresolved promise to the caller. On the consumer topic you would then lookup the id and resolve/reject each promise based on the responses.

**Comment by artemitcraft** [comment]
@tacyarg yes, I was going this approach. please check my gist in the first message. the problem is in the event.emitter which are working incorrectly on the second request. it is simulated with nested code inside the promise.all. So I think it is not directly connected with kafka or kafkajs. If you can take a look on it I will appreciate a lot.

**Comment by Nevon** [comment]
I will close this issue as it is not directly related to Kafka or KafkaJS.
