### ISSUE TITLE
Documentation for connecting to Azure EventHubs

### ISSUE THREAD

**Issue by justinmchase** [tulios/kafkajs#1228]
I am unable to connect to AzureEvent hubs, i see a few issues in here indicating that its possible but I'm getting some error that is hard to decipher while trying to connect. It would be nice to have a little documentation from someone who was able to do it successfully to see the recipe.

**Describe the solution you'd like**
I'd like to see the code for this library but also any hints on how to set it up in azure, if you need to check or uncheck any boxes to make it work.

**Additional context**
Here's the code I have right now:
```ts
const azureEventHubsEndpoint = 'Endpoint=sb://mynamespace.servicebus.windows.net/;SharedAccessKeyName=XXXXXX;SharedAccessKey=XXXXXX'
this.client = new Kafka({
  clientId: 'example',
  ssl: true,
  sasl: {
    mechanism: 'plain',
    username: '$ConnectionString',
    password: azureEventHubsEndpoint,
  },
  brokers: [
    `mynamespace.servicebus.windows.net:9093`
  ],
  logLevel: logLevel.DEBUG
})
```

But I'm getting the error `Connection error: Client network socket disconnected before secure TLS connection was established`. I don't think this is a bug of this library just that there is some kind of a configuration issue that probably some documentation could help with.

**Comment by justinmchase** [comment]
Azure itself gives examples using a different library:
https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/quickstart/node/producer.js#L10

But I really don't want to use it because it has native code modules in it I don't want to have to depend on. It would be super great if it was possible for it to work with this library.

**Comment by justinmchase** [comment]
For the record here is what I did:

```ts
// e.g. 'Endpoint=sb://mynamespace.servicebus.windows.net/;SharedAccessKeyName=XXXXXX;SharedAccessKey=XXXXXX'
const [, broker] = azureEventHubsEndpoint.match(/^Endpoint=sb:\/\/(.*)\/;.*$/)
if (!broker) {
  throw new InvalidValueError(broker, 'azureEventHubsEndpoint is in an invalid format, unable to extract the broker endpoint')
}
this.client = new Kafka({
  clientId,
  ssl: true,
  sasl: {
    mechanism: 'plain',
    username: '$ConnectionString',
    password: azureEventHubsEndpoint,
  },
  brokers: [
    `${broker}:9093`
  ],
  logLevel: logLevel.NOTHING
})
```

Where `azureEventHubsEndpoint` is the full "connection string" azure gives you for EventHubs.

**Comment by MichaelKoch** [comment]
any news regarding that topic ?

**Comment by justinmchase** [comment]
The last post in this thread shows the recipe for it to work. Were you not able to get it to work @MichaelKoch ?

**Comment by indyone** [comment]
@justinmchase maybe I'm wrong, but both code samples https://github.com/tulios/kafkajs/issues/1228#issue-1050281169 & https://github.com/tulios/kafkajs/issues/1228#issuecomment-1018715133 produce the same `broker` value.

In you example the `const azureEventHubsEndpoint = 'Endpoint=sb://mynamespace.servicebus.windows.net/;SharedAccessKeyName=XXXXXX;SharedAccessKey=XXXXXX'` after the regex `/^Endpoint=sb:\/\/(.*)\/;.*$/` match, the broker value will be `mynamespace.servicebus.windows.net` which is the same as your first example.

Am I missing something here?
