### ISSUE TITLE
Connecting to AWS IAM via SASL

### ISSUE THREAD

**Issue by marcusshu** [tulios/kafkajs#1236]
![image](https://user-images.githubusercontent.com/17269172/142832205-10760290-7720-489a-9d03-540cf5d4d237.png)

I'm trying to connect to my publicly accesible kafka cluster on AWS MSK using IAM, but I am getting the error that 'aws' is not assignable to '"aws"', even though `KafkaConfig` takes in the keyof `SASLMechanismOptionsMap`.  Here's the config that I used to pass into Kafka():

![image](https://user-images.githubusercontent.com/17269172/142838431-b325d2e3-0e52-4e05-ab4e-8c2d0a2f55db.png)

**Comment by Nevon** [comment]
What version of KafkaJS are you using and what version of Typescript are you using?

Here's a TS playground that shows this working with the types from v1.15.0: https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgeUwFcYALAI2EyjQAUoIA3BAEzQCVgBnSJLvAN4AoOHEaYANkWAAuOFxhRkAcyEBfIUJgBPMHgDKAQX0AZALLBspTEgRcAtvjAwEEPmcxg4AXjjDRAORgEpjIAXICcET8UEiY9rLyiioANHBgmFxcAO7QLHIKSkjKcGopInABXNhQ8QC0XNZ1AEwArABs4X5RMXEJBcnFaRlZuVD5SUUlZRVVNfWNmHWtAIzNXZHRaH2JhanpmTl5A1Ol5YGY2VwbcMRk0AgAXpgubgCSbCgIOif7OLhZADSwG0H1+Q3klhoMEM2ABXGB2nByjS-CyriQABUIABrYBIAD8yLOswgdwoVBoUBuZJIpAAQpS6AxmGwoHIABQASh8AD44PQIPY7MAADyEOmUajMpisDjcXj8fkaDRCUCQWBwHR6OBGUwWKw2Oz2HxwPHaCDoXXGcyWay2BxOV7uTxaXQGG0G+3Gp0YriizH83yYuCgVBIFhca36u1GhxwAndBKGh32OQhtRwABk0dtKZ9zj9HjAAG1MQBdOByJDARhoNXgaDwbUe0y+txR3x6vPex2Fjui7teuP2XmaITYDvN7gwOTd9t8U3+URwZO9tOVS7Xc4r8kPZ7Oj74lw-SroCAQAI70T-bgIkFgyrkahXiqifg1YAwuF3xFyALPo8ATqEAA

**Comment by marcusshu** [comment]
Hello Nevon, thanks for the reply. I'm aware of that, and I'm using typescript version 4.3.5, and KafkaJS version 1.15.0. Could it be a mismatch between my typescript version? It works when I //@ts-ignore it.

**Comment by Nevon** [comment]
I tried setting the TS playground to 4.3.5 and it still typechecks just fine. Do you have a tsconfig with some nonstandard configuration or something? 

> It works when I //@ts-ignore it.

Yeah, but that's just turning off the type system.

**Comment by Nevon** [comment]
Closing this as inactive.
