### ISSUE TITLE
New consumer config parameter: "group.initial.rebalance.delay"

### ISSUE THREAD

**Issue by hebelal** [tulios/kafkajs#1237]
**Problem**
My kafka application is running on multiple instances.
The time for each instance startup might vary and therefore my application often logs "The group is rebalancing, re-joining" right at the start of my instances.
Sometimes I don't receive the error and my assumption is that this could be solved by changing the parameter [group.initial.rebalance.delay.ms](https://kafka.apache.org/documentation/#group.initial.rebalance.delay.ms).
As far as I know this parameter is not available in kafkajs yet, please correct me if I'm wrong.

**Solution**
Implement the config parameter offered by Kafka called [group.initial.rebalance.delay.ms](https://kafka.apache.org/documentation/#group.initial.rebalance.delay.ms)

**Comment by Nevon** [comment]
`group.initial.rebalance.delay.ms` is a broker configuration, not a consumer configuration, so it's not something that's controllable from the client.

On the client side, we have `rebalanceTimeout` which is essentially the same thing but applied on every rebalance. The rebalance timeout on the initial group rebalance will be `min(group.initial.rebalance.delay.ms, rebalanceTimeout)`
