### ISSUE TITLE
sendBatch should allow defining partition

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#1239]
**Describe the solution you'd like**

sendBatch method to have optional partition number inside messages array. Like producer.send() method has.

**Additional context**
Use case: I have a service that filters and forwards messages from one topic to another. I read them in via batch, filter some out and forward them to topic that has exactly same amount of partitions. Because I read by batch I already know which partition I should send the messages. Right now I can't define a partition

**Comment by Nevon** [comment]
[`send` is implemented using `sendBatch`](https://github.com/tulios/kafkajs/blob/229b6f490be8e2e217cef889583b734c5001de8e/src/producer/messageProducer.js#L118-L126), so anything you can do with `send` you can do with `sendBatch`. If you check the documentation for the `topicMessages` property in the `sendBatch` call, it says it's the same type as `messages` in `send`.

**Comment by pimpelsang** [comment]
You're right. I must be getting blind :)
