### ISSUE TITLE
consumer.run() method gives the Connection Timeout Error

### ISSUE THREAD

**Issue by Amitesh47** [tulios/kafkajs#1259]
This is my consumer.js code

       const { Kafka } = require("kafkajs");

       async function run() {
       try {
          const kafka = new Kafka({
                 clientId: "sysadminKafka",
                 brokers: ["localhost:9092"],
                 });

       const consumer = kafka.consumer({ groupId: "test" });
       console.log("Connecting.....");
       await consumer.connect();
       console.log("Connected!");

       await consumer.subscribe({
          topic: "Users",
          fromBeginning: true,
       });
       console.log("Subscribed");

       await consumer.run({
            eachMessage: async (result) => {
                       console.log("RESULT", result);
                                },
      });
    } catch (ex) {
       console.error(`Something bad happened ${ex}`);
      process.exit(0);
      }}
     run();

I am getting the following error in the console after the connection is established

        Connecting.....
        Connected!
        Subscribed
        {"level":"INFO","timestamp":"2021-12-21T06:47:35.166Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test"}
        {"level":"ERROR","timestamp":"2021-12-21T06:47:36.167Z","logger":"kafkajs","message":"[Connection] Connection 
        timeout","broker":"sysadmin-kafka:9092","clientId":"sysadminKafka"}
        {"level":"ERROR","timestamp":"2021-12-21T06:47:36.170Z","logger":"kafkajs","message":"[Consumer] Crash: 
        KafkaJSConnectionError: Connection timeout","groupId":"test","stack":"KafkaJSConnectionError: Connection timeout\n    at 
        Timeout.onTimeout [as _onTimeout] (/home/aranjan/Desktop/Nouveau/dvc_scripts/sysadmin- 
        ui/src/kafka/node_modules/kafkajs/src/network/connection.js:165:23)\n    at listOnTimeout (internal/timers.js:557:17)\n    at 
        processTimers (internal/timers.js:500:7)"}

**Comment by Nevon** [comment]
This is a misconfiguration of your broker. You can see that your client is initially connecting to `localhost:9092`, then the broker returns metadata with an advertised hostname of `sysadmin-kafka`, which is not a hostname you can connect to from your local network (I'm guessing you're running this in Docker, in which case you can only resolve that hostname within the Docker network).

See this: https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/

**Comment by kkedawat** [comment]
hi @Nevon
I am facing the same issue of "[Connection] Connection timeout" also memory utilisation is too high. Can you please help me out with this?
