### ISSUE TITLE
Add topic offset methods to admin client

### ISSUE THREAD

**Issue by dstelljes** [tulios/kafkajs#126]
Following up from #111. `ListOffsets` is already implemented [on the broker](https://github.com/tulios/kafkajs/blob/master/src/broker/index.js#L300), so exposing it on the admin client would entail either adding another operation on the admin client that accepts topic and timestamp (maybe specific partition(s) as well) or overloading `fetchOffsets`. It would also be good to define EARLIEST and LATEST constants somewhere as well.

**Comment by tulios** [comment]
@dstelljes have you worked on this? I can take it soon (probably my next issue).

**Comment by dstelljes** [comment]
I had started working on it, but I was having trouble getting tests to run locally. I can aim to have a PR submitted this weekend unless you're planning to work on it before then.

**Comment by tulios** [comment]
Ok, don't worry. You don't need to rush; I was just organizing my tasks.

This can solve #137

**Comment by dstelljes** [comment]
How would you recommend approaching this? `fetchTopicsOffset` on the cluster looks like the best place to call into from the admin client, but I’m not sure what to do about `fromBeginning`. Overload to accept a timestamp as well? Only accept a timestamp and move the `fromBeginning` logic somewhere else?

**Comment by tulios** [comment]
@dstelljes sorry for the delay. You already have `listOffsets` on the broker, let's try to keep the admin logic in the admin, so get the leader of the topic and use `listOffsets` to figure out the offsets. We can replicate the `fromBeginning` logic in the admin client; it's a duplication we can afford for now. I don't know about the timestamp part, I have to research a bit.
