### ISSUE TITLE
Batch Consumption waiting ~2 seconds

### ISSUE THREAD

**Issue by Driviz** [tulios/kafkajs#1260]
**Describe the bug**
While reading from kafka using _eachBatch_ in a consumer group from multiple topics. After each consumer has consumed the message. It takes 2 seconds to read another set of batch.

**To Reproduce**
1. Create consumer group of 4 consumers named `group1`.
2. Create 2 Kafka Topics.
3. Use `group1` to read from both of the topics.
4. Keep the kafka filled with data > max limit before starting the consumer. (So multiple batches could be processed)

**Expected behavior**
Simultaneous reading by consumers is expected without any unusual delay.

**Observed behavior**
Delay of 2 seconds is noticed once every consumer has read once from the topics.

**Environment:**
 - OS: Mac OS 12.1
 - KafkaJS version: 1.15.0
 - NodeJS version : 17.2.0

**Additional context**

**Comment by ramank775** [comment]
Have a look at PR #1258, it fixes the concurrency issue.

**Comment by Driviz** [comment]
thanks @ramank775, looks like this should resolve the issue. Will check once with the fork.
