### ISSUE TITLE
subscribeTopic fromBegining=true does not work with kafka 3.0.0

### ISSUE THREAD

**Issue by salos1982** [tulios/kafkajs#1262]
**Describe the bug**
Very strange behavior of flag `fromBeginning` in consumer.subscribe()

**To Reproduce**
```
const { Kafka, logLevel } = require('kafkajs');

const kafka = new Kafka({
  logLevel: logLevel.INFO,
  brokers: ['localhost:9092'],
  clientId: 'tests',
});

async function run() {
  const topic = 'test-topic';

  const producer = kafka.producer();
  await producer.connect();
  await producer.send({
    topic,
    messages: [{ key: '1', value: 'test value' }],
  });

  let numberMessage = 0;
  const consumer = kafka.consumer({ groupId: 'consumer' });
  await consumer.connect();
  await consumer.subscribe({ topic, fromBeginning: true });
  const promise = new Promise((resolve) => {
    consumer.run({
      eachMessage: async (mesageData) => {
        console.log(`got message ${numberMessage++} offset ${mesageData.message.offset}`);
        resolve(true);
      },
    });
  });

  await promise;

  await new Promise((resolve) => {
    setTimeout(resolve, 2000);
  });

  await producer.disconnect();
  await consumer.disconnect();
}

run()
```

Run code above multiple times. 

**Expected behavior**
Every time I have the messages started with 0 offset in console. E.g. 
```
got message 0 offset 0
```

**Observed behavior**
And you will see that every time offset value is increasing (see console) and not started with 0 offset

**Environment:**
 - OS: Windows 11
 - KafkaJS version 1.15
 - Kafka version 3.0.0
 - NodeJS version 16.13.0

**Additional context**

**Comment by OneCricketeer** [comment]
Not seeing how this is version specific problem. 

The `auto.offset.reset` property only applies when a consumer group doesn't exist. You appear to already have a group, so running multiple times will increase the offset, yes.

If you want to always start at the beginning of the topic, disable consumer commits, and/or ensure the consumer seeks to the beginning of the topic before polling

**Comment by Nevon** [comment]
As @OneCricketeer says, this is expected behavior. As the docs say:

> The consumer group will use the latest committed offset when starting to fetch messages. If the offset is invalid or not defined, fromBeginning defines the behavior of the consumer group.

https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning
