### ISSUE TITLE
Using third party libraries

### ISSUE THREAD

**Issue by Lehks** [tulios/kafkajs#1263]
I am connecting to a Kafka service that requires additional libraries (these are kakfa-oauth-common, kafka-oauth-client, keycloak-common and keycloak-core). In the tutorial that I followed, these libraries would be downloaded and put into a certain directory next to the kafka executable.

Is it possible to use these libraries with kafkajs?

The guide I followed was this one: [https://developer.mercedes-benz.com/products/connect_your_business/docs](https://developer.mercedes-benz.com/products/connect_your_business/docs). Look for the caption "Connect to the Push API & Consume Vehicle Signals".

**Comment by Nevon** [comment]
Those libraries are for the Java Kafka client, so no, you can't use them in NodeJS. Looking at the Mercedes documentation, it looks like they're using the oauthbearer mechanism, which we do support, but you have to write the integration towards their oauth server yourself (or use some generic oauth integration library). The documentation you linked to links to [an example repo integration with a Python client](https://github.com/Daimler/kafka-integration-samples/blob/master/kafka-sample/python/kafka-oauth-demo.py#L51-L64), which does something similar.

[See our documentation](https://kafka.js.org/docs/configuration#oauthbearer-example) for a generic example of using the oauthbearer mechanism in KafkaJS. The bit that's missing is the part where you integrate with the oauth server to get the token.
