### ISSUE TITLE
How to prioritize topics in Kafkajs

### ISSUE THREAD

**Issue by tfrot** [tulios/kafkajs#1268]
In Java I can prioritise one topic over another creating 2 consumers each listening to 1 of my 2 topics. Then loop over my consumer in priority order and call consumer1.poll, for example.

Is there a way to do something similar with kafkajs since there is no poll() or fetch() method?

Thanks,
Thomas

**Comment by Nevon** [comment]
I would be curious to know what you mean by prioritizing in this case. Some pseudo-code showing what you mean would be helpful. From your description I don't really understand how one topic would be prioritized over the other in any meaningful sense:

```js
for (const consumer of consumers) {
  const records = await consumer.poll()
  for (const record of records) {
    await processRecord(record)
  }
}
```

In the example above, one consumer isn't prioritized over the other - it just happens to be polled before the other. They will still be using the same amount of resources and have the same throughput and latency. To prioritize one of the other you'd need to do something more complex like measure the amount of time/resources spent and only fetch with the second producer if there's enough time/resources available once the first has finished. Something like:

```js
const startTime = process.hrtime.bigint()
const records = await prioritizedConsumer.poll()
await processRecords(records)
const duration = process.hrtime(start) - startTime

if (TIME_BUDGET - duration >= THRESHOLD) {
  const records = await lessPrioritizedConsumer.poll()
  await processRecords(records)
}
```

Something like that could be achieved by using [`pause & resume`](https://kafka.js.org/docs/consuming#a-name-pause-resume-a-pause-resume)

**Comment by tfrot** [comment]
Hi Nevon,

In java you could achieve that by creating a list of consumers ordered by priority and do something like that:
![image](https://user-images.githubusercontent.com/19874195/152997402-f76eb237-8745-4794-aaeb-678164e6278b.png)

I am not sure if something like that is possible with Kafkajs, because I think there is no function such as `consumer.poll()` returning the list of records to check if the list empty or not. But I am quite new with Kafkajs, so please tell me if I am wrong and how I can do that.

If not possible, then I will try what you propose using pause & resume function.

Let me know if this is not clear.

Thanks!

**Comment by Nevon** [comment]
The code you just took a screenshot of is roughly equivalent to my first example above, but as I said, there's nothing about this that makes it prioritized. It's still just going to poll with one consumer, process those messages, then poll the next consumer and process those messages, etc. That's not prioritization. Both consumers are getting the exact same resources and time. Whether you poll consumer A and then B or B and then A doesn't matter, they will both have the exact same throughput and latency over time.

Let's simplify it with an example:

```js
const counters = new Map();

const createWorker = (name) => () => {
  for (let i = 0; i < 10; i++) {
    const current = counters.get(name) ?? 0
    counters.set(name, current + 1)
  }
}

const workers = [createWorker('A'), createWorker('B')]

for (let i = 0; i <10; i++) {
  for (const worker of workers) {
    worker()
  }
}
```

Once this runs, both A and B are going to have processed 100 records. If I swap the order of them, they're still going to have processed 100 records. If you toss this into an infinite loop, whenever you stop the loop they are going to have processed approximately the same number of records - one is not prioritized over the other.

**Comment by Nevon** [comment]
Well, this is just some pseudo-code. You could probably do it in a nicer way. It's true that on startup you wouldn't have all the partitions in there, so you'd start out consuming from the less prioritized topic as well.

One way to make it more robust is to listen to the `GROUP_JOIN` event, which contains `memberAssignment`, which are all the topic-partitions that are assigned to the consumer. so you could keep track of which partitions are assigned, and then in the `END_BATCH_PROCESS` event see if all the assigned partitions have had 0-size batches.

**Comment by Nevon** [comment]
I'll close this as it doesn't refer to an issue with KafkaJS itself. Feel free to re-open if needed.
