### ISSUE TITLE
Local tests

### ISSUE THREAD

**Issue by patrickleet** [tulios/kafkajs#127]
Hey, I had some minor issues with running the tests locally.

They were caused by getContainerId by name call.

The reason seems to be that https://github.com/tulios/kafkajs/blob/master/scripts/waitForKafka.js#L13 is using a filter on some labels that do not exist on my machine.

Changing the filters to just `name=${node}` does work though.

Is there something I'm missing in the setup to create those labels, or should I make a PR to filter on name?

**Comment by tulios** [comment]
I think you need to update docker/docker-compose. I have to proper document the versions. You can run the tests by booting kafka first (`scripts/dockerComposeUp.sh`) and then just `yarn test:local`. Can you give it a try? I'm on vacation now but I should be back in the end of the week and then I can check the proper docker versions.

**Comment by tulios** [comment]
Hi @patrickleet, you are right. The project was using labels from docker-compose which makes it coupled with the version we are using. I've updated the project to use custom labels, which should improve the compatibility.

Take a look at commit 7cfb5b85f7b14fa32182a93a43a57cadecac27c3 for more information.

Can you try again? Feel free to re-open this issue if the problem isn't entirely solved.
Thanks
