### ISSUE TITLE
Help: SSL configuration in kafkajs

### ISSUE THREAD

**Issue by ImAbhishekTomar** [tulios/kafkajs#1272]
Hi, I am consuming my topic in the console using the below command with SSL settings, need help to consume same in kafkajs.

```
../../../confluent/bin/kafka-avro-console-consumer  \
    --bootstrap-server my-server.com:443   \
    --topic my-topic-name  \
    --property schema.registry.url=http://my-server-registry.com/   \
    --consumer.config ./client-ssl.properties   \
    --from-beginning   \
    --property print.key=true   \
    --max-messages 10
```

### File : client-ssl.properties 

```
  bootstrap.servers=my-server.com:443
  schema.registry.url=http://my-server-registry.com/ 
  security.protocol=SSL
  sasl.mechanism=PLAIN
  ssl.keystore.location=./keystore.jks
  ssl.keystore.password=***********
  ssl.truststore.location=../truststore.jks
  ssl.truststore.password=***********
  ssl.client.auth=required

```

**Where I am currently**
So after reading many documentation i found that i need to convert my jks file in PEM and i have converted omy certificate files in PEm and trying using below code but its showing error.
```

import fs from "fs";
import { Kafka } from "kafkajs";

let kafka = new Kafka({
  clientId: "myapp",
  brokers: ["my-server.com:443"],
  ssl: {
    key: fs.readFileSync("keystore.pem", "utf-8"),
    cert: fs.readFileSync("truststore.pem", "utf-8"),
  },
});

const topic = "my-topic-name";
const consumer = kafka.consumer({ groupId: "test-group" });

const run = async () => {
  await consumer.connect();
  await consumer.subscribe({ topic, fromBeginning: true });
  await consumer.run({
    eachBatch: async ({ batch }) => {
      console.log(batch);
    },
    eachMessage: async ({ topic, partition, message }) => {
      const prefix = `${topic}[${partition} | ${message.offset}] / ${message.timestamp}`;
      console.log(`- ${prefix} ${message.key}#${message.value}`);
    },
  });
};

await run();
```

**ERROR**

`{"level":"ERROR","timestamp":"2022-01-28T15:03:48.242Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Failed to connect: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch","retryCount":0,"retryTime":270}
`

**Comment by ImAbhishekTomar** [comment]
please help

**Comment by Nevon** [comment]
Your KafkaJS example code is correct. The error you're getting is telling you that the private key doesn't match the certificate, and has nothing to do with KafkaJS. Likely it's an issue in your conversion from the Java Keystore format to PEM format. I would suggest googling the error and reading about the formats, and determining what went wrong in your conversion process.
