### ISSUE TITLE
Document the clientId a little better

### ISSUE THREAD

**Issue by justinmchase** [tulios/kafkajs#1273]
**Is your feature request related to a problem? Please describe.**
The docs just show `'my-app'` for the clientId everywhere. It would be immensely helpful to have a little blurb describing what a good clientId value should be. For example, if I have a horizontally scaling api, each with a kafka client, should they all have distinct clientId values or should they all have the same clientId? I'm having a hard time determining what is more correct.

**Describe the solution you'd like**
Just a paragraph in the docs somewhere with the keyword `clientId` linked to it, since that was what I was searching for.

**Additional context**
Perhaps a link to any relevant kafka documentation as well, I am having a hard time finding it though I'm assuming its there somewhere. This is just where I started the search and it would probably help others as well.

**Comment by Nevon** [comment]
Sounds good! My understanding is that the client id is only used for client quotas and for request logging inside Kafka.

[The Kafka documentation says](https://kafka.apache.org/documentation/#design_quotasgroups):

> **Client-id is a logical grouping of clients with a meaningful name chosen by the client application.** The tuple (user, client-id) defines a secure logical group of clients that share both user principal and client-id. Quotas can be applied to (user, client-id), user or client-id groups.

Based on this, I would use the clientId to represent "my application". Each instance of that application within the same environment would use the same client id, and I would not use the same client id in multiple different applications. Hence why the example is "my-app" - something that uniquely identifies my application.

I think it can deserve its own heading next to "Broker Discovery" [here](https://kafka.js.org/docs/configuration#broker-discovery). Want to take a crack at it?

**Comment by justinmchase** [comment]
Perfect, thank you! Your interpretation of that documentation is the same as how I am understanding it.

I'm happy to make a PR, you did all the heavy lifting though 😄
