### ISSUE TITLE
Module parse failed: Unexpected token 155:34

### ISSUE THREAD

**Issue by esuarezz** [tulios/kafkajs#128]
./node_modules/kafkajs/src/consumer/consumerGroup.js
Module parse failed: Unexpected token (155:34)
You may need an appropriate loader to handle this file type.
|       const safeAssignment = arrayDiff(assignedTopics, topicsNotSubscribed)
|       currentMemberAssignment = safeAssignment.reduce(
|         (assignment, topic) => ({ ...assignment, [topic]: decodedAssignment[topic] }),
|         {}
|       )

I am loading:
 const consumer = new Consumer({
    groupId: 'eurostar-group'
});
Using a typescript project with create-react-app, in my another project on node is working fine

**Comment by tulios** [comment]
Hi @esuarezz, you shouldn't import `consumerGroup` directly, the only public API is what is exposed in the index. Can you explain a bit more your use case?
To use it in the browser you will need to transpile the code with browserify or something similar. We are not supporting this right now, but maybe we can help.

**Comment by tulios** [comment]
Please, re-open the issue if you need.
