### ISSUE TITLE
Converting byte[] to Kafka Connect data failed due to serialization error: java.io.CharConversionException: Invalid UTF-32 character 0xed7a2268. #182 #183

### ISSUE THREAD

**Issue by sudheer9640** [tulios/kafkajs#1280]
**Describe the bug**

**To Reproduce**
Please provide either a link to a:

1. While publishing nested json data encoded using @kafkajs/confluent-schema-registry library, to kafka topic with json schema 
Message is getting inserted to topic.
While using http sink connector with value convertor as org.apache.kafka.connect.json.JsonConverter
getting the above error.
So do we need to encode the json payload using @kafkajs/confluent-schema-registry library or can we send payload as string using JSON.stringify.

**Comment by Nevon** [comment]
I'm going to close this as it's not an issue with KafkaJS. The issue tracker is not a support forum, and definitely not for things that aren't KafkaJS.

I would suggest [reading the documentation](https://docs.confluent.io/platform/current/schema-registry/connect.html#using-kconnect-long-with-sr) for Kafka Connect and how to use it together with JSON Schema and schema registry.
