### ISSUE TITLE
tutorial for beginner....help me

### ISSUE THREAD

**Issue by Lora336** [tulios/kafkajs#1295]
[](url)hi,  guys.
'kafkajs' is hard to understand. So I try to tutorial, but failed.

i am using just 'react.js' and 'visual studio'
and this is my step for using 'kafkajs'

step 1. 
npm install kafkajs

setp 2.
I try this code in 'https://www.npmjs.com/package/kafkajs's Usage

```
const { Kafka } = require('kafkajs')

const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['kafka1:9092', 'kafka2:9092']
})

const producer = kafka.producer()
const consumer = kafka.consumer({ groupId: 'test-group' })

const run = async () => {
  // Producing
  await producer.connect()
  await producer.send({
    topic: 'test-topic',
    messages: [
      { value: 'Hello KafkaJS user!' },
    ],
  })

  // Consuming
  await consumer.connect()
  await consumer.subscribe({ topic: 'test-topic', fromBeginning: true })

  await consumer.run({
    eachMessage: async ({ topic, partition, message }) => {
      console.log({
        partition,
        offset: message.offset,
        value: message.value.toString(),
      })
    },
  })
}

run().catch(console.error)
```

but, errors occurred. what happend?
no one explains to me. please answer me. 
what more do you need?......
![image](https://user-images.githubusercontent.com/85551779/154246737-9bf2a258-b038-4ab8-95c3-8d60efb07eee.png)

**Comment by Nevon** [comment]
Please see [Can KafkaJS be used in a browser?](https://kafka.js.org/docs/faq#can-kafkajs-be-used-in-a-browser)
