### ISSUE TITLE
Ping check for availability of all Kafka brokers and zoo keeper

### ISSUE THREAD

**Issue by sureshballa** [tulios/kafkajs#1296]
Hi team,

As part of our distributed architecture based on EDA where Kafka is our event hub, we wanted to bring down services in the event Kafka not being available, so we are writing k8s health checks to check the connectivity of Kafka. Currently, we are using Kafka admin API method listTopics. Could you please suggest if we have a better or right way to check if Kafka is available (specifically around all brokers being available)? I guess admin API method listTopics will still get data if even all brokers are down.

**Comment by Saeger** [comment]
Maybe you could do something like this:
```
  public async ping(): Promise<string | null> {
    this.log.debug('Pinging Kafka Cluster');
    try {
      const clusterInfo = await this.admin.describeCluster();
      this.log.debug(`Ping successfull ${clusterInfo?.clusterId}`);
      return null;
    } catch (error) {
      this.log.error('Ping to Kafka was unsuccessful', error);
      return error.message;
    }
  }
```

**Comment by otroboe** [comment]
Would it be more efficient to listen to [events](https://kafka.js.org/docs/instrumentation-events)?
Like the events `CONNECT` and `DISCONNECT`, and save in DB when it's connected or disconnected.

**Comment by otroboe** [comment]
> No, the events won't tell you about transient disconnects. However, the efficiency isn't the real problem. The real problem is that you really shouldn't worry about connections. Magnus Edenhill, the author of librdkafka, says it really well in his FAQ: https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

I see, thank you for the link! 
So we should blindly trust that the event is gonna be pushed in Kafka no matter what...? It seems too much optimistic for me.  Nothing has a 100% uptime right?
