### ISSUE TITLE
Subscribe to a specific partition of a topic

### ISSUE THREAD

**Issue by yusuf5033** [tulios/kafkajs#1331]
How can we subscribe to a specific partition of a topic ? for example like partition number 4

I'm trying;

`await consumer.subscribe({ topic: "my-topic",  partition: 3 });`

But it does not seem to work.

**Comment by Nevon** [comment]
You cannot. The API you're looking for is called `assign`, and KafkaJS does not support manual assignment.

Closing as duplicate of #373
