### ISSUE TITLE
False [Topic authorization failed] error for topic

### ISSUE THREAD

**Issue by dgyimesi** [tulios/kafkajs#1346]
**Describe the bug**

Broker reports [Topic authorization failed] for a topic that KafkaJS could publish to before in the same Producer instance.
Broker provider: Confluent

**To Reproduce**
1. set up ACL for your API key (eg. this.is.my.env, PREFIXED)
2. create a producer instance
3. send a message to a topic that matches your ACL, like 'this.is.my.env.created', it will pass
4. send a message to a topic that does NOT match your ACL, like 'this.is.my.otherenv.created', it will fail with error above (as expected)
5. as in step 3. send a message to a topic that matches your ACL, like 'this.is.my.env.created', it will fail again with the same error (unexpected)

**Expected behavior**
Messages that matches the ACL will pass even if there were failing attempts before

**Environment:**
 - OS: [e.g. Windows 10]
 - KafkaJS version [e.g. 1.14.0, 1.15.0, 2.0.0]
 - NodeJS version [e.g. 16.14.0]

**Additional context**
During debugging I found that the Metadata protocol message buffer contains the forbidden topic name after encoding, even at step 5. send() gets only one topic (that matches the ACL) as a parameter, still the buffer contains the topic name from my previous send attempt.

**Comment by Nevon** [comment]
I was able to reproduce this here: https://github.com/tulios/kafkajs/blob/8cbfb1b88505b2dbf5bcb9bc6e8234d771f1e9bb/src/admin/__tests__/createAcls.spec.js#L255-L304

**Comment by dgyimesi** [comment]
Since my report I found an additional use case which leads to the same issue. Regardless of ACLs on your topics publishing to an existing topic after an attempt to publish to a non-existing one has the same effect, except that the error message will be "This server does not host this topic-partition", presumably because of the very same beheviour on metadata fetching as described above.

**Comment by dgyimesi** [comment]
@Nevon as I see #667 is still open and not approved. Any plans to incorporate it in the next release?

**Comment by mattia-crypto** [comment]
I have a similar issue here: #1377

**Comment by Nevon** [comment]
Sorry to disappoint, but the direction in #667 isn't going to work, as I realized once I spent a few days on it and the cracks started to show. I've elaborated in https://github.com/tulios/kafkajs/pull/667#issuecomment-1143543733

In the meantime, I think this specific issue can probably be solved with a bit of a quick-fix by just removing the topic from `targetTopics` when we get an authorization error on metadata refresh.

**Comment by Nevon** [comment]
Fixed by #1385
