### ISSUE TITLE
Allocation strategy for connections in connection pools

### ISSUE THREAD

**Issue by thereisnospoon** [tulios/kafkajs#1352]
Hi,

We have many replicas of the same Node.js application producing messages to a set of Kafka topics. Each application replica uses single kafkajs producer to distribute records across more than 20 topics. During peak hours we have around 300 application replicas running in parallel. At the same time in monitoring we see that that the number of active connections is more than 8k:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/2090448/167906532-535a2853-fbb5-4b37-b1a9-4a39795ef051.png">

This is a bit surprising. I wonder if this can be explained by each producer using large connection pools (e.g. 20-30 connections per pool). 

It would be great if someone could clarify if my assumption is correct. After quick glance into kafkajs internals I could see that seemingly the max number of connections in a pool is just `2` [link](https://github.com/tulios/kafkajs/blob/4246f921f4d66a95f32f159c890d0a3a83803713/src/network/connectionPool.js#L19). But for sure I am missing something.

**Comment by Nevon** [comment]
Each producer will use 2 connections per broker that it needs to communicate with. So if you have a cluster of say 10 brokers, that will be up to 20 connections per producer. 300 * 20 = 6000 connections in total (or 600 per broker).

**Comment by thereisnospoon** [comment]
Thank you for clarification, @Nevon !

I've checked the cluster brokers using `kafka-broker-api-versions` and it appears that there are 25 brokers. In such case wouldn't there be even more connections (25 * 2 * 300 = 15,000)?

**Comment by Nevon** [comment]
The producers connect to brokers on demand, so if a producer is only producing to a subset of partitions, it will likely not connect to every broker. That's why I mentioned _up to_.

**Comment by thereisnospoon** [comment]
Thank you @Nevon
