### ISSUE TITLE
first page of getting started doesn't work

### ISSUE THREAD

**Issue by flyingwolf1701** [tulios/kafkajs#1357]
**Describe the bug**
When I try and create the getting started page it won't work. In order to get it to work I had to have someone experienced help me create a docker yaml file. This tutorial is missing some very key information. It certainly is not adequate for a newbie.

**Comment by Nevon** [comment]
Thanks for the feedback.

Our documentation is not intended as an introducing to _Kafka_ in general. That scope would be far too big for us to be able to take on. It is intended as documentation for _KafkaJS_ itself. It assumes that the reader is already familiar with Kafka and has a cluster to connect to.

For information on getting started with Kafka itself, I would refer you to [the Kafka documentation](https://kafka.apache.org/quickstart)
