### ISSUE TITLE
Logger still work after call disconnect(), this make jest error

### ISSUE THREAD

**Issue by vvtri** [tulios/kafkajs#1367]
I am running test with jest and find out jest do not exist after test done, after some troubleshooting, I know problem is kafka logger still work after I call disconnect method. This cause problem with CICD
![image](https://user-images.githubusercontent.com/82482496/169518433-ec7157e6-5da8-4d66-819c-442a698a6659.png)

**Comment by Nevon** [comment]
In your screenshot, we can see that the log is coming from a consumer, but in your shutdown code you are disconnecting a producer. As you can tell from our codebase, we use jest to test kafkajs, and the tests shut down cleanly when disconnecting consumers/producers.
