### ISSUE TITLE
Consumer method for retrieving all current topics.

### ISSUE THREAD

**Issue by jfaulstick** [tulios/kafkajs#137]
Can we have a consumer method for retrieving all current topics to in code ahead of subscribing?

**Comment by tulios** [comment]
Hi @jfaulstick, I'm not sure I understood your question, can you give me more details or some pseudo code of what you want?

**Comment by jfaulstick** [comment]
What would be great is to have the ability to write a consumer that can fetch a list of all of the current topics from the server without having to know the topic names ahead of time. Here is an example of how kafka-node does it.

https://www.npmjs.com/package/kafka-node#how-do-i-get-a-list-of-all-topics

**Comment by tulios** [comment]
Right, we can do it. The library already has support for that; we can add this as an admin operation.

**Comment by tulios** [comment]
`admin#fetchTopicMetadata()` can fetch all topics now; issue #336 will add subscribe by regex, which should address this. I will close the issue, for now, feel free to re-open if you think that #336 won't solve all concerns.
