### ISSUE TITLE
Consumer runner tries to start the fetch manager without delay

### ISSUE THREAD

**Issue by adripc64** [tulios/kafkajs#1384]
**Describe the bug**
When the FetchManager detects that a kafka node is lost, it tries to rebalance the fetchers. If there are no kafka nodes available, no fetchers are created. That causes the consumer runner to call FetchManager.start() in an infinite loop without any delay.
**This blocks any other processing like responding to http requests**. Also, the consumer is not disconnected properly nor can recover when kafka is available again.

**To Reproduce**
1. Having a kafka with a single node
2. Run a consumer that subscribes to a topic and consumes messages
3. Stop kafka instance
4. The consumer runner tries to rebalance fetchers. As there are no nodes, no fetchers are created. The consumer runner is calling FetcherManager.stat() continuosly without any delay, so blocking any other kind of processing in node.js

**Expected behavior**
The consumer should be disconnected properly and start retrying to connect it again.
As a hint, we have managed to solve this issue adding a simple delay of 1ms after the call to FetcherManager.stat(). Example:

```ts
async scheduleFetchManager() {
    this.consuming = true

    while (this.running) {
      try {
        await this.fetchManager.start()
        await new Promise(resolve => setTimeout(resolve, 1));
      } catch (e) {
      ...
      }
    }
    ...
}
```

**Observed behavior**
```
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.213Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Created 0 fetchers","nodeIds":[],"concurrency":1}
{"level":"DEBUG","timestamp":"2022-06-02T09:57:05.214Z","logger":"kafkajs","message":"[FetchManager] Starting..."}
```

**Environment:**
 - OS: Mac OS 11.3.1
 - KafkaJS version 2.0.2
 - Kafka version 6.0.0
 - NodeJS version 17.1.0

**Additional context**

**Comment by Nevon** [comment]
> do we have an ETA for a fix for this one?

No, that's not how free, open-source projects work. If this is very important to you, you are more than welcome to spend the resources to fix the issue. I'm in the middle of my vacation, and even once I'm back, no one other than me decides what I should spend my free time on.

**Comment by tugtugtug** [comment]
> > do we have an ETA for a fix for this one?
> 
> No, that's not how free, open-source projects work. If this is very important to you, you are more than welcome to spend the resources to fix the issue. I'm in the middle of my vacation, and even once I'm back, no one other than me decides what I should spend my free time on.

Sorry @Nevon if my question offended you and sorry to have interrupted your vacation. Maybe we have a different view on how open-source projects work. If I were a maintainer of a open-source project, I would certainly feel some responsibility for the quality of my product and if the issue has wide impact, I would probably put it as a priority (if I'm not on vacation, and have free time, of course). 
I think your vent above certainly doesn't mean that you will just ignore this issue. Maybe you felt I was pushing you like I was a paying customer. I did try to put some urgency color to the issue, but that's that's typical response when the user of the product feels devastated trying to seek help to a deadly problem, hope you could understand.
I'm not sure I would be familiar enough to the project to contribute code in the same quality standard that I would hold for any of my code I release, thus I decided to create an issue with details of my analysis (#1387) to help whoever that may be able to fix this more professionally.

**Comment by adripc64** [comment]
In the issue description I shared a 1-line fix that worked for me. I didn't opened a PR with such fix because I thought that someone with more knowledge about the project could implement a better solution. However, if you think that fix is acceptable I'll be pleased to open a PR.

**Comment by ixalon** [comment]
I've hit this problem too. I've applied a workaround using logging (horrid, hacky, but temporary) for the time being. The following approach prevents the tight loop (needs tweaked for whatever logging system you're using) without needing a patched copy of kafkajs.

```
new Kafka({
  ...
  logLevel: logLevel.DEBUG,
  logCreator: (level) => (entry) => {
    if (level == logLevel.DEBUG) {
      if (entry.log.message.startsWith('Created 0 fetchers')) {
        throw new Error('No brokers available! Avoiding tight loop. See: https://github.com/tulios/kafkajs/issues/1384');
      }
    } else {
      console.log(entry.log.message);
    }
  }
});
```

**Comment by chranmat** [comment]
I have today discovered that we are facing the same issue as you describe after several weeks of high CPU load from time to time. I have now tried to implement the workaround that @adripc64 describes by adding the following line;

`await new Promise(resolve => setTimeout(resolve, 1));`

When doing this a new issue occurs. Every x (10ish) second, reports the following messages, and re-connects:

`{"level":"ERROR","timestamp":"2022-06-22T17:57:55.692Z","logger":"kafkajs","message":"[Connection] Response OffsetCommit(key: 8, version: 5)","broker":"servicebus:9092","clientId":"6b128c7bf805","error":"The coordinator is not aware of this member","correlationId":97,"size":32}`

`{"level":"ERROR","timestamp":"2022-06-22T17:57:55.694Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"servicebus:9092","clientId":"6b128c7bf805","error":"The coordinator is not aware of this member","correlationId":99,"size":10}`

`{"level":"ERROR","timestamp":"2022-06-22T17:57:55.694Z","logger":"kafkajs","message":"[Runner] The coordinator is not aware of this member, re-joining the group","groupId":"orderservice","memberId":"6b128c7bf805-8f19dce5-b0cf-4c3c-b178-37642d7a1ca2","error":"The coordinator is not aware of this member"}`

`{"level":"INFO","timestamp":"2022-06-22T17:57:55.696Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"orderservice","memberId":"6b128c7bf805-3bcbbf76-ad8e-46aa-b33b-8d512fb2ad2f","leaderId":"6b128c7bf805-3bcbbf76-ad8e-46aa-b33b-8d512fb2ad2f","isLeader":true,"memberAssignment":{"ACL":[0],"announce":[0],"ORDER":[0]},"groupProtocol":"RoundRobinAssigner","duration":30010}`

It seems like this additional 1ms wait causes the heartbeat to be "out of sync". @adripc64 or @Nevon, is there another workaround I possibly can implement? I will try to investigate more to possibly find one, but if you know any obvious, please shout out.

**Comment by chranmat** [comment]
Now also tried to apply the patch as described by @tugtugtug, and same issue occurs:

`[Runner] The coordinator is not aware of this member, re-joining the group`

**Comment by Nevon** [comment]
Opened up #1402 to fix this. The issue was that the rebalancing mechanism in the FetchManager would detect that the number of available nodes had changed, and trigger the recreation of the fetchers. Because there were no available nodes, no fetchers were created, and we entered the infinite tight loop. By bypassing the rebalancing mechanism in case there are no nodes available, the fetcher ends up attempting to fetch from the now unavailable node, and a KafkaJSConnectionError bubbles up as expected, causing the consumer to try to reconnect and eventually crash - same as in 1.16.0.

**Comment by pravin-raha** [comment]
Still facing same problem. Anyone have same issue even with 2.1.0 version. Am I missing something. Do I need to set something in configuration. I tried to resolve the problem with #1428.
