### ISSUE TITLE
The requested module 'kafkajs' does not provide an export named 'CompressionCodecs'

### ISSUE THREAD

**Issue by Kiddinglife** [tulios/kafkajs#1391]
**Describe the bug**
Import `CompressionCodecs` in typescript project. Got error message
`The requested module 'kafkajs' does not provide an export named 'CompressionCodecs'`

**To Reproduce**
```typescript
import {
  CompressionCodecs,
  CompressionTypes,
  Kafka,
  logCreator,
  logLevel,
} from "kafkajs"
import LZ4Codec from "kafkajs-lz4"

const lz4Codec = new LZ4Codec({
  preferences: {
    compressionLevel: 12,
  },
}).codec
CompressionCodecs[CompressionTypes.LZ4] = lz4Codec
```
then run npm run build, I got the error message shown in the top.

**Expected behavior**
should compile successfully

**Observed behavior**
The requested module 'kafkajs' does not provide an export named 'CompressionCodecs'

**Environment:**
 - OS: MacOS
 - KafkaJS version  1.15.0
 - Kafka version 2.3.1
 - NodeJS version 14
 
 **PR**
https://github.com/tulios/kafkajs/pull/1393

**Comment by Nevon** [comment]
I'm not sure I understand what's happening here, but I suspect it comes from mixing up CommonJS and ESM. KafkaJS uses CommonJS, where you only have a single exported object, so indeed there is no named export. I suspect that if you did this, it would work:

```ts
import KafkaJS from "kafkajs"

const { CompressionCodecs } = KafkaJS
```

You can see that we are in fact validating that the CompressionCodecs are being exported in our type validation check: https://github.com/tulios/kafkajs/blob/48b8bc72512d94331790712c22382b449e906445/types/tests.ts#L289

Could you share some more information about how you are compiling your project? Your tsconfig might be helpful.

**Comment by bgeisberger** [comment]
I've encountered the same issue when using kafkajs with ESM. Using https://github.com/nodejs/cjs-module-lexer/ (which is the reference for the lookup process of named imports in ESM code from CommonJS modules) on the `index.js` file, I can only see a few detected exports: 
```
 [
      'Kafka',
      'PartitionAssigners',
      'AssignerProtocol',
      'Partitioners',
      'logLevel',
      'CompressionTypes'
]
```

This improves with some adjustments to the file which should not affect its usage in CommonJS, but improve it in ESM:
```
[...]
const { LEVELS } = require('./src/loggers')
const CompressionCodecs = Compression.Codecs
const CompressionTypes = Compression.Types

module.exports = {
  Kafka,
  PartitionAssigners,
  AssignerProtocol,
  Partitioners,
  logLevel: LEVELS,
  CompressionTypes,
  CompressionCodecs,
  ConfigResourceTypes,
  AclResourceTypes,
  AclOperationTypes,
  AclPermissionTypes,
  ResourcePatternTypes,
  ConfigSource,
  ...errors
}
```


The resulting imports are now:
```
[
      'Kafka',
      'PartitionAssigners',
      'AssignerProtocol',
      'Partitioners',
      'logLevel',
      'CompressionTypes',
      'CompressionCodecs',
      'ConfigResourceTypes',
      'AclResourceTypes',
      'AclOperationTypes',
      'AclPermissionTypes',
      'ResourcePatternTypes',
      'ConfigSource'
]
```

This is still not everything, because the errors are not detected. I couldn't figure out a way to do this until now.

**Comment by bgeisberger** [comment]
Honestly, I have no idea. For me, it looks like the name detection just stops at the `CompressionCodecs` entry if it is not declared as `const` before.

**Comment by Kiddinglife** [comment]
closed. problem solved thx all.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
