### ISSUE TITLE
Kafka-node vs kafkajs Producer

### ISSUE THREAD

**Issue by harshagarwal00** [tulios/kafkajs#1394]
I am confused if to use kafkajs producer or Kafka-node producer..
Configuring kafka-node producer seems very easy.. just very small code..
kafkajs seems more involved..
https://kafka.js.org/docs/producer-example
catching all these signals:

```
const errorTypes = ['unhandledRejection', 'uncaughtException']
const signalTraps = ['SIGTERM', 'SIGINT', 'SIGUSR2']
```

**Comment by Nevon** [comment]
You haven't shown any comparison, but the signal handling is there as a reference for how to cleanly shut down. You would need to do the exact same thing in kafka-node - they might just not have included shutting down in their examples.

Closing this as it is not an issue.
