### ISSUE TITLE
Handle kafka message

### ISSUE THREAD

**Issue by Sergio9777** [tulios/kafkajs#1395]
I would like handle the errors that kafka returns when something fails.
For example, im trying to create topic that already exists and it returns one error, but i want to use that error to inform about the specific type of error.
I can only manage the result of the function, in this case, false if the topic isnt created or true if it is. But with this information i cant really know what is the problem if i dont watch the console.
![imagen](https://user-images.githubusercontent.com/60984280/174276024-4a5d27a2-5079-4b0f-889a-962f1aa9945f.png)

**Comment by Nevon** [comment]
You can switch on the `name` property of the thrown error to know which type of error it is. They are all listed [here](https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L1044-L1213). For generic KafkaJSProtocolErrors, you have the `code` property which corresponds to the [error code in the Kafka protocol](https://kafka.apache.org/protocol.html#protocol_error_codes).
