### ISSUE TITLE
Make maxWaitTimeInMs doc more accurate

### ISSUE THREAD

**Issue by thomaslule** [tulios/kafkajs#1397]
**Is your feature request related to a problem? Please describe.**
We encountered the same problem as https://github.com/tulios/kafkajs/issues/370 : we were experiencing a 5s lag from kafka and we didnt understand where it came from.

We saw the `maxWaitTimeInMs` option but discarded this lead because of the documentation:

> The maximum amount of time in milliseconds the server will block before answering the fetch request if there isn’t sufficient data to immediately satisfy the requirement given by minBytes

(from https://kafka.js.org/docs/consuming#options)

Our `minBytes` option had the default value 1, so by reading the doc we thought that `maxWaitTimeInMs` had no effect in our case.

Turns out that we resolved the problem by reducing `maxWaitTimeInMs`.

**Describe the solution you'd like**
I believe that the doc doesnt describe exactly what this option does? In my understanding, in case of multi brokers, this is the polling interval for new messages even if the available messages are larger than `minBytes`.

**Comment by Nevon** [comment]
Your understanding is the same understanding that I have, which is based on the Kafka documentation:

> **[fetch.min.bytes](https://kafka.apache.org/documentation/#consumerconfigs_fetch.min.bytes)**
> The minimum amount of data the server should return for a fetch request. If insufficient data is available the request will wait for that much data to accumulate before answering the request. The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.

> **[fetch.max.wait.ms](https://kafka.apache.org/documentation/#consumerconfigs_fetch.max.wait.ms)**
> The maximum amount of time the server will block before answering the fetch request if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.

> **[fetch.max.bytes](https://kafka.apache.org/documentation/#brokerconfigs_fetch.max.bytes)**
> The maximum number of bytes we will return for a fetch request. Must be at least 1024.

> **[max.partition.fetch.bytes](https://kafka.apache.org/documentation/#consumerconfigs_max.partition.fetch.bytes)**
> The maximum amount of data per-partition the server will return. Records are fetched in batches by the consumer. If the first record batch in the first non-empty partition of the fetch is larger than this limit, the batch will still be returned to ensure that the consumer can make progress. The maximum record batch size accepted by the broker is defined via message.max.bytes (broker config) or max.message.bytes (topic config). See fetch.max.bytes for limiting the consumer request size.

Based on this, if you have at least 1 byte available in at least one of the partitions, the broker should not block and immediately return the response, given `minBytes = 1`.

I did a simple test using the producer and consumer from the [examples](https://github.com/tulios/kafkajs/tree/master/examples), where I just listen to the consumer `FETCH` event and output the duration (how long the request took). Running the consumer subscribed to an empty topic, we can see that the fetch request took approximately 5 seconds:

```
info:  ┏ [Consumer] Received fetch response
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2022-06-27T07:32:02.617Z",
info:  ┃ [2]   "logger": "kafkajs",
info:  ┃ [3]   "numberOfBatches": 0,
info:  ┃ [4]   "duration": 5004,
info:  ┃ [5]   "nodeId": "1"
info:  ┗ [6] }
```

After producing a single message to the topic, the fetch request took a little over 100ms:

```
info:  ┏ [Consumer] Received fetch response
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2022-06-27T07:32:13.028Z",
info:  ┃ [2]   "logger": "kafkajs",
info:  ┃ [3]   "numberOfBatches": 0,
info:  ┃ [4]   "duration": 123,
info:  ┃ [5]   "nodeId": "1"
info:  ┗ [6] }
```

You didn't specify what version of KafkaJS you were using, but I suspect what you're running into is a limitation of how versions <2.0.0 used to work, where a consumer would wait to get the fetch response from all brokers before starting to process the batches. So this meant that if your consumer was assigned partitions across 2 brokers, one of the partitions had >0 bytes of data available but the partitions on the other broker did not have any data available yet, the batches from the first broker would immediately return but not be processed until you got the response from the second broker (after the 5 second wait). In KafkaJS versions >= 2.0.0 this is no longer the case. Responses will now be processed independently of outstanding requests towards other brokers.

**Comment by thomaslule** [comment]
Mmmh ok I still dont really understand what happened and why the server was blocking the response, but I tried with kafkajs version 1.16.0 and 2.0.2, I had the same behaviour.

I didnt realize those config options were tied to kafka config, maybe it would help to have the links in the doc: `maxWaitTimeInMs` = `fetch.max.wait.ms` and so on?

**Comment by Nevon** [comment]
They are not tied to any broker config. They are just the equivalent of the Java client options. Sometimes we have equivalent options, and sometimes we have different options, depending on how the clients are structured.

> I tried with kafkajs version 1.16.0 and 2.0.2, I had the same behaviour.

Another thing to consider is that when the consumer fetches data, it fetches data for all partitions it is subscribed to that are available from a given broker. So say your consumer is assigned partitions 1, 2 and 3. Partitions 1 and 2 are available from broker A, and partition 3 is available from broker B. It will make one request to broker A and one request to broker B. Assuming that partitions 1 and 3 have data available, but partition 2 does not, broker A will block for up to `maxWaitTimeInMs` (assuming that partition 1 does not have enough data to satisfy `minBytes`) and broker B will respond immediately.

In your case, you were saying that you were using the default config, where `minBytes` is set to 1, so I would expect it to respond immediately as long as all the requested partitions on the given broker has at least 1 byte of new data for you.
