### ISSUE TITLE
data.topicMetadata.flatMap is not a function

### ISSUE THREAD

**Issue by heritechie** [tulios/kafkajs#1398]
**Describe the bug**
kafka setup locally using the following [docker-compose](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui.yaml) file, on the other side I want to connect existing nodejs project but the log give me error message related to **flatMap** function

**To Reproduce**
1. using NodeJS version 10.13.0

**Expected behavior**
kafka client connected successfully .

**Observed behavior**
`{"level":"ERROR","timestamp":"2022-06-21T08:39:17.466Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 6)","broker":"192.168.100.67:9092","clientId":"kafka-client-dev","error":"data.topicMetadata.flatMap is not a function","correlationId":1,"size":118}`

**Environment:**
 - OS: Mac OS [12.4]
 - KafkaJS version [2.0.2]
 - Kafka version [docker-image: confluentinc/cp-kafka:5.3.1]
 - NodeJS version [10.13.0]

**Comment by Nevon** [comment]
Node 10 has been end-of-life since over a year ago, and is not supported by KafkaJS.

https://github.com/tulios/kafkajs/blob/a733eaa2f215c8d763da4a595c50f65fcd050566/package.json#L14-L16

Please upgrade to a supported version of nodejs.
