### ISSUE TITLE
Producer trying to connect to MSK Cluster using Lambda function but, "[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout"

### ISSUE THREAD

**Issue by dilshan-98** [tulios/kafkajs#1409]
Please help @tulios @Nevon @meister @Dieken @pihentagy 

When trying to connect to MSK cluster through a Lambda function, it shows below error.

{     "level": "ERROR",     "timestamp": "xxxxx",     "logger": "kafkajs",     "message": "[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout",     "retryCount": 0,     "retryTime": 350 }
--
ERROR	{     "level": "ERROR",     "timestamp": "xxxxx",     "logger": "kafkajs",     "message": "[Connection] Connection timeout",     "broker": "b-1.xxxxx.xxxxx.xxxx.xxxxx.xxxxx-xxxxx-xxxxx.amazonaws.com:9094",     "clientId": "my-app-1" }

I have tried accessing the brokers through plaintext, IAM and TLS authentication types but every time it gives the same error after 6seconds timeout.
My code snippet for Kafka producer (here brokers are given in TLS format):

`const clientId = "my-app-1";

const brokers = [`b-2.xxxxmskcluster.xxxxxx.xxxxx.xxxx.xxxx-xxxxxx-xxxxxx.amazonaws.com:9094`, `b-1.xxxxxxmskcluster.xxxxx.xx.xxx.xxxx-xxxx-xxxx.amazonaws.com:9094`];

const topic = "AWSKafkaTopic1";

  const kafka = new Kafka({
    clientId,
    brokers,
    ssl: true,
});

 const producer = kafka.producer({
    retry: 5,
    idempotent: true,
    transactionTimeout: 10000
  });

await producer.connect();`

**Comment by dilshan-98** [comment]
I was missing some configuration criteria

**Comment by Jrakk19** [comment]
@dilshan-98 What criteria exactly were you missing ? I am having the same error so I am curious if I am missing something.
