### ISSUE TITLE
Broadcast messages to multiple consumers

### ISSUE THREAD

**Issue by Aemiro** [tulios/kafkajs#1420]
I have used kaskajs with NestJs for the last 5 months but I saw that apache kafka does not support broadcast message to multiple consumers or groupids. So is there any way to implement this feature on the core implementation

**Comment by Nevon** [comment]
KafkaJS is not Kafka, so this would be better raised in a Kafka support forum than in the issue tracker of this client.

There's no "broadcast" exactly in Kafka, but if you publish a message to a topic it can be consumed by multiple consumer groups. It will still only be consumed by one consumer of that group (without getting into at-least-once semantics). But considering the term "broadcast", I'm not sure that Kafka is appropriate for what you're doing. If you want to "broadcast" your message to a number of different systems, then just have those systems have their own consumer groups and everything will work just fine. If you want to broadcast to every instance of one or more systems, then Kafka is probably not what you should use.
