### ISSUE TITLE
 Consumer-aware concurrency

### ISSUE THREAD

**Issue by iljaiwjew** [tulios/kafkajs#1433]
Hi, I know it's possible to adjust concurrency for partition but is it possible somehow to handle only one batch per time for along the all  topics consumer subscribed to? does maxInFlightRequests allow it?

**Comment by Nevon** [comment]
That is how the consumer works today. `partitionsConsumedConcurrently` controls how many batches are processed concurrently, regardless of which topic(s) the partitions belong to. In other words, if you have `partitionsConsumedConcurrently: 1`, it doesn't matter if you're assigned 3 partitions from 1 topic or from 3 different topics, you'll still be processing one partition at any given time.
