### ISSUE TITLE
Using kafkajs on nodejs cluster consumes all inodes

### ISSUE THREAD

**Issue by vasmanas** [tulios/kafkajs#144]
We are using kafkajs with nodejs cluster. Forking multiple workers, one for each partition. Service consumes inodes each minute and never releases. What could be the cause of it?

**Comment by tulios** [comment]
@vasmanas can you post some example code? I've tested the cluster code running one consumer per worker. In my example, I have a topic with 6 partitions, and I run 6 workers, each consuming from one partition. This example worked fine, but I haven't checked the inodes.

Or perhaps you are talking about consuming the messages and passing to workers for processing?

My example, based on the consumer example in the repo: https://gist.github.com/tulios/1605365a6c136c9726172a364bdcfc64

**Comment by vasmanas** [comment]
@tulios here is a simplified code example that we use:

**Comment by vasmanas** [comment]
@tulios here is a simplified code example that we use:

**Comment by vasmanas** [comment]
@tulios here is a simplified code example that we use:
```javascript
const cluster = require('cluster');
const { Kafka } = require('kafkajs');

const clusterMap = {};
const numWorkers = 10;

const createWorker = (env) => {
  const worker = cluster.fork(env);
  clusterMap[worker.id] = env;
};

const onExit = (worker) => {
  try {
    const workerEnv = clusterMap[worker.id];

    // delete the process from the cluster map
    delete clusterMap[worker.id];

    // WORKER AUTO-RESTART
    setTimeout(() => {
      console.info('restarting...');
      createWorker(workerEnv);
    }, 3000);
  } catch (e) {
    console.log(e);
  }
};

const masterRunner = async () => {
  cluster.on('exit', onExit);

  for (let i = 0; i < numWorkers; i + 1) {
    createWorker({ index: i });
  }
};

const workerRunner = async () => {
  const kafka = new Kafka({
    clientId: 'myClientId',
    brokers: ['127.0.0.1:9092'],
    heartbeatInterval: 10000,
    sessionTimeout: 120000,
    maxBytes: 524288,
    maxWaitTimeInMs: 30000,
  });

  const consumer = kafka.consumer({ groupId: `${process.env.group}` });

  try {
    await consumer.connect();
    await consumer.subscribe({ topic: process.env.topic });
    await consumer.run({
      autoCommitThreshold: 10,
      eachMessage: async ({ topic, partition, message }) => {
        const prefix = `${topic}[${partition} | ${message.offset}] / ${message.timestamp}`;
        console.log(`- ${prefix} ${message.key}#${message.value}`);
      },
    });

    const awaitStop = new Promise((resolve, reject) => {
      const { STOP } = consumer.events;

      consumer.on(STOP, (e) => {
        try {
          console.log(`stop at ${e.timestamp} - ${JSON.stringify(e)}`);
        } catch (error) {
          reject();
        } finally {
          resolve();
        }
      });
    });

    await awaitStop;
    await consumer.disconnect();
  } catch (e) {
    console.log(e);
    await consumer.disconnect();

    throw e;
  }
};

const run = async () => {
  try {
    if (cluster.isMaster) {
      await masterRunner();
    } else {
      await workerRunner();
    }
  } catch (e) {
    console.log(e);
  }

  if (cluster.isWorker) {
    process.exit();
  }
};

run();
```

**Comment by Nevon** [comment]
You are creating infinite workers. I logged the `clusterMap` every time `createWorker` was being invoked. This is the output after about half a second:

![screen shot 2018-10-08 at 10 29 28](https://user-images.githubusercontent.com/83586/46598670-36c4f880-cae5-11e8-8413-dbf798963623.png)

It's because you are not re-assigning the value of `i` in your for-loop.

This is an infinite loop: `for (let i = 0; i < 10; i + 1) {}`. To make it actually terminate, you need to reassign i: `for (let i = 0; i < 10; i++) {}` or `for (let i = 0; i < 10; i = i + 1) {}`.
