### ISSUE TITLE
AWS MSK with IAM Error 33: The broker does not support the requested SASL mechanism when trying to connect with KafkaJS

### ISSUE THREAD

**Issue by cr-urra** [tulios/kafkajs#1470]
Hello,

Currently I am testing with an EC2 instance with the Amazon Linux image, where I have loaded an application in Node with KafkaJS, to produce and consume messages with a cluster in MSK, initially I made simple tests connecting without authentication, up to that point everything It was going well, however when trying to test with some security mechanism such as IAM in the MSK, the console returns the following error message:

{"level":"ERROR","timestamp":"2022-10-18T18:36:51.225Z","logger":"kafkajs","message":"[Connection] Response SaslHandshake(key: 17, version: 1)","broker":"b-2.mskdevkfk.y404ub.c19.kafka.us-east-1.amazonaws.com:9098","clientId":"my-app","error":"The broker does not support the requested SASL mechanism","correlationId":1,"size":23}
{"level":"ERROR","timestamp":"2022-10-18T18:36:51.227Z","logger":"kafkajs","message":"[BrokerPool] The broker does not support the requested SASL mechanism","retryCount":0,"retryTime":335}
KafkaJSProtocolError: The broker does not support the requested SASL mechanism
    at createErrorFromCode (/home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/protocol/error.js:581:10)
    at Object.parse (/home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/protocol/requests/saslHandshake/v0/response.js:24:11)
    at Connection.send (/home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/network/connection.js:433:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SASLAuthenticator.authenticate (/home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/broker/saslAuthenticator/index.js:35:23)
    at async /home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/network/connection.js:139:9
    at async Connection.authenticate (/home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/network/connection.js:315:5)
    at async Broker.connect (/home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/broker/index.js:111:7)
    at async /home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/cluster/brokerPool.js:93:9
    at async /home/ec2-user/environment/node-kafka/node_modules/kafkajs/src/cluster/index.js:107:14 {
  retriable: false,
  helpUrl: undefined,
  type: 'UNSUPPORTED_SASL_MECHANISM',
  code: 33,
  [cause]: undefined
}

As additional information, the configuration to connect to the Kafka cluster in the Node application is the same as described in the KafkaJS documentation: https://kafka.js.org/docs/configuration#aws-iam-example

The error message makes me think that the cluster in AWS MSK does not recognize the authentication mechanism sent by KafkaJS, maybe it is the version of the Kafka cluster that I am using incompatible with the IAM authentication mechanism used in KafkaJS? I leave the details of the cluster in MSK configured:

- Kafka version: 2.6.2
- Cluster Type: Provisioned
- Authentication: IAM
- Total number of brokers: 2

Thank you very much.

**Comment by Nevon** [comment]
As the documentation says:

> Use of this functionality requires STACK's Kafka AWS IAM LoginModule, or a compatible alternative to be installed on all of the target brokers.

The AWS IAM authentication mechanism built into KafkaJS predates the IAM authentication mechanism in MSK. The IAM authentication mechanism supported by MSK is not supported by any built in mechanism, but can be implemented as a custom authentication mechanism. For that, see #1098.
