### ISSUE TITLE
Level: "Error" - The group coordinator is not available

### ISSUE THREAD

**Issue by keerthana-inmar** [tulios/kafkajs#1494]
**Describe the bug**

Getting error when i try to subscribe to the given topics at the very first time,

```
{"level":"INFO","timestamp":"2022-11-28T10:44:44.711Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"xxxx"}

**{"level":"ERROR","timestamp":"2022-11-28T10:44:44.740Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 2)","broker":"xxxxx:9093","clientId":"kafkajs","error":"The group coordinator is not available","correlationId":0,"size":55}**

{"level":"INFO","timestamp":"2022-11-28T10:44:45.075Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"xxxx","memberId":"kafkajs-48a24287-cc14-4e7d-8550-e3a2a044f71f","leaderId":"kafkajs-48a24287-cc14-4e7d-8550-e3a2a044f71f","isLeader":true,"memberAssignment":{"3":[0,1,2],"4":[0,1,2],"5":[0,1,2],"6":[0,1,2]},"groupProtocol":"RoundRobinAssigner","duration":363}
```

**To Reproduce**
run the below commands to setup the cluster 
```
bin/zookeeper-server-start.sh config/zookeeper.properties
bin/kafka-server-start.sh config/server.2.properties 
bin/kafka-server-start.sh config/server.1.properties 
bin/kafka-server-start.sh config/server.3.properties 

And create topics using below command 
bin/kafka-topics.sh --create --topic 3  --bootstrap-server localhost:9093 --partitions 3 --replication-factor 2
bin/kafka-topics.sh --create --topic 5  --bootstrap-server localhost:9093 --partitions 3 --replication-factor 2
bin/kafka-topics.sh --create --topic 6  --bootstrap-server localhost:9093 --partitions 3 --replication-factor 2
```

after that , run consumer code of kafkajs.

**Expected behavior**
I hope to see only INFO level messages or WARNING level messages

**Observed behavior**
But happen to see ERROR level at the very first time when i ran consumer code. If i restart the consumer it is not throwing the error. 
This is because, consumer_offsets were not there, when it ran first time. after some time consumer_offsets gets created internally. And then if i start the consumer , i could see INFO messages.

I would like to know, Why its is throwing error when the consumer_offsets topic is been generated internally. If i need to set the properties to suppress the error. please let me know.

**Environment:**
 - OS: ubuntu -22.04
 - KafkaJS version : kafkajs@2.2.2
 - Kafka version : kafka_2.13-3.0.0
 - NodeJS version : v16.17.1

**Comment by ilkkao** [comment]
I'm seeing this same issue in my tests where a topic is created and then the consumer testing starts immediately after. 

Added some delay, but it needs to be multiple seconds. Is there a better solution?

**Comment by keerthana-inmar** [comment]
ok. Thank you. But what i wanted why that is been logged as error. it should have logged as warning right?

**Comment by ilkkao** [comment]
I'm new to kafkajs, not sure. In my case the test fails because "The group coordinator is not available" is an exception. I assumed it's the same underlying issue that generates the error message.

**Comment by keerthana-inmar** [comment]
ok. But the error "The group coordinator is not available" is not blocking functionality. Automatically it creates the group coordinator if its not available. Once the consumer_offsets are available, then the error "group coordinator is not available" is not shown at console(i.e when i restart the application).
Do you have any thought about it?

**Comment by ilkkao** [comment]
agreed, it could be just a warning or info when automatic retry handles the situation.

**Comment by keerthana-inmar** [comment]
Thank you For your time. So i can ignore the error  "group coordinator not available ", because that will not be a problem since automatic retries happen.

**Comment by ErfanSeidipoor** [comment]
I encountered the same issue when initially running the application. However, I discovered that after producing a message and restarting the app, the error disappeared.

**Comment by kasir-barati** [comment]
@keerthana-inmar what you said [here](https://github.com/tulios/kafkajs/issues/1494#issuecomment-1369567429) is correct but I wholeheartedly agree with @ilkkao's [comment](https://github.com/tulios/kafkajs/issues/1494#issuecomment-1369681282). It should be `warn` or `info` and not error. Also probably some link to a doc about how to get rid of it if one wants to do it.
