### ISSUE TITLE
Undefined array key TopicName

### ISSUE THREAD

**Issue by mustarifinmuhtar** [tulios/kafkajs#1495]
[2022-11-29 03:21:41] local.ERROR: Undefined array key "TopicName" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"TopicName\" at /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/gdg-tangier/cloud-pubsub/src/Subscriber/Pipeline/HasTopicName.php:17)
[stacktrace]
#0 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/gdg-tangier/cloud-pubsub/src/Subscriber/Pipeline/HasTopicName.php(17): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): GDGTangier\\PubSub\\Subscriber\\Pipeline\\HasTopicName->handle()
#3 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/gdg-tangier/cloud-pubsub/src/Subscriber/Pipeline/GetMessage.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#4 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): GDGTangier\\PubSub\\Subscriber\\Pipeline\\GetMessage->handle()
#5 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#6 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/gdg-tangier/cloud-pubsub/src/Subscriber/SubscriberQueue.php(164): Illuminate\\Pipeline\\Pipeline->then()
#7 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/gdg-tangier/cloud-pubsub/src/Subscriber/SubscriberQueue.php(127): GDGTangier\\PubSub\\Subscriber\\SubscriberQueue->pipe()
#8 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/gdg-tangier/cloud-pubsub/src/Subscriber/SubscriberQueue.php(111): GDGTangier\\PubSub\\Subscriber\\SubscriberQueue->processMessages()
#9 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(342): GDGTangier\\PubSub\\Subscriber\\SubscriberQueue->pop()
#10 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(351): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}()
#11 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(160): Illuminate\\Queue\\Worker->getNextJob()
#12 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(146): Illuminate\\Queue\\Worker->daemon()
#13 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#14 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#15 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#19 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Illuminate\\Container\\Container->call()
#20 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#21 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Console/Command.php(148): Symfony\\Component\\Console\\Command\\Command->run()
#22 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run()
#23 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#24 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#25 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#26 /home/mande/Mande/Vivobook/AQI/Chalange/admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#27 /home/mande/Mande/Vivobook/AQI/Chalange/admin/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#28 {main}
"} 

please help me

**Comment by tulios** [comment]
@mustarifinmuhtar this is a stack trace from a PHP application. It doesn't make sense to have it here.
