### ISSUE TITLE
Cacheable DNS lookup.

### ISSUE THREAD

**Issue by bokzor** [tulios/kafkajs#1496]
Following the official NodeJS documentation :

> Under the hood, [dns.lookup()](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback) uses the same operating system facilities as most other programs. For instance, [dns.lookup()](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback) will almost always resolve a given name the same way as the ping command. On most POSIX-like operating systems, the behavior of the [dns.lookup()](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback) function can be modified by changing settings in [nsswitch.conf(5)](http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html) and/or [resolv.conf(5)](http://man7.org/linux/man-pages/man5/resolv.conf.5.html), but changing these files will change the behavior of all other programs running on the same operating system.
> 
> Though the call to dns.lookup() will be asynchronous from JavaScript's perspective, it is implemented as a synchronous call to [getaddrinfo(3)](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html) that runs on libuv's threadpool. This can have surprising negative performance implications for some applications, see the [UV_THREADPOOL_SIZE](https://nodejs.org/api/cli.html#uv_threadpool_sizesize) documentation for more information.
> 
> Various networking APIs will call dns.lookup() internally to resolve host names. If that is an issue, consider resolving the host name to an address using dns.resolve() and using the address instead of a host name. Also, some networking APIs (such as [socket.connect()](https://nodejs.org/api/net.html#socketconnectoptions-connectlistener) and [dgram.createSocket()](https://nodejs.org/api/dgram.html#dgramcreatesocketoptions-callback)) allow the default resolver, dns.lookup(), to be replaced.

How is it working internally in KafkaJS ? Is there a caching mechanism for DNS resolution ?

**Comment by Nevon** [comment]
No, KafkaJS does not implement its own DNS layer - it just delegates to the `net`/`tls` modules, which [by default uses `dns.lookup`](https://nodejs.org/api/net.html#socketconnectoptions-connectlistener)

However, we have [the option to provide your own mechanism for creating sockets](https://kafka.js.org/docs/configuration#custom-socket-factory) where you can override any option passed to `net`/`tls` or use something else entirely if you so choose, which means you can provide any DNS lookup mechanism you want to `net.connect`/`tls.connect`.
