### ISSUE TITLE
Consumer does not process messages on startup when no committed offset

### ISSUE THREAD

**Issue by scmorse** [tulios/kafkajs#150]
Reproduce steps:

1. Create a topic (10 partitions is what I used)
2. Produce a message onto that topic at partition 0 / offset 0
3. Start up a consumer for that topic

Expected: The consumer will process the message that was created before it subscribed to the topic

Actual: The consumer does not process the message at partition 0 / offset 1. Creating a message at partition 0 / offset 1 will get picked up by the consumer, but the message at offset 0 is skipped.

I think it should be configurable what happens here as well. When no offset is committed for a particular partition, the consumer should be able to decide if it wants to start from the earliest available offset, or from the latest offset. Again, this would only be used for determining what to do when no offset is committed on a particular partition.

**Comment by tulios** [comment]
Hi @scmorse, this feature is already supported. When you call subscribe just pass `fromBeginning: true`, example:

```javascript
await consumer.subscribe({ topic, from beginning: true })
```

This will be used as the default behavior when the group has no valid offsets, the default value is `false`

**Comment by scmorse** [comment]
@tulios I was under the impression that flag would start all partitions from the beginning even when an offset had been committed, is that not the case? I only want to start from the beginning when an offset has not been committed yet

**Comment by scmorse** [comment]
The `fromBeginning` flag appears to be working (not actually seeking all partitions to 0, just ones that don't have a committed offset), I guess I was just confused by the name.

**Comment by tulios** [comment]
It just starts from the beginning when an offset has not been committed yet, we can improve the docs to make this clear
