### ISSUE TITLE
Kafkajs compatible version for node 8.12

### ISSUE THREAD

**Issue by abhay12** [tulios/kafkajs#1510]
I have node version 8.12, I am using kafkajs 2.2.3 but getting error. I suspect if there is any version compatibility issues. 

**_Error:_**

/kafkajs/src/protocol/encoder.js:12
const UNSIGNED_INT64_MAX_NUMBER = 0xffffffffffffff80n
                                                               ^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)

**Comment by Nevon** [comment]
Node 8 was EoL 3 years ago. You should not be using that, as it has not received any security updates since then. KafkaJS supports all active versions of Node, of which the oldest is currently 14.
