### ISSUE TITLE
Kafka Consumer taking too much memory and CPU utilization. 

### ISSUE THREAD

**Issue by shidhu40** [tulios/kafkajs#1528]
I am using Kafkajs library to produce and consumer message. I have produce 1Lac message. Consumer will consumer each message and download image from url. In Production I have noticed its consuming too much memory and CPU. 

Below are my code sample.

const { Kafka, logLevel } = require("kafkajs");
const download = require('image-downloader');
const kafka = new Kafka({
  logLevel: logLevel.INFO,
  clientId: 'my-app',
  brokers: [localhost:9092],
  connectionTimeout: 3000,
  retry: {
    initialRetryTime: 30000,
    retries: 200
  }
});

const topic = "downloadImage";
const imageConsumer = kafka.consumer({groupId: "downloadImage"});

const funConsumerProcess = async () => {
	await imageConsumer.subscribe({ topic, fromBeginning: true });
	await imageConsumer.run({
		eachMessage: async (task) => {
			let mesg = JSON.parse(task.message.value);
			if (mesg.portrait_mounturl == '') {
				  let imgpath = '/mount/localImages/';
				  if (!fs.existsSync(imgpath)) {
					fs.mkdirSync(imgpath, {
					  recursive: true
					});
				  }
				  const options = {
					url: mesg.portrait_mounturl,
					dest: imgpath
				  };
				  download.image(options)
					.then(({ filename }) => {
						console.log('Saved to', filename);
					})
					.catch((err) => { 
					  console.log(err);
					  
					});
			}
		await imageConsumer.commitOffsets([{ topic: task.topic, partition: task.partition, offset: (Number(task.message.offset) + 1).toString() }]);
        kafka.logger().info(`topic : ${task.topic} partition: ${task.partition},  offset: ${task.message.offset} consumed and commited`);
		}
  });
}

const run = async () => {
  await imageConsumer.connect();
  funConsumerProcess(imageConsumer).catch(console.error);
};
run().catch(e => console.error(`[example/consumer] ${e.message}`, e));

**Comment by Nevon** [comment]
You are not awaiting the promise where you download the image so you are not applying any backpressure and so messages are being consumed faster than you are actually handling them.

```js
eachMessage: async (task) => {
  let mesg = JSON.parse(task.message.value);
  if (mesg.portrait_mounturl == '') {
    let imgpath = '/mount/localImages/';
    if (!fs.existsSync(imgpath)) {
      fs.mkdirSync(imgpath, {
        recursive: true
      });
    }
    const options = {
      url: mesg.portrait_mounturl,
      dest: imgpath
    };

    // Either await this promise or return it
    return download.image(options).then(({ filename }) => { console.log('Saved to', filename); })
  }
}
```
