### ISSUE TITLE
MaxListenersExceededWarning on high concurrency/big cluster

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#153]
The broker uses a lock mechanism to prevent issues with authentication when creating connections in parallel; this can be caused by the use of `producer.send` in a `Promise.all` or in recovery scenarios where the brokers have to re-connect.

The lock mechanism is based on `EventEmitter`, which has max listeners set to 11. If the number of connections is higher than 11, it will warn with something like:

```sh
(node:20592) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 releaseLock listeners added. Use emitter.setMaxListeners() to increase limit
```

To solve this, we must set `maxListeners` to the number of brokers in the cluster; this can be done after metadata refresh in the `BrokerPool`.

https://github.com/tulios/kafkajs/blob/cf0005f07a1465cca0697463f1b7d7f8c6888e07/src/cluster/brokerPool.js#L111

**Comment by Nevon** [comment]
Maybe we should rewrite the lock to not use EventEmitter rather than increasing `maxListeners`. We shouldn't really need EventEmitter anyway.
