### ISSUE TITLE
[Producer] Cannot read property 'compress' of null

### ISSUE THREAD

**Issue by abhinavgautam07** [tulios/kafkajs#1533]
**Describe the bug**
Getting the following error while producing message.
`{"level":"ERROR","timestamp":"2023-02-22T10:14:33.350Z","logger":"kafkajs","message":"[Producer] Cannot read property 'compress' of null","retryCount":0,"retryTime":267}
error TypeError: Cannot read property 'compress' of null`

**To Reproduce**
Try to produce this message.
`{
  topic: 'audit_log_event',
  messages: [
    {
      key: 'part',
      value: 'eyJhdWRpdF9sb2dfaW5mbyI6eyJuYW1lIjoic3VwcGx5LXBsYW5uaW5nIiwiY2l0eSI6Imd1cnVncmFtIn0sIl90cmFuc2FjdGlvbl9pZF8iOiJjNDhjMGQ3Y2JjOGQ4OWFiMTQxNjYxYjA3NGY4MzBlMCIsInByb2R1Y2VySWQiOiJzdXBwbHktcGxhbm5pbmctc2VydmljZSJ9',
      timestamp: '1677060873157'
    }
  ],
  compression: 2,
  acks: 1,
  idempotent: false,
  timeout: 30000
}`

**Expected behavior**

Message should have been produced successfully.

**Observed behavior**

`{"level":"ERROR","timestamp":"2023-02-22T10:14:33.350Z","logger":"kafkajs","message":"[Producer] Cannot read property 'compress' of null","retryCount":0,"retryTime":267}
error TypeError: Cannot read property 'compress' of null`

**Environment:**
 - OS: [e.g. Mac OS 13.1]
 - KafkaJS version -  2.0.1
 - Kafka version 3.1
 - NodeJS version 14.18.0

**Additional context**

**Comment by Nevon** [comment]
To use snappy compression you need to have installed the snappy compression codec and made it available to the client. See [the docs on producing with snappy compression](https://kafka.js.org/docs/producing#a-name-compression-snappy-a-snappy)
