### ISSUE TITLE
Heartbeat needs to be called during message consumption?

### ISSUE THREAD

**Issue by scmorse** [tulios/kafkajs#156]
I'm confused by the need to call a heartbeat function during `eachBatch`. Shouldn't heartbeats be done independently of whether or not any messages are currently being processed? What if no messages are being processed on a particular topic for a long period of time?

**Comment by tulios** [comment]
The heartbeats are used to inform Kafka about the liveness of the consumer, so they are performed constantly on a set interval. The call is tied to the message processing to detect problems with the consumer quickly, imagine you have a bug on userland and the `each*` function is never released. The time would pass, and it this consumer would be flagged as dead after the `heartbeatInterval`.

> What if no messages are being processed on a particular topic for a long period of time?

This works just fine; even if you don't have any messages to process, the fetch loop will still be active. It will get empty batches and heartbeat on the same interval. Kafka will wait for `minBytes` or `maxWaitTime`, which is `5s` by default. It means that every fetch request will block for `5s` before returning the empty batch, so the consumer will maintain a steady pace until it gets data again.

**Comment by scmorse** [comment]
> This works just fine; even if you don't have any messages to process, the fetch loop will still be active. It will get empty batches and heartbeat on the same interval. Kafka will wait for minBytes or maxWaitTime, which is 5s by default. It means that every fetch request will block for 5s before returning the empty batch, so the consumer will maintain a steady pace until it gets data again

So do we need to call `heartbeat()` outside of looping through `batch.messages` to make sure that the heartbeat is sent for empty batches? Or is the `eachBatch` function not even called when an empty batch is returned from kafka, and heartbeats are done automatically by the lib when empty batches are received?

Thanks for your help, btw!

**Comment by scmorse** [comment]
I took a look at the code, and I saw that `heartbeat` is called at the end of a batch process regardless, so I think my questions have been answered now. Thanks!

**Comment by tulios** [comment]
Nice, just some notes. The library will regularly call heartbeat for you, but when using `eachBatch` where you process each message individually instead of the whole batch it might take too long between the heartbeats, causing your consumer to be kicked out of the group. That's why `eachBatch` gives you access to heartbeat, so you can heartbeat between each message and take as much as you need processing the batch. Heartbeat will only execute if it's time to heartbeat, so calling it very often is not a problem.
