### ISSUE TITLE
Failed to connect: error:0308010C:digital envelope routines::unsupported.

### ISSUE THREAD

**Issue by ultrarunner** [tulios/kafkajs#1562]
**Describe the bug**
As node16 is coming to EOL in September 2023, our team has started exploring upgrading to node18. We are running into the following error "error:0308010C:digital envelope routines::unsupported." trying to connect kafka using ssl/mtls. We are using the latest version of the library (2.2.4). See below for the full stack of os version / kafkajs / kafka version / node version.

**Expected behavior**
I would assume that ssl kafka connectivity would behave the same under node 16 or 18.

**Observed behavior**
On startup our EKS containers, we connect with kafka using the following ssl configuration.
kafkaOptions.ssl = {
  rejectUnauthorized: true,
  ca: {validCa},
  cert: {validCert},
  key: {validKey},
  passphrase: {validPassword}
}
We are observing the following error attempting to connect to kafka: "error:0308010C:digital envelope routines::unsupported."

**Environment:**
 - OS: ubuntu:20.04
 - KafkaJS version: 2.2.4
 - Kafka version: 7.3.1
 - NodeJS version: 18.15

**Additional context**
I found this article (https://www.programmingbasic.com/solve-error-0308010c-digital-envelope-routines-unsupported-error-in-node) regarding breaking issues related to node 17+ and open ssl breaking changes and followed some of the suggestions with no luck so far. 

Please let me know if this is not relevant to the kafkajs library at all and related to nodejs only. Also please let me know if you need more details. Thank you so much.

**Comment by ultrarunner** [comment]
Quick update. Just wanted to let you know that ssl works using the --openssl-legacy-provider node option on startup. Feel free to close this bug but I would still be curious if anyone has any suggestions related to the underlying issue. Is kafkajs using an "outdated" version of ssl? Thank you.

**Comment by Nevon** [comment]
KafkaJS uses the TLS module from the Node standard library, so it'll use whatever version of openssl it's built against. Given the error you shared, I would think this means your Kafka cluster doesn't support modern, secure cryptographic algorithms and so newer versions of openssl (and thus Nodejs) won't connect to it because it can't do so securely. See [the openssl documentation](https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-legacy.html).
