### ISSUE TITLE
Can't connect to MSK Broker using kafkaJS

### ISSUE THREAD

**Issue by parab-bloom** [tulios/kafkajs#1642]
For IAM I followed the following steps, and not able to connect. Error is still saying "Closed Connection"

* Made the IAM user named kafka-user
* Created role with MSKFullAccess policy and gave that role to user
* for that user created access keys
* made an inbound rule in the security group for allowing All traffic

Using following code:

```
this.kafka = new Kafka({
      clientId: 'user_service', // Replace with your desired client ID
      brokers: ['KAFKA_BROKER_ADDRESS'],
      sasl: {
        mechanism: 'aws',
        authorizationIdentity: 'kafka-user', // UserId or RoleId
        accessKeyId: 'ACCESS_KEY',
        secretAccessKey: 'ACCESS_SECRET',
        // sessionToken: '' // Optional
      },
    });
```
I commented the sessionToken as it is optional and I do not know how to get it.

Error: 
```
{"level":"ERROR","timestamp":"2023-11-23T11:43:55.513Z","logger":"kafkajs","message":"[BrokerPool] Closed connection","retryCount":5,"retryTime":6586}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionClosedError: Closed connection
```

**Comment by akospaska** [comment]
Hello.
It is propably too late, but try this.
[](https://github.com/aws/aws-msk-iam-sasl-signer-js#getting-started
)

**Comment by parab-bloom** [comment]
Hi @akospaska ,
Thank you for your reply, I used this module `@jm18457/kafkajs-msk-iam-authentication-mechanism` with kafkajs library. According to a blog on aws repost https://repost.aws/knowledge-center/msk-cluster-connection-issues, kafkajs iam is slightly different from what aws actually uses so previously mentioned module will work fine and its working flawlessly.
