### ISSUE TITLE
kafka Invalid receive (size larger than defined)

### ISSUE THREAD

**Issue by anbiasenggagau** [tulios/kafkajs#1643]
I'm using kafka Docker images of

https://hub.docker.com/r/ubuntu/kafka
https://hub.docker.com/r/ubuntu/zookeeper

I followed the getting started source code
https://kafka.js.org/docs/getting-started

but I got error of 
Invalid receive (size = 369295617 larger than 104857600)

which is strange since I only sent message of "Hello KafkaJS user!" to the topic.
anybody know what cause this error?

thanks for help

**Comment by mattiaforc** [comment]
Hi, I also had this problem and noticed that passing an empty object in the `ssl` parameter when initializing `Kafka` turned on SSL (which in my local docker-compose was not enabled). 

So, try this:
```js
const kafka = new Kafka({
    logLevel: logLevel.DEBUG,
    clientId: 'xxxxx',
    brokers: [`${ipAddress()}:9092`]
    /* Remove completely the ssl block
    ssl: {} 
    */
})
```

**Comment by winfriedgerlach** [comment]
For everyone finding this via Google: This error (in particular with size > 300,000,000) generally indicates that a Kafka client configured for TLS tries to talk to a non-TLS Kafka broker or vice versa.
