### ISSUE TITLE
Add protocol AddOffsetsToTxn v0

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#168]
Sends the groupId to the transaction coordinator, from which it can deduce the TopicPartition for this consumer group in the internal `__consumer-offsets` topic. The transaction coordinator logs the addition of this topic partition to the transaction log

```
AddOffsetsToTxn Request (Version: 0) => transactional_id producer_id producer_epoch group_id 
  transactional_id => STRING
  producer_id => INT64
  producer_epoch => INT16
  group_id => STRING
```

```
AddOffsetsToTxn Response (Version: 0) => throttle_time_ms error_code 
  throttle_time_ms => INT32
  error_code => INT16
```

https://kafka.apache.org/protocol.html#The_Messages_AddOffsetsToTxn

**Comment by ianwsperber** [comment]
Starting work on this
