### ISSUE TITLE
Kafka upgrade 2.7 -> 3.6

### ISSUE THREAD

**Issue by brennonh** [tulios/kafkajs#1681]
Not an issue, just a question.

Your documentation states that kafkajs supports Kafka 0.10 onwards. My Kafka cluster is being upgraded to 3.6 and I'm using kafkajs 1.12 (legacy apps, I know, don't ask). My question therefore is "Will 1.12 be compatible with 3.6?" 
Thank you for your support

**Comment by vikrant3c** [comment]
I have the same concern. 
@brennonh have you found out?

**Comment by brennonh** [comment]
> I have the same concern. @brennonh have you found out?

Tested against version 3.6 and it works as expected @vikrant3c

**Comment by brennonh** [comment]
Works

**Comment by vikrant3c** [comment]
thanks for the update, really appreciated  😊
