### ISSUE TITLE
KafkaJSRequestTimeoutError during consumption leading to partition backlog

### ISSUE THREAD

**Issue by xiaoxiaodek** [tulios/kafkajs#1691]
**Describe the bug**
When attempting to consume messages from a Kafka topic using KafkaJS, a timeout error occurs. The error log states “KafkaJSRequestTimeoutError: Request ListOffsets(key: 2, version: 3) timed out”. This issue appears to be similar to the one reported in #1410.

**To Reproduce**
1. Run a producer that continuously sends messages to a topic with 10 partitions.
2. Launch several consumer instances with the same consumer group ID, subscribing to the aforementioned topic and logging each message offset.
3. Introduce network issues such as packet loss.

**Expected behavior**
The consumer should either retry the connection or gracefully exit the subscription process.

**Observed behavior**
some partition's lag continuing growing.  and the following error message is displayed:
```sh
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
KafkaJSRequestTimeoutError: Request ListOffsets(key: 2, version: 3) timed out
    at SocketRequest.timeoutRequest (/home/node_modules/kafkajs/src/network/requestQueue/socketRequest.js:107:19)
    at /home/node_modules/kafkajs/src/network/requestQueue/index.js:94:21
    at Map.forEach (<anonymous>)
    at Timeout._onTimeout (/home/node_modules/kafkajs/src/network/requestQueue/index.js:92:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

```

**Environment:**
 - OS: [Linux 3.10.0]
 - KafkaJS version [2.2.4]
 - Kafka version [v2.0]
 - NodeJS version [v14.21.3]

**Comment by DjellalAbdou** [comment]
Can we have a description of why is this issue closed? I think I have the same issue with both producing and consuming (in a red panda cluster)
