### ISSUE TITLE
Add protocol EndTxn v0

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#170]
Once the data has been written, the user must call `commit` or `abort` methods of the KafkaProducer. These methods will begin the process of committing or aborting the transaction respectively.

Regardless of which producer method is called, the producer issues EndTxn to the transaction coordinator, with additional data indicating whether the transaction is to be committed or aborted. Upon receiving this request, the coordinator:

- Writes a `PREPARE_COMMIT` or `PREPARE_ABORT` message to the transaction log.
- Begins the process of writing the command messages known as `COMMIT` (or `ABORT`) markers to the user logs through the WriteTxnMarkers API.
- Finally writes the `COMMITTED` (or `ABORTED`) message to the transaction log.

```
EndTxn Request (Version: 0) => transactional_id producer_id producer_epoch transaction_result 
  transactional_id => STRING
  producer_id => INT64
  producer_epoch => INT16
  transaction_result => BOOLEAN
```

```
EndTxn Response (Version: 0) => throttle_time_ms error_code 
  throttle_time_ms => INT32
  error_code => INT16
```

https://kafka.apache.org/protocol.html#The_Messages_EndTxn

**Comment by ianwsperber** [comment]
Starting work
