### ISSUE TITLE
What is max size of Message[]?

### ISSUE THREAD

**Issue by Alocart** [tulios/kafkajs#1707]
Hi there!

I'd like to know about messages array max size per producer send. Is there a limit?

**Comment by WaleedAshraf** [comment]
@Alocart this is configured in the broken/topic config. See [message.max.bytes](https://kafka.apache.org/documentation/#brokerconfigs_message.max.bytes) config.

It can be applied at topic level or cluster level.
- message.max.bytes (broker config)
- max.message.bytes (topic config).

 According to Kafka 3.8 the default is 1 Megabyte.

**Comment by Alocart** [comment]
@WaleedAshraf you are talking about the size of one message whereas I'm asking about array size.

**Comment by WaleedAshraf** [comment]
Do you mean the length of the array of `messages` in the [Producer.send()](https://kafka.js.org/docs/producing#producing-messages) method?
There is not limit on that from Kafkajs.

Also, the broken limit of [message.max.bytes](https://kafka.apache.org/documentation/#brokerconfigs_message.max.bytes) applied to " whole batch of messages". That means everything you send in the `messages` array.
