### ISSUE TITLE
Add protocol WriteTxnMarkers v0

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#171]
This request is issued by the transaction coordinator to the leader of each TopicPartition which is part of the transaction. Upon receiving this request, each broker will write a COMMIT(ID) or ABORT(ID) control message to the log.

This message indicates to consumers whether the messages with the given ID must be delivered to the user or dropped. As such, the consumer will buffer messages which have an ID until it reads a corresponding COMMIT or ABORT message, at which point it will deliver or drop the messages respectively.

```
WriteTxnMarkers Request (Version: 0) => [transaction_markers] 
  transaction_markers => producer_id producer_epoch transaction_result [topics] coordinator_epoch 
    producer_id => INT64
    producer_epoch => INT16
    transaction_result => BOOLEAN
    topics => topic [partitions] 
      topic => STRING
      partitions => INT32
    coordinator_epoch => INT32
```

```
WriteTxnMarkers Response (Version: 0) => [transaction_markers] 
  transaction_markers => producer_id [topics] 
    producer_id => INT64
    topics => topic [partitions] 
      topic => STRING
      partitions => partition error_code 
        partition => INT32
        error_code => INT16
```

https://kafka.apache.org/protocol.html#The_Messages_WriteTxnMarkers

**Comment by tulios** [comment]
You are right; I think I took this from an old document. We can skip this protocol

**Comment by ianwsperber** [comment]
Ok cool, closing this issue then
