### ISSUE TITLE
Expose low-level metrics

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#175]
Currently there is no way for a user to collect low-level metrics on things like network calls (latencies etc.)

The way it's implemented in kafka-python is that they register a bunch of metrics in a local registry, and then expose a [pluggable interface](https://github.com/dpkp/kafka-python/blob/master/kafka/metrics/metrics_reporter.py#L6) that will be called when metrics are added/changed/removed, which would allow you to create a glue layer to for example Prometheus.

We could even include metrics on things that are technically already possible to collect, like batch size for example, so that the userland consumer code doesn't have to contain code to collect those metrics.

**Comment by tulios** [comment]
We have decided to expose metrics through the instrumentation events; we can revisit this in the future.
