### ISSUE TITLE
Add description to lock instances to improve error messages

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#177]
The lock is locking a particular resource and it would be nice to have what is being locked on errors. Currently, we throw an error like:

```sh
Timeout while acquiring lock
```

With the proposed change:
```javascript
const lock = new Lock({ description: 'Broker connection broker2.net' })
await lock.acquire()
// throws: [Producer] Timeout while acquiring lock: "Broker connection broker2.net"
```

**Comment by AlirezaSadeghi** [comment]
Hi,
Um, can you please point to a documentation or a guide on what is this locking mechanism and why it's required?

I'm running a KafkaJS production server, which handles nearly 100K transactions per second or so, depending on the load.

I've been unable to track down why the following error happens:

`{"level":"ERROR","timestamp":"2019-02-26T15:35:49.691Z","logger":"kafkajs","message":"[BrokerPool] KafkaJSLockTimeout: Timeout while acquiring lock (1674 waiting locks): \"connect to broker 10.240.0.20:9092\"","retryCount":0,"retryTime":914,"stack":"KafkaJSLockTimeout: Timeout while acquiring lock (1674 waiting locks): \"connect to broker 10.240.0.20:9092\"\n    at Timeout.setTimeout (..../node_modules/kafkajs/src/utils/lock.js:43:22)\n    at ontimeout (timers.js:424:11)\n    at tryOnTimeout (timers.js:288:5)\n    at listOnTimeout (timers.js:251:5)\n    at Timer.processTimers (timers.js:211:10)"}
`

Any help would be really appreciated, I can't seem to figure out how to resolve this issue.
Thanks

**Comment by tulios** [comment]
Hi @AlirezaSadeghi, the lock is required because of some of the authentication mechanisms; for example, SCRAM uses a handshake and requires at least three requests to authenticate the user. KafkaJS will connect the required brokers on demand since Kafka can add new brokers after the initial connection, so the library will connect to one of the seed brokers (the brokers you configure), and will establish new connections as necessary when producing or consuming messages.

In some old version of KafkaJS, this wasn't in place and users were calling, for example, `producer.send` in a `Promise.all` had failures due to concurrent authentication requests on the same broker. We since introduced `producer.sendBatch` to have a better solution for this use case, but we can't prevent users from calling some of the methods in `Promise.all`.

For broker connections, the lock expects the resource release to happen within `connectionTimeout + authenticationTimeout`, which currently is 2s. But from your logs, I can see that you are not using any authentication mechanisms, so the connection to the broker might be taking too long (it took more than 2s to connect to `10.240.0.20:9092`, as indicated in the log).

Can you post some code snippet on how are you using KafkaJS, is this a consumer or a producer? And 100k p/s is quite a load, in your example, you have `1674` calls waiting for the lock to be released, so I'm assuming you have something calling KafkaJS in a `Promise.all`.

**Comment by AlirezaSadeghi** [comment]
Thanks for the explanations. 

Yes, authentication is currently not configured, since the cluster is protected by a firewall and is only accessed within the private network.

Since it only happens in specific load conditions, it's hard for me to reproduce it right away, but looking at the logs, I think it's from a `producer.send` call. You can find the following snippet on how I'm initializing the producer and how I'm calling the send function.

```
// Incoming data ... Can be considered something like this:
for (let i = 0; i < 100000; i++)
    queueMessage(message, 'specific-topic');

// Producer chunk ...
const kafkaClient = new Kafka({
    clientId: `SomeID`,
    brokers: ['10.240.0.6:9092', '10.240.0.7:9092', '10.240.0.20:9092'],
    connectionTimeout: 5000,
    requestTimeout: 60000,
    maxInFlightRequests: 200,
    retry: {
        initialRetryTime: 1000,
        retries: 5
    }
});

const producer = kafkaClient.producer();

async function queueMessage(message, topic, retries = 0) {
    try {
        await producer.send({
            topic,
            // TODO -> KafkaJS probable bug? key=null should be present
            messages: [{key: null, value: JSON.stringify(message)}],
            acks: 1,
            compression: kafkaUtils.SNAPPY
        });
    } catch (e) {
        if (retries < 2)
            setTimeout(() => queueMessage(message, topic, retries + 1), 2000 * (retries + 1));
    }
}

```

I'm not using any Promise.all, and the flow of incoming messages is a stream of small messages, so I can't actually batch them together and send them, it's more like streaming a lot of messages in realtime, for a messaging application.
