### ISSUE TITLE
KafkaJSNumberOfRetriesExceeded: Timeout while acquiring lock at Object.send

### ISSUE THREAD

**Issue by scmorse** [tulios/kafkajs#184]
```
KafkaJSNumberOfRetriesExceeded: Timeout while acquiring lock at Object.send
```

Using KafkaJS v1.3.1.

Upgraded a microservice to use KafkaJS (instead of no-kafka), and after running fine for ~5 days, requests to produce messages are now throwing the error above. Not sure why this is happening.

I saw some other closed issues for the same error when a broker disconnects/reconnects. Could it be the same issue?

**Comment by tulios** [comment]
We made several improvements on this, can you upgrade to `1.4.1`?

**Comment by scmorse** [comment]
Already in progress of updating!

**Comment by scmorse** [comment]
Updated to 1.4.1 and haven't seen any issues yet. I'll re-open if they issues crop back up.
