### ISSUE TITLE
topic message lost

### ISSUE THREAD

**Issue by huanhuang-wang** [tulios/kafkajs#186]
I have 2 consumers in one group which consumes one single topic with 2 partitions, and created a custom assigner to assign one consumer per partition. 
start consumer 1 first, and send messages to 2 partitions randomly, only messages in partition 1 is being consumed, then start consumer 2, it will not receive messages that not consumed in partition 2, got some error like :"The requested offset is not within the range of offsets maintained by the server".  messages sent after consumer 2 started will get consumed correctly.

**Comment by tulios** [comment]
This is happening because by default the consumers have `fromBeginning: false`, so it works for the first consumer because it's up before you publish the messages, by the time you start consumer 2 it will "fast forward" to the end. Try adding `fromBeginning: true` on the subscribe, example:

```javascript
await consumer.subscribe({ topic: 'topic-C', fromBeginning: true })
```

**Comment by huanhuang-wang** [comment]
Thanks. I forgot that.
