### ISSUE TITLE
Add option to make admin.fetchOffsets resolve the offsets

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#205]
`await admin.fetchOffsets` might return -1 or -2 depending on the state of the consumer group. We could add an option to force it to resolve the offsets, so you get the earliest or the latest offset.

proposal:
```javascript
await admin.fetchOffsets({ groupId, topic, resolveOffsets: true })
```

**Comment by WaleedAshraf** [comment]
If this is still a valid issue, I can try to pick it. @tulios @Nevon

**Comment by WaleedAshraf** [comment]
Any update here?
