### ISSUE TITLE
support kerberos?

### ISSUE THREAD

**Issue by yuu2lee4** [tulios/kafkajs#213]
whether supported kerberos or not?

**Comment by tulios** [comment]
Hi @yuu2lee4, sorry for the delay. We don't have plans to support Kerberos on KafkaJS, but the authentication system is modular, which means it can be implemented as a separate library. If you decide to write the library, I can support you on the integration part.

We could also support it in KafkaJS if the implementation doesn't require any dependencies, I can also support you with this implementation if you want.

**Comment by Nevon** [comment]
I'm closing this for now. Feel free to re-open if you want to support us in implementing this.
