### ISSUE TITLE
describe none existing topic

### ISSUE THREAD

**Issue by imalik8088** [tulios/kafkajs#224]
Hi,
I'm getting still for none existing topic a result and bunch of configs and I could see if this scenario was tested in according test. I'm using Kafka 1.1. 

Is this bug?
```
const response = await admin.describeConfigs({
                resources: [
                    {type: RESOURCE_TYPES.TOPIC, name: "none_existing_topic"}
                ]
            });
```

thats the result which I'm getting:

```
 { throttleTime: 0,
  resources:
   [ { errorCode: 0,
       errorMessage: null,
       resourceType: 2,
       resourceName: 'none_existing_topic',
       configEntries: [Array] } ] }
```

**Comment by tulios** [comment]
Hi @imalik8088, you are just getting the default configurations for the topic, you get that even if the topic doesn't exist.

**Comment by imalik8088** [comment]
ok thanks!
