### ISSUE TITLE
Update README with transactional API

### ISSUE THREAD

**Issue by ianwsperber** [tulios/kafkajs#225]
Once the transactional API has been completed we'll need to update the README to document the new methods, options and workflows.

**Comment by ianwsperber** [comment]
@tulios @Nevon I will have a PR in place for this within the next day. Hopefully we'll be more or less ready to do a version bump with the EoS features then?

**Comment by Nevon** [comment]
We tend to run a pre-release version on one of our systems first for a couple of days, to see if there are any issues introduced. We can do that early next week, and if all goes well, we can release a new version shortly after.

**Comment by tulios** [comment]
Since this version (`1.5.0`) has a lot of new things, I was thinking about releasing a `1.5.0-rc1` so we can have some time to make sure everything is stable, but we don't block anyone that wants to use the features. WDYT?

**Comment by ianwsperber** [comment]
@tulios Yeah I think that's a good idea to get a beta out that people can install while we're doing testing
