### ISSUE TITLE
high cpu used but none message received by subscribe to a broadcast use new group

### ISSUE THREAD

**Issue by superbogy** [tulios/kafkajs#234]
high cpu used but none message received by subscribe to a broadcast use new group

```
 ● consumer                           [||||||||||||||||||||||||||||||] 100 %
[1] [cluster_mode]                     [||||||                        ] 154.547 MB
```

there are none error

```

log:
```
{"level":"INFO","timestamp":"2018-12-24T08:06:52.908Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"log-app-op"}

{"level":"INFO","timestamp":"2018-12-24T08:06:52.928Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"log-app-op","memberId":"log-collector-op-27893b74-7633-4fa5-b5bf-f825dc66dab3","leaderId":"log-collector-op-27893b74-7633-4fa5-b5bf-f825dc66dab3","isLeader":true,"memberAssignment":{"test_binlog":[2,5,4,7,1,3,6,0]},"duration":19}
```
DEBUG:
```
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.347Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 4)","broker":"172.31.10.243:9092","clientId":"log-collector-op","correlationId":162,"size":295683,"data":"[filtered]"}
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.347Z","logger":"kafkajs","message":"[ConsumerGroup] Fetching from 1 out of 1 topics","topics":["test_binlog"],"activeTopics":["test_binlog"],"pausedTopics":[]}
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.348Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"172.31.10.243:9092","clientId":"log-collector-op","correlationId":163,"expectResponse":true,"size":105}
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.348Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"172.31.15.99:9092","clientId":"log-collector-op","correlationId":160,"expectResponse":true,"size":105}
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.348Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"172.31.10.76:9092","clientId":"log-collector-op","correlationId":161,"expectResponse":true,"size":105}
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.348Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"172.31.14.138:9092","clientId":"log-collector-op","correlationId":164,"expectResponse":true,"size":105}
{"level":"DEBUG","timestamp":"2018-12-24T08:16:54.362Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 4)","broker":"172.31.10.76:9092","clientId":"log-collector-op","correlationId":161,"size":323407,"data":"[filtered]"}

```

**Comment by tulios** [comment]
Hi @superbogy, sorry for the delay, we were out on holiday vacations. We have a lot of projects running kafkajs, some of them with extreme load and we haven't seen this behavior. Can you provide some code example with the cluster so we can investigate the issue, there was another thread about cluster mode some time ago that might shed some light (#144)

**Comment by tulios** [comment]
@superbogy feel free to re-open this ticket if you need.
