### ISSUE TITLE
Throwing an error in eachBatch for a consumer without resolved offsets skips messages

### ISSUE THREAD

**Issue by kpala** [tulios/kafkajs#238]
When using `eachBatch`, offsets are not committed when throwing an error in the eachBatch methods as documented:

> eachBatchAutoResolve configures auto-resolve of batch processing. If set to true, KafkaJS will automatically commit the last offset of the batch if eachBatch doesn't throw an error. Default: true.

However, if the consumer was just added so that not all partitions yet have resolved offsets, the consumer seems to restart by starting from the latest offsets for the partitions instead from the stored offsets. I.e., the consumer will skip messages.

In the following example, "RECEIVED MESSAGE" should be found in the console output multiple times, but `eachBatch` is called only once:

```javascript
const client = new kafka.Kafka({
    brokers: ['127.0.0.1:9092'],
    clientId: 'test-clientId'
});

const consumer = client.consumer({
    groupId: `test-groupId-${Math.random()}`
});
await consumer.subscribe({ topic: 'test-topic' });
const producer = client.producer();

// eachBatch should be fired multiple times, but it's fired only once
await consumer.connect();
await consumer.run({
    eachBatch: () => {
        console.log('RECEIVED MESSAGE');
        throw new errors.KafkaJSNonRetriableError();
    }
});
await producer.connect();
await producer.send({
    messages: [{ key: null, value: 'Hello world' }],
    topic: 'test-topic'
});

await new Promise(resolve => {
    setTimeout(resolve, 10000);
});

await consumer.disconnect();
await producer.disconnect();
```

However, ensuring the consumer has resolved offsets for all partitions, the following example will keep calling `eachBatch`:

```javascript
const client = new kafka.Kafka({
    brokers: ['127.0.0.1:9092'],
    clientId: 'test-clientId'
});

const consumer = client.consumer({
    groupId: `test-groupId-${Math.random()}`
});
await consumer.subscribe({ topic: 'test-topic' });
const producer = client.producer();

await consumer.connect();
await consumer.run({
    eachMessage: () => {}
});
await producer.connect();
// make sure all partitions will have a resolved offset (in this case, it's 3 partitions)
for (let i = 0; i < 3; i += 1) {
    await producer.send({
        messages: [{ key: null, value: 'Hello world' }],
        topic: 'test-topic'
    });
}

await new Promise(resolve => {
    setTimeout(resolve, 10000);
});
await consumer.disconnect();
await producer.disconnect();

// eachBatch will be fired multiple times
await consumer.connect();
await consumer.run({
    eachBatch: () => {
        console.log('RECEIVED MESSAGE');
        throw new errors.KafkaJSNonRetriableError();
    }
});
await producer.connect();
await producer.send({
    messages: [{ key: null, value: 'Hello world' }],
    topic: 'test-topic'
});

await new Promise(resolve => {
    setTimeout(resolve, 10000);
});
await consumer.disconnect();
await producer.disconnect();
```

I guess https://github.com/tulios/kafkajs/issues/205 relates to this issue. Could we maybe introduce a feature where adding a consumer would resolve the offsets before starting to process any messages?

**Comment by tulios** [comment]
Hi @kpala, this is the intended behavior. The first time you connect a consumer group it will initialize the offsets based on the default policy, which in this case is `fromBeginning: false`, you can configure your consumer groups to start from the beginning, like:

```js
const consumer = kafka.consumer({ groupId: 'example', fromBeginning: true})
```

Take a look at https://github.com/tulios/kafkajs/blob/master/README.md#consuming-messages-from-beginning for more information about this configuration.

**Comment by kpala** [comment]
Thanks, I realized this as well while digging deeper. Sorry for the false alarm!
