### ISSUE TITLE
[question] Slow consumption

### ISSUE THREAD

**Issue by boedy** [tulios/kafkajs#242]
Currently experimenting with Kafkajs. I notice when consuming message from the beginning (`fromBeginning: true`) the consumer processes the first couple of thousand messages fast, but then it slows down considerably. it will do 50 - 100 messages per 5 seconds. Is this expected behaviour?

Setting `maxWaitTimeInMs` to `1` circumvents the issue. Is lowering this number to `1` a bad idea? Is there something I'm missing?

**Comment by tulios** [comment]
Hi @boedy, last time we benchmarked KafkaJS it was processing 80k messages p/s with `eachBatch` and 65k messages p/s with `eachMessage`. I would guess that your test isn't producing fast enough, the consumer will wait for `maxWaitTimeInMs` or `maxBytes`, which is 10M by default. So I guess that it is always waiting for the `maxWaitTimeInMs`, you can try to configure `maxBytes` to something that makes sense for your system.

About your second question, it's not a bad idea to have a lower value for `maxWaitTimeInMs`, but I would say the best is a combination of both `maxWaitTimeInMs` and `maxBytes`, so you make fewer requests and fetch a decent amount on each request.
