### ISSUE TITLE
Opportunistic message sending 

### ISSUE THREAD

**Issue by KBInmarsat** [tulios/kafkajs#248]
We have a requirement where we have limited bandwidth between a producer and a broker and with two classes of messages (high and low priority) on a topic.  Low priority messages should only be sent if there is no congestion on the line.

I have implemented a change that adds a new option "opportunistic" to send/sendBatch which if set to true only sends the message(s) if the broker(s) socket is not congested.  If successful send/sendBatch works as normal, however if there is congestion the callback returns an empty array.  

The changes are minimal, bufferSize is exposed via connnection and broker classes with some small changes to messageProducer and sendMessages.  

It would be great if this could be integrated into the main branch.

Thanks

**Comment by tulios** [comment]
Hi @KBInmarsat, interesting use case. Can't you accomplish the same by setting `maxInFlightRequests` to one? and what about keeping this logic on userland, what would you need to keep the "queue" on your side? We already have some instrumentation events, I will take a look at your changes to propose something.

**Comment by KBInmarsat** [comment]
I looked into maxInflighRequest but the problem is it obviously does n't take into account of the message size and on a wan link the round trip time for an acknowledgement would result in lower thoughput.  socket bufferSize is releatively good platform independant way of establishing if there is congestion on the socket, it also works when there are bandwidth limits have been set in Kafka.  

We maintain a queue on our side that is drained via the callback, our use for this is where a live stream of data is interrupted and we want to send now old unsent data in conjuction with the live stream but with a lower priority.  The asynchronous nature of things makes our current implementation a bit messy and a better synchonous way would be to have a function like canSend(topic, key) where we can predicate before doing a send rather than this method, however that would mean a new method.  I will see if I can put something together as an alternative.

**Comment by KBInmarsat** [comment]
FYI, we've managed to do this without changing the core message implementation by using two producers and prioritising packets at the network level.  We do however have to need access the underlying broker socket to set some socket options.  I've added a BROKER_CONNECTION event that exposes network connections. Thanks.

**Comment by tulios** [comment]
@KBInmarsat just to let you know, we want to move forward with PR #263, it's taking a while because we want to release `v1.5.0` first. I am just keeping you in the loop.

**Comment by tulios** [comment]
PR #263 should address this problem as previously discussed.

**Comment by tulios** [comment]
The socketFactory feature (#263) was released on `v1.6.0`
