### ISSUE TITLE
Unable to connect to kafka broker without ssl option

### ISSUE THREAD

**Issue by DominicGinger** [tulios/kafkajs#249]
Hello :wave:

The kafka client is unable to connect to the broker pool unless the ssl option exists, even if it only has `rejectUnauthorized: false` in it. 

> Example
```javascript
const client = new Kafka({
    clientId: '123',
    brokers: [`my-broker:9094`],
    sasl: {
      mechanism: 'scram-sha-512',
      username: 'my-username',
      password: 'password'
    }
  })
const consumer = client.consumer({ groupId: 'my-group' })
await consumer.connect()
```
> Error
```
[BrokerPool] KafkaJSConnectionError: Closed connection
```

Adding `ssl: { rejectUnauthorized: false }` makes it work.

It looks like this is related to using `net.connect` in https://github.com/tulios/kafkajs/blob/master/src/network/socket.js#L12

Thanks!

**Comment by tulios** [comment]
Hi @DominicGinger, your broker might require the connection to be secure since port `9094` requires authentication. I don't see anything in KafkaJS that would prevent what you are doing, so I'm assuming that the broker is rejecting the request.

**Comment by DominicGinger** [comment]
@tulios That's exactly it 🤦‍♂️ , thanks :+1:
