### ISSUE TITLE
Deleting topic in via admin client, causes all further calls to fail due to unknown topic

### ISSUE THREAD

**Issue by cross311** [tulios/kafkajs#252]
Using the admin API to delete a topic works, but after you delete the topic it is still in the tracked topics.  Each additional use of the same client throws unknown topic or partition error.

I looked at the code to try and debug, it appears that the deleted topic is in the tracked topic set.  When new functions are called the metadata is attempted to be refreshed, and since this unknown topic is in that list it throws an error.

**Comment by tulios** [comment]
Hi @cross311, the admin client is throwing an error after you delete the topic, right? Because consumers will crash if you delete the topics they are subscribed (justing making it clear).

Thanks

**Comment by cross311** [comment]
@tulios honestly your test is exactly what I was doing.  So if this passes makes me feel like I am either using an older version or just really doing something wrong.  I am currently using version `1.4.6`.  Let me look a little bit more and see if I can one reproduce if I update and two get an exact test case for you.  Thank you for looking at it.

**Comment by tulios** [comment]
Hey @cross311 I will go ahead and add a PR to remove the topic from the target list, it makes sense anyway. Maybe this only happens when the cluster is busy, I will add the fix and you can try out.

Thanks
