### ISSUE TITLE
Infinite loop while fetching with compression not setup

### ISSUE THREAD

**Issue by aurelien-ldp** [tulios/kafkajs#254]
I am using Kafkajs latest version with a kafka broker v1.0.1. I have setup my consumer as explained in the documentation nad I can see in the logs that it connects ok to Kafka and it joins the consumer group, but when I send a message (AVRO compressed using **Snappy**), the consumer starts looping like if it is not autocommiting and trying to fetch the same offset each time.

Thanks to the KafkaJS team we figured out it is because I didn't set the compression codecs.
But it should actually throw an error in that case.

Thanks 😄

**Comment by tulios** [comment]
@aurelien-ldp it turns out that kafkajs already throws an error, check your producer it is probably ignoring the errors. I wrote some more tests to make sure.

**Comment by tulios** [comment]
Right, if you produce outside of kafkajs it should fail. Adding some more code... :)
