### ISSUE TITLE
Consumer takes 30 seconds for first message

### ISSUE THREAD

**Issue by jafri** [tulios/kafkajs#260]
Consumer code:
```
    await this.abisConsumer.connect()

    // Subscribe can be called several times
    await this.abisConsumer.subscribe({ topic: 'abis', fromBeginning: true })

    let startTime = performance.now()
    this.abisConsumer.run({
      eachMessage: async ({ /*topic, partition,*/ message }) => {
        console.log(`Took ${Math.round(performance.now() - startTime)} to execute`)
        console.log({
          key: message.key,
          value: message.value
        })
      },
    })  
    await this.abisConsumer.seek({ topic: 'abis', partition: 0, offset: 0 })
```

Only retrieving 6 messages and here is the output
```
Took 30827 to execute
{ key: null,
  value:
   <Buffer 7b 22 70 72 65 73 65 6e 74 22 3a 74 72 75 65 2c 22 62 6c 6f 63 6b 5f 6e 75 6d 22 3a 39 33 36 2c 22 61 63 63 6f 75 6e 74 22 3a 22 65 6f 73 69 6f 22 2c ... > }
```

Stuck on
```
{"level":"INFO","timestamp":"2019-02-05T21:21:27.618Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"deserialize-abis"}
```

The delay appears to be in joining the consumer group. However, the issue is only seen from kafkajs, works fine using command-line `kafkacat`

**Comment by jafri** [comment]
The delay appears to be in joining the consumer group. However, the issue is only seen from kafkajs, works fine using command-line `kafkacat`

**Comment by Nevon** [comment]
Can you show what kafkacat command you are comparing to? I'm thinking that this might be due to different default configurations. The default session timeout in kafkajs is 30 seconds, so my guess would be that the broker uses that value during the group join as a timeout value for how long it should wait for additional members to join, but I don't know for sure without investigating more.

The duration of each network request is available using the instrumentation events, so you could take a look at the `REQUEST` event to see how long the `JoinGroup` request takes:

```javascript
const { REQUEST } = consumer.events

const requestTimers = {}
consumer.on(REQUEST, ({ payload }) => {
  if (payload.apiName === 'JoinGroup') {
    console.log(`"JoinGroup" took ${payload.duration}ms`)
  }
})
```

**Comment by jafri** [comment]
Simple `kafkacat -C -t abis`

**Comment by tulios** [comment]
Hi @jafri, are you using the same `groupId` of another consumer group? Because this time is influenced by the number of consumers in the group and their ability to stop processing and re-sync. Can you run your example with `KAFKAJS_LOG_LEVEL=debug` so we can see what's happening, this process should be fast.

I run the example we have in the repo and it took some ms to join the group:

```sh
# Uncompressed
→ node examples/consumer.js
{"level":"INFO","timestamp":"2019-02-06T09:12:25.638Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group"}
{"level":"INFO","timestamp":"2019-02-06T09:12:25.725Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"test-group","memberId":"example-consumer-7e704ac0-64d5-4fb2-b900-f29c54fcd332","leaderId":"example-consumer-7e704ac0-64d5-4fb2-b900-f29c54fcd332","isLeader":true,"memberAssignment":{"topic-test":[2,5,4,1,3,0]},"groupProtocol":"RoundRobinAssigner","duration":86}
Took 513 to execute

# Using Snappy
→ node examples/consumer.js
{"level":"INFO","timestamp":"2019-02-06T09:15:42.257Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group"}
{"level":"INFO","timestamp":"2019-02-06T09:15:42.309Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"test-group","memberId":"example-consumer-e0931320-41e1-4b11-b4b7-cc2fdc308b8a","leaderId":"example-consumer-e0931320-41e1-4b11-b4b7-cc2fdc308b8a","isLeader":true,"memberAssignment":{"topic-test-2":[0]},"groupProtocol":"RoundRobinAssigner","duration":51}
Took 274 to execute

# 2nd run using Snappy
→ node examples/consumer.js
{"level":"INFO","timestamp":"2019-02-06T09:16:33.620Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group"}
{"level":"INFO","timestamp":"2019-02-06T09:16:33.685Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"test-group","memberId":"example-consumer-15246b24-092b-4ef1-bc2a-c1093fbb1a1f","leaderId":"example-consumer-15246b24-092b-4ef1-bc2a-c1093fbb1a1f","isLeader":true,"memberAssignment":{"topic-test-2":[0]},"groupProtocol":"RoundRobinAssigner","duration":64}
Took 721 to execute
```

**Comment by tulios** [comment]
@jafri do you have more information for us?

**Comment by dmoena** [comment]
Hey! Maybe I do... I'm having the same issue, but looking into kafka's logs, seems to be a group rebalance issue, which might be consequence of kafkajs using subscribe `kafka.consumer({ groupId: 'group-id' })` instead of assign (IMPORTANT: I'm not saying is wrong. I'm just pointing a possible cause).

Interesting related read here: https://dzone.com/articles/dont-use-apache-kafka-consumer-groups-the-wrong-wa

A simple test is to use an existent groupId and see it getting slow rebalancing. Then, using a completely new groupId makes it fast again.

Now, I'm just learning about kafka, so any advice or further information will be really appreciated.

```
[2019-02-14 22:35:53,794] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group in state PreparingRebalance with old generation 10 (__consumer_offsets-12) (reason: Adding new member 7f55fc0d-7744-4c3d-92ca-0bb90984c35d) (kafka.coordinator.group.GroupCoordinator)
[2019-02-14 22:36:10,041] INFO [GroupCoordinator 0]: Member 0e6b17fd-efec-4360-80b9-acdfcddfa6c1 in group test-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-02-14 22:36:10,042] INFO [GroupCoordinator 0]: Stabilized group test-group generation 11 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-02-14 22:36:10,053] INFO [GroupCoordinator 0]: Assignment received from leader for group test-group for generation 11 (kafka.coordinator.group.GroupCoordinator)
```

**Comment by dmoena** [comment]
More info here https://kafka.apache.org/documentation/#intro_consumers

**Comment by tulios** [comment]
Hi @dmoena, ideally, you want to take advantage of automatic rebalances. When using manual assignment you end-up rebuilding most of what's already in Kafka. I would say that a manual assignment should only be used in special cases.

The most common issue is when the group has to rebalance and the old consumers won't acknowledge the rebalance, for example, the consumer fetches a big batch and have a long heartbeat configured, which means that the consumer won't be aware of any changes in the group until it heartbeats or fetches the next batch. You can see early indications of this problem on your logs (`Member <ID> in group test-group has failed, removing it from the group`), this means that the group probably failed to heartbeat on a given interval and was kicked out of the group, triggering a new rebalance. This can indeed cause long rebalances but I would say Kafka is working as intended here.

**Comment by dmoena** [comment]
Agreed. Automatic rebalance it is!

Thank you. Keep the good work with the library!

**Comment by tulios** [comment]
Feel free to re-open the issue if you need; this is stale for 21 days.

**Comment by expelledboy** [comment]
Hey guys, what exactly is the solution to get the consumer to join the group immediately after restarts?

I have integration tests that run on files changes, and it they arent working.

**Comment by Nevon** [comment]
The consumer automatically re-joins the group after a restart. If it's not working for you, it's likely an issue with your test or how you are configuring Kafka.

**Comment by tulios** [comment]
Not necessarily @Nevon, if you reuse the same `groupId` Kafka will trigger a rebalance and wait for the consumers to join, which by default is 30s. It's very likely @expelledboy that you are using the same `groupId` across tests, try generating a new ID per test and it should improve.

**Comment by Nevon** [comment]
Right, I guess I missed the key word "immediately".

**Comment by expelledboy** [comment]
@tulios Yes I am using the same groupId, as its testing the code that will actually run in production. I have just been manually changing it so get it working on each test cycle.

Is it not possible to cleanup, or re-use the consumer memberId? Just skimming your code and trying to figure out kafka at the same time 😂

**Comment by irissoftworks** [comment]
I actually stumbled across this in a funny scenario - as pointed out by @tulios this is related to old consumers not acknowledging the rebalance. 

The slow rebalancing occurred to me while using nodemon because I was missing the consumer.disconnect code below on process exit, and consumers were being left behind unresponsive, instead of gracefully disconnecting.

This code is from the consumer example in the docs, but it's not pointed out anywhere under usage - consuming messages:

```
const errorTypes = ['unhandledRejection', 'uncaughtException']
const signalTraps = ['SIGTERM', 'SIGINT', 'SIGUSR2']

errorTypes.map(type => {
  process.on(type, async e => {
    try {
      console.log(`process.on ${type}`)
      console.error(e)
      await consumer.disconnect()
      process.exit(0)
    } catch (_) {
      process.exit(1)
    }
  })
})

signalTraps.map(type => {
  process.once(type, async () => {
    try {
      await consumer.disconnect()
    } finally {
      process.kill(process.pid, type)
    }
  })
})
```

I am new to Kafka and this library, and correct me if I am wrong but I believe that may also be needed for the tests use case ? If previous tests are leaving unresponsive consumers behind that will cause the slow rebalancing.

I guess this would be obvious to most people, but maybe a quick update to the docs could save someone some pain in the future ?

**Comment by Nevon** [comment]
Indeed. During testing, you also need to disconnect your consumers. You can also make sure that you use unique groupIds during each test run, so that even if you forget to disconnect it shouldn't impact the other tests.

> maybe a quick update to the docs could save someone some pain in the future ?

Sure. A section on disconnecting could be useful. Feel free to open up an issue and someone will get to it eventually.

**Comment by jaiswarvipin** [comment]
Hi Team, 
we are facing the same issue, however time remain unpredictable.
As we are using the same code KafkaJS in the production environment, so this is not possible to change the consumer groupID after each call, it must kept same to make make sure that we can read only those message which was not read from the groupID, if we keep changing the groupID on each request/interval then we will always getting the all message again and again, yes this improvement connection and message getting time like anytime. 

**Current Stat**
**Keeping same consumer group ID:** 20-30 Seconds
**Keep changing the groupID:** 2-5 mili second

here we are looking for your help, how to improve the connection time and message fetching keeping consumer groupID same

my code base is.....

**.env**

DEFAULT_MESSAGE_POLLING_TIME=700
KAFAK_BROKER_ENDPOINT=localhost:9094
KAFAK_OUTBOUND_TOPIC_PREFIX=
KAFAK_OUTBOUND_TOPIC_POSTFIX=_OUT

**I have set the consumer group name and topic name in the Database, in this case**
consumer_group_name = "customer_demo_group"
outbound_topic = "customer_demo_OUT"

```
/***************************************************************************/
/*Purpose   : Polling the mesage from topic.
/*Input     : None.
/*Response  : None. 
/*Created By: Jaiswar Vipin Kumar R.
/***************************************************************************/
setInterval(function(){
	/* Iterating the operation array loop */
	Object.keys(strTopicArr).forEach(function(key, index) {
		//console.log(this[key].inbound_topic);
		/* get the message of each outbound topic */
		resetTheConsumer(this[key].consumer_group_name, this[key].outbound_topic);
	}, strTopicArr);
},process.env.DEFAULT_MESSAGE_POLLING_TIME);
```

**and consumer code base is**

```
/***************************************************************************/
/*Purpose   : Reading Message from topics.
/*Input     : pStrConsumerGroup :: Topic consumer Group,
			: pStrTopicName :: Topic name.
/*Response  : Message Detail
/*Created By: Jaiswar Vipin Kumar R.
/***************************************************************************/
function getMessageFromTopic(pStrConsumerGroup, pStrTopicName, callback){
	try{
		/* Getting the kafak avaliable messge broker reference */
		const { Kafka } 				= require('kafkajs')
		const kafakBrokerendPointArr 	= (process.env.KAFAK_BROKER_ENDPOINT).split(',');
		const kafka 					= new Kafka({clientId: pStrConsumerGroup+'_client',brokers: kafakBrokerendPointArr,logLevel:0});
		
		/* Creating the consumer */
		//const consumerObj = kafka.consumer({ groupId: pStrConsumerGroup+"_"+getRandomInt(10)});
		const consumerObj = kafka.consumer({ groupId: pStrConsumerGroup});
		
			/* Creating the non-blocking aync consumer request */
			const runs = async () => {
				/* Connecting to the consumer */
				consumerObj.connect()
				.then(returnObj =>{
					/* Subscribing consumer to the topic */
					consumerObj.subscribe({ topic: process.env.KAFAK_OUTBOUND_TOPIC_PREFIX+pStrTopicName+process.env.KAFAK_OUTBOUND_TOPIC_POSTFIX, fromBeginning: true})
					//console.log(pStrConsumerGroup+" === "+pStrTopicName);
					/* Runnign the look for getting the messge */
					consumerObj.run({
						partitionsConsumedConcurrently: 3,
						eachMessage: async ({ topic, partition, message }) => {
							try{
								//console.log(message.value.toString());
								if(message.value.toString() !=''){
									/* return callback({
										partition,
										offset: message.offset,
										value: message.value.toString(),
									}) */
									//console.log(message.value.toString());
									sendMessage(message.value.toString());
								}
							}catch(Exception){							
								console.log(Exception);
							}
							
						}
					})
				})
				.catch(excp =>{
					console.log(excp);
				}).finally(fObj=>{
					
				})
				consumerObj.disconnect();
			}
			runs().catch(e => console.error(`[example/consumer] ${e.message}`, e))
		
	}catch(exception){
		console.log(exception);
	}
}
```
**and we expecting 0.1-0.2 billions of message in the 15 min time to be get consumer and send to the requester**

@tulios  @Nevon  Kindly assist
