### ISSUE TITLE
Instrumentation Support, Exposing GROUP_JOIN

### ISSUE THREAD

**Issue by KBInmarsat** [tulios/kafkajs#271]
Hi,
We're exposing GROUP_JOIN instrumentation for our application as it's not currently enabled and was wondering what the situation was with instrumentation as a feature? do you plan on dropping it/replacing it with something else in the future?
Thanks

**Comment by Nevon** [comment]
I think that we have found the instrumentation events to be really useful for monitoring our applications, so I think it's unlikely that they'll go away. The interfaces, however, are not considered stable yet. We haven't had any reason to change them as of yet though, so I don't expect them to dramatically change anytime soon, but I can't _guarantee_ that they won't.

If it's solving a problem for you, we're definitely interested in receiving feedback, as it affects what we'll do with the events going forward. I'm gonna close this issue, but feel free to either continue the discussion here or in [our Slack](https://kafkajs-slackin.herokuapp.com).
