### ISSUE TITLE
sendBatch doesn't accept an empty array of messages

### ISSUE THREAD

**Issue by t-d-d** [tulios/kafkajs#284]
I would expect to be able to pass an empty topicMessages array to sendBatch.

Is there a reason why it's explicitly disallowed?  Seems to still work if I remove the check (for my code at least.)  If it is needed, then the error message could be better.

[](https://github.com/tulios/kafkajs/blob/master/src/producer/messageProducer.js#L32)
```
    if (topicMessages.length === 0 || topicMessages.some(({ topic }) => !topic)) {
      throw new KafkaJSNonRetriableError(`Invalid topic`)
```

And thanks guys - great library.

**Comment by Nevon** [comment]
This was explicitly disallowed, but looking at it now, I think you're right that we should allow this (even if it's just a noop). It doesn't make sense that you should have to validate this before calling `sendBatch`/`send`.

**Comment by tulios** [comment]
Yeah, we added some validations to prevent common mistakes, but I also agree that this is a valid use case, thanks for the report.
