### ISSUE TITLE
fromBeginning belongs to subscribe() and not consumer

### ISSUE THREAD

**Issue by HungUnicorn** [tulios/kafkajs#285]
when reading the document 
https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning

`The consumer group will use the latest committed offset when fetching messages. If the offset is invalid or not defined, fromBeginning defines the behavior of the consumer group.`
it doesn't say which function takes this parameter `fromBeginning`

it would be nice to update the document that this parameter is used as 
```javascript
consumer.subscribe({ topic: 'test', fromBeginning: true })
```

**Comment by tulios** [comment]
I agree, thanks for the suggestion
