### ISSUE TITLE
Consumer not being a ConsumerGroup and subscribe to a single partition?

### ISSUE THREAD

**Issue by bobzsj87** [tulios/kafkajs#294]
Is there anyway to create a consumer which only subscribe to a single partition of a topic and not being a consumer group?

**Comment by tulios** [comment]
Hi @bobzsj87, we only support consumer groups for now, but you can write a small assigner that will assign one partition and discard the rest. You can take a look at how to write custom consumer assigners here: https://kafka.js.org/docs/consuming#a-name-custom-partition-assigner-a-custom-partition-assigner

The benefit of this approach is that if the consumer processing the partition dies another one will take over, so you have all the advantages of the consumer group.

**Comment by tulios** [comment]
Feel free to re-open this issue.

**Comment by bobzsj87** [comment]
@tulios Thanks for the pointer. I am trying to implement a request-response mode, that the consumer knows exactly what partition to subscribe to (by external automatic counter), and only cares about the responses to that particular partition. 

The question is that is there a way to write an assigner that only affects the consumer itself, not affecting the other consumers in the group? Say, consumer A joins the group and subscribe to 0, when consumer B joins and subscribes to partition 1, it doesn't care and affect A. And C joins 2, and doesn't affect A and B, etc...
