### ISSUE TITLE
Flaky test in connection.spec.js

### ISSUE THREAD

**Issue by sergeyevstifeev** [tulios/kafkajs#3]
The test relies on a local network setup, which is not guaranteed to end up in connection timeout for a specific hardcoded IP address.

```FAIL  src/network/connection.spec.js
 ● Network > Connection › #connect › PLAINTEXT › rejects the Promise in case of errors

   expect(object).toHaveProperty(path, value)

   Expected the object:
     [Error: Connection error: connect ECONNREFUSED 99.99.99.99:9092]
   To have a nested property:
     "message"
   With a value of:
     "Connection timeout"


     at Object.<anonymous> (node_modules/jest-matchers/build/index.js:176:51)
         at Generator.throw (<anonymous>)
         at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by tulios** [comment]
True, but the socket requires a valid address. I'll have to pick a better address or try to figure out an unused address, any ideas?

**Comment by tulios** [comment]
I have switched the IP with a proper test IP according to to RFC 5737:

> The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2),
> and 203.0.113.0/24 (TEST-NET-3) are provided for use in documentation.

https://github.com/tulios/kafkajs/blob/f8bc6826e043bb1f44d30ba5b5e23b04c71dad3e/src/network/connection.spec.js#L9
