### ISSUE TITLE
KafkaJS crashes with typescript due to missing offset

### ISSUE THREAD

**Issue by jdfindwise** [tulios/kafkajs#307]
I tried to use KafkaJS but it crashed immediately using these dependencies: `"@types/node": "^11.10.5",` and `"kafkajs": "^1.5.0",`
I'm using it in a Typescript environment though, might be the issue.

`producer/partitioners/default.js` line 22
`let counter = crypto.randomBytes(32).readUInt32BE()`

According to `@types/node/globals.d.ts` `readUInt32BE(offset: number): number;`.

I don't know what the offset should be, if it should be zero or something, but leaving out an offset will have the application crash for me.

**Comment by tulios** [comment]
Hi @jdfindwise, we noticed that. PR #300 should fix this issue, can you work around the issue? We have some team using KafkaJS with typescript, and it is working fine, we should release a version soon fixing this problem.

**Comment by tulios** [comment]
You can try out the code in master:

```sh
yarn add https://github.com/tulios/kafkajs.git#5f152019b47e3ea5e912e48134204385b3350e91
```

**Comment by jdfindwise** [comment]
@tulios thank you for that link.
It did indeed fix the compile issue, I can now start the application.
I do get another issue
```
{"level":"ERROR","timestamp":"2019-03-08T14:43:22.423Z","logger":"kafkajs","message":"[BrokerPool] KafkaJSConnectionError: Failed to connect: net.connect is not a function","retryCount":0,"retryTime":243}
{"level":"ERROR","timestamp":"2019-03-08T14:43:22.425Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Failed to connect: net.connect is not a function","retryCount":0,"retryTime":243}
```
Not sure if you have seen this issue before?

**Comment by tulios** [comment]
This error is weird, `net` is part of the node.js standard library. Are you running using something else?

**Comment by jdfindwise** [comment]
Nevermind, was totally my fault that one.
Tried to run it in a browser, which obviously won't work, works fine from a node.js console :)

**Comment by Nevon** [comment]
That's awesome. I'm actually working on browser compatibility at the moment, but it's unfortunately not quite ready yet. In some weeks, I hope to have something available for you. 😃

**Comment by Borewit** [comment]
The error thrown if the offset is not provided is most likely related to feross/buffer#237
