### ISSUE TITLE
Nest Js Integration

### ISSUE THREAD

**Issue by reviloera** [tulios/kafkajs#308]
Sorry for asking a very basic question .... I am getting started on NestJs and just learned how Kafka is amazing, but on Nestjs documentation its indicated that they dont support kafka ... so am wondering can KAFKAJS work with NestJs? Is there anyone here who has tried ?  Thank you.

**Comment by tulios** [comment]
Hi @reviloera, it should work just fine. I haven't done anything with NestJS but there is nothing preventing you to use Kafka (with KafkaJS) on NestJS.

What they don't support is Kafka on their abstraction layer:
>  The NATS is a simple, high performance open source messaging system.

so you won't be able to use their abstraction to interact with Kafka, like `@MessagePattern`, etc.

**Comment by reviloera** [comment]
Hi @tulios thanks for the quick response.
