### ISSUE TITLE
How to send valid tombstones?

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#326]
I tried producing these key values, but seems kafka compaction cleaner doesn't count them as correct tombstones - these records never get removed, last value stored.

Created topic with such configuration, data compaction itself works well. But not tombstones removal.

Topic conf is following: 
```
{
	'test-compaction',
	configEntries: [
		{ name: 'cleanup.policy', value: 'compact' },
		{ name: 'segment.ms', value: '30000' },
		{ name: 'segment.bytes', value: '1000' },
		{ name: 'delete.retention.ms', value: '100' },
		{ name: 'min.cleanable.dirty.ratio', value: '0.01' }
	]
}
```

And procusing like that:
```
await producer.send({
	topic: `test-compaction`,
	messages: [{
		key: 'test1',
		value: null
	}]
});
```
or
```
await producer.send({
	topic: `test-compaction`,
	messages: [{
		key: 'test1',
		value: Buffer.from('')
	}]
});
```

With kafka console consumer, it first one shows value as null, another empty string. 
```
test1###null
test1###
```

But never seen any tombstone removed from kafka topic... which makes it grow forever with increasing keys

**Comment by tulios** [comment]
Hi @pimpelsang, your first example is correct. PR #185 fixed this some time ago; I think the best way to try this feature is to decrease the retention a lot; it's a tricky thing to test.

**Comment by pimpelsang** [comment]
Thanks!
