### ISSUE TITLE
This server is not the leader for that topic-partition

### ISSUE THREAD

**Issue by timojokinen** [tulios/kafkajs#335]
I have a consumer that listens to messages and processes them. It works fine for a few days but after a while it breaks:
This server is not the leader for that topic-partition

I set the following options:
autoCommitInterval: 5000,
autoCommitThreshold: 100,

Does anyone have an idea why that happens?

**Comment by Nevon** [comment]
Are you sure that the application breaks? `NOT_LEADER_FOR_PARTITION` is a transient error that happens when a partition migrates from one broker to another. The operation should be retried and the application should continue as usual afterwards.

**Comment by timojokinen** [comment]
Yes kafka retries 10 times but fails every time and then stops listening to messages

**Comment by timojokinen** [comment]
Hi, I actually don't have the logs except the error I mentioned above. I need to wait until it happens again. There were some errors below this error (i think it was errors while retrying to connect). Do you have any idea how I can reproduce this, so I can investigate it further? I am very clueless right now.

**Comment by tulios** [comment]
This feels like a cluster operation (leaders been moved), what version of KafkaJS are you using? We had an issue in some old version where the consumer would give up on the retries.

**Comment by timojokinen** [comment]
I'm using 1.4.6, should I upgrade?

**Comment by tulios** [comment]
yes, I did a quick check on the changelog, and I can spot at least two fixes that might help with this issue:

```
[1.4.8] - 2019-02-18
Fix consumer restart on find coordinator errors #253

[1.5.0] - 2019-03-05
Restart consumer on crashes due to retriable error #269
```

you can safely upgrade to `1.7.0`.

**Comment by Nevon** [comment]
I'm closing this due to lack of feedback. Feel free to open it back up if the issue persists, @timojokinen

**Comment by chainhead** [comment]
https://github.com/tulios/kafkajs/issues/518
