### ISSUE TITLE
Consume wildcard topics

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#336]
Something librdkafka and java clients support.

await consumer.subscribe({ topic: 'data-source-tables.*' });

And keeps up to date when new topics added :)

**Comment by Nevon** [comment]
This was implemented in #346 and will be available in the next release! 🎉

**Comment by denic** [comment]
@Nevon 

> This was implemented in #346 and will be available in the next release! tada

This is good news! Thanks for the effort. I have one question regarding handling of topics added after the consumer subscribed to a pattern. The documentation states: 

> The consumer will not match topics created after the subscription. If your broker has topic-A and topic-B, you subscribe to /topic-.*/, then topic-C is created, your consumer would not be automatically subscribed to topic-C.

So is the client using KafkaJS required to keep track of available topics and subscribed topics on its own?

**Comment by Nevon** [comment]
What it means is that there's no automatic polling in the background to see if there are any new topics available. If you want to automatically subscribe to new topics, I would think periodically repeating the subscribe call would work.
