### ISSUE TITLE
Throttle - Consume messages one by one

### ISSUE THREAD

**Issue by vykimo** [tulios/kafkajs#345]
Hello, I've a question :
Is this possible with this implementation of Kakfa to process message one by one (or more) ?
A way to makes Kafka act like with a throttle.

Thank you in advance for your answer 👍

**Comment by Nevon** [comment]
The default behavior of `eachMessage` is to process messages one by one, sequentially. So if you just configure a standard consumer, that's how it will work out of the box.

I'm not sure what you mean by a throttle though. There's no built in way to artificially limit the amount of messages that you process within a certain timespan, but you could fairly easily implement that outside of the library if needed.

**Comment by vykimo** [comment]
Oh ok I see, so `eachMessage` is the direct application of my use case.
but what if I want to allow the consumption of 2, 3 or 4+ messages maximum at the same time by a single consumer ? (that's actually my idea of the throttle)

**Comment by Nevon** [comment]
The current `master` of KafkaJS actually introduces a new [`partitionsConsumedConcurrently` setting](https://kafka.js.org/docs/consuming#a-name-concurrent-processing-a-partition-aware-concurrency) that allows you to do exactly that. If you set it to 3, it will process up to 3 messages at any given time.

However, that has not been released in any stable version yet. If you want to test it out, you are more than welcome to do so by using the master branch, but be aware that we can't guarantee that it's stable yet.

Your only other option would be to implement your own concurrency controls using [`eachBatch`](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch). It gives you the entire batch of messages for you to manage, which means that you could control how many you want to process concurrently yourself. `eachBatch` is a more complicated usage scenario though, so if you're new to Kafka I wouldn't recommend starting there.

**Comment by vykimo** [comment]
Wonderfull ! I will test it for sure. 
What are the possible side-effects or deviances ?

**Comment by Nevon** [comment]
That's correct. Kafka guarantees that the messages are ordered within a partition, so if we want to keep that guarantee, the maximum concurrency is bounded by the number of partitions. Note that if you are consuming from 2 topics with 3 partitions each, the maximum concurrency would be 6, and so on.

There are no known side-effects to using this option, but we also haven't tried it out with production-level load yet.

**Comment by vykimo** [comment]
Ok, I will. I keep you informed about my load test then.

**Comment by vykimo** [comment]
I just tested basic program and I have 2 questions @Nevon :
1. First of all, with a simple consumer described [https://kafka.js.org/docs/consuming](here) with `async eachMessage` and `partitionsConsumedConcurrently` set to 3, I succeed to read only messages from partition 0. Is that normal? What do I have to change in order to read from any partition of a topic?
2. Secondly, with `eachMessage` I cannot commit by myself messages, is that right? If yes, are the messages commited at the end of eachMessage or when entering the function?

Thanks by advance for your fast answers. 👍

**Comment by tulios** [comment]
@vykimo check if your topic have more than 1 partition, to have more partitions you have to create the topic with the number of partitions you want. `eachMessage` will commit the offset after the function is executed, if you throw inside the function it won't commit the offsets.

**Comment by vykimo** [comment]
Sorry my bad for partitions.
> `eachMessage` will commit the offset after the function is executed, if you throw inside the function it won't commit the offsets.

This information is verified. I'm ok with that.

I've a question now regarding the custom partitioner ; as I can read [https://kafka.js.org/docs/producing#custom-partitioner](here), we can get some infos about partitions. But is it possible to get the current offset of each partition. My strategy is that I want to set the id of partition with the lowest offset of the group.

**Comment by vykimo** [comment]
Can you tell me when `partitionsConsumedConcurrently` will be included in a npm version approximately? (with warning on users to be aware of it)
It's working well with master src.

**Comment by tulios** [comment]
We run all candidates in production before we release a new version, we updated one of our production systems last week with the latest code in master, so we are aiming to release this week. We usually post on our slack channel about new versions.

> is it possible to get the current offset of each partition

You can take a look at the admin client; you can easily fetch the topics offset and initialize your partitioner.

https://kafka.js.org/docs/admin#a-name-fetch-topic-offsets-a-fetch-topic-offsets

**Comment by tulios** [comment]
@vykimo is this answered? Can I close the issue?

**Comment by vykimo** [comment]
Yes sure @tulios, just tell me when you'll release a npm version including `partitionsConsumedConcurrently`.
