### ISSUE TITLE
Brokers received from metadata overwrite initially configured brokers

### ISSUE THREAD

**Issue by tim-mit** [tulios/kafkajs#352]
Before I start, I'm not sure if this is actually a bug, or indeed a feature hence feel free to close as you see fit!

My situation is that I wish to connect to a Kafka broker on a machine which I've only got SSH access to. I 'enable' this connection through the use of an SSH tunnel, exposing the broker port on my local machine where I'm running a `kafkajs` consumer on `localhost` (i.e. I've exposed the remote broker port locally in order to be able to connect to something that I otherwise wouldn't be able to connect to directly).

I've configured `kafkajs` to use this broker as;

```js
const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['127.0.0.1:9092']
})
```

and then establish a connection as shown in the examples. But what happens is that after the initial attempt to connect to the broker at `127.0.0.1:9092` it then attempts connection again to a different IP - one that I believe corresponds to data returned by the initial connection to the Kafka broker. My Kafka knowledge is limited but I'm guessing it first returns metadata about the broker or something, and part of that happens to be a list of brokers or something? The problem for me though is that that IP isn't resolvable from where I'm running my application - I've got an SSH tunnel in place as my means of access and the actual IP of the broker isn't useful for me.

After adding some logging to the library I see that the function returned from `refreshMetadata` in `cluster/brokerPool.js` is being called which in turn calls `connectionBuilder.build(..)` with a `host` parameter extracted from `this.metadata.brokers` (this code is all in a reducer loop). The value of `host` in `this.metadata.brokers` happens to be the real IP of the broker but sadly one I can't access directly. I've hacked my way around this for now by changing the parameter passed to the connection builder to be `seedHost` instead of `host` to ensure that the new connection that is established also uses my initially configured broker which works but is obviously a big hack!

Is it correct for the library to be picking up and overwriting the initially configured broker details by values returned from the initial connection to Kafka?

Is there some configuration I'm missing that will force the library to not use the returned metadata for subsequent requests and simply rely on the set of brokers configured to start with?

Cheers,
Tim

**Comment by Nevon** [comment]
Kafka does indeed return a list of brokers to connect to, and it is intentional that this overwrites the statically specified broker(s) that you have configured. This is because brokers can be removed from the cluster over time, which would mean that your initially configured ones may no longer be valid.

I'm actually working on something related, where I need to make the configuration to the broker through a proxy.

What you can do to enable this is to provide your own `SocketFactory`. The default one looks like this: https://github.com/tulios/kafkajs/blob/343947a10f00a155417f43b267f9cf5afc6d43e7/src/network/socketFactory.js#L3-L22

In your case, you would want to overwrite the host. Something like:

```javascript
const net = require('net')
const tls = require('tls')
const KEEP_ALIVE_DELAY = 60000 // in ms

module.exports = ({ host, port }) => {
  return ({ ssl, onConnect }) => {
    const socket = ssl
      ? tls.connect(
          Object.assign({ host, port }, ssl),
          onConnect
        )
      : net.connect(
          { host, port },
          onConnect
        )

    socket.setKeepAlive(true, KEEP_ALIVE_DELAY)

    return socket
  }
}
```

You would then specify that `socketFactory` when instantiating your client:

```javascript
const CustomSocketFactory = require('./customSocketFactory')
const { Kafka } = require('kafkajs')

const client = new Kafka({
  clientId: 'my-app',
  brokers: ['127.0.0.1:9092'],
  socketFactory: CustomSocketFactory({ host: '127.0.0.1'. port: 9092 })
})
```

Note that this means that you'll always connect to a single machine. If you only have a single broker, that might be fine, but in most scenarios you'd have more than one broker, and specific requests would need to go to one broker or another.

**Comment by tulios** [comment]
Hi @tim-mit, the seed brokers are just that, seed. They are only used to load metadata once when the library boots. I know that this makes your use-case harder, but that's the correct behavior. I have seen some libraries offering a function to map the hosts, that's a much simpler approach than having a custom socket factory, we could consider that.

**Comment by tim-mit** [comment]
Thanks for the pointers guys, I'll have a go at the custom socket for now.

@tulios do you have an example of the sort of thing you would consider as an appropriate API/config for mapping? If you do have a proposal I may be able to find time to try and contribute something back.

**Comment by Nevon** [comment]
So here's one of those things where Tulio and I will violently disagree. 😄 My proposal is that this belongs outside of KafkaJS core, and that we should just provide powerful primitives. The way I think a mapping should be implemented is to have KafkaJS export the default socket factory, and then just wrap that in something that replaces the host and port and delegates back to the default socket factory. Something like:

```javascript
const { SocketFactory, Kafka }  = require('kafkajs')

const MappedSocketFactory = (mapping = {}) => {
  const defaultSocket = SocketFactory()

  return ({ host, port, ...rest }) => {
    const mappedDestination = mapping[`${host}:${port}`] || { host, port }
    return defaultSocket({ host: mappedDestination.host, port: mappedDestination.port, ...rest })
  }
}

const client = new Kafka({
  socketFactory: MappedSocketFactory({
    '10.10.10.10:1234': { host: '127.0.0.1', port: 9092 }
  })
})
```

Tulio tends to have a different philosophy, so we'll see what he says. 😉

**Comment by tulios** [comment]
I agree with you @Nevon, I always advocate on the developer experience, but my question was more to highlight that this is a requested feature. I think we fully cover the needs of a mapper function with the socket factory.

**Comment by Nevon** [comment]
I'm gonna go ahead and close this issue. Feel free to open up a new one if you feel that the current capabilities don't adequately solve your issue, @tim-mit
