### ISSUE TITLE
Error "Producing to topic without metadata" 

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#354]
Producing right after 
`await this.producer.connect()`

logs this error, which later is fixed automatically?

Why it happens, is is critical or retry handles it?

**Comment by Nevon** [comment]
When sending a message, the client needs to know which broker to send the request to. If it hasn't had a chance to load metadata yet, it throws a `KafkaJSMetadataNotLoaded` error which gets caught by the retrier, which in turn fetches metadata and then retries sending the message.

This is handled automatically and is not a problem unless it persists through several retries.

**Comment by pimpelsang** [comment]
Can this be avoided? Isn't error level log too high?

**Comment by micaelmbagira** [comment]
@Nevon I am asking myself the same question, shouldn't this be a warning?

**Comment by tulios** [comment]
I think it should be a warning, we included this log some time ago to shed some light on another bug, but it should be a warning. I will change it.
