### ISSUE TITLE
KafkaJS and java producer partitioning returning different results

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#357]
Producing message with the same key gets assigned to different partitions depending if app is using java or nodejs client. 

This creates problems when using kafka streams for joining those data - **meeting the co-partitioning requirement fails** even when message keys are the same.

I created an isolated test code which confirmed it. Simple java and nodejs app with partitioning using murmur2 code extracted from the latest kafkajs and java producer. The code looks the same, but results differ. Even checked that input bytes are equal. ¯\_(ツ)_/¯

Test runner result matches the partition number I'm seeing in Kafka broker...

Any idea why and can it be fixed? 

Our current workaround is to repartition all kafkajs based messages with java producer.. 

```
let key = '100:48069';
let numPartitions = 12;

node bytes {"type":"Buffer","data":[49,48,48,58,52,56,48,54,57]}
node murmur 1713501762
node hash 1713501762
node partition 6

java bytes 49 48 48 58 52 56 48 54 57 
java murmur 1009543857
java hash 1009543857
java partition 9
```
 
[partitioning test code.zip](https://github.com/tulios/kafkajs/files/3155784/partitioning.test.code.zip)

**Comment by Nevon** [comment]
I have a feeling this is gonna be a fun one. 😄 I added a branch with a repro case based on what you did. The partitioner code was written by @tulios in the beginning of time, so I don't have any immediate idea why it doesn't match. I'll probably take a look later this week, but feel free to investigate further.

**Comment by Nevon** [comment]
I found where the issue is, though I don't understand it yet.

https://github.com/tulios/kafkajs/blob/c5ab8c229369ae4966ffd3ce22e2b0c00191943b/src/producer/partitioners/default/murmur2.js#L28

I ran some interactive debugging of both the Java and JS implementations, executing them side-by side and comparing the values. On this line, the values diverge between the JS and Java implementations. Given the key you provided, on the first iteration of the loop, `k` is `976236593` and `m` is `1540483477` in both JS and Java, but after doing `k *= M`, the value of `k` is `2095687045` in Java and `1503876341159274000` in JS.

Essentially:

```java
int k = 976236593
int m = 1540483477

k * m == 2095687045
```

```javascript
const k = 976236593
const m = 1540483477

k * m === 1503876341159274000
```

**Comment by Nevon** [comment]
And just because I'll forget unless I write it down, to interactively debug a Java program in the CLI:

```
javac -g Test.java
jdb Test
stop in Test.murmur2
step
list // shows you the code and where you are
locals // print local variables
print <variable>
```

**Comment by Nevon** [comment]
@pimpelsang Would you be able to try out latest `master` with the Java compatible partitioner and see if it works as it should?

As soon as the master build is done, there'll be documentation available at https://kafka.js.org/docs/producing#a-name-custom-partitioner-a-custom-partitioner but this is the gist of it:

```javascript
const { Partitioners } = require('kafkajs')

kafka.producer({ createPartitioner: Partitioners.JavaCompatiblePartitioner })
```

**Comment by pimpelsang** [comment]
Tried it out. Works! Thank you very much for so fast fix
