### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kareha** [tulios/kafkajs#363]
Hi,
I get this warning, when send message:

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

> [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It happens in File src/cluster/brokerPool.js at Line 120:
`this.metadata = await broker.metadata(topics)`

Is there a way you can catch the warning?
Thx

**Comment by tulios** [comment]
Hi @kareha, can you post a snippet of code similar to the one you use to send the message? You are probably passing something that can't be serialized.

**Comment by kareha** [comment]
I tried to send the following message:

```
message = {
  topic: 'my_topic',
  messages:  [
    {
       headers: { type: 'error' },
       value: '{"error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"tmp/test.pdf"}}'
    } 
  ]
}
```

**Comment by tulios** [comment]
I tried your example with the example producer in the repo and it works, so it has to be the code around that. Can you provide the code interacting with the client?

```javascript
const sendMessage = () => {
  return producer
    .send({
      topic,
      messages: [
        {
          headers: { type: 'error' },
          value: '{"error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"tmp/test.pdf"}}',
        },
      ],
    })
    .then(console.log)
    .catch(e => console.error(`[example/producer] ${e.message}`, e))
}

const run = async () => {
  await producer.connect()
  setInterval(sendMessage, 3000)
}

run().catch(e => console.error(`[example/producer] ${e.message}`, e))
```

**Comment by kareha** [comment]
Thanks, that helped :)
I think I missed the catch. Can be closed
