### ISSUE TITLE
Consumer: Fails to subscribe after run()

### ISSUE THREAD

**Issue by denic** [tulios/kafkajs#371]
Hi guys, I have a follow up question to https://github.com/tulios/kafkajs/issues/336#issuecomment-490830101

I started to play around with kafkajs and tried to integrate it to our high-level solution. We need to dynamically subscribe to  topics during runtime. 
To me it looks like subscribing to topics after consumer.run(...) was called does not add the new topic to the list of topics that get fetched in the ConsumerGroup:

![kafkajs_subscribe_bug_1](https://user-images.githubusercontent.com/129499/58260344-8f948900-7d76-11e9-91a9-1348e351085f.png)
('topic-test' and 'service__alpha' gets subscribed before calling `run()`, 'XXX' after `run()`)

Is it me doing it wrong, is the consumer not intended to be used in this way or did I stumble over a bug?

Thanks a lot in advance!

**Comment by tulios** [comment]
Hi @denic, looking at the code I can say that this won't work with the current implementation. To add topics on demand, the client will have to force a rebalance so that the leader can assign the partitions of the new topics.

We will need to change some internals to make this happen, what you can do in the meantime is to use the admin client to fetch the list of topics continuously and once you find a new topic you restart the consumer, which will use the regexp subscribe to fetch the new topics correctly.

We are planning a small release soon, but I don't think we would include this change now.

**Comment by denic** [comment]
Thanks @tulios . Much appreciated!

**Comment by tulios** [comment]
Feel free to re-open the issue; I can create a feature request issue later describing the steps.

**Comment by Arkh1** [comment]
@tulios - Could you elaborate on what you mean by restarting the consumer?  I also have a need for dynamically creating and subscribing to topics.  I tried calling consumer.stop() followed by consumer.run(), but that didn't seem to help.  I also tried just creating a new instance of the same consumer and subscribing to all existing topics again.  That also didn't seem to work.

Also, has there been any updates on supporting dynamic topics in a more natural way?

**Comment by Tony1704** [comment]
Hi @tulios, thanks for providing the workaround. Restarting the consumer will be quite slow when a lot of topics are involved, right? 
Is there any update on when a subscription for a running consumer will be possible?

**Comment by shaolinjr** [comment]
Anyone got solution for this??

**Comment by ori-rezonate** [comment]
Is anything new about this? any recommended workaround for big-scale env (rebalancing costs a lot)

**Comment by fyilmaz2** [comment]
any updates on this?

**Comment by nightknighto** [comment]
Sad

**Comment by jvbfelix** [comment]
Hi, after some tries, I can do the subscription I need.
The problem is the stop method. It gets blocked when I make an `await consumer.stop()`
The solver for me is to use the consumer.stop() and a .then() solver.

```
const objectList = [ obj1, obj2, obj3]
kafkaConsumer.stop().then(async () => {
      console.log('Kafka consumer stopped');
      await Promise.all(
        objectList.map(async (obj) => {
          const topics = [
            obj+'-topic1',
            obj+'-topic2',
          ];
          await kafkaConsumer.subscribe({ topics, fromBeginning: true });
        })
      );
  
      await kafkaConsumer.run(consumerRunConfig);
      console.log('Topics updated');
});
```
