### ISSUE TITLE
use turbo-crc32 as most faster pure js crc32 library

### ISSUE THREAD

**Issue by reklatsmasters** [tulios/kafkajs#372]
### Benchmark

*nodejs 10.14.1 / Ubuntu 16.04 x64*

```
buffer-crc32:   1387.205ms
crc:            987.866ms
turbo-crc32:    447.711ms
```

https://www.npmjs.com/package/turbo-crc32

**Comment by tulios** [comment]
Does this benchmark use our implementation o crc32? We don't have dependencies on any libraries; you can swap the implementation with turbo crc32 if you want.
