### ISSUE TITLE
 The group is rebalancing, re-joining

### ISSUE THREAD

**Issue by LakhsmiC** [tulios/kafkajs#375]
I am getting below error every few minutes. Below are the logs for the same .
"level":"ERROR","timestamp":"XXX","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 1)","broker":"XXXX","clientId":"kafkajs","error":"The group is rebalancing, so a rejoin is needed","correlationId":12,"size":10}
{"level":"ERROR","timestamp":"XXXX","logger":"kafkajs","message":"[Runner] The group is rebalancing, re-joining","groupId":"XXX","memberId":"kafkajs-XXXX","error":"The group is rebalancing, so a rejoin is needed","retryCount":0,"retryTime":261}.

Can you please look into this issue.

**Comment by tulios** [comment]
Hi @LakhsmiC, this is a common error in Kafka. If the rebalance is happening too frequently, it means that eachMessage or eachBatch are taking too long and the consumer is been kicked out of the group. The default session timeout and heartbeat interval are quite small, it's recommended to adjust those values to something that matches the type of workload you are doing. maxBytes defaults to 10MB which can be too much depending on what you are doing in the consumer, take a look at this: https://kafka.js.org/docs/faq#what-does-it-mean-to-get-rebalance-in-progress-errors

it might give you a better overview of what is happening.
