### ISSUE TITLE
[help needed] custom rebalance function to subscribe to a single partition

### ISSUE THREAD

**Issue by bobzsj87** [tulios/kafkajs#376]
I am working on a response-request feature based on partition. Let's say you have 20 partitions in a topic, and worker A subscribe to 0, worker B joins later and subscribe to 1, and so on.

How to write such rebalance assignment function that only takes care of its own member and its assignment, without rebalancing any existing workers?

Reopening #294

**Comment by JaapRood** [comment]
I'm not 100% sure, but would #373 do what you want to do?

**Comment by bobzsj87** [comment]
> I'm not 100% sure, but would #373 do what you want to do?

Yes, the java document describes the behaviour I want.

**Comment by dhessler** [comment]
Also looking for this feature; is this possible with the current kafkajs apis?

In my case each consumer maintains state relative to a single partition, and I'm trying to assign each partition to a dedicated consumer (preferably without unnecessary rebalances).

**Comment by JaapRood** [comment]
You _can technically work_ around it and sort of get the behaviour you want, but it's not idiomatic Kafka (manual assignments would be, see #373):

- Create a consumer with a random `groupId` (uuid would work well).
- Subscribe to the topic you want to consume. You'll be assigned all the partitions, as you'll be theo only consumer in the group.
- Consume all messages through `eachMessage` or `eachBatch`, but skip all the messages that don't have the partition you wish to consume.

While this should work, it also creates a bunch of noise on your kafka cluster in form of lots  and lots of consumer groups. On top of that, you're actually fetching messages for all partitions, which depending on how many partitions the topic has, can cause significant overhead to the client and load on the cluster.

**Comment by dhessler** [comment]
Thank you for the input @JaapRood,

Processing all partitions is not feasible in my case, so I came up with the follow:
- Create a manual partition assigner that ensures a consumer group is only assigned a single fixed partition
- Create a consumer with a fixed `groupId` for each partition (e.g., `group-0`, `group-1`, etc), configured with the manual partition assigner

At first glance, this implementation seems to be working nicely.
Apart from the need for a consumer group for each partition, do you see any glaring performance/maintenance issues with this strategy?

**Comment by JaapRood** [comment]
@dhessler nice one 👌 Reminds me of actually discussing something similar a while back, when I first ran into this (I didn't actually work around it at the time). Should be  the most efficient way of doing it at the moment, gets rid of all the extra fetching overhead.
