### ISSUE TITLE
Validate message format in producer

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#39]
KafkaJS won't raise any errors if the message doesn't have a `value` attribute and this might be hard to debug.

Messages without `value` (e.g: `{ key: 'key1'}`) should raise an error.

**Comment by Nevon** [comment]
This happened again now. It was being called with:

```javascript
// This was being AVRO encoded, which made it less obvious
const message = { foo: 'bar' }

await producer.send({
  topic,
  messages: [message],
})
```

Which led to messages being pushed with `key` and `value` `null`.
