### ISSUE TITLE
Regexp based subscription not subscribing topics

### ISSUE THREAD

**Issue by rafalneves** [tulios/kafkajs#391]
![image](https://user-images.githubusercontent.com/4136503/59427961-d3a60700-8dd3-11e9-8b60-e0a6cb35a27f.png)

Regexp base subscription seems not to be working as expected. Or I could be doing something wrong.

Take this example, that you can see in the image above:

```
consumer.disconnect().then(() => {
  consumer.connect().then(() => {
     consumer.subscribe({ topic: /.*-something/i });
     consumer.subscribe({ topic: '2-something' });

```

The first one generates no subscription what so ever, but multiple active topics exist, currently receiving data. The second one works as expected.

**Comment by tulios** [comment]
Hi, this is bad. Can you try using `RegExp` instead of double slashes? Maybe the regexp check is failing, I will take a look.

Thanks for the report

**Comment by rafalneves** [comment]
I should've mentioned that I tried that too. Same result.

**Comment by tulios** [comment]
ok, that's weird because we have integration tests for that, and they are working

https://github.com/tulios/kafkajs/blob/0ff0d40274f85189c39806939b61fc3628dc3ee4/src/consumer/__tests__/subscribe.spec.js#L57-L97

I will take a look

**Comment by rafalneves** [comment]
Let me know if I can be of any help.

I have SASL enabled, not sure if it's relevant.

> 
> info [Monitor]: 2019-06-13 12:36:31 Consumer Stopped
> debug [Monitor]: 2019-06-13 12:36:31 Consumer consumer has stopped, disconnecting
> debug [Monitor]: 2019-06-13 12:36:31 Connection Connecting
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request ApiVersions(key: 18, version: 2)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response ApiVersions(key: 18, version: 2)
> debug [Monitor]: 2019-06-13 12:36:31 Broker Verified support for SaslAuthenticate
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request SaslHandshake(key: 17, version: 1)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response SaslHandshake(key: 17, version: 1)
> debug [Monitor]: 2019-06-13 12:36:31 SASLPlainAuthenticator Authenticate with SASL PLAIN
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request SaslAuthenticate(key: 36, version: 0)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response SaslAuthenticate(key: 36, version: 0)
> debug [Monitor]: 2019-06-13 12:36:31 SASLPlainAuthenticator SASL PLAIN authentication successful
> info [Monitor]: 2019-06-13 12:36:31 Consumer Starting
> debug [Monitor]: 2019-06-13 12:36:31 Cluster No brokers in the broker pool, refreshing metadata and trying again...
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Consumer Subscription based on RegExp
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response Metadata(key: 3, version: 5)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request GroupCoordinator(key: 10, version: 1)
> debug [Monitor]: 2019-06-13 12:36:31 Connection Response GroupCoordinator(key: 10, version: 1)
> debug [Monitor]: 2019-06-13 12:36:31 Cluster Found group coordinator
> debug [Monitor]: 2019-06-13 12:36:31 Connection Request JoinGroup(key: 11, version: 2)
>

**Comment by rafalneves** [comment]
Were you able to replicate this?

**Comment by rafalneves** [comment]
Nevermind, my fault.

**Comment by tulios** [comment]
@rafalneves sorry that took this long, can you share what happened? Maybe it is something other people could face in the future.

**Comment by rafalneves** [comment]
No problem. Was calling consumer consumer.run without waiting for the subscription to complete.

```
  consumer.subscribe({ topic: /.*-sensors-control/i });
  consumer.subscribe({ topic: /.*-rule-alerts/i });

  consumer.run({ eachMessage: dataHandler });
```

Instead of:
```
  await consumer.subscribe({ topic: /.*-sensors-control/i });
  await consumer.subscribe({ topic: /.*-rule-alerts/i });

  await consumer.run({ eachMessage: dataHandler });

```
