### ISSUE TITLE
Consumer can not pause and resume individual partitions

### ISSUE THREAD

**Issue by JaapRood** [tulios/kafkajs#396]
While the Consumer has `pause` and `resume` methods, these can only be used on the topic level. Since the partition is the unit of concurrency Kafka has been designed around, it would make sense to control the consumption rate for each partition individually.

## Proposed solution

Accept a `partition` or `partitions` argument as part of `consumer.pause` and `consume.resume`.

**Comment by JaapRood** [comment]
It's Friday past 6pm local time, so this issue is less detailed than I would normally make them. Happy to expand on it later if that's required!

**Comment by tulios** [comment]
We kept this feature out consciously; we needed resume and pause, so we implemented just what we need back them, we knew we would eventually come back and add the remaining features. We were waiting for the need, so the time has come. 😄

**Comment by JaapRood** [comment]
> [...] so we implemented just what we need back them, [...]

👏👏🙌

We'll get along just fine :)

**Comment by JaapRood** [comment]
Fixed by #417.
