### ISSUE TITLE
TypeError: isStale is not a function

### ISSUE THREAD

**Issue by Thymios** [tulios/kafkajs#401]
Tried the eachBatch processing as in the docs controlling for isStale() and got this type error:
TypeError: isStale is not a function

await consumer.run({
    eachBatch: async ({ batch, heartbeat, isRunning, isStale }) => {
      for (let message of batch.messages) {
        if (!isRunning() || isStale()) break
....

using kafkajs v1.8.0
node v12.4.0

**Comment by Nevon** [comment]
`isStale` has not been released yet. Unfortunately the docs are not versioned, so whatever is in master is what's on the website.

If you need the functionality, you can use master directly, otherwise `isStale` will be part of the next release.
