### ISSUE TITLE
I'm not pretty sure how to batch processing works

### ISSUE THREAD

**Issue by nkt** [tulios/kafkajs#406]
Hello, thanks for your library. I'm not pretty sure if this code is correct:
```js
  await consumer.run({
    async eachBatch({ batch, commitOffsetsIfNecessary }) {
      const messages = batch.messages.map((message) => deserialize(message.value));
      await processTransactionally(messages);
      await commitOffsetsIfNecessary();
    },
  });
```

**Comment by Nevon** [comment]
There are potentially some issues with the code you posted, but what problem are you having exactly?

You can see an example of how to use the `eachBatch` interface here: https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch

If all you want to do is to process messages concurrently, you don't necessarily need to use `eachBatch`, but can instead use the simpler [`partitionsConsumedConcurrently` option of the `eachMessage` interface](https://kafka.js.org/docs/consuming#a-name-concurrent-processing-a-partition-aware-concurrency).

**Comment by anupamd2-zluri** [comment]
@Nevon Hi. I had a question. What if I have 4 partitions and 4 consumers which will have 1-1 mapping. I am trying to run eachBatch() and for each message in the batch there is some DB operation. Currently what is happening is it keeps on reading the batches but the DB calls for each message isn't happening. Am I missing something here?
