### ISSUE TITLE
LogCreator typings do not match documentation

### ISSUE THREAD

**Issue by ramesius** [tulios/kafkajs#408]
I think the typescript typings maybe wrong for the `LogCreator` functionality

The signature in the typings is as follows:
https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L348-L350

Whereas the docs mention something along the lines of:
```typescript
(logLevel: string) => (namespace: string, level: string, label: string, log: { timestamp, logger, message, ...extraKeys }) => void
```
Link: https://kafka.js.org/docs/custom-logger

Do the typings need to be updated to match the documentation?

Edit: Added link to docs

**Comment by tulios** [comment]
The documentation is correct, I have a patch for the typings. I caught that late yesterday, we should have a new version soon. Thanks for the report

**Comment by ramesius** [comment]
Excellent, thanks :)

**Comment by tulios** [comment]
`1.9.2` is out, thanks again!
