### ISSUE TITLE
Add a paused method to consumer

### ISSUE THREAD

**Issue by terebentina** [tulios/kafkajs#415]
ATM the consumer doesn't expose the `paused()` method from `consumerGroup`. It looks trivial to do so, so...any reason I am missing not to?
Happy to submit a PR for it if you're ok with a `consumer.paused()` method.

**Comment by tulios** [comment]
@terebentina we never had the need, so we never implemented. Feel free to submit a PR; we would gladly accept. 😄

**Comment by tulios** [comment]
Fixed on #444, released on `v1.10.0`
