### ISSUE TITLE
Support for max.poll.records

### ISSUE THREAD

**Issue by mt4c** [tulios/kafkajs#420]
Will there be support for max.poll.records in config so  that I can control how many records are fetched by consumer?

**Comment by tulios** [comment]
Hi @mt4c, we had a discussion some time ago about this property and concluded that it wasn't the time to invest in this feature for a couple of reasons.

1) If you have a stable message, it's quite simple to have the average message size, for example, we do it like this:

```javascript
const AVG_MESSAGE_SIZE = 280 // bytes
const NUMBER_OF_MESSAGES_TO_RECEIVE = 400
const MAX_BYTES_PER_PARTITION = NUMBER_OF_MESSAGES_TO_RECEIVE * AVG_MESSAGE_SIZE
const MAX_BYTES = 32 * MAX_BYTES_PER_PARTITION
```

2) If you use plain JSON and have variable sizes, or have way too different sizes, it becomes a harder problem. The messages might have 100 bytes or 53 MB, which makes the size detection harder and we would need to change the `maxBytes` configuration dynamically, so we think userland code would be easier to write and deal with this case for now. You can use `eachBatch` and only feed the expected amount of messages to your handlers.

**Comment by JaapRood** [comment]
@tulios regarding `maxBytes` being able to change dynamically: that _would_ be one of the main requirements to implement a proper _Stream_ in userland, which is quite possibly the cleanest and most platform native way to consume messages in a memory-efficient and performant way. Feeding a stream from an `eachBatch` is what we're doing currently, but you're basically creating a second buffer that you don't really have any control over. Now there's more required to implement a _Stream_ on top of this (like #417), but it's worth to keep in mind as a limiting factor of `eachBatch`.

**Comment by tulios** [comment]
Yeah, I don't think it's a lot of work to allow changes to `maxBytes`, I am talking about having the logic to increase/decrease based on the messages in KafkaJS, more as a priority thing. If we get more time or people interested, we can definitely do it.

* Over here we had to upgrade the cluster and make significant changes to work the growth we had, so most of my time is now debugging some mysterious bugs and helping the teams to adjust to the new setup.

**Comment by mt4c** [comment]
OK, after some search on the google I found that it is a bad idea to implment task queues on kafka. Trying to find another way. So should I close this issue?

**Comment by JaapRood** [comment]
Not sure what in Kafka makes it a bad idea for implementing task queues, we're definitely employing it in such a way. One thing is that it's basically a lower level tool than most dedicated task queues, so it's not as easy to work that way, but it's got all the primitives you need. That probably means that if all you're doing is a task queue, and you're not _that_ worried about things like solid processing guarantees (like at-least-once or exactly-once), it might be a bit overkill for just that.

**Comment by tulios** [comment]
I guess you need to be creative to have priority and other mechanisms with Kafka, is feasible, and we have a similar setup, but depending on the needs it can be overkill, especially due to the increase in complexity.

**Comment by nickyromeijn** [comment]
Are there any plans to add this feature to the roadmap? I'm currently running into a situation where it would be very nice to have. While creating new consumers and setting maxBytes dynamically is technically possible it would mean I'd have to know and broadcast the message size in advance to consumers. Which seems a bit weird considering the premise of Kafka

**Comment by Nevon** [comment]
No one is actively working on this, and it's fairly unlikely that one of us will have time to pick it up. 

Regarding your particular use-case, why does it matter if the consumer picks up 1 or 10 messages at a time? It can still process them one at a time, and anyway it's not likely anyone else can pick up a message on the same partition, so it's not like you're gaining any concurrency.

**Comment by nickyromeijn** [comment]
Actually I am and would be. I work with massively different message sizes and sometimes processing can take up to 10+ minutes. In that case I add in extra consumers which are AWS EC2 machines to pick up the slack. If one machine pulls for example 500 messages I do not gain anything by spinning up more machines. My workaround for now is just to create topics with 1000 partitions which allows me to scale up to 1000 consumers and let the rebalancer do its work

**Comment by SEUNGGWANSHIN** [comment]
> Hi @mt4c, we had a discussion some time ago about this property and concluded that it wasn't the time to invest in this feature for a couple of reasons.
> 
> 1. If you have a stable message, it's quite simple to have the average message size, for example, we do it like this:
> 
> ```js
> const AVG_MESSAGE_SIZE = 280 // bytes
> const NUMBER_OF_MESSAGES_TO_RECEIVE = 400
> const MAX_BYTES_PER_PARTITION = NUMBER_OF_MESSAGES_TO_RECEIVE * AVG_MESSAGE_SIZE
> const MAX_BYTES = 32 * MAX_BYTES_PER_PARTITION
> ```
> 
> 1. If you use plain JSON and have variable sizes, or have way too different sizes, it becomes a harder problem. The messages might have 100 bytes or 53 MB, which makes the size detection harder and we would need to change the `maxBytes` configuration dynamically, so we think userland code would be easier to write and deal with this case for now. You can use `eachBatch` and only feed the expected amount of messages to your handlers.

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
now... that time 
i wanna use 'max.poll.records' options.
have you plan to develop 'max.poll.records' options?

**Comment by rambo-panda** [comment]
> 嗨 @mt4c, 前段时间我们就此物业进行了讨论,并得出结论,由于以下几个原因,现在不是时候对该功能进行投资。
> 
> 1. 如果您有稳定的消息,则具有平均消息大小非常简单,例如,我们这样做是:
> 
> ```js
> const AVG_MESSAGE_SIZE = 280 // bytes
> const NUMBER_OF_MESSAGES_TO_RECEIVE = 400
> const MAX_BYTES_PER_PARTITION = NUMBER_OF_MESSAGES_TO_RECEIVE * AVG_MESSAGE_SIZE
> const MAX_BYTES = 32 * MAX_BYTES_PER_PARTITION
> ```
> 
> 2. 如果您使用纯JSON且尺寸可变,或者尺寸太不同,则这将成为一个更困难的问题。消息可能具有100字节或53 MB,这使大小检测更加困难,我们需要更改 `maxBytes` 动态配置,因此我们认为userland代码目前更容易编写和处理这种情况。你可以使用 `eachBatch` 并且仅将预期数量的消息提供给您的处理程序。

Hello, I have a question about this?
I have opened a test kafka topic locally with 16 partitions. The consumer configuration is as follows
```
    partitionsConsumedConcurrently: 1,
    maxBytesPerPartition: 100,
    maxBytes: 100 + 1024,
    minBytes: 1,
```
I used the `kcat` to punch `40bytes * 10` into the topic. I think the consumer should receive two (80bytes) or three (120bytes), but it gives me all (10 * 40bytes).

Please suggest an answer to this query. Thanks a lot.

**Comment by rambo-panda** [comment]
> Hi @mt4c, we had a discussion some time ago about this property and concluded that it wasn't the time to invest in this feature for a couple of reasons.
> 
> 1. If you have a stable message, it's quite simple to have the average message size, for example, we do it like this:
> 
> ```js
> const AVG_MESSAGE_SIZE = 280 // bytes
> const NUMBER_OF_MESSAGES_TO_RECEIVE = 400
> const MAX_BYTES_PER_PARTITION = NUMBER_OF_MESSAGES_TO_RECEIVE * AVG_MESSAGE_SIZE
> const MAX_BYTES = 32 * MAX_BYTES_PER_PARTITION
> ```
> 
> 2. If you use plain JSON and have variable sizes, or have way too different sizes, it becomes a harder problem. The messages might have 100 bytes or 53 MB, which makes the size detection harder and we would need to change the `maxBytes` configuration dynamically, so we think userland code would be easier to write and deal with this case for now. You can use `eachBatch` and only feed the expected amount of messages to your handlers.


----
Hello, I have a question about this?
I have opened a test kafka topic locally with 16 partitions. The consumer configuration is as follows

    partitionsConsumedConcurrently: 1,
    maxBytesPerPartition: 100,
    maxBytes: 100 + 1024,
    minBytes: 1,
I used the kcat to punch 40bytes * 10 into the topic. I think the consumer should receive two (80bytes) or three (120bytes), but it gives me all (10 * 40bytes).

Please suggest an answer to this query. Thanks a lot.
