### ISSUE TITLE
kafka consumer group latest messages not working

### ISSUE THREAD

**Issue by kashikhan1** [tulios/kafkajs#432]
every time i restart the node server or create a new connection with socket using kafka node version 4.1.3.its take the previous messages again.I want to see only new messages using conusmer or consumerGroup thanks in advance
const options = {
				// connect directly to kafka broker (instantiates a KafkaClient)
				kafkaHost: process.env.KAFKA_HOST,
				autoCommit: false,
				protocol: ['roundrobin'],
				fromOffset: 'latest'
			}
const consumerGroup = new ConsumerGroup(options as any, topic_all)
consumerGroup.on('message', (message:any) => {
	io.emit(JSON.parse(message.value).unit_id, message.value)
});

**Comment by tulios** [comment]
Hi @kashikhan1, wrong library. KafkaJS is a different library, you are looking for the node-kafka repository.
