### ISSUE TITLE
TypeError: topicPartitions is not iterable

### ISSUE THREAD

**Issue by yishain11** [tulios/kafkajs#439]
When I try to pause a message reading, like so:
consumer.pause({topic: 'SomeTopic',partitions:[0]})
// do something... and then:
consumer.resume({topic: 'SomeTopic',partitions:[0]})

and I get the following error message:
TypeError: topicPartitions is not iterable

I have Centos 7 machine, and the latest kafka, zookeeper and kafkaJS versions.

**Comment by tulios** [comment]
Hi @yishain11, you have to provide an array of topics to resume/pause. You can take a look here:
https://kafka.js.org/docs/consuming#a-name-pause-resume-a-pause-resume

**Comment by yishain11** [comment]
Oh my. Sorry, I havn't noticed. Thanks!

**Comment by tulios** [comment]
@yishain11 KafkaJS always loads a batch of messages, even if you use `eachMessage`, but if you await when processing your message it won't move to the next one until the promise is resolved.

**Comment by JaapRood** [comment]
@tulios we _could_ probably accept either a single `topicPartition` or array of them. Extends the API surface area a tiny bit, but would make it easier to use!

**Comment by tulios** [comment]
@JaapRood I would go for another method, but I am anti polymorphic methods
It always bit you back :D

**Comment by yishain11** [comment]
@tulios Thanks for the tip, but every combination I tried with async await still ended up reading the next one before finishing to process that current one.

**Comment by tulios** [comment]
@yishain11 you post some code I can take a look, we have a lot of consumers using KafkaJS and we this always works, so maybe we are talking about different things
