### ISSUE TITLE
Randomly fails to connect to local kafka cluster

### ISSUE THREAD

**Issue by ThisIsMissEm** [tulios/kafkajs#443]
Occasionally when working with kafkajs, I notice that the client outputs a bunch of errors like this:

```
{"level":"ERROR","timestamp":"2019-07-24T14:37:36.979Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka.quandoo.local:9092","clientId":"fake-qwell"}
{"level":"ERROR","timestamp":"2019-07-24T14:37:36.984Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":322}
```
And the client then proceeds to repeat that message and never eventually connects to kafka. If I  exit my program, give it a few moments, then try again, then it connects fine.

I'm using kafka+zookeeper in Docker, with the broker host being resolved by a locally running dnsmasq instance; Kafkacat remains connected the entire time.

**Comment by ThisIsMissEm** [comment]
It seems that it's actually an issue with exhausting the number of connections that the Kafka Broker can handle or something. I finally managed to get kafkacat to crash under the same conditions:
```% Reached end of topic fake-qwell.reservations [0] at offset 4
%5|1563984005.027|REQTMOUT|rdkafka#consumer-1| [thrd:kafka.quandoo.local:9092/bootstrap]: kafka.quandoo.local:9092/1: Timed out FetchRequest in flight (after 1109309ms, timeout #0)
%4|1563984005.027|REQTMOUT|rdkafka#consumer-1| [thrd:kafka.quandoo.local:9092/bootstrap]: kafka.quandoo.local:9092/1: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
% ERROR: Local: Timed out: kafka.quandoo.local:9092/1: 1 request(s) timed out: disconnect (after 3594446ms in state UP)
% ERROR: Local: All broker connections are down: 1/1 brokers are down : terminating```

**Comment by Nevon** [comment]
Could you provide a little more context as to what it is you're doing? Certainly if you are repeatedly creating new connections, eventually either the client or the server will run out of resources, but I would consider that a rather unusual situation. A more typical case is that you create one or a few long-lived client instances, in which case you'd only have 1 connection per client-broker pair.

**Comment by ThisIsMissEm** [comment]
@Nevon for my application, I am writing a CLI to produce messages into a set of Kafka topics. When working on the CLI, I had frequent crashes due to code just not working as expected; I also had some cases where I'd have to exit the CLI with ctrl+c as it'd get into a state where it'd think it was still waiting for kafka messages that it needed to consume in order to be able to produce a new state, given a kappa architecture.

I think we can probably close this issue.
