### ISSUE TITLE
What is the default autoCommitInterval and autoCommitThreshold?

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#446]
From docs it says default is null.
https://kafka.js.org/docs/consuming#a-name-auto-commit-a-autocommit

Thats hard to believe as when using eachMessage handler offsets will get commited sometime.

**Comment by tulios** [comment]
The default value is actually `null`, even without this configurations if the `autoCommit` is enabled the consumer will commit the offsets, the difference is that it will only commit after the whole batch has been processed. With `autoCommitInterval` and `autoCommitThreshold` you can control the frequency of the commits.

**Comment by pimpelsang** [comment]
so the vanilla

consumer.run({
    eachMessage: async ({ topic, partition, message }) => {
     ...
    })
});

will try to commit after every message?

**Comment by pimpelsang** [comment]
got it, thanks

**Comment by tomerguttman** [comment]
Thanks @tulios
