### ISSUE TITLE
Raw HTML shows on the documentation right side

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#450]
This was caused by the docusaurus update, version `1.12.0` has the issue.

https://github.com/facebook/docusaurus/issues/1703

**Comment by ThisIsMissEm** [comment]
Hopefully, my patch to Docusaurus will be accepted and then we can have this:

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td><img width="290" alt="Screenshot 2019-08-18 at 04 35 36" src="https://user-images.githubusercontent.com/30827/63219405-b1cd5580-c171-11e9-8ec3-7dda7878ac3d.png"></td>
    <td><img width="291" alt="Screenshot 2019-08-18 at 04 35 26" src="https://user-images.githubusercontent.com/30827/63219404-b1cd5580-c171-11e9-8728-9ea2a46e474e.png"></td>
  </tr>
</table>

**Comment by ThisIsMissEm** [comment]
Though, also, we may not actually need those `<a name="..."></a>` tags anymore

**Comment by Nevon** [comment]
The only reason we want to keep them is that some error logs that we output contain links to help sections, so we need the anchors to be stable. We don't have that guarantee with the autogenerated ones, especially since we'd want the anchor to stay the same even if we change the actual title text.

**Comment by ThisIsMissEm** [comment]
@Nevon okay, this totally makes sense. In which case, my patch will fix the issue. Perhaps you'd like to give it a review?

**Comment by yangshun** [comment]
> We don't have that guarantee with the autogenerated ones, especially since we'd want the anchor to stay the same even if we change the actual title text.

I see. I was wondering why you didn't use the autogenerated anchors and instead manually wrote your own. As a suggestion I think it'll be better to shift those anchors to the end of the heading to prevent it from taking up space. Currently by putting it at the start it takes up some one letter space (the pink highlighted "text"): 

<img width="479" alt="Screen Shot 2019-09-13 at 2 39 50 PM" src="https://user-images.githubusercontent.com/1315101/64896381-686b0b80-d634-11e9-9421-869aace6a34f.png">

**Comment by ThisIsMissEm** [comment]
Oh! Good point, we could do thar, but we'd still see anchors in the page's ToC without the docusaurus patch linked above

**Comment by yangshun** [comment]
Yep, just merged your PR. Thank you! 😄

**Comment by ThisIsMissEm** [comment]
Amazing! Thanks ✨

**Comment by tulios** [comment]
Fantastic! Thanks @ThisIsMissEm @yangshun

**Comment by ThisIsMissEm** [comment]
@Nevon ha, you beat me to it; Had doing that PR to update docusaurus on my todo list for this week :D

**Comment by Nevon** [comment]
Seeing that messed up sidebar had annoyed me greatly. Thanks for taking care of it!

**Comment by ThisIsMissEm** [comment]
Ha, same here Tommy, same here 😊
