### ISSUE TITLE
Read from earliest

### ISSUE THREAD

**Issue by danielsinai** [tulios/kafkajs#456]
Hi,  thanks for this great lib.
Recently I wanted to reflow all the messages with the same consumer group from a topic. 
I saw this question in #139 , but the solution isn't really stable in case of adding more parttions for example.
Would love to hear maybe there's any other way I can do it, thanks :)

**Comment by JaapRood** [comment]
With "reflow" do you mean "consume from the beginning"? If that's the case using `consumer.seek`, as mentioned in #139, is the only way of doing so while a consumer is already running. Can you maybe explain with what you mean by "the solution isn't really stable in case of adding more parttions for example", I'm not sure what problem you're running into exactly.

**Comment by danielsinai** [comment]
Yea of course, what I meant is that partitions may grow during my consumer is running, so I cant foreach on all of the partitions. Because I dont know the IDs of the new ones

**Comment by tulios** [comment]
@danielsinai that's not a problem, you can get the low offsets of the topic and seek to the beginning.

**Comment by JaapRood** [comment]
> Yea of course, what I meant is that partitions may grow during my consumer is running, so I cant foreach on all of the partitions. Because I dont know the IDs of the new ones

This seems to be a problem in timing of _when_ to call `consumer.seek`, which is hard to reason about for me with any more information. 

If you're just trying to reset the committed offsets once, but are just concerned about not hardcoding in which partitions to do that for (as that might be different from cluster to cluster, or within a single cluster at different points of time), you can use `await admin.fetchTopicMetadata({ topics: <Array<String> })` ([see Admin docs](https://kafka.js.org/docs/admin)). That will give you a current list of partitions that the topic has, so you can seek for everyone one of them.

Maybe you're trying to do something else, more context on that would help us to help you :)

**Comment by danielsinai** [comment]
That's helps alot, thanks !

**Comment by Nevon** [comment]
This seems to be resolved, so I'm going to close this. Feel free to re-open the issue if you run into problems.
