### ISSUE TITLE
Authenticating with SASL PLAIN results in ILLEGAL_SASL_STATE error from kafka

### ISSUE THREAD

**Issue by ThisIsMissEm** [tulios/kafkajs#472]
I think I've properly configured kafka to use SASL, and the credentials are correct; however, kafkajs fails SASL authentication at the handshake stage. The logs are as follows:

```
[2019-08-17T18:36:35.808Z] DEBUG:
    logger: "kafkajs"
    message: "[Broker] Verified support for SaslAuthenticate"
    broker: "kafka.quandoo.local:9092"
    supportAuthenticationProtocol: true
[2019-08-17T18:36:35.810Z] INFO :
    logger: "kafkajs"
    message: "Post client"
[2019-08-17T18:36:42.386Z] INFO :
    logger: "kafkajs"
    message: "[Connection] Request SaslHandshake(key: 17, version: 1)"
    broker: "kafka.quandoo.local:9092"
    clientId: "fake-qwell"
    correlationId: 1
    expectResponse: true
    size: 31
[2019-08-17T18:46:11.425Z] INFO :
    logger: "kafkajs"
    message: "[Connection] Response SaslHandshake(key: 17, version: 1)"
    broker: "kafka.quandoo.local:9092"
    clientId: "fake-qwell"
    error: "Request is not valid given the current SASL state"
    correlationId: 1
    size: 10
```

Any ideas what could cause this?

My kafka server is setup with the follow environment variables (docker):

```
JAVA_SECURITY_AUTH_LOGIN_CONFIG: /etc/kafka/jaas.conf
KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
```

```
# /etc/kafka/jaas.conf

external.KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_alice="alice-secret";
};
```

I've tried connecting with both admin/admin-secret and alice/alice-secret, neither gets past the SASL handshake.

(as an aside, the logs above are formatted with Pino, and it'd be great to have official support for Pino as the logger)

**Comment by ThisIsMissEm** [comment]
Turned out that I hadn't configured kafka in docker correctly, and as such, it literally wasn't expecting a saslHandshake 🤦🏻‍♀️

**Comment by matanrabi** [comment]
@ThisIsMissEm How did you solve it??
I'm running kafka from docker and having the same issue ... :(

**Comment by ThisIsMissEm** [comment]
Absolutely no idea, was over a year ago.

Emelia

**Comment by melksidorov** [comment]
Looks like sasl was not enabled on Kafka, try connecting client without authentication
