### ISSUE TITLE
UNKNOWN_PRODUCER_ID error non-retriable

### ISSUE THREAD

**Issue by eliw00d** [tulios/kafkajs#485]
So, we started running into this error:
```
{
  "type": "KafkaJSProtocolError",
  "message": "This exception is raised by the broker if it could not locate the producer metadata associated with the producerId in question. This could happen if, for instance, the producer's records were deleted because their retention time had elapsed. Once the last records of the producerId are removed, the producer's metadata is removed from the broker, and future appends by the producer will return this exception",
  "stack":
"KafkaJSProtocolError: This exception is raised by the broker if it could not locate the producer metadata associated with the producerId in question. This could happen if, for instance, the producer's records were deleted because their retention time had elapsed. Once the last records of the producerId are removed, the producer's metadata is removed from the broker, and future appends by the producer will return this exception
    at createErrorFromCode (/usr/src/app/node_modules/kafkajs/src/protocol/error.js: 536: 10)
    at Object.parse (/usr/src/app/node_modules/kafkajs/src/protocol/requests/produce/v3/response.js: 47: 11)
    at Connection.send (/usr/src/app/node_modules/kafkajs/src/network/connection.js: 295: 35)
    at process._tickCallback (internal/process/next_tick.js: 68: 7)",
  "name": "KafkaJSProtocolError",
  "retriable": false,
  "code": 59
}
```
which is set to a non-retriable error. However, according to https://issues.apache.org/jira/browse/KAFKA-7190, this should be a retriable error. 

Other than changing [this](https://github.com/tulios/kafkajs/blob/master/src/protocol/error.js#L381) to true, what can be done to remedy this from the client's/producer's perspective? Disconnect, reconnect, then send again?

**Comment by tulios** [comment]
I read the issue, and I can't see where it mentions that the error is retriable. I think the discussion is about changes in the broker. In the errors list, it shows a non-retriable (https://kafka.apache.org/protocol.html#protocol_error_codes).

I can do some investigation, but this seems like something for the Kafka broker. It appears that reconnecting should make it work.

**Comment by hao5743** [comment]
Got same problem. I want to know if any solutions to avoid this.

**Comment by Nevon** [comment]
I don't think this is a KafkaJS issue, unless the EOSManager has a bug, in which case a way to reproduce the issue would be helpful. If you do manage to replicate the issue, feel free to open up a new issue.

More likely, what's happening is that you have short enough retention time that your producer id is deleted and thus you get this error the next time you try to produce, as explained in the ticket you linked to. The solution to that is to disconnect your producer and create a new one (note, just reconnecting will not work. You have to actually instantiate a new instance of the producer).
