### ISSUE TITLE
[Question] Can I assign a consumer to a specific partition ?

### ISSUE THREAD

**Issue by syncush** [tulios/kafkajs#486]
We would like to ditch kafka-node in favor of kafkajs, is it possible to assign a consumer to a specific partition?

I would like to be able to write something like this:

```
await consumer.subscribe({topic:  'bla-bla', partition: 3});
await consumer.run({
    eachMessage: async ({topic, partition, message} => {
        console.log(partition); // will always print 3 for every message consumed
    })
});
```

#373 Found a related issue, I couldn't find the project which indicates the progress of the feature request

**Comment by tulios** [comment]
Hi @syncush, not yet. We are planning to support manual assignment soon. You can write your own assigner to do that, but I would wait for the manual assignment feature.

**Comment by tulios** [comment]
This issue will be covered by the manual assignment feature #373
