### ISSUE TITLE
Add listConsumerGroup method in Kafka admin

### ISSUE THREAD

**Issue by dhineshpandiyan** [tulios/kafkajs#499]
We need method to check whether consumer group is already exist or not before creating consumer group instance using kafka consumer.

**Comment by tulios** [comment]
We want to make the describe group method available in the admin client; for now, you can use `fetchOffsets` to check if the consumer group exists.

https://kafka.js.org/docs/admin#a-name-fetch-offsets-a-fetch-consumer-group-offsets

**Comment by tulios** [comment]
I will create a new issue later with the "list consumer group" feature request.
