### ISSUE TITLE
SNI Support by Default

### ISSUE THREAD

**Issue by JohnCMcDonough** [tulios/kafkajs#503]
It seems like by default, TLS/SSL connections don't use SNI when connecting to the Kafka Brokers.

I know that we could create a new Socket Factory as done below, but it seems like the TLS `servername` should be set by default when connecting to any of the brokers. Is there any downsides to just assuming the `servername` from the host and using that?

For example, changing the socketFactory.js to be like this:

```javascript
const KEEP_ALIVE_DELAY = 60000 // in ms

module.exports = () => {
  const net = require('net')
  const tls = require('tls')

  return ({ host, port, ssl, onConnect }) => {
    const socket = ssl
      ? tls.connect(Object.assign({ host, port, servername: host }, ssl), onConnect)
      : net.connect({ host, port }, onConnect)

    socket.setKeepAlive(true, KEEP_ALIVE_DELAY)

    return socket
  }
}
```
rather than
```javascript
const KEEP_ALIVE_DELAY = 60000 // in ms

module.exports = () => {
  const net = require('net')
  const tls = require('tls')

  return ({ host, port, ssl, onConnect }) => {
    const socket = ssl
      ? tls.connect(Object.assign({ host, port }, ssl), onConnect)
      : net.connect({ host, port }, onConnect)

    socket.setKeepAlive(true, KEEP_ALIVE_DELAY)

    return socket
  }
}
```

**Comment by tulios** [comment]
Hi @JohnCMcDonough, sorry for the delay. It makes sense; I will do some testing and create a PR with the change. Thanks.

**Comment by tulios** [comment]
@JohnCMcDonough  pre-release `1.12.0-beta.1` was published with the change, thanks for reporting.
