### ISSUE TITLE
kafka not working with consumer subscribe multi topic

### ISSUE THREAD

**Issue by hoanghiep1x0** [tulios/kafkajs#504]
I cannot listen to many topics at the same time

`const { Kafka } = require('kafkajs')

const kafka = new Kafka({
    clientId: 'my-app',
    brokers: ["localhost:9092"]
})

const topic = 'topic-test'
const consumer = kafka.consumer({     groupId: 'email', })

const run = async () => {
    await consumer.connect()
    // await consumer.subscribe({ topic })
    await consumer.subscribe({ topic: 'req-mail-register', fromBeginning: true });
    await consumer.subscribe({ topic: 'req-email-register-very', fromBeginning: true });

    await consumer.run({
        // eachBatch: async ({ batch }) => {
        //   console.log(batch)
        // },
        eachMessage: async ({ topic, partition, message }) => {
            const prefix = `${topic}[${partition} | ${message.offset}] / ${message.timestamp}`
            console.log(`- ${prefix} ${message.key}#${message.value}`)
        },
    })
}

run().catch(e => console.error(`[example/consumer] ${e.message}`, e))

const errorTypes = ['unhandledRejection', 'uncaughtException']
const signalTraps = ['SIGTERM', 'SIGINT', 'SIGUSR2']

errorTypes.map(type => {
    process.on(type, async e => {
        try {
            console.log(`process.on ${type}`)
            console.error(e)
            await consumer.disconnect()
            process.exit(0)
        } catch (_) {
            process.exit(1)
        }
    })
})

signalTraps.map(type => {
    process.once(type, async () => {
        try {
            await consumer.disconnect()
        } finally {
            process.kill(process.pid, type)
        }
    })
})`

result 

`
node index.js
{"level":"INFO","timestamp":"2019-09-20T06:18:03.040Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"email"}
{"level":"INFO","timestamp":"2019-09-20T06:18:04.918Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"email","memberId":"my-app-4c268bc8-febf-4aa2-9f92-aec6ff2a7cb6","leaderId":"anphabes-e5c5c03b-1f32-41f0-b51c-2bc875ed8f0e","isLeader":false,"memberAssignment":{"req-mail-register":[]},"groupProtocol":"RoundRobinAssigner","duration":1877}
`

How do I listen to multiple messages at the same time?

**Comment by hoanghiep1x0** [comment]
Sorry, I seem to have found an error because another consumer was listening to the same topic.

**Comment by theronic** [comment]
Note that in Kafka Java library, consumer.subscribe(...) overrides any previous call to subscribe.
