### ISSUE TITLE
SSL servername needs to be set to leader broker host before connecting

### ISSUE THREAD

**Issue by LibanAbukar** [tulios/kafkajs#510]
Whenever I tried accessing my SSL configured Kafka cluster externally, I always ran into a NotLeaderForPartition error. It looks like even though the correct host for the leader broker was found, the servername on the TLS socket established with the leader always remained the same one I originally set it to in the sslOptions:

```js
const kafkaClientOptions = {
	brokers: ['<mybroker>'],
	ssl: {
		ca: fs.readFileSync('./kafkaCerts/ca.crt'),
		cert: fs.readFileSync('./kafkaCerts/user.crt'),
		key: fs.readFileSync('./kafkaCerts/user.key'),
		servername: '<mybroker>', //same as <mybroker> in brokers array above
	},
	logLevel: logLevel.ERROR,
};
```

I was poking around and found that I could solve this by setting the servername to the host after the leader was found and before I connected to it. I made this change locally in my node_modules in the broker class:

```js
...
async connect() {
    try {
      await this.lock.acquire()

      if (this.isConnected()) {
        return
      }

      this.authenticated = false
      this.connection.ssl.servername = this.connection.host; // this is the line I added
      await this.connection.connect()
...
```

I'd like to make this change to the library myself as obviously updating a file in your node_modules is not a permanent solution.

Does anybody see an issue with me making this change?

**Comment by tulios** [comment]
I think issue #503 would solve your problem, can you try the solution described in the issue and check if it works for you?

**Comment by LibanAbukar** [comment]
Thanks @tulios this worked for me. Is there a PR in the works?

**Comment by tulios** [comment]
Not yet, but now that you tried I will create one.

**Comment by tulios** [comment]
I am closing this issue now; you can follow #503. Feel free to re-open if you need it.

**Comment by tulios** [comment]
@LibanAbukar pre-release `1.12.0-beta.1` was published with the change; you can update.
