### ISSUE TITLE
Property 'info' does not exist on type 'Logger' and duplicate outputs

### ISSUE THREAD

**Issue by Awatatah** [tulios/kafkajs#514]
HI I am getting this error with below code. Seems I cannot access logger
```
const KafkaClient = new Kafka({
  // kafkajs will add a extra id string to end of this
  clientId: 'ms-consumer',
  brokers: kafkaVars.host.split(','),
  ssl: {
    rejectUnauthorized: false,
    key: kafkaVars.clientCertKey,
    cert: kafkaVars.clientCert,
    ca: kafkaVars.trustedCert
  },
  logLevel: level(),
  logCreator: StandardLogger
});
KafkaClient.logger().info('some error')
```

> Property 'info' does not exist on type 'Logger'.

I also noticed if I use `comsumer.logger().info('Subscriber 'testSubscriber1' successful request. {}')` the logs work but I am seeing multiple outputs:

> 2019-10-02T20:06:50.510Z INFO [Consumer] Subscriber 'testSubscriber1' successful request. {}
2019-10-02T20:06:50.510Z INFO [Consumer] Subscriber 'testSubscriber1' successful request. {}

**Comment by tulios** [comment]
Hi @Awatatah, I think your custom logger is wrong. From the error message (`Property 'info' does not exist on type 'Logger'`), I can see that it tries to access an object called `Logger`.

**Comment by tulios** [comment]
Feel free to re-open this issue if you need
