### ISSUE TITLE
Allow API version lock

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#52]
Currently, kafkaJS uses the API versions call to decide on which API to enable. This approach is the way forward, but to have a smooth transition between the stable APIs and the new APIs introduced by this initiative the project should be able to lock the used APIs.

```javascript
const { Kafka, BROKER_VERSIONS } = require('kafkajs')

new Kafka({
  brokerVersion: BROKER_VERSIONS.V0_10
})
```

eventually, the default value should be set to `BROKER_VERSIONS.AUTO` which effectively uses the best implemented version (current behavior).

**Comment by Nevon** [comment]
Maybe we should just expose something like `allowExperimental`, since we don't want people to arbitrarily sit on some old version when both broker and client support a newer version.

**Comment by tulios** [comment]
I like the suggestion, what about`allowExperimentalV011`?
