### ISSUE TITLE
Kafka.js support kafka v2.3.0 protocol?

### ISSUE THREAD

**Issue by jarcodallo** [tulios/kafkajs#520]
Hi Guys,

Nice work's with this library, we are currently testing this library for replace kafka-node. So far all works great! :D

But i have a concern about the kafka protocol support. Do you support for kafka +v.2.3.0 protocol?

**Comment by tulios** [comment]
Hi @jarcodallo, KafkaJS doesn't support protocol 2.3 yet, it fully supports protocol 1. Kafka protocols are backward compatible, so you won't have problems using a new version of Kafka. Are there any features in 2.3 that you are particularly interested in?

On a side note, we have plans to update the protocol continually, so we will eventually catch up. KafkaJS also has a modular implementation of the protocol, which means that, if desired, you can implement the versions you need without depending on us.

**Comment by jarcodallo** [comment]
Hi @tulios, thanks for reply. That's sounds good. You have an example or documentation about, how we can extends protocol module?

**Comment by jarcodallo** [comment]
Hi @tulios, Yesterday I test KafkaJS with kafka@2.3.0 and works fine :D, so I will close this issue.

Thanks.
