### ISSUE TITLE
Modify broker.address.ttl property on the client

### ISSUE THREAD

**Issue by vinaykhebbar** [tulios/kafkajs#527]
Hi,

Is there any to set property "broker.address.ttl" while creating the client. Currently the default value is 300000 based on kafka documentation. But we want to reduce it to 120000. This will help in resolving the dns changes quicker if there any changes to the kafka endpoint.

Thanks,
Vinay

**Comment by Nevon** [comment]
The default network implementation in KafkaJS uses `dns.lookup` to resolve broker addresses, [which uses the underlying OS implementation](https://nodejs.org/api/dns.html#dns_dns_lookup). There is no special handling of TTL within KafkaJS, and by default NodeJS doesn't do any caching of DNS resolutions (but the OS layer probably does).

If you want to control TTL yourself, either configure it in your OS or provide your own [custom SocketFactory](https://kafka.js.org/docs/configuration#custom-socket-factory) using a [different `dns.lookup` implementation](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener), such as [dns-lookup-cache](https://github.com/LCMApps/dns-lookup-cache).

I'm not sure where you got the `broker.address.ttl` configuration parameter from. Googling, I can only find references to librdkafka, which has nothing to do with KafkaJS.

**Comment by JaapRood** [comment]
> I'm not sure where you got the broker.address.ttl configuration parameter from.

I've done this in the past, looking for config parameters that seemed to be a general Kafka thing, but turned out to be specific to the client, environment, etc. 🙂
