### ISSUE TITLE
connect to remote kafka instance

### ISSUE THREAD

**Issue by rubiin** [tulios/kafkajs#529]
i have a kafka running on a google instance. However when i add 
brokers: ["ip-address:9092"] , it is not connecting. Also in the logs it shows to connecting to localhost. Any idea

**Comment by rubiin** [comment]
@tulios

**Comment by rubiin** [comment]
pinpointed the problem in broker.js . Its not accepting the connection

**Comment by rubiin** [comment]
https://github.com/tulios/kafkajs/blob/master/src/broker/index.js

**Comment by tulios** [comment]
Hi @rubiin , KafkaJS works with remote servers, the problem is.most likely in your broker setup. How the cluster was configured? A common mistake is to forget to configure the advertised host in the cluster, without the configuration the cluster usually broadcast local ips.

**Comment by rubiin** [comment]
@tulios can you point me to an example

**Comment by rubiin** [comment]
I am using this docker image with the command . It works well on localhost but when i try to set it up on google cloud it wont connect although the port and host are up. ```docker run --rm -it -p 2181:2181 -p 3030:3030 -p 8081:8081 -p 8082:8082 -p 8083:8083 -p 9092:9092 -e ADV_HOST=127.0.0.1 landoop/fast-data-dev  ```

**Comment by tulios** [comment]
`ADV_HOST` looks like the advertised host that I mentioned, and it is pointing to localhost, try to use the host name or your public IP.
