### ISSUE TITLE
Producer connection error crashes app

### ISSUE THREAD

**Issue by stychu** [tulios/kafkajs#537]
Hello, I'm trying to implement a simple producer for pushing messages to Kafka from my application. but whenever the producer can't connect it throws an error that crashes my app and I can't seem to catch the on connection error from kafkajs. How to properly handle connection error

**Comment by Nevon** [comment]
Everything will be propagated up to `producer.connect` and `producer.send`, so essentially:

```js
const main = async function () {
  const kafka = new Kafka(...)
  const producer = kafka.producer(...)

  try {
    await producer.connect()
    await producer.send(...)
  } catch (error) {
    console.error(`Failed to send message to Kafka: ${error.message}`, { error })
    throw error
  }
}

main()
  then(() => console.log('Application successfully executed'))
  .catch(error => console.error('Application exited with unhandled exception', { error }))
```

You have a more complete example here: https://github.com/tulios/kafkajs/blob/master/examples/producer.js
