### ISSUE TITLE
SSL-SASL connection

### ISSUE THREAD

**Issue by stychu** [tulios/kafkajs#541]
Hello there,
I've some problems understanding how to configure Kafkajs with sasl-ssl.
We have Kafka configuration with Truststore Keystore sasl-ssl authentication. [Kafka security](https://docs.confluent.io/2.0.0/kafka/security.html) and I don't quite understand how this configuration relates to the Kafkajs ssl {ca, key, cert}.

**Comment by StevenLangbroek** [comment]
@stychu did you resolve this?

**Comment by prabhatmishra33** [comment]
@StevenLangbroek  @stychu Please share, if you have any update on this.
