### ISSUE TITLE
`Response Fetch` error messages

### ISSUE THREAD

**Issue by ashercoren** [tulios/kafkajs#553]
Hi,
I have a Kafka consumer listening on one topic.
Occasionally I see this error message in my logs: `Response Fetch(key: 1, version: 7)`.
What does it mean? Should I be bothered by it?

**Comment by Nevon** [comment]
If you look at the full log line, you'll see that the log level of the line is `info`, meaning that this is not  an error log. That particular log is likely just a response log in regards to a `Fetch` request.

If you don't want to see info logs, you can [set the log level to for example `WARN`](https://kafka.js.org/docs/configuration#logging).

**Comment by ashercoren** [comment]
Thanks @Nevon for the reply.
I looked at the full log line, and the log level is `ERROR`.
The same goes for the following log messages:
`Response JoinGroup(key: 11, version: 2)`
`Response SyncGroup(key: 14, version: 1)`

Shouldn't all the log messages have a log level of `info`?

**Comment by Nevon** [comment]
> I looked at the full log line, and the log level is ERROR

I see. Then I apologize for mistakenly assuming that it was an info (we very frequently get people asking why they see some "error" message that's actually just an info log telling them that something succeeded).

Could you post the full log line? There should be some more context if this is an error.

> Shouldn't all the log messages have a log level of info?

Not if they're not informational. Errors and warnings will of course be logged as err/warn, and debug logs as debug, etc.

**Comment by ashercoren** [comment]
I added some more logging to my app so that I could post the full log. Waiting for the errors to happen again...

**Comment by ashercoren** [comment]
Here is an example for an error log. Should it be an error?

```
{
timestamp: "2019-11-20T13:28:41.688Z",
logger: "kafkajs",
message: "Response Heartbeat(key: 12, version: 1)",
broker: "10.102.0.29:12272",
clientId: "kafkajs",
error: "The group is rebalancing, so a rejoin is needed",
correlationId: 45,
size: 10
}
```

**Comment by Nevon** [comment]
Yes, it's an error from the broker letting your consumer know that it needs to rejoin the group. This is how group membership in Kafka is communicated. Whenever the group changes in some way (a member left the group or a new one joined), all the members need to sync up by rejoining. The way they find out about this is that they get an error on whatever API call they make to the broker, such as for example the heartbeat.

**Comment by ashercoren** [comment]
Thank you for the detailed explanation!

**Comment by tulios** [comment]
I can also add that you might get some rebalances under normal conditions, maybe the broker elects a new leader, etc. So it's a normal operation but it shouldn't happen all the time.
