### ISSUE TITLE
KafkaJSLockTimeout: Timeout while acquiring lock

### ISSUE THREAD

**Issue by LakhsmiC** [tulios/kafkajs#554]
Hello Team 

We  are seeing below KafkaJSLockTimeout error while acquiring lock. 

{"level":"ERROR","timestamp":"2019-11-08T10:35:20.646Z","logger":"kafkajs","message":"[BrokerPool] KafkaJSLockTimeout: Timeout while acquiring lock (29 waiting locks): \"connect to broker <brokerIP>\"","retryCount":2,"retryTime":1260,"stack":"KafkaJSLockTimeout: Timeout while acquiring lock (29 waiting locks): \"connect to broker <brokerIP>\"\n at Timeout.setTimeout (/opt/att/app/node_modules/kafkajs/src/utils/lock.js:43:22)\n at Object.dynatraceOnServiceExecutionIndicator [as doInvoke] (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1559:20)\n at Object.c.safeInvoke (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1612:29)\n at Timeout.<anonymous> (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:2955:21)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)"}

Below is the Producer Kafka code snippet we use in our code
kafka = await new Kafka({
      brokers: kafkaBrokerList,
      ssl: {
        rejectUnauthorized: true,
        ca: [fs.readFileSync(certfile, 'utf-8')]
      },
      sasl: {
        mechanism: 'plain',
        username: saslUser,
        password: saslPass
      }
    });
producer = await kafka.producer();
        await producer.send({
          topic,
          messages: [
            { value: msgToPublish }
          ]
        });

Can someone look into this issue ?
Thankyou in advance.
Lakshmi

**Comment by tulios** [comment]
Hi, you are not connecting the producer, it is connecting on demand, that's why you are getting lock errors

**Comment by LakhsmiC** [comment]
Actually, i am connecting to the producer as well , missed posting it in the post  
await producer.connect()

**Comment by LakhsmiC** [comment]
can you also please share the load KafkaJs can take per second. we observed the above errors when we performed a load test .

**Comment by LakhsmiC** [comment]
Hello Team, 
we are still seeing these errors in production . We are instantiating the kafka connection only once throughout the lifecycle of the application and then publish the messages . when the application exits the kafka connection is closed. KafkaJs version used in application : 1.8.0. kafka connection options in our application.
kafka = await new Kafka({
      brokers: kafkaBrokerList,
      ssl: {
        rejectUnauthorized: true,
        ca: [fs.readFileSync(certfile, 'utf-8')]
      },
      sasl: {
        mechanism: 'plain',
        username: saslUser,
        password: saslPass
      },      
      requestTimeout: 30000,
      retry: {
        initialRetryTime: 500,
        maxRetryTime: 10000,
        retries: 2,
      }
    });

Let me know if you need some more information.
Thank you in advance.
Lakshmi

**Comment by Nevon** [comment]
It would be helpful if you could provide the code, so that we can see how you instantiate and use your producer. It would also be helpful to have debug logs, which you can get by running with the environment variable `KAFKAJS_LOG_LEVEL=debug`.

**Comment by LakhsmiC** [comment]
Hello Nevon
Below are the files which contains the producer code and app.js is where we instantiate the kafka connection only once in our applicaiton. 
[kafka-producer.txt](https://github.com/tulios/kafkajs/files/3989372/kafka-producer.txt)
[app.js.txt](https://github.com/tulios/kafkajs/files/3989373/app.js.txt). 
By default the  KAFKAJS_LOG_LEVEL=error in production. i will check my team if we can turn it to "debug" for Kafkajs. 
Let me know if you need any information.

**Comment by Nevon** [comment]
I looked through the code, and as you say, you are only creating one instance of the producer. One thing to note is that you are keeping state in your application (`isConnected`), which won't really be representative of the real state of the producer, since it could disconnect or connect to new brokers over time. If you want to actually keep track of the connection state, you have the [instrumentation events](https://kafka.js.org/docs/instrumentation-events#producer) for that.

Anyway, `producer.connect` doesn't actually connect the producer to all the brokers - it just does an initial connection to a broker that it can use to discover the rest of the cluster. After that, it connects on demand to whichever broker is the leader for the partition it is producing to. So what we can see is that it takes longer than `2 * connectionTimeout + authenticationTimeout` to connect, so maybe the default `connectionTimeout` (1000ms) and/or `authenticationTimeout` (1000ms) aren't appropriate values for your application.

**Comment by LakhsmiC** [comment]
Thank you so much for your time and taking a  look into our code. 
1. We will start using instrumentation events for connectionState.
2. We have initially set connectionTimeout = 3000ms and authenticationTimeout at its default. 
But we got _**"This server does not host this topic or partition"**_ errors resulting in producer failure . So we had to remove . We will again play around the connectionTimeout and authenticationTimeout values and let you know how it goes. 

Thanks
Lakshmi

**Comment by rs6696** [comment]
@Nevon : Thank you for your time for looking into it.
as per your sggestion i was trying to play around  connectionTimeout: 2000,   and   authenticationTimeout: 2000 as below, but got an error as below with **authenticationTimeout** as it's not an option with kafkaoption.

 kafka = await new Kafka({
      brokers: kafkaBrokerList,     
      ssl: {
        rejectUnauthorized: true,
        ca: [fs.readFileSync(certfile, 'utf-8')]
      },
      sasl: {
        mechanism: 'plain',
        username: saslUser,
        password: saslPass
      },      
      requestTimeout: 30000,
      retry: {
        initialRetryTime: 500,
        maxRetryTime: 10000,
        retries: 2,
      },
      connectionTimeout: 2000,
      authenticationTimeout: 2000,
    });

**compilation error** 
Argument of type '{ brokers: string[]; authenticationTimeout: number; ssl: { rejectUnauthorized: true; ca: string[]; }; sasl: { mechanism: "plain"; username: string; password: string; }; requestTimeout: number; retry: { ...; }; connectionTimeout: number; }' is not assignable to parameter of type 'KafkaOptions'.
  Object literal may only specify known properties, **and 'authenticationTimeout' does not exist in type 'KafkaOptions'**

**Comment by Nevon** [comment]
This is not an issue with KafkaJS, but something with your project. I don't know where you are getting your types from or even what type system you are using. We don't have any type called `KafkaOptions` in our TypeScript types. [The corresponding interface would be `KafkaConfig`](https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L14-L28).

**Comment by rs6696** [comment]
@Nevon - Thank you ,after upgrading kafkaJs version with 1.11.0 i was able to access authenticationTimeout .

we will check on load test and find out if KafkaJSLockTimeout error is still there with authenticationTimeout and connectionTimeOut or not.will keep you posted.

**Comment by tulios** [comment]
I will close this issue for now, feel free to re-open it if you need it.

**Comment by sp-suresh** [comment]
> @Nevon - Thank you ,after upgrading kafkaJs version with 1.11.0 i was able to access authenticationTimeout .
> 
> we will check on load test and find out if KafkaJSLockTimeout error is still there with authenticationTimeout and connectionTimeOut or not.

Any improvements you observed?
I am facing a similar issue

**Comment by LakhsmiC** [comment]
Hi
Yes acrer increasing thise values we are looking good. Please close the
issue and Thankyou for your support.

**Comment by vaibhavkumbhar1** [comment]
@LakhsmiC can toy create a github gist for the way you have handled reconnection using events? It will be helpful for other also and later can be included  in kafkajs documentation examples..
Current documentation examples shows creating connections for every push. Thank you..
