### ISSUE TITLE
Consuming a part of a topic

### ISSUE THREAD

**Issue by akoenig** [tulios/kafkajs#559]
First of all, thanks for developing `kafkajs` 🙏🏽 It is a great library!

I have one question though, maybe it is also more targeted to Kafka in general. Currently, we are in the process of building mutation functions which are capable of replaying events of one particular aggregate. For this I need a mechanism for replaying a defined subset of events from a stream (a.k.a. `topic`) and exit afterwards. Furthermore, we persist snapshots in another stream (per aggregate). For getting just the last snapshot, we need a mechanism for fetching just the last event in a stream.

Any chance to get a pointer into the right direction how this could be achieved with `kafkajs`? 🙂

**Comment by JaapRood** [comment]
Not sure what you're after completely, here's some pointers that might help.

- Each consumed message has an `offset`, to denote it's position in the log.
- [`admin.fetchTopicOffsets`](https://kafka.js.org/docs/admin#a-name-fetch-topic-offsets-a-fetch-topic-offsets) can be used to figure out the offset of the last message in each topic-partition (also called high water in Kafka parlance). 
- [`consumer.seek`](https://kafka.js.org/docs/consuming#seek) can be used to consume from any offset (position in a topic-partition). See the docs for details on that.

All of those can be combined to great effect to do things like read certain messages, read the last message, etc. For more guidance on that, there's some great books on the topic. The one I'd recommend is [Event Driven Systems](http://www.benstopford.com/2018/04/27/book-designing-event-driven-systems/) by Ben Stopford, but other great books are available, too!

**Comment by akoenig** [comment]
Hi @JaapRood, thanks for the pointers. `admin.fetchTopicOffsets` is exactly the function I was searching for.
