### ISSUE TITLE
[Suggestion] Emit the event "rebalance in progress" in the consumerGroup

### ISSUE THREAD

**Issue by jarcodallo** [tulios/kafkajs#568]
Hi, Guys

I want to listener the event when the consumer group is rebalancing, because is useful to send metrics and see what is going on with the consumer group.

Maybe this can be added [here](https://github.com/tulios/kafkajs/blob/fcf64350d16bb8af09b1e16706dea85901417cbd/src/consumer/runner.js#L73-L79
), If you thing this is a good idea i can send a PR :D

Thanks,

**Comment by JaapRood** [comment]
There is [the `GROUP_JOIN` event](https://kafka.js.org/docs/instrumentation-events#a-name-list-list-of-available-events) which is fired for this purpose. Every time the group rebalances, every consumer joins back in with the assignments it received from the leader, which is when this event is fired.

If there's some way where that event is not sufficient, it would be great if you could explain your use case for an additional event, how it would differ from the current one, etc.

**Comment by jarcodallo** [comment]
@JaapRood Thanks  for you replay, that's exactly what i need. I will try with that event.

**Comment by JaapRood** [comment]
@jarcodallo no problem! Assuming that'll work just fine, I'll close this for now. Feel free to re-open if you find you have use case that isn't covered by this event!
