### ISSUE TITLE
Is resolveOffset a promise or awaitable value?

### ISSUE THREAD

**Issue by ThisIsMissEm** [tulios/kafkajs#569]
In the documentation examples, `resolveOffset` is always used as `await resolveOffset(message.offset)`, however, in the typescript definitions, it appears that `resolveOffset` returns `void` instead of `Promise<void>`

Which is correct? The examples or the typescript definitions?

**Comment by StevenLangbroek** [comment]
I looked at the implementation at the time and it doesn't return a promise so the type is correct 🤔

**Comment by goriunov** [comment]
If i understand correctly `resolveOffset` is used internally to resolve it and then you have to use `commitOffsetsIfNecessary` to actually commit offset to kafka. `commitOffsetsIfNecessary` relies on `autoCommitInterval` to determine if it should commit now or not.

**Comment by Nevon** [comment]
`resolveOffset` is synchronous. The only thing it does is set a value in an object. The examples must be off.
