### ISSUE TITLE
Force kill connection ?

### ISSUE THREAD

**Issue by goriunov** [tulios/kafkajs#571]
Is there any way to kill connection to kafka. I have tried using disconnect but it can get in infinity loop if onBatch or onMessage will never complete processing of one single message (which could be triggered by other things/errors). As a solution to my use case i would like to kill kafka connection and reestablish that again to reread uncommitted messages. Unfortunatle when i call disconnect i can some thing like:

```
[34mdebug[39m:  timestamp=2019-12-02T08:36:45.211Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5000ms (sent: 0 | received: 0)
[34mdebug[39m:  timestamp=2019-12-02T08:36:46.212Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:47.214Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:48.219Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:49.220Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5003ms (sent: 0 | received: 0)
[34mdebug[39m:  timestamp=2019-12-02T08:36:50.220Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:51.220Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:52.223Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:53.231Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:54.235Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5001ms (sent: 0 | received: 0)
[34mdebug[39m:  timestamp=2019-12-02T08:36:55.238Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:56.241Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:57.244Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:58.249Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:36:59.251Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5003ms (sent: 0 | received: 0)
[34mdebug[39m:  timestamp=2019-12-02T08:37:00.252Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:01.253Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:02.254Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:03.256Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:04.260Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5003ms (sent: 0 | received: 0)
[34mdebug[39m:  timestamp=2019-12-02T08:37:05.264Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:06.265Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:07.269Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:08.270Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:09.270Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5005ms (sent: 0 | received: 0)
[34mdebug[39m:  timestamp=2019-12-02T08:37:10.274Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:11.277Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:12.279Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:13.281Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[34mdebug[39m:  timestamp=2019-12-02T08:37:14.282Z, logger=kafkajs, message=waiting for consumer to finish..., groupId=ABC, memberId=ABCDE
[32minfo[39m: [54210] Elapse: 5003ms (sent: 0 | received: 0)
```

And it never stops

**Comment by JaapRood** [comment]
Beyond `consumer.disconnect`, there is no way to force the connection to stop. 

> As a solution to my use case i would like to kill kafka connection and reestablish that again to reread uncommitted messages.

I would strongly advise against this, as the error that triggered before puts your app in an undefined state. Even if you'd kill the connection and somehow get the consumer to stop consuming (not sure how that would work), you'd run into undefined behaviour as a result of being in an undefined state. That can lead to some really hard to explain bugs, data corruption, etc. The thing to do there is to let the process crash, log the error and restart the process.

Your best course of action here, would be to figure out why your consumer "gets stuck" processing a message. Perhaps we can be of help there, maybe with the help of some code that replicates the issue. If that contains too much private information, some psuedo code could help, some [logs](https://kafka.js.org/docs/configuration#logging) might, etc.

**Comment by goriunov** [comment]
@JaapRood thanks for suggestion, i have been doing chaos testing (stoping/starting kafka nodes for random amount of time), disconnecting internet for some time and connecting back. As an observation i have noticed that sometimes it can take a while to recover from this kinda situations event thought system is up (do not see any logs in debug as well) (as a work around i thought about the above solution to forcefully kill connection and restart consumer). Do you have any suggestion on kafkajs configuration for max resilience from above cases ?

**Comment by JaapRood** [comment]
Subjecting your systems to some chaos testing is always an interesting exercise, and theoretically something Kafka should shine in, and so should KafkaJS.

A big part of where you'll see delays in recovery is through how Kafka's `ConsumerGroup` work, which problems are rooted deep in distributed systems theory. Basically, to prevent a system from becoming super over-reactive to any type of fault and no longer actually productive, significant time-outs are used in the leader-election between consumers in a single group. 

The biggest one of these is the `sessionTimeout` (a configurable parameter), which is set to 30 seconds by default. Not only is that the time that any consumer within the group can go without reporting that it's alive and healthy, it's also the time it's allowed to take to rejoin a group when a rebalance is triggered. This means that if one of the consumers in a group dies and stops reporting it's health to the Broker, it can take up to 30 seconds for a group rebalance to be triggered. If another node then dies or is delayed (through a network partition or garbage collection for example), it can take another 30 seconds for any of the consumers to receive their assigned topic-partitions again, which they need to know what to process.

There's a lot of reasons why this work this way, and simply turning down the session timeout to a way lower value isn't always helpful either. For example, if you set it to 5 seconds, a small network partition or connection dropout can cause an entire rebalance where one wasn't necessary. Depending on the type of processing, that can cause a bunch more consumer lag.

If you're interested to learn more about the underpinnings of this, I couldn't recommend a book more than [Data Intensive Applications](https://dataintensive.net) by Martin Kleppmann. 

Apart from all those inherent delays, it's of course totally possible that something in the currently implementation of the KafkaJS client is causing more delay than necessary. Also, the default configuration _can_ be altered to better fit your use case, changing trade-offs between throughput, latency, etc. For that, I'd have to rope in @tulios and @Nevon, who's company runs a way bigger deployment than us.

**Comment by goriunov** [comment]
@JaapRood Thank you for your explanation :)  @tulios @Nevon i would be really interested in knowing about your kafkajs configurations.

**Comment by Nevon** [comment]
We're not doing anything particularly advanced. The only things we do are to adjust `sessionTimeout` and `heartbeatInterval` to be as small as possible, while still keeping them high enough to allow us to do some processing in between. But then our workloads are not particularly latency sensitive. If a machine dies and it takes a minute for the group to stabilize again, that's not a problem for us, so we haven't optimized for it.

**Comment by JaapRood** [comment]
That's basically our approach as well. We're actually running with the default 30 seconds for `sessionTimeout`, as a bit of time for things to rebalance is not that big of a deal. We've had it 5 seconds before, that increased the amount of rebalances we saw, so actually increased the total time we weren't processing and consumer lag somewhat.
