### ISSUE TITLE
Bad use of null-like value: logCreator

### ISSUE THREAD

**Issue by Fotiman** [tulios/kafkajs#581]
If createLogger is called with { logCreator: undefined }, the default value of null will be assigned to logCreator.  The value of logCreator is not checked prior to calling logCreator(logLevel) resulting in   an exception such as a TypeError.

https://github.com/tulios/kafkajs/blob/3c3a91c94f3b32b9c5e35ff6af671244eee45487/src/loggers/index.js#L38

This is probably a low priority issue, but it's detected by Coverity scanning as a [CWE-476](https://cwe.mitre.org/data/definitions/476.html).

**Comment by Nevon** [comment]
Do you have a suggestion for better handling of this? Although it's not intentional, raising a TypeError seems like a pretty reasonable thing to do when being passed an invalid type.

**Comment by Fotiman** [comment]
I think the default assignment of null is a bit unusual, given that you wouldn't expect a "default" case to lead to a TypeError.  I can think of 3 options:
1. Removing the null default.  It will still throw a TypeError if undefined, but at least it's not implied that null is ok,
2. Defaulting the logFunction if logCreator is null/undefined (instead of calling logCreator and triggering a TypeError)
3. Defaulting the logCreator to something more like a noop function, that returns a noop function to logFunction.  

But with those last 2 options now you'd be changing the logic to indicate that undefined is a valid type for logCreator.  If logCreator is required, then I think option 1 (no default) is the best option.
