### ISSUE TITLE
How to normally consume from all partitions except the broken one?

### ISSUE THREAD

**Issue by xozzslip** [tulios/kafkajs#587]
I have 50 partitions consumed by the service. When the service consume a message from one of the partition which leads to exception in `eachBatch` Kafka js throws exception to the Kafka. Which leads to stop consumption of all other 49 partitions stops. But I would like all other 49 partitions to be processed normally and one broken partition to be stuck in reprocessing. How can I do this?

**Comment by Nevon** [comment]
The simple answer is that your `eachBatch` shouldn't throw, if you want to continue processing the other partitions, so you'll need to catch and handle whatever errors your receiving. The only problem is that by default we will resolve the last offset of the batch after your `eachBatch` resolves, so you'll need to turn that off and resolve manually instead. If there's an error processing a message, stop processing the batch, which will commit the last successfully resolved message and continue re-processing from that point during the next fetch.

Something like:

```js
consumer.run({
  eachBatchAutoResolve: false
  eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning, isStale }) => {
    for (let message of batch.messages) {
      if (!isRunning() || isStale()) break

      try {
        await processMessage(message)
        resolveOffset(message.offset)
      } catch (error) {
        console.error(`Error processing message: ${error.message}`, { error })
        break
      }
    
      await heartbeat()
    }
  }
})
```

**Comment by xozzslip** [comment]
Thanks for the answer! I think this fits great
