### ISSUE TITLE
Is there any plans to support Kafka Connect protocol?

### ISSUE THREAD

**Issue by ThisIsArnab** [tulios/kafkajs#599]
It would be a nice feature to have Kafka connector API in kafkajs.

**Comment by tulios** [comment]
Hi @ThisIsArnab, what would you like to see in KafkaJS? Kafka connect can do a lot of things, how do you see this working?

**Comment by JaapRood** [comment]
I'd imagine Kafka Connect is outside of the scope of KafkaJS. As far as I know, Kafka Connect isn't actually a protocol between a Kafka Client and Kafka Cluster. In fact, it's a library on top of that, with a massive collection of plugins, that uses a Kafka client (the Java one in this case). To me, it seems like something to be built on top of KafkaJS, rather than as part of it.

**Comment by ThisIsArnab** [comment]
I need to stream messages from TIBCO system into Kafka cluster and consume those messages in my Node.js application. I'm new to kafka world and Kafka connect seemed to fit my requirements.

_Apache Kafka documentation:_

> The Connector API allows building and running reusable producers or consumers that connect Kafka topics to existing applications or data systems. For example, a connector to a relational database might capture every change to a table

**Comment by JaapRood** [comment]
@ThisIsArnab even in the Java API, that would be a separate Connector you'd have to install. The Connector API is only a framework for individual connectors to be implemented against. So even if KafkaJS supported the Connect API (which as I've noted before I think is better served as it's own project), somebody would have to implement that particular Connector in Node.js.

In other words: if you're stuck in Node.js, you'll best bet is to implement this yourself (I don't know of anyone else who's looking at doing so). More productive would be running the connector in Java. Once the connector publishes the messages on Kafka, you can consume them from anywhere, including Node.js with KafkaJS.

**Comment by Nevon** [comment]
Going to close this as it's not something that would be included in the client itself, but rather something someone could build on top.
