### ISSUE TITLE
Clean shutdown of long-running consumer/producer task using eachBatch and highWatermark

### ISSUE THREAD

**Issue by jeromecovington** [tulios/kafkajs#601]
Hello, I reached out in the slack channel but thought it made sense to go ahead and open an issue as well. I understand this can be tricky but: I have a long-running task that will consume and produce back to a very large topic. I will be using `eachBatch()` as this allows me to have access to `highWatermark`. I would like to be able to run this script and be able to walk away from it, having it manage it's own clean shutdown and process exit once the final offset is reached. Here's an example of what I have so far with all the domain-specific stuff removed:
```javascript
await consumer.run({
  eachBatch: async ({ batch, heartbeat, resolveOffset }) => {
    const { messages, highWatermark } = batch;
    for await (const message of messages) {
      // Removed: some domain specific stuff involving the consumer and producer.

      resolveOffset(message.offset);
      await heartbeat();

      if (parseInt(message.offset, 10) === parseInt(highWatermark, 10) - 1) {
        console.log('Script finished, disconnecting...');

        // FIXME: Calls to disconnect seem to hang. Neither the consumer nor
        // producer disconnect are logged by the internal kafkajs logger, and
        // we never get to the call to exit the process.
        await consumer.disconnect();
        await producer.disconnect();
        process.exit(0);
      }
    }
  }
});
```
As you can see by my fixme comment, I cannot seem to get this script to cleanly shutdown the consumer/producer and exit. I've seen such a pattern alluded to in a [previous issue](https://github.com/tulios/kafkajs/issues/531) and while I know that ongoing consumers are the typical use-case, I would like to identify a solid pattern for my long-running, but self terminating consumer/producer use case. Any tips much appreciated!

**Comment by jeromecovington** [comment]
It seems that when calling `consumer.disconnect()`, `consumer.stop()` is first called, which calls [`runner.stop()`](https://github.com/tulios/kafkajs/blob/fcf64350d16bb8af09b1e16706dea85901417cbd/src/consumer/index.js#L132). Then, we attempt to [`waitForConsumer()`](https://github.com/tulios/kafkajs/blob/fcf64350d16bb8af09b1e16706dea85901417cbd/src/consumer/runner.js#L128). However, `this.consuming` never transitions to `false` so the [Promise never resolves](https://github.com/tulios/kafkajs/blob/fcf64350d16bb8af09b1e16706dea85901417cbd/src/consumer/runner.js#L142). (Hope these lines help, I haven't identified yet whether it is is appropriate to introduce another part of the code where `this.consuming` should be set `false`.

**Comment by jeromecovington** [comment]
I ended up doing some manual management, tracking the number of times `highWatermark` was reached, against my total number of partitions, then shutting down, something like this:
```javascript
// Removed: use admin api to derive the total number of partitions as totalPartitions.

await consumer.run({
  eachBatch: async ({ batch, heartbeat, resolveOffset }) => {
    const { messages, topic, partition, highWatermark } = batch;
    for await (const message of messages) {
      // Removed: some domain specific stuff involving the consumer and producer.              

      resolveOffset(message.offset);
      await heartbeat();

      if (parseInt(message.offset, 10) === parseInt(highWatermark, 10) - 1) {
        highWatermarksReached++;
        break;
      }
    }
  }
});

setTimeout(async () => {
  if (highWatermarksReached === totalPartitions) {
    console.log('High watermark reached, disconnecting...');
    await consumer.disconnect();
    await producer.disconnect();
    await admin.disconnect();
    process.exit(0);
  }
}, 3000)
```

This is a workable solution for me, I'll close this for now, hopefully it will help someone else too!

**Comment by tulios** [comment]
Hi @jeromecovington, sorry for the delay, most of the team is already on vacation so bear with me :D

I will take a look at the shutdown sequence, thanks for the detailed investigation.

**Comment by tulios** [comment]
@jeromecovington I checked the code and everything looks correct, what do you mean by `However, this.consuming never transitions to false so the Promise never resolves`?

`scheduleFetch` makes sure that `consuming` will always end up as false
https://github.com/tulios/kafkajs/blob/67c71927e9c649ff00a88eda8c752849b2eda864/src/consumer/runner.js#L393-L395

maybe you can provide an example?

Thanks

**Comment by Nevon** [comment]
> `scheduleFetch` makes sure that `consuming` will always end up as false

Right, but since he's calling `consumer.disconnect` from _within_ his `eachBatch`, won't we get sort of a deadlock since `disconnect` will wait for the consumer to finish, which only happens when `eachBatch` terminates, which it won't because it's waiting for the `disconnect`, etc?

**Comment by tmikus** [comment]
Sorry for being late to the party. I just encountered the same issue and luckily I found a solution.
The simplified version of my code looked like this:
```
consumer.run({
  autoCommit: true,
  eachBatch: async (payload) => {
    try {
      await doSomethingWithPayload(payload);
    } catch (ex) {
      await consumer.disconnect();
      setTimeout(retryConsumerConnection, 60000);
    }
  },
  eachBatchAutoResolve: false,
});
```
The lock was caused by the `await consumer.disconnect();` which internally waits for the `eachBatch` to finish. As you see that poses a problem, because `eachBatch` can't finish until `consumer.disconnect()` finishes, which waits for `eachBatch` to finish ...
Solution: Don't await for `consumer.disconnect`!

```
consumer.run({
  autoCommit: true,
  eachBatch: async (payload) => {
    try {
      await doSomethingWithPayload(payload);
    } catch (ex) {
      consumer.disconnect().then(() => {
        setTimeout(retryConsumerConnection, 60000);
      });
    }
  },
  eachBatchAutoResolve: false,
});
```
