### ISSUE TITLE
kafkajs questions in a cluster environment

### ISSUE THREAD

**Issue by NoahHahm** [tulios/kafkajs#603]
I am using kafkajs in a k8s kafka cluster environment.
Kafkajs A, B, and C servers with a common groupId are receiving one topic.
 - eachBatchAutoResolve false used.

const consumer = kafka.consumer({ 
  groupId: "common",
  partitionAssigners: [ roundRobin ]
});

I issued 1 message from producer
while server B is running eachBatch (at least 5 minutes), server C is receiving duplicate messages.
Which option should I use to avoid receiving duplicate messages from kafka during eachBatch? seek advice

**Comment by Nevon** [comment]
> Which option should I use to avoid receiving duplicate messages from kafka during eachBatch?

As long as all the consumers join the same consumer group, which they do based on the groupId, each consumer will be assigned one or more partitions, so they won't be receiving the same messages.

However, by default Kafka has at-least-once delivery semantics, so you are _not guaranteed_  not to receive duplicates. For example, imagine that consumer A gets a batch of messages and then dies in the middle of processing them. Once the Kafka cluster discovers that consumer A is dead, those partitions will be reassigned to another consumer, which will now receive the same messages that consumer A got.

[Here you have an example of using eachBatch](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch).
