### ISSUE TITLE
type error for ProducerBatch

### ISSUE THREAD

**Issue by kambing86** [tulios/kafkajs#606]
should be

```ts
export interface ProducerBatch {
  acks?: number
  timeout?: number
  compression?: CompressionTypes
  topicMessages: TopicMessages[]
}
```

**Comment by ankon** [comment]
Went through the code, and indeed all parameters seem to be optional (including `topicMessages`, see https://github.com/tulios/kafkajs/pull/287):

`acks` and `topicMessages` get defaults here:
https://github.com/tulios/kafkajs/blob/67c71927e9c649ff00a88eda8c752849b2eda864/src/producer/messageProducer.js#L31

`timeout` and `compression` get defaults here:
https://github.com/tulios/kafkajs/blob/67c71927e9c649ff00a88eda8c752849b2eda864/src/broker/index.js#L242
