### ISSUE TITLE
how to use .keytab file to connect kafka

### ISSUE THREAD

**Issue by kouguopeng** [tulios/kafkajs#609]
how to use .keytab file to connect kafka

**Comment by tulios** [comment]
Hi @kouguopeng, KafkaJS doesn't have built-in support for the Kerberos authentication.

**Comment by Nevon** [comment]
I'm closing this as inactive. Feel free to open up an issue with a feature request for Kerberos authentication.

**Comment by kouguopeng** [comment]
2020年1月5日 下午7:51，Tommy Brunn <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #609<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftulios%2Fkafkajs%2Fissues%2F609&data=02%7C01%7C%7Cea676e55a26a4281d3c808d791d59c1d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637138218939712207&sdata=S3HYvd2PJOFKvgwqZfLwSx0ygVZfRoM0RNB4OaqTXS4%3D&reserved=0>.
