### ISSUE TITLE
How to use SASL_SSL for confluent.cloud?

### ISSUE THREAD

**Issue by PowerMogli** [tulios/kafkajs#611]
Hi guys, 

I am trying to connect to confluent.cloud with SASL_SSL configuration. I have the username and password. When I specify ssl: true I get no connection at all. With node-rdkafka all worked without any issues. There I specified 

'sasl.username': config['sasl.username'],
'sasl.password': config['sasl.password'],
'security.protocol': 'SASL_SSL',
'sasl.mechanisms': 'PLAIN',

But how do I have to configure kafkajs to work as expected?

**Comment by Nevon** [comment]
It would be helpful if you would share how you are configuring KafkaJS.

**Comment by PowerMogli** [comment]
const kafkaClient = new Kafka({ brokers:[config['bootstrap.servers']],
clientId: `${app.get('service').toUpperCase()}::#${process.env.NODE_APP_INSTANCE || 1}`,
ssl: true,
sasl: { mechanism: 'plain', password: config['sasl.password'], username: config['sasl.username'] },
    });

**Comment by Nevon** [comment]
What's the datatype of `config['bootstrap.servers']`? Based on the name, it doesn't sound like a string containing a single broker address, but either an array of strings or maybe a comma-delimited string (common with environment variables).

`brokers` should be an array of strings, with each string being a broker address. Ex `broker: ["broker1:9094"]`,

**Comment by PowerMogli** [comment]
It is a single string value. Something like "confluent.cloud:9092".
 So in the end I have brokers: ["confluence.cloud:9092"]. Exactly like you suggested.

**Comment by Nevon** [comment]
There are people who have connected to Confluent Cloud with KafkaJS, like this person for example https://confluentcommunity.slack.com/archives/C499EFQS0/p1575779294235000?thread_ts=1575779294.235000&cid=C499EFQS0 with basically the config you describe. I would recommend that you double check that you have the right port, the right username and password, and that the server certificate is trusted by your system.

You can also enable more logging with `KAFKAJS_LOG_LEVEL=debug`, which might be able to shed some light on the issue.

**Comment by PowerMogli** [comment]
One last question: What is the best practise to instantiate a kafkajs client instance? should it be created for each consumer and producer or only once for each consumer/producer?

```ts
import { Kafka } from 'kafkajs';
const kafkaClient = new Kafka({...});
```

**Comment by Nevon** [comment]
You only need to create it once, and can then reuse it for creating all your producers and consumers. You only need to create a new KafkaJS instance if you want to have different configuration.

**Comment by PowerMogli** [comment]
Ok, one last question: what are valid values for configEntries while creating a new topic with adminClient? I'm trying to set max.message.size.bytes but then I get an exception.

**Comment by Nevon** [comment]
Have you read the exception? The format is like:

```js
configEntries = [{
  name: 'cleanup.policy',
  value: 'compact'
}]
```

The possible values depend on the version of Kafka that you're running. [You'll have to consult the Kafka docs](https://docs.confluent.io/current/installation/configuration/topic-configs.html).

**Comment by cubbuk** [comment]
I am having a similar issue while connecting to broker:

Basically my client configuration looks like the following:

```
const kafka = new Kafka({
    brokers: ['<BROKER>:9092'],
    clientId: '<CLIENT_ID>',
    ssl: true,
    sasl: {
      mechanism: 'plain',
      username: <ACCESS_KEY>
      password: <ACCESS_PASSWORD>,
    },
  });
```

I am getting the following error:
```
{"level":"ERROR","timestamp":"2020-04-06T12:11:48.028Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker": "<BROKER:PORT>","clientId":"<CLIENT_ID>"}
{"level":"ERROR","timestamp":"2020-04-06T12:11:48.031Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":306}
```

Am I using some wrong configuration?

**Comment by cubbuk** [comment]
Nvm apparently the issue was with `connectionTimeout`. After setting it to 3000 it started working actually.

The following configuration object worked for us:
```
{
    brokers: ['<BROKER>:9092'],
    connectionTimeout: 3000,
    ssl: true,
    sasl: {
      mechanism: 'plain',
      username: config.KAFKA_USERNAME,
      password: config.KAFKA_PASSWORD,
    },
}
```
