### ISSUE TITLE
Kafka Stops Consuming when batch contains only control messages.

### ISSUE THREAD

**Issue by nj-jking** [tulios/kafkajs#619]
the batch.isEmpty() check short circuits when a batch contains no filtered messages. this causes the consumer to continually fetch the batch and will not continue. control record offsets are not acknowledge and the batch is fetched in a endless loop.
see line 292 of consumer/batch.js

**Comment by tulios** [comment]
Hi @nj-jking, can you try the latest pre-release version? `1.12.0-beta.17`

**Comment by nj-jking** [comment]
You bet. I'll give it a shot and report back.

**Comment by nj-jking** [comment]
Confirmed. this is resolved with 1.12.0-beta.17
