### ISSUE TITLE
Delete all messages in a topic

### ISSUE THREAD

**Issue by rajjagani021** [tulios/kafkajs#621]
Do we have any function or anyway by using that I can delete all the messages in a topic? I have checked the documentation and there are no such things. I just found the below way but I think to change the retention time of the topic, Is there any function for this as well?

`To purge the Kafka topic, you need to change the retention time of that topic. The default retention time is 168 hours, i.e. 7 days. So, you have to change the retention time to 1 second, after which the messages from the topic will be deleted. Then, you can go ahead and change the retention time of the topic back to 168 hours.`

So I just want to know the answer to the below questions.

1. Is there any function that can delete all messages in a topic?
2. Is there any function to update the configuration of the topic?
3. If I delete the topic then it will also delete all the messages from Kafka Queue as well, right?

**Comment by JaapRood** [comment]
Kafka's topics (logs), from a consumer's point of view, are immutable. That means that once a message is created, it can't be deleted. It's only _the cluster_ itself that can delete messages. It will do this in these two cases:

- By default, after a certain amount of time has passed, aka time-based retention. Any messages older than a certain setting _can_ be deleted by the cluster, to make space. (`cleanup.policy=retention`).
- When configured, by deleting the last message for every unique key. When producing a message a `key` can be sent (`cleanup.policy=compaction`).

Deleting a topic _would_ also remove all the data of that topic. However, it's important to note that this is also an asynchronous command, with the Admin client only being able to mark a topic for deletion in the future (although on small clusters, this happens very quickly). Note that on some production clusters the ability to delete topics might be disabled, to prevent dataloss.

So to get back to your questions:

1. There isn't, as the concept does not exist within Kafka.
2. You can update the configuration of a topic through [using the Admin client](https://kafka.js.org/docs/admin#a-name-alter-configs-a-alter-configs).
3. Yes, once the topic is deleted by the cluster, the messages will be as well.
