### ISSUE TITLE
Conflict With Grok-Js

### ISSUE THREAD

**Issue by lcharbon** [tulios/kafkajs#623]
When the library [grok-js](https://github.com/honzahommer/grok-js) is imported to an app with `kafkajs` the output of `await producer.send()` is an empty array.

See minimal example [here](https://github.com/lcharbon/gork-conflict).

In this example, if `const grok = require('grok-js');` is uncommented kafkajs will stop working.

Issue submitted to grok-js [here](https://github.com/honzahommer/grok-js/issues/19).

**Comment by JaapRood** [comment]
The only way I can see these two libraries conflict is if one of them mutates the environment, a global, altering the behaviour of some native functionality. A quick glance at the code of `grok-js` itself, I couldn't spot any, nor am I aware of the use of global in KafkaJS. More likely, I'd say, would be one of grok's dependencies being the culprit.

It'll be pretty hard to spot, which is exactly why the practice of mutating the environment shouldn't have passed code-review on this end. Good luck hunting it down, happy to help if you find anything more concrete!

**Comment by Nevon** [comment]
This is because `gork-js` depends on `collections`, which replaces `Array.prototype.from` with a version that doesn't work with iterables. See montagejs/collections/issues/169

Closing this, as it has nothing to do with KafkaJS.

**Comment by JaapRood** [comment]
> This is because gork-js depends on collections, which replaces Array.prototype.from with a version that doesn't work with iterables.

🤦‍♀️
