### ISSUE TITLE
KafkaJSProtocolError: Request parameters do not satisfy the configured policy

### ISSUE THREAD

**Issue by rajjagani021** [tulios/kafkajs#625]
I am getting the error **"KafkaJSProtocolError: Request parameters do not satisfy the configured policy"** while creating a new topic. I can successfully connect with the admin client. Here is my code. I am trying to create the topic on confluent using kafkajs. 

```
await admin.createTopics({
                validateOnly:false,
                topics: [{
                    topic: top.name,
                    numPartitions: top.parition,
                    configEntries:[{
                        name:'cleanup.policy',
                        value:'delete'
                    }]
                }],
            });
```

**Error Trace** 
`{"level":"ERROR","timestamp":"2020-01-08T14:06:30.270Z","logger":"kafkajs","message":"[Connection] Response CreateTopics(key: 19, version: 2)","broker":"b13-pkc-4nym6.us-east-1.aws.confluent.cloud:9092","clientId":"kafkajs","error":"Request parameters do not satisfy the configured policy","correlationId":2,"size":79}`

What config I should pass when creating the topic? I am already passing the cleanup policy. Do I need to pass any other config parameters while creating the topic?

**Comment by Nevon** [comment]
This is not an issue with KafkaJS, but with your Kafka cluster configuration. You are trying to create a topic that violates the configured policy, as the error states. You'll have to consult whoever manages your Kafka cluster for support.

Note that you misspelled `top.partition`, just in case it's the number of partitions that is invalid.
