### ISSUE TITLE
PartitionAssigner type definition is incorrect

### ISSUE THREAD

**Issue by gimbalgambit** [tulios/kafkajs#627]
The [type declaration](https://github.com/tulios/kafkajs/blob/0b70749931a1be3bfce81ca48ad2cf744e7e5e23/types/index.d.ts#L108) for customer partition assigners (`PartitionAssigner`) implies that a class should be passed in the assigner array, but it actually expects a function that returns an object. 

The current type def looks like:
```ts
export interface PartitionAssigner {
  new (config: { cluster: Cluster }): Assigner
}
```
*(An object with a constructor that takes a config object argument with a `Cluster`-type property named `cluster`, and the object must conform to the `Assigner` interface)*

Instead, it seems like it should look like:
```ts
export type PartitionAssigner = (config: { cluster: Cluster }) => Assigner;
````
*(A function that takes an object with a `Cluster`-type property named `cluster`, and returns an object that conforms to the `Assigner` interface)*

**Comment by ankon** [comment]
Fixed with https://github.com/tulios/kafkajs/pull/675
