### ISSUE TITLE
Randomize brokers to connect to from the connection seed

### ISSUE THREAD

**Issue by fjuan** [tulios/kafkajs#631]
In order to better spread connection load towards brokers, clients could randomize the one broker selected to initiate the connection from the seed brokers list.

https://github.com/tulios/kafkajs/blob/0b70749931a1be3bfce81ca48ad2cf744e7e5e23/src/cluster/connectionBuilder.js#L33

The randomization mechanism should be aware of the possiblity that the selected broker is not available. A suggestion could be to change the default `index` value at https://github.com/tulios/kafkajs/blob/0b70749931a1be3bfce81ca48ad2cf744e7e5e23/src/cluster/connectionBuilder.js#L26-L27

Maybe something like
```javascript
let index = Math.floor(Math.random() * size)
```

**Comment by fjuan** [comment]
Another implementation idea would be to shuffle the list of brokers right after reading it and keep the current connectionBuilder.js as is. Suggestion from @matthiasfeist

**Comment by Nevon** [comment]
I'm of two minds on this.

On the one hand, this is probably the behavior you want in 90% of cases, so from that perspective it makes sense for us to handle it internally.

On the other hand, there may be situations where you actually _want_ to prefer connecting to a certain broker, which would become impossible to do if we force a random order. If we don't do this in the client, it's still easily implementable in userland code by just shuffling the list before handing it to the client.

**Comment by tulios** [comment]
Out on pre-release `1.12.0-beta.21`
