### ISSUE TITLE
Kafka Consumer subscription on AWS Lambda

### ISSUE THREAD

**Issue by ashishsharma91** [tulios/kafkajs#634]
I would like to upload consumer code of NodeJs to AWS Lambda. Actually, using Kafka JS I have created Consumer and subscribed with some topics. It's working fine over my local machine but, when am uploading it to AWS Lambda function it doesn't call consumer.eachMessage event.

Please help me with this.

```js
consumer.connect()
consumer.subscribe({ topic: 'mh912co8-default', fromBeginning: true })

consumer.run({
    eachMessage: async ({ topic, partition, message }) => {
    if (counter % numMessages === 0) {
      // console.log("calling commit");
      // consumer.commit(message);
    }
    console.log('Message would be :',  message.value.toString()); 

    console.log({
      partition,
      offset: message.offset,
      value: message.value.toString(),
    })
    },
  })
```

**Comment by Nevon** [comment]
I'm not sure what you are proposing makes sense. AWS Lambda functions need to be triggered to run by something, such as an incoming HTTP request, an event from SNS, etc. alternatively be invoked manually by you. Just uploading your code to AWS Lambda doesn't actually mean that anything is running (that's kind of the point with AWS Lambda).

I'm going to close this issue, as it's not an issue with KafkaJS. I would recommend that you read the AWS docs to understand the Lambda execution model better.

**Comment by nfroidure** [comment]
@ashishsharma91 I'm having the ame problem. I basically try to do something like this in order to backup KafkaJS messages into S3 via a cron based AWS Lambda and nothing happens while it work on my machine : https://stackoverflow.com/questions/64631411/spring-boot-kafka-polling-until-queue-is-empty-and-sleep

Not sure why this happens, maybe due to memory/cpu configuration, I'll try to tweak those but if you found a solution I'd like to ear about it :).

@Nevon I do not see any `consumer.poll(timeout)` method, is there something that could allow such behavior in the current KafkaJS API?

**Comment by Nevon** [comment]
I don't know what `consumer.poll(timeout)` does, so I can't really say if there's an equivalent in KafkaJS. Your code doesn't really make sense though, as `consumer.run` will resolve before you have even processed a single batch.

The Kafka consumer will continue to run until you call `consumer.stop` and/or `consumer.disconnect`, and continually call `eachMessage`/`eachBatch` with the fetched batches of messages. Your lambda would be something more like:

```js
const ratelimit = ms => {
  const promise = new Promise((resolve) => {
    setTimeout(resolve, ms)
  })

  return () => promise
}

consumer.run({
  partitionsConsumedConcurrently: 1,
  eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning, isStale }) => {
    if (!isRunning() || isStale()) break

    const wait = ratelimit(10000)

    const body = batch.messages.map((value) => JSON.parse(value.toString())).join('\n')
    await s3.upload({
      Bucket: bucket,
      Key: key,
      Body: body,
    }).promise()

    await heartbeat()
    await wait()
  }
})
```

But frankly, if I were you, I would ditch this approach entirely and use AWS' built-in functionality for using a Kafka cluster as an event source and consume that from a lambda directly instead. See https://docs.aws.amazon.com/lambda/latest/dg/kafka-using-cluster.html

**Comment by nfroidure** [comment]
> use AWS' built-in functionality for using a Kafka cluster as an event source
I do this for on the fly messages handling but for S3 backups, I want to avoid having thousands of S3 buckets created per hour.

Thank you for your help.
