### ISSUE TITLE
Unable to use Static Membership feature

### ISSUE THREAD

**Issue by ahmeddwaheed** [tulios/kafkajs#638]
I couldn't use any client configuration that is mentioned in apache/confluent docs.

I'm using nodemon in development mode and everytime it restarts the server takes 3-4 minutes to join the group.

I found this blog https://www.confluent.io/blog/kafka-rebalance-protocol-static-membership/

> Static Membership introduces a new consumer configuration called group.instance.id, which is configured by users to uniquely identify their consumer instances. Although the coordinator-assigned member ID gets lost during restart, the coordinator will still recognize this member based on the provided group instance ID in the join request. Therefore, the same assignment is guaranteed.

I want to set the `group.instance.id` configuration to a unique ID for the consumer but I don't know if it's doable to pass this shape of configuration to KafkaJS client or if there is any other way that I could achieve static membership.

**Comment by andycmaj** [comment]
hmmm 🤔 https://github.com/edenhill/librdkafka/pull/2638

**Comment by Nevon** [comment]
I believe you are confused about how the Kafka client works. The configurations you mention are not KafkaJS configuration options. I don't know what client the apache/confluent docs are talking about - possibly librdkafka.

> I want to set the group.instance.id configuration to a unique ID for the consumer but I don't know if it's doable to pass this shape of configuration to KafkaJS client or if there is any other way that I could achieve static membership.

Static membership is not supported by KafkaJS yet. If it's taking 3-4 minutes for your consumer to join the group, you should look into configuring [`rebalanceTimeout` and `sessionTimeout` on the consumer](https://kafka.js.org/docs/consuming#options). Whenever you restart the process, Kafka has to figure out that the old instance is dead and remove it from the group, as well as let the new process join the group, before the group is considered stable and can start to consume again. In development you could have much lower values for both `sessionTimeout` and `rebalanceTimeout` than you would likely want to have in production.

**Comment by rdbenoit** [comment]
I know this issue was closed due to it's relationship to librdkafka, but I wanted to follow up as it is something that I believe would be a valuable addition to kafkajs as the reduction in rebalancing is significant. We've made the changes in our fork of kafkajs but have also targeted it at kafka 2.4 and above so not sure it's a great implementation for the library (hence why we haven't submitted a pull request with the change). We have been using it in production for a few months and it's been a great improvement in terms of the rebalancing "dance" we used to see with Kafka.

Here is the changes if it's helpful:
https://github.com/ambyint/kafkajs/tree/feature/group-instance-id-support

**Comment by kolpakov-p** [comment]
> Here is the changes if it's helpful: https://github.com/ambyint/kafkajs/tree/feature/group-instance-id-support

I've tried to use this and it works pretty good!

Steps to start using improved package coupled with NestJS:
1. Install package using:
```bash
yarn add kafkajs@https://github.com/ambyint/kafkajs.git#feature/group-instance-id-support
```
2. Provide “group instance ID” to `connectMicroservice()`:
```javascript
  app.connectMicroservice({
    transport: Transport.KAFKA,
    options: {
      consumer: {
        groupInstanceId: 'test',
        ...
      }
    }
  })
```
