### ISSUE TITLE
Allow .subscribe() to accept array of topics

### ISSUE THREAD

**Issue by WaleedAshraf** [tulios/kafkajs#640]
As discussed in these comments,
https://github.com/tulios/kafkajs/issues/289#issuecomment-585497627
https://github.com/tulios/kafkajs/issues/289#issuecomment-585591295
by @ThisIsMissEm and @tulios.

The limitation on KafaJS is that it doesn't let you subscribe to multiple topics at once with an array of topics. That fixes the issues of having multiple consumers for multiple topics.

It's be something like
```
await consumer.subscribe([
	{ topic: 'topic-a', fromBeginning: true },
	{ topic: 'topic-b', fromBeginning: true }
])
```

**Implementation**
It can be possible to pass the array of topics to `.subscribe()` method, and it will be used as `const topicsToSubscribe = []` here https://github.com/tulios/kafkajs/blob/master/src/consumer/index.js#L163

**Comment by tulios** [comment]
@WaleedAshraf it's not possible to pass an array but you can call `subscribe` multiple times or use subscribe with a regexp.

**Comment by WaleedAshraf** [comment]
@tulios, sorry, maybe I misunderstood the comment in other issues.
You mean it is possible to do this:

```
const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['kafka1:9092', 'kafka2:9092']
})

const consumer1 = kafka.consumer({ groupId: 'test-group' })

await consumer1.connect()
await consumer1.subscribe({ topic: 'topic-a', fromBeginning: true })
await consumer1.subscribe({ topic: 'topic-b', fromBeginning: true })
await consumer1.subscribe({ topic: 'topic-c', fromBeginning: true })
```

The groupId is the same, and the consumer is subscribed to multiple topics.

**Comment by tulios** [comment]
Yes, this is possible and used in production. You can also do:
`await consumer1.subscribe({ topic: /topic-*/, fromBeginning: true })`

**Comment by WaleedAshraf** [comment]
Thanks, 👍  I'll close this issue.
