### ISSUE TITLE
Should the KafkaMessage type allow for null value?

### ISSUE THREAD

**Issue by jeromecovington** [tulios/kafkajs#642]
It is useful to produce null records "tombstone" to a key. It may also be useful to know when consuming a null record that has not yet been compacted out.

Currently with the types defined for KafkaJS we can describe null values when producing:
https://github.com/tulios/kafkajs/blob/1904481eefe53ce169b38420db59cc68ec819cf7/types/index.d.ts#L56-L62

But not on the consumer side: https://github.com/tulios/kafkajs/blob/1904481eefe53ce169b38420db59cc68ec819cf7/types/index.d.ts#L402-L410

Should the KafkaMessage type allow for null value?

**Comment by JaapRood** [comment]
> It is useful to produce null records "tombstone" to a key

Totally! Tombstones are key (pardon the pun) to making changelogs work.

>  It may also be useful to know when consuming a null record that has not yet been compacted out.

Another definitely! Again, essential to making change logs work.

> Should the KafkaMessage type allow for null value?

It probably should be. While the Kafka protocol requires a value to be bytes (hence the `Buffer` type` in Node), it also allows for null. AFAIK `null` equating to a tombstone is more of a convention than part of the spec, but supporting it as a payload should probably supported regardless.

**Comment by Nevon** [comment]
Fixed by #764
