### ISSUE TITLE
Create Topic

### ISSUE THREAD

**Issue by al66** [tulios/kafkajs#65]
Is it planned to add a method to create new topics? 
( running kafka with auto.create.topics.enable )

**Comment by tulios** [comment]
Hi, it's planned. The effort now is to enable native support to Kafka 0.11.0+, but we plan to add all the admin operations later on. If you run Kafka with auto create it should work.

**Comment by al66** [comment]
Yes it works, but throws an error [LeaderNot Available] during first commit.
But sounds good, that it is planned!

**Comment by tulios** [comment]
It's possible to create topics with KafkaJS now, this feature should be in the next version (`v1.1.0`), I have a couple more things to add to this version, but it should be out soon.
