### ISSUE TITLE
Error when pausing a consumer, adding new topics and then resume (KafkaJSNonRetriableError)

### ISSUE THREAD

**Issue by robertbarron** [tulios/kafkajs#652]
Hello,

I have an instance that scans for new topics each 5 minutes to a database. When it detects new topics, it'll try to add these topics to the consumer. I am currently having troubles pausing the consumer, adding the topics and then resuming it. I get the following error:

_KafkaJSNonRetriableError: Cannot subscribe to topic while consumer is running_

What I am doing is something like this:

1. Get list of topics from database.
2. Get settings for connection.
3. Get consumer instance with the list of topics.
4. call consumer.run().
5. After 5 minutes, call for a scan for new topics to a database.
6. Do a consumer.pause()
7. **Call for consumer.subscribe(list-of-new-topics).**
8. Do a consumer.resume()

The step 7 is giving the following error:
_KafkaJSNonRetriableError: Cannot subscribe to topic while consumer is running_

Am I using the wrong function or is there something I am not seeing?

Thank you

**Comment by Nevon** [comment]
You have to call `consumer.stop` before you subscribe, not `consumer.pause`. Consequently you have to then call `consumer.run` rather than `consumer.resume`.
