### ISSUE TITLE
seek consumer to timstamp, ie offsetsForTimes functionality?

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#653]
Any plans to implement this feature to consumer or admin client?

As in java
https://kafka.apache.org/0102/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#offsetsForTimes(java.util.Map)

or librdkafka wrapper
https://blizzard.github.io/node-rdkafka/current/Client.html

**Comment by Nevon** [comment]
There is an open PR for this, but it's not in an active state: #604.

Is this something you could help drive forward?

**Comment by tulios** [comment]
#604 is merged and the feature was released on 1.14.0

**Comment by hanspoo** [comment]
Hello andt hanks for the great job !! i have an application that query a topic from a timestamp, kafkajs support this, it is working fine, but it requires to create a consumer group, and the broker administrator is asking to me to stop creating these volatile creating consumer groups, ¿ is there a chance to use this without a consumer group ?

**Comment by Nevon** [comment]
KafkaJS' consumer is very much built around the concept of consumer groups, and we don't have any mechanism for doing manual consuming without consumer groups. You'll either have to re-use the same consumer group or use a different tool for this use-case.

**Comment by hanspoo** [comment]
Thank you
