### ISSUE TITLE
Unhandled promise rejection in consumerGroup.fetch

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#656]
Since introducing the `BufferedAsyncIterator` to `ConsumerGroup.fetch`, the test below is extremely flaky. It is currently the biggest contributor to #654. It has two failure modes, and I'm not sure if they are related or not. This is the less common one, but the more worrying one:

```
(node:32993) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 201)
 FAIL  src/consumer/__tests__/assignmentForUnsubscribedTopic.spec.js
  ● Consumer › starts consuming from new topics after already having assignments

    KafkaJSNonRetriableError
      Caused by: TypeError: iterator.next is not a function

      319 |
      320 |     while (true) {
    > 321 |       const result = iterator.next()
          |                               ^
      322 |       if (result.done) {
      323 |         break
      324 |       }

      at Runner.fetch (src/consumer/runner.js:321:31)
      at src/consumer/runner.js:382:9
```

It looks like `iterator` is sometimes not an iterator, which makes sense as there are two places where it returns early by returning an empty array:

https://github.com/tulios/kafkajs/blob/728a32556a4a9dc50578e7d47c1421030f9599b2/src/consumer/consumerGroup.js#L353

https://github.com/tulios/kafkajs/blob/728a32556a4a9dc50578e7d47c1421030f9599b2/src/consumer/consumerGroup.js#L463

My current assumption is that these are the cause of the issue. I naively tried to wrap the empty arrays into a `BufferedAsyncIterator`, but then all hell broke loose. I then replaced the `[]` with `(function*() {})()`, which seems to work, but  I don't feel I understand the issue enough to feel confident in the change. I would like some input from @tulios. 

The following test passes just fine:

```javascript
it('yields an empty iterator if passed an empty array of promises', async () => {
  const iterator = BufferedAsyncIterator([])
  const result = iterator.next()

  expect(result.done).toBe(true)
})
```

**Comment by tulios** [comment]
This was a problem; I faced this a couple of times while running the pre-release.
