### ISSUE TITLE
Module not found: Error: Can't resolve 'net'

### ISSUE THREAD

**Issue by sergiocalero** [tulios/kafkajs#673]
When building the app (angular 8) I get these errors:
ERROR in ./node_modules/kafkajs/src/network/socketFactory.js
Module not found: Error: Can't resolve 'net' in '/home/developer/git/supervision/node_modules/kafkajs/src/network'
ERROR in ./node_modules/kafkajs/src/network/socketFactory.js
Module not found: Error: Can't resolve 'tls' in '/home/developer/git/supervision/node_modules/kafkajs/src/network'

Could you please tell me how to solve it? 

Thank you in advance. 

Regards!

**Comment by Nevon** [comment]
KafkaJS is targetting NodeJS, not browsers. It will not run in browsers at the moment. See https://github.com/tulios/kafkajs/issues/426#issuecomment-511179307 for more details.
