### ISSUE TITLE
How can i config 'security.protocol' which is same with python config?

### ISSUE THREAD

**Issue by lzj723** [tulios/kafkajs#676]
my python and nodejs config as below, but i can't see any options about 'security.protocol': 'SASL_PLAINTEXT' in KafkaJS. the problem is: the python code works, and the nodejs code can't work.

python
`
from confluent_kafka import Producer
p = Producer({
  'bootstrap.servers': '1.2.3.4:19099',
  **'security.protocol': 'SASL_PLAINTEXT',**
  'sasl.mechanism':'SCRAM-SHA-256',
  'sasl.username':'test',
  'sasl.password':'test123'
})
`

nodejs
`
const { Kafka } = require('kafkajs');
const kafka = new Kafka({
  clientId: 'test_client_id',
  brokers: ['1.2.3.4:19099'],
  ssl: {
    rejectUnauthorized: false,
  },
  sasl: {
    mechanism: 'scram-sha-256',
    username: 'test',
    password: 'test123',
  },
});
const producer = kafka.producer();
`

when i try to connect kafka server, it throws an error:
`
{ KafkaJSConnectionError: Connection error: read ECONNRESET
       at TLSSocket.onError (/project-a/node_modules/kafkajs/src/network/connection.js:136:23)
       at TLSSocket.emit (events.js:182:13)
       at TLSSocket.EventEmitter.emit (domain.js:442:20)
       at emitErrorNT (internal/streams/destroy.js:82:8)
       at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     name: 'KafkaJSConnectionError',
     retriable: true,
     helpUrl: undefined,
     broker: '1.2.3.4:19099',
     code: 'ECONNRESET' },
  retryCount: 5,
  retryTime: 9884 }
`

**Comment by Nevon** [comment]
You have to set `ssl` to false. Currently you are trying to connect over TLS.

Note that authenticating without TLS means that the credentials will be visible in plain text, which is not recommended for production deployments.

**Comment by tulios** [comment]
Hi @lzj723 you should use `plain`

https://kafka.js.org/docs/configuration#plain-scram-example

SASL_PLAINTEXT = plain

**Comment by lzj723** [comment]
thanks for your answers!
i tried these 4 cases, and all failed again.

---
{
  ssl: false,
  sasl: {
    mechanism: 'plain',
    username: 'test',
    password: 'test123',
  },
}
Error: { KafkaJSProtocolError: The broker does not support the requested SASL mechanism
  at createErrorFromCode (/project-a/node_modules/kafkajs/src/protocol/error.js:536:10)
  at Object.parse (/project-a/node_modules/kafkajs/src/protocol/requests/saslHandshake/v0/response.js:24:11)
  at Connection.send (/project-a/node_modules/kafkajs/src/network/connection.js:306:35)
  at process._tickCallback (internal/process/next_tick.js:68:7)
name: 'KafkaJSProtocolError',
retriable: false,
helpUrl: undefined,
type: 'UNSUPPORTED_SASL_MECHANISM',
code: 33 }

---
{
  ssl: true,
  sasl: {
    mechanism: 'plain',
    username: 'test',
    password: 'test123',
  },
}
Error: { KafkaJSConnectionError: Connection error: read ECONNRESET
  at TLSSocket.onError (/project-a/node_modules/kafkajs/src/network/connection.js:136:23)
  at TLSSocket.emit (events.js:182:13)
  at TLSSocket.EventEmitter.emit (domain.js:442:20)
  at emitErrorNT (internal/streams/destroy.js:82:8)
  at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
  at process._tickCallback (internal/process/next_tick.js:63:19)
name: 'KafkaJSConnectionError',
retriable: true,
helpUrl: undefined,
code: 'ECONNRESET' }

---
{
  ssl: false,
  sasl: {
    mechanism: 'scram-sha-256',
    username: 'test',
    password: 'test123',
  },
}
Error: { KafkaJSSASLAuthenticationError: SASL SCRAM SHA256 authentication failed: Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-256
  at SCRAM256Authenticator.authenticate (/project-a/node_modules/kafkajs/src/broker/saslAuthenticator/scram.js:157:21)
  at process._tickCallback (internal/process/next_tick.js:68:7)
name: 'KafkaJSSASLAuthenticationError',
retriable: false,
helpUrl: undefined }

---
{
  ssl: true,
  sasl: {
    mechanism: 'scram-sha-256',
    username: 'test',
    password: 'test123',
  },
}
Error: { KafkaJSConnectionError: Connection error: read ECONNRESET
  at TLSSocket.onError (/project-a/node_modules/kafkajs/src/network/connection.js:136:23)
  at TLSSocket.emit (events.js:182:13)
  at TLSSocket.EventEmitter.emit (domain.js:442:20)
  at emitErrorNT (internal/streams/destroy.js:82:8)
  at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
  at process._tickCallback (internal/process/next_tick.js:63:19)
name: 'KafkaJSConnectionError',
retriable: true,
helpUrl: undefined,
code: 'ECONNRESET' }

**Comment by tulios** [comment]
right, sorry about the plain. It was actually the ssl configuration.

You should use scram-256, and the error is saying that your credentials are invalid. I recommendo you to double check that: `Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-256`

**Comment by lzj723** [comment]
@tulios i double-check my username and password, and they are corrent. so i can't find out what's wrong with my configuration.

**Comment by tulios** [comment]
I am closing this issue for now since it is stale for a while. We have many services running in production using SCRAM, so I am confident that it works. Feel free to re-open the issue if you are still facing problems.

**Comment by jacace** [comment]
I am facing the exact same issue when connecting to confluent cloud
I should provide the following params:

bootstrap.servers=cluster-id.us-east-2.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username={{ CLUSTER_API_KEY }}
sasl.password={{ CLUSTER_API_SECRET }}

I trie dthe following:
    const kafka = new Kafka({
        clientId: 'my-app',
        brokers: ['cluster-id.us-east-2.aws.confluent.cloud:9092'], 
        ssl: false,
        sasl: {
            mechanism: 'scram-sha-256', // scram-sha-256 or scram-sha-512
            username: '',
            password: ''
        },
    }) 

I also tried with ssl false and mechanism plain but got same error:

    "message": "[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout",

**Comment by Nevon** [comment]
For connecting to Confluent Cloud, you should use the `plain` mechanism. We have an application running against a confluent cloud cluster that connects just like that:

https://github.com/kafkajs/canary-app/blob/master/app/config/production.json#L3-L11

(`username` and `password` are `null` in that configuration file, but it gets overridden with the actual cluster API key and secret later using environment variables)

One thing to note is that we saw very long connection times against CC, so the default connection timeout of 1000ms is too short. I changed it to 15 seconds in our application, but I haven't done any real measurements to figure out what connection times to expect.

**Comment by tulios** [comment]
Also `sasl.mechanisms=PLAIN` maps to `mechanism: 'plain'` and not `scram-sha-256`

**Comment by jacace** [comment]
thanks fo rthe rpely.
I switched to plan and ssl true but still getting teh same error:
"message": "[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout"

This code runs in a lambda function which has acces sto internet, i.e. the SG enables all traffic outbound and it has an internet gateway
in fact have another components runing within teh same setup which also access resource on internet, so I don't see how only the lambda function coudl be affected.
