### ISSUE TITLE
Infinite loop in batch consumer

### ISSUE THREAD

**Issue by yrsh** [tulios/kafkajs#679]
Version of kafkajs: 1.12.0

When autoresolve is disabled, the consumer begins an infinite loop with the current batch, instead of stop consuming and waiting for manual commit/resolve before go for the next batch.

For example, if i have one message in topic 'test', i will get infinite loop in this this case with the same payload.

Code:
```javascript
const { Kafka } = require('kafkajs');

const kafka = new Kafka({
    clientId: `app_${Math.random()}`,
    brokers: ['localhost:9092']
});

const consumer = kafka.consumer({ groupId: `group_${Math.random()}` });

async function run() {
    await consumer.connect();
    await consumer.subscribe({ topic: 'test', fromBeginning: true });
    await consumer.run({
        eachBatchAutoResolve: false,
        autoCommit: false,
        eachBatch: async (payload) => {
            console.log(payload); // infinite log
        }
    });
}

run().catch(console.error);
```

**Comment by tulios** [comment]
@yrsh you have to resolve the offsets. Auto resolve is different than commit, that tracks the offset the consumer should fetch, and in this case, the consumer knows that it's not in the end of the topic and it continues to fetch the same offset.

> instead of stop consuming and waiting for manual commit/resolve before go for the next batch.

This is not what's expected from the client's perspective.

**Comment by yrsh** [comment]
@tulios 
> Auto resolve is different than commit

But according to the documentation autoResolve makes commit:
> eachBatchAutoResolve configures auto-resolve of batch processing. If set to true, KafkaJS will automatically commit the last offset of the batch if eachBatch doesn't throw an error. Default: true.

How can i do fully manual commiting in this case?

**Comment by ankon** [comment]
> you have to resolve the offsets. 

vs 

> But according to the documentation autoResolve makes commit:

The point here is: You need to resolve offsets somehow. One way is using the autoResolve functionality, another approach is to use the resolveOffsets callback given to your eachBatch function: 
```
await consumer.run({
    eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning, isStale }) => {
```
