### ISSUE TITLE
Current published version and documentation not in sync

### ISSUE THREAD

**Issue by marghidanu** [tulios/kafkajs#681]
I was looking at the Admin API and the documentation contains information about the `listGroups()` function which is not available in the current version available on NPM. I see. the implementation in the master branch, maybe you need to do a new release?

**Comment by tulios** [comment]
Yes, that's something we want to improve in the future, but every merge on master generates a pre-release with the change. The latest available is `1.13.0-beta.14`. You can find all pre-releases on NPM.

**Comment by rob3000** [comment]
@marghidanu I think this should now be fixed with the new documentation versioning: 
* Ver 1.12: https://kafka.js.org/docs/admin
* Latest master: https://kafka.js.org/docs/next/admin

cc @Nevon

**Comment by Nevon** [comment]
Indeed it is.
