### ISSUE TITLE
Exposing "is consumer running" to clients

### ISSUE THREAD

**Issue by ankon** [tulios/kafkajs#688]
The documentation says this snippet will get a consumer running:

```js
const consumer = kafka.consumer({ groupId: 'test-group' })

await consumer.connect()
await consumer.subscribe({ topic: 'test-topic', fromBeginning: true })

await consumer.run({
  eachMessage: async ({ topic, partition, message }) => {
    console.log({
      value: message.value.toString(),
    })
  },
})
```

In our case though we need to do some `seek`-ing, which can only happen after the consumer is running, so after `await consumer.run` we run a bunch of `consumer.seek` calls.

If everything goes well this works just fine. But ... what if it doesn't? `run` actually will never throw/reject, but it is possible that when `run` resolves the consumer is actually not running. One example that we have seen in production is that the broker is slow, and partition assignment (sync group) fails with "KafkaJSProtocolError: The coordinator is not aware of this member". In that case the crash handling will happen, set the runner and consumer group to `null`, and schedule a restart. 
Our `seek` calls then will notice that the consumer is not actually there, and fail with "Consumer group was not initialized, consumer#run must be called first". This exception isn't retriable, and all kinds of bad things happen now.

Now, ideally I'd love if `consumer.run` could just reject, but right now that doesn't seem to be workable: After all, it has actually scheduled another attempt, and things may just work out. I'm also somewhat tempted to say that the exception message from `seek` is misleading, because I actually shouldn't call `run` now, but rather wait until it has worked out the problems on its own(?).

What I now do is hook into the `CRASH` instrumentation, set a flag when I see a crash happening, and when `run` resolves I first check that flag: If there was a crash then there is a problem somewhere, and I need to handle (how? nasty question, and the answer depends on whether the whole crash was retriable or not ...)

I think what I would need is this:
1. Somehow expose the consumer "state": I want to know whether it is running, "running-but-right-now-waiting-to-restart", etc
2. Make the seek method not fail when the consumer is in the "running-but-right-now-waiting-to-restart" state, and instead _wait until the request can be scheduled_.

**Comment by ankon** [comment]
> (how? nasty question, and the answer depends on whether the whole crash was retriable or not ...)

I've just found #69 / #643, which will actually help with that: I can return `false` in all cases. ...

**Comment by tulios** [comment]
Yeah, I think two things can improve this:
1) #69 as you mentioned
2) Block on the instrumentation events; I'm still in doubt about that as it becomes super easy to break the client

**Comment by ankon** [comment]
For the record: We're now indeed running with #69 and a "never retry automatically", and so far this seems to work well.

**Comment by dunse** [comment]
It feels like there's a missing else statement here:
https://github.com/tulios/kafkajs/blob/c51dda6fd3d1626535cd7a44e763426e317f2d3a/src/consumer/index.js#L256

The main problem here appears to be the errors which are set as "retriable = false". Maybe we could expose a user-land function for non-retriable crashes?

**Comment by HunderlineK** [comment]
`

> It feels like there's a missing else statement here:
> 
> https://github.com/tulios/kafkajs/blob/c51dda6fd3d1626535cd7a44e763426e317f2d3a/src/consumer/index.js#L256
> 
> The main problem here appears to be the errors which are set as "retriable = false". Maybe we could expose a user-land function for non-retriable crashes?

That would be fantastic! Though I'm assuming, if there's a non-retriable crash, the consumer is going to throw and error and we can externally just restart the consumer in that case without having to do a shutdown and get a clean consumer back online?

**Comment by tulios** [comment]
This seems to be solved; I am closing it for now. Feel free to re-open the issue if it is not the case.
