### ISSUE TITLE
Implement a means to react on retries

### ISSUE THREAD

**Issue by delanni** [tulios/kafkajs#69]
## Context
Currently we're facing a situation, where we either swallow an exception from a message handler immediately after it's raised, or wait for the consumer to die because the heartbeats timing out after retrying too many times.

We'd need something like a hook or callback after all the retries are used up on trying to handle a certain message, in which we can decide to prevent the client crashing by committing the event. Alternatively a counter that tells us how deep are we in the retry-cycle, and act with our own logic.

## Proposal
- Implement a retry option, that would be called with the last or all exceptions during retrying after all the retries are exceeded.
- Feed the retry cycle counter to the eachMessage handler, or the batch message handler.

**Comment by tulios** [comment]
Implemented on #643
