### ISSUE TITLE
KafkaJSLockTimeout: Timeout while acquiring lock (2 waiting locks): "updating target topics"

### ISSUE THREAD

**Issue by ankon** [tulios/kafkajs#695]
When switching to KafkaJS 1.13.0-beta.14 for testing I had a few services report this error message. The error appeared multiple times, with increasing number of waiting locks.

I believe the increasing number of waiting locks is fixed by #694, this issue is about the underlying problem though of _why_ we saw these in the first place.
This lock was introduced with #666, which is only in KafkaJS 1.13.0-beta.X from what I can see.

I _think_ what happens is that at the time we get the exception we're trying to produce multiple messages through the same producer, but through different `send` calls. Our KafkaJS client is not configured with any specific `requestTimeout`, we're relying on the defaults. This means that the `mutatingTargetTopics` lock is configured with an `undefined` timeout:
https://github.com/tulios/kafkajs/blob/fe4d73d2a3f1645e0661f3c7994821325b59489b/src/cluster/index.js#L82-L85

Later this timeout value is used for the `setTimeout` call: https://github.com/tulios/kafkajs/blob/fe4d73d2a3f1645e0661f3c7994821325b59489b/src/utils/lock.js#L16

Now, a `setTimeout` with a undefined timeout will basically trigger the timeout in the next tick: https://nodejs.org/dist/latest-v12.x/docs/api/timers.html#timers_settimeout_callback_delay_args
> When delay is larger than 2147483647 or less than 1, the delay will be set to 1. Non-integer delays are truncated to an integer.

So, I guess the first `send` grabs the lock, eventually a second `send` tries to also do that, and triggers the exception. And then due to the issue in #694 I never manage to produce anything anymore :)

The documentation says there is a 30s default for the `requestTimeout`, but this is only configured when creating connections:
https://github.com/tulios/kafkajs/blob/fe4d73d2a3f1645e0661f3c7994821325b59489b/src/network/connection.js#L45

The fix probably is to have a reasonable default timeout for locks, or move setting the default request timeout higher up (client/cluster?)

**Comment by Nevon** [comment]
I don't think having a default lock timeout is the correct approach, since it depends vastly on the usage of the lock, but rather to throw if the lock gets an undefined timeout. Moving the default request timeout up to the cluster level seems like the better solution.

**Comment by ankon** [comment]
FWIW: In production we explicitly configure the request timeout (to 30s), thereby avoiding the problem.

**Comment by ankon** [comment]
Somewhat related: #748 would reduce the number of locks taken/released when producing to multiple topics at once.
