### ISSUE TITLE
SSL Connection Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by mbarany** [tulios/kafkajs#70]
I'm using the Heroku kafka addon. The hosts are just ec2 hosts (eg. `ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com`), but the certs CN is a random alpha string. Using `"rejectUnauthorized": false` _works_ but then it does not verify the cert is signed by the provided CA. Is there any way to ignore the hostname match but keep all the rest of the verification?

**Comment by Nevon** [comment]
The `ssl` option (https://github.com/tulios/kafkajs/blob/master/README.md#-ssl) is passed directly to `tls.connect`, which means that you can define the `checkServerIdentity` option (https://nodejs.org/api/tls.html#tls_tls_connect_options_callback), which allows you to bypass hostname verification if you so choose.

**Comment by mbarany** [comment]
thanks!! IMO that should be in the README instead of or in addition to `"rejectUnauthorized": false` - especially since you are defining a list of CA's which basically won't be used if you disable all verification. I can open a PR for that if you think it makes sense.

**Comment by Nevon** [comment]
Well, given that it's a Node TLS option, it doesn't really have much to do with KafkaJS. Personally I don't think we should document every option, since they're already documented in the Node docs, but I'm all for improving our documentation if it is inconsistent.

What do you think, @tulios?

**Comment by mbarany** [comment]
I agree it doesn't make sense to document them all. perhaps just the important ones. or at least remove `rejectUnauthorized` as it's confusing.

**Comment by ethanresnick** [comment]
@mbarany What was your ultimate solution here?

**Comment by mbarany** [comment]
Adding the **checkServerIdentity** option.
Example:
```
const kafkaOptions = {
  clientId: `...`,
  brokers: process.env.KAFKA_URL.split(',').map((host) => {
    return host.replace('kafka+ssl://', '');
  }),
  logLevel: logLevel.ERROR,
  ssl: {
    checkServerIdentity: () => undefined, // disables hostname verification only
    ca: [process.env.KAFKA_TRUSTED_CERT],
    key: process.env.KAFKA_CLIENT_CERT_KEY,
    cert: process.env.KAFKA_CLIENT_CERT
  }
};

const kafka = new Kafka(kafkaOptions);
```

**Comment by ethanresnick** [comment]
@mbarany Thanks. That's what I ended up doing too.
