### ISSUE TITLE
heartbeat() not being called after eachBatch()

### ISSUE THREAD

**Issue by WaleedAshraf** [tulios/kafkajs#708]
**Describe the bug**
Heartbeat() not being called after `eachBatch()`. Because of that, I get error 
```
"message":"[Runner] The coordinator is not aware of this member,
```

**To Reproduce**
1. Run consumer which is consuming from one topic with a lot of partitions.
2. Start processing fetched batches with eachBatch()
3. After the consumer is done with all the batches it fetched from the broker, if 30 sec has been elapsed, Error "The coordinator is not aware of this member" will be thrown before next fetch.

**Expected behavior**
heartbeat() should be called after processing `eachBatch()`. As described here: https://kafkajs.slack.com/archives/CF6RFPF6K/p1563277272018700?thread_ts=1563275923.018600&cid=CF6RFPF6K

> Tommy Brunn: Can you show us what your eachBatch block looks like? If executing the eachBatch takes longer than the sessionTimeout, you'll need to make sure to heartbeat periodically to keep the member from being kicked out of the group.

**Observed behavior**
kafkajs is calling `heartbeat()` between the `fetch` calls, not between `eachBatch()`.

![image](https://user-images.githubusercontent.com/8335457/80007872-302f8380-84c7-11ea-9548-f4e8d67669f9.png)

From the logs, you can see that `END_BATCH_PROCESS` event is being logged, that means `eachBatch()` was done, but still consumer got kicked out because of sessionTimeout.

**Environment:**
 - OS: Mac OS: 10.15.3
 - KafkaJS version: 1.12.0
 - Kafka version: 2.4
 - NodeJS version: 10.16.3

**Additional context**
Seems it is fixed in beta version, in this PR in line [346 in runner.js](https://github.com/tulios/kafkajs/pull/570/files#diff-0706eb2c0060b2da86157638eb477a86R346)

I have not tested it on master yet. Will do it later.

**Comment by WaleedAshraf** [comment]
I don't see this issue while testing on the `1.13.0-beta.15`.

**Comment by Nevon** [comment]
I'm gonna close this as it's fixed in the beta version.
