### ISSUE TITLE
Consumer throws KafkaJSNumberOfRetriesExceeded after 5 retries when default is 10

### ISSUE THREAD

**Issue by WaleedAshraf** [tulios/kafkajs#709]
**Describe the bug**
Consumer throws KafkaJSNumberOfRetriesExceeded after 5 retries where the default is 10 as here:
https://kafka.js.org/docs/configuration#a-name-retry-a-default-retry

**To Reproduce**
- Start consumer without providing retry config (let it use default 10)
- Throw error 5 times while consuming
- The consumer will restart with KafkaJSNumberOfRetriesExceeded

**Expected behavior**
The consumer should retry 10 by d times by default.

**Observed behavior**
![image](https://user-images.githubusercontent.com/8335457/80212835-83751380-8638-11ea-889d-6c79821a7e39.png)

**Environment:**
 - OS: Mac OS 10.15.4
 - KafkaJS version: 1.12.0
 - Kafka version: 2.4.0
 - NodeJS version: 10.16.3

**Additional context**
It's happening because we send empty object here,
https://github.com/tulios/kafkajs/blob/aec71606610b39bbdb9afc5a6610b40c840b3120/src/index.js#L137-L140

And inside the consumer, the default value is not assigned because we received the value as an empty object.
https://github.com/tulios/kafkajs/blob/aec71606610b39bbdb9afc5a6610b40c840b3120/src/consumer/index.js#L37-L39

**Comment by tulios** [comment]
Good catch, can you attempt a PR?

**Comment by WaleedAshraf** [comment]
@tulios Yes. Will do that 👍
