### ISSUE TITLE
End of topic event.

### ISSUE THREAD

**Issue by SergeyFromHell** [tulios/kafkajs#710]
**Is your feature request related to a problem? Please describe.**
I have some finish logic running when all currently pushed data has been processed (some stats update and external backpressure). Right now I use idle timeout (wait some minutes, and if no messages received, conclude topic end has been reached). But it is a very fragile way.

**Describe the solution you'd like**
It would be much better to have some (instrumentation?) event fired when consumer reaches end of topic (for all partitions simultaneously).

**Comment by tulios** [comment]
Hi @SergeyFromHell, you can implement this feature without new code. You can listen to the `END_BATCH_PROCESS` instrumentation event and compare the `highWatermark` with your current offset, if they are off by one you can emit an event saying that you reached the end of the topic. To cater to all partitions you will have to keep some state, but it's also possible.

**Comment by Nevon** [comment]
See https://github.com/tulios/kafkajs/issues/825#issuecomment-674106799 for an example of this.
