### ISSUE TITLE
How to consume data in batches with Kafkajs

### ISSUE THREAD

**Issue by alikhiti** [tulios/kafkajs#716]
Hello, thanks for your library. How can I consume messages in batches from kafka. Let's say I want to perform some operations on 5 messages at a time for example. Or I want to consume all the messages from a certain period at the same time and have them as an array.
I tried to combine **partitionsConsumedConcurrently** and **eachBatch** but it keep returning one message at a time:

```
    partitionsConsumedConcurrently: 4, 
    eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning, isStale }) => {
      console.log(batch.messages)
    }
```

**Comment by Nevon** [comment]
`partitionsConsumedConcurrently` just controls the concurrency, i.e. if we have batches from 10 partitions and you have set `partitionsConsumedConcurrently` to 5, we will call your `eachBatch` 5 times with different batches concurrently, and then call you with the rest once the earlier calls have resolved.

Partitions are the unit of concurrency in Kafka, so we will always call your `eachBatch` with messages from a single partition. To control the size of the batches, you have `minBytes`, `maxBytes`, `maxBytesPerPartition` and `maxWaitTimeInMs`. These are all explained in the documentation: https://kafka.js.org/docs/consuming#options

There is no way in Kafka to say that you want to get exactly 5 messages in a batch, as the protocol is all about bytes. If your message size is fairly consistent, then you can do some rough match to tweak `minBytes`/`maxBytes`/`maxBytesPerPartition` to receive approximately the number of messages that you want, but if you want exactly a certain number of messages you should just split up `batch.messages` into however many "batches" you want.
