### ISSUE TITLE
How to list all topics?

### ISSUE THREAD

**Issue by dashie** [tulios/kafkajs#717]
- How can I list all topics? Maybe using a regex pattern.
- And how can I subscribe to the "new topic created" event?

The only way I've found is

`(await admin.clusterRef().metadata()).topicMetadata.map(t => t.topic);`

but to do it I need to expose the `cluster` property by the method `clusterRef` and modify the library.

So I propose the following pull request #718

**Comment by Nevon** [comment]
Fixed by #718
