### ISSUE TITLE
Runner#stop takes too much time because of hardcoded 1000ms timer

### ISSUE THREAD

**Issue by sempasha** [tulios/kafkajs#723]
As you can see at [runner source](https://github.com/sempasha/kafkajs/blob/c51dda6fd3d1626535cd7a44e763426e317f2d3a/src/consumer/runner.js#L144), call of Runner#stop first change `this.running` state, then wait consumer to be done and then leave consumer group.

When runner wait consumer to be done it check `this.consuming` flag is set or not. When flag is not set - we done, but when flag is not set, next flag check will be scheduled one second later.

So every time we need to stop runner (that mean every time we need to stop consumer) we may get unnecessary one second delay, caused by waiter based on `setTimeout`.

```js
  async stop() {
    if (!this.running) {
      return
    }
    ...
    this.running = false

    try {
      if (!isTestMode) {
        await this.waitForConsumer()
      }
      await this.consumerGroup.leave()
    } catch (e) {}
  }

  waitForConsumer() {
    return new Promise(resolve => {
      const scheduleWait = () => {
        ...
        setTimeout(() => (!this.consuming ? resolve() : scheduleWait()), 1000)
      }
      if (!this.consuming) {
        return resolve()
      }
      scheduleWait()
    })
  }
```

If runner could emit events on each change of `this.consuming`, we will use this events instead of `setTimeout` with hardcoded one second interval.

```js
  waitForConsumer() {
    return new Promise(resolve => {
      if (!this.consuming) {
        resolve()
      } else {
        this.once('consuming flag becomes off', () => resolve());
      }
    })
  }
```

**Comment by ankon** [comment]
Nice find!

Given that we're starting and stopping consumers a lot due to the way we implement dynamic subscription changes (see https://github.com/tulios/kafkajs/issues/476#issuecomment-522458641 for a description of the approach), this might help us quite a bit :)
