### ISSUE TITLE
Connection creation strategy

### ISSUE THREAD

**Issue by mo-harris** [tulios/kafkajs#727]
What is the recommended strategy for creating connections in production?
I have these strategies in mind:
1. Using a connection pool
2. Using one shared connection
3. One connection for producing and one connection for consuming
4. Create a connection per topic
which one do you recommend?

**Comment by tulios** [comment]
It depends 😄 
If you have one consumer subscribed to several topics I would recommend one connection for the producer and one for the consumer.
If you have different consumers in the same project then one connection for the producer and one for each consumer.

**Comment by mo-harris** [comment]
I appreciate the quick response.
Let's say I have a RestAPI which its endpoints produce messages to Kafka topics. Do you suggest using a shared connection for all requests or using a connection pool?
I'm not much familiar with the Kafka protocol, What I'm trying to understand is, if it is a blocking protocol (e.g.: Running a query in a PostgreSQL connection would block that connection) or it's non-blocking?

**Comment by tulios** [comment]
It's non-blocking, and the library has a connection pool and will manage the connections for you, so you can use the same instance of the producer for all handlers and the library will block and create new connections as it needs to.

**Comment by mo-harris** [comment]
Great! Thanks
