### ISSUE TITLE
admin listTopics mentioned in documentation but function doesn't exist.

### ISSUE THREAD

**Issue by Zappatta** [tulios/kafkajs#741]
**Describe the bug**
The documentation [here](https://kafka.js.org/docs/admin) mentions you can call admin.listTopics. But when doing so I get `.listTopics is not a function`

Printing the admin object I get:
```
{
  connect: [AsyncFunction: connect],
  disconnect: [AsyncFunction: disconnect],
  createTopics: [AsyncFunction: createTopics],
  deleteTopics: [AsyncFunction: deleteTopics],
  getTopicMetadata: [AsyncFunction: getTopicMetadata],
  fetchTopicMetadata: [AsyncFunction: fetchTopicMetadata],
  events: {
    CONNECT: 'admin.connect',
    DISCONNECT: 'admin.disconnect',
    REQUEST: 'admin.network.request',
    REQUEST_TIMEOUT: 'admin.network.request_timeout',
    REQUEST_QUEUE_SIZE: 'admin.network.request_queue_size'
  },
  fetchOffsets: [AsyncFunction: fetchOffsets],
  fetchTopicOffsets: [AsyncFunction: fetchTopicOffsets],
  setOffsets: [AsyncFunction: setOffsets],
  resetOffsets: [AsyncFunction: resetOffsets],
  describeConfigs: [AsyncFunction: describeConfigs],
  alterConfigs: [AsyncFunction: alterConfigs],
  on: [Function: on],
  logger: [Function: getLogger]
}
```

I am on 1.12.0 which appears to be the latest version.

**To Reproduce**

```
    const kafkaAdmin = Kafka.admin()
    await kafkaAdmin.connect();
    const existingTopics = await kafkaAdmin.listTopics();
```

**Expected behavior**
returns list of topics on server

**Observed behavior**
Function does not exist. 

Looking at kafka under node_modules/kafkajs/src/admin/index.js. There is indeed no such function. But looking at node_modules/kafkajs/package.json the version 1.12.0. Did try to remove node_modules and rerun npm i

**Environment:**
 - OS: OSX Catalina. But don't think is relevant
 - KafkaJS version: 1.12.0
 - Kafka version N/A
 - NodeJS version 12.16.0

**Additional context**

**Comment by Nevon** [comment]
As mentioned on the [start page of the docs](https://kafka.js.org/docs/getting-started):

> This documentation is generated from latest master. There may be differences from the current stable version of KafkaJS. Contributions setting up [versioned documentation](https://github.com/tulios/kafkajs/issues/279) are welcome.

[The beta version](https://www.npmjs.com/package/kafkajs/v/beta), which is built from latest master, does have this method, but there has not been a stable release containing it yet.

**Comment by Zappatta** [comment]
Missed that. Sorry. Thanks for the response. 

May i suggest only updating the website on stable release? I'm sure I'm not the first one to make this mistake.

Even more preferable would be to state in the docs at what version a feature was introduced. But that's probably a pain to manage.

Anyways, thanks again.

**Comment by Nevon** [comment]
Our documentation platform, Docusaurus, already supports versioned docs, so that you can have one version for each release, plus one version for master, but no one has volunteered to set it up yet. #279

**Comment by MikeShiner** [comment]
I just stumbled across this myself. Thanks for raising the issue Zappatta.

**Comment by sureshballa** [comment]
When can we expect this in new release? we are in need of this.

**Comment by Zappatta** [comment]
Hey @sureshballa. 
Until this is released you can get a list of topics by calling `fetchTopicMetadata()`

for example:
```javascript
const topicsMetaData = await kafkaAdmin.fetchTopicMetadata();
const existingTopicNames = topicsMetaData.topics.map(topic => topic.name);
```

**Comment by sureshballa** [comment]
Thanks @Zappatta . this works great.
