### ISSUE TITLE
maxInFlightRequests documented in the wrong place

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#753]
**Describe the bug**
Currently `maxInFlightRequests` is documented as being an option for `retry`, when it's actually a top-level option for the `consumer` and `producer` factory functions.

**To Reproduce**

https://kafka.js.org/docs/configuration#a-name-retry-a-default-retry

**Expected behavior**

The option should be removed from the `retry` documentation and added to the consumer & producer.

**Comment by sujayneglur123** [comment]
Is this programmatically handled or hardcoded in the website related things?

**Comment by sujayneglur123** [comment]
Is this handled programmatically or hardcoded in the docs directory's .MD files?

**Comment by sujayneglur123** [comment]
https://github.com/tulios/kafkajs/pull/754

**Comment by Nevon** [comment]
Closed by #754
