### ISSUE TITLE
Wrong type definitions for `describeGroups`

### ISSUE THREAD

**Issue by tzachshabtay** [tulios/kafkajs#756]
The current type definition claims it returns an array of group descriptions:
https://github.com/tulios/kafkajs/blob/bd5cf4c3e2ea9b82343e8927319876fa35f3a675/types/index.d.ts#L673

But it actually returns an object which has a property `groups` which is the array of group descriptions, i.e
```
{
    groups: []
}
```

**Comment by ankon** [comment]
The snippet you referenced talks about `Consumer.describeGroup`, `Admin.describeGroups` is a few lines down:
https://github.com/tulios/kafkajs/blob/bd5cf4c3e2ea9b82343e8927319876fa35f3a675/types/index.d.ts#L329
