### ISSUE TITLE
How does message fetching work?

### ISSUE THREAD

**Issue by khanv-it** [tulios/kafkajs#760]
Hi, I'm trying kafkajs recently and wondering how consumer fetchs a batch of messages ?
- After a fix interval, kafkajs will fetch a new batch of messages not considering the previous one processed completely or not
OR
- Only after a batch is handled entirely ( all old messages is checked as resolved ) a new batch will be consumed.
In any scenario, is it possible for a consumer to drain out of memory due to getting too many messages and can not handle them as fast?!

**Comment by Nevon** [comment]
You would probably benefit from reading up on Kafka and Kafka consumer groups to get a theoretical understanding of how it works. [This article](https://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/#:~:text=In%20Kafka%2C%20each%20topic%20is,of%20logs%20known%20as%20partitions.&text=While%20the%20old%20consumer%20depended,selected%20as%20the%20group%20coordinator.), although the code snippets themselves refer to the Java client, gives a quick intro to consumer groups, which is how KafkaJS is typically used.

As to your question, the KafkaJS consumer is essentially running a loop where it first fetches a batch of messages from the brokers and then calls your `eachMessage`/`eachBatch` handlers. Once your handlers resolve or reject, it then executes the next fetch.

> In any scenario, is it possible for a consumer to drain out of memory due to getting too many messages and can not handle them as fast?!

No. Until your handlers resolve or reject, we won't fetch any more messages, so consumption only happens at the rate that you are able to process.

**Comment by khanv-it** [comment]
Many thanks for your so quick reply!! Sure I will check the article.
