### ISSUE TITLE
Process won't shutdown even after consumer.disconnect()

### ISSUE THREAD

**Issue by dhulke** [tulios/kafkajs#767]
**Describe the bug**
I'm trying to get the last message of a topic, from partition 0 and after retrieving the message I cant disconnect the consumer, the process hangs forever. I tried calling `await consumer.disconnect();` in the `eachMessage` callback but the disconnect call hangs. Then I tried calling it with `setImmediate` and "end" is printed, but the process still hangs.
This is the error I get:

This is the code:
```
require("dotenv").config();

const { Kafka } = require('kafkajs');

(async () => {

    const kafka = new Kafka({
        // clientId: 'my-app',
        brokers: process.env.KAFKA_BROKER_LIST.split(","),
        ssl: true,
        sasl: {
            mechanism: process.env.KAFKA_SASL_MECHANISM,
            username: process.env.KAFKA_SASL_USERNAME,
            password: process.env.KAFKA_SASL_PASSWORD
        },
    })

    const admin = kafka.admin();

    await admin.connect();
    const offsets = await admin.fetchTopicOffsets(process.env.KAFKA_TOPIC);
    await admin.disconnect();

    const consumer = kafka.consumer({ groupId: 'my-group' })

    await consumer.connect()
    await consumer.subscribe({ topic: process.env.KAFKA_TOPIC })

    consumer.run({ autoCommit: false, eachMessage: async ({ topic, message }) => {
            const event = JSON.parse(message.value.toString());
            console.log(topic, event.event.replayId);
            setImmediate(async () => {
                await consumer.disconnect();
                console.log('end');
            });
        }
    })
    consumer.seek({ topic: process.env.KAFKA_TOPIC, partition: 0, offset: offsets[0]['offset'] })

})(...process.argv.slice(2)).catch(console.log);
```

**Comment by goriunov** [comment]
@dhulke @Nevon i can confirm that this issue persists even on latest beta, it happens only if connection to one or more brokers failed and and in brokerPool file `this.seedBroker` has been rotated in `retrier`. I believe we are missing some disconnect/clean up for old/rotated failed connections somewhere but that is as far as i have tracked for now (will look at it more later). TBH i was able to reproduce that few times with just admin client

**Comment by dhulke** [comment]
I can confirm this problem happens whenever an error is thrown from inside the module and I get to see it in stderr. I can also confirm that when no errors happen, `fetchTopicOffsets` is successfully disconnected, but that doesn't happen to `consumer.run`. I don't know if I'm disconnecting in the wrong place or if theres a problem with one of the brokers and kafkajs just didn't spit it out in stderr.

**Comment by goriunov** [comment]
@dhulke would you be able to run above branch and see if that resolves you issue

**Comment by Nevon** [comment]
This should be fixed in the beta version of KafkaJS. Feel free to re-open if this is still reproducible.
