### ISSUE TITLE
can't control the threshold committing value

### ISSUE THREAD

**Issue by yuriabaev** [tulios/kafkajs#773]
i set autoCommitThreshold to 5 and send messages, as here:
 ```javascript
await consumer.run({
    autoCommit: true,
    autoCommitThreshold: 5,

    eachMessage:...})
```
but I see that messages are committed per **every** message I send and not after 5 messages as I would expect

why?

**Comment by Nevon** [comment]
Please don't create multiple issues for the same thing. #774
