### ISSUE TITLE
Offsets get committed with autoCommit: false if a rejection happens

### ISSUE THREAD

**Issue by rafalneves** [tulios/kafkajs#782]
`consumer.run({ autoCommit: false, eachMessage: () => Promise.reject(new Error('Error')) });`

On the consumer above, message offsets should never be committed. The first message of the topic should be retried.

That doesn't happen. Offset gets committed and opens the possibility of data loss.

**To Reproduce**
1. Create a consumer with autoCommit disabled
2. On eachMessage trigger a rejection
3. Check topic offsets for your consumer group - if it's a new topic should be 0, but that's not the case.

**Expected behavior**
The topic offset should not be changed on message rejection. **Much less committed with autoCommit: false.**

**Environment:**
 - OS: Not relevant
 - KafkaJS version 1.12.0
 - Kafka version: Not relevant
 - NodeJS version: Not relevant

**Comment by Nevon** [comment]
This was fixed by #866 and is out now in version 1.14.0.
