### ISSUE TITLE
Transaction documentation does not mention transactionalId

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#789]
In order to create a transaction, the producer must be created with a transactionalId. However, this is not mentioned anywhere in the documentation for transactions.

See: https://kafka.js.org/docs/transactions

**Comment by senseluo** [comment]
oh yes i didn't find it as well

**Comment by megakoresh** [comment]
Yes, still not documented.

**Comment by eliw00d** [comment]
Documentation and examples would be great! In the meantime, has anyone gotten transactions to work in a way that supports multiple instances of an app? I think Streams and other implementations use a combination of topic, group, and partition for the transactional.id, so knowing how we can get that to work would be awesome.

**Comment by Nevon** [comment]
Fixed by #902
