### ISSUE TITLE
when will restartOnFailure  will be released?

### ISSUE THREAD

**Issue by yuriabaev** [tulios/kafkajs#790]
when will restartOnFailure for the consumer will be released?

**Comment by ankon** [comment]
I don't think there is a fixed timeline for the next release.

But, you can always try to use the versions created from master, see https://kafka.js.org/docs/pre-releases for details on that.

**Comment by yuriabaev** [comment]
thanks @ankon , is pre-releases production ready?

**Comment by ankon** [comment]
They are releases made from master, so of course they can always contain bugs. 

I think there’s quite some testing done on each build though, and from our experience the prereleases work well. 

You definitely should have some form of testing them for your setup, and be prepared to update when needed — but that’s something I think you anyways need with any software & dependencies :)

**Comment by Nevon** [comment]
I will close this issue as @ankon summarizes it quite well. If you want more information on the stable release process, see #736. We don't have a set release frequency, so the next release will happen when we have a pre-release version that we are confident is production ready, which has been quite challenging recently.
