### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#8]
I was thinking about an octopus tentacle, drawn in a way the looks like the Kafka logo. I'm no designer but I made an attempt using Sketch and I quite like it 😆 

![tentacle](https://user-images.githubusercontent.com/33231/33856183-98153826-dec7-11e7-9bc5-f1dafa1cefa6.png)

@sebastiannorde has the proper skill set to solve this problem and has helped with other projects in the past, can you give us a hand here?

Maybe we can tweak the colors to use the Node.js green, @matthiasfeist @Nevon WDYT?

**Comment by matthiasfeist** [comment]
Looks good. I guess @sebastiannorde can whip up something nice.

**Comment by sebastiannorde** [comment]
![kafka_js](https://user-images.githubusercontent.com/4101446/36434354-22b90e34-165f-11e8-927b-e1e1af20aab5.png)
What do you think about this @tulios

**Comment by tulios** [comment]
Amazing!! ❤️
