### ISSUE TITLE
Support for dynamic topics or multiple consumers each with one topic?

### ISSUE THREAD

**Issue by Arkh1** [tulios/kafkajs#809]
Our team has a need for dynamic topics or the ability to stand up a new consumer for each new topic.  For our project topics are created/removed on a very regular basis.

Is it possible in kafkajs to cleanly subscribe to new topics after consumer.run() has been called?  If not... does kafkajs support multiple consumers to a degree in which we can stand up a new consumer for each new topic as it gets created?  Then subsequently tear down said consumers?

Any help would be appreciated, Thanks!

**Comment by ankon** [comment]
You can certainly create multiple consumers with KafkaJS.

For changing subscriptions after a consumer is running: See https://github.com/tulios/kafkajs/issues/476

**Comment by Arkh1** [comment]
> You can certainly create multiple consumers with KafkaJS.
> 
> For changing subscriptions after a consumer is running: See #476

We are transitioning off of kafka-node.  For their library they recommended having a new kafka client instance for each new consumer.  Is that true for KafkaJS as well?  When I tried standing up a new consumer for each new topic the first consumer I created was working, but subsequent consumers didn't start consuming messages from their dedicated topics.

**Comment by ankon** [comment]
With KafkaJS you typically have one client, and create your producers/consumers through it. See https://kafka.js.org/docs/consuming

**Comment by Nevon** [comment]
> When I tried standing up a new consumer for each new topic the first consumer I created was working, but subsequent consumers didn't start consuming messages from their dedicated topics.

Make sure that you use a different groupId for the different consumers, as they will form individual consumer groups.

**Comment by pinturic** [comment]
@Arkh1 For me it is the same!
I am moving from kafka-node and there we were using a client for consumer. My understanding is that it should not be needed to create a client for consumer ...
The point is that instead it seems that only one consumer seems to be owrking for each client...
