### ISSUE TITLE
Wrong types definition for fetchTopicMetadata parameter

### ISSUE THREAD

**Issue by katerina-semikina** [tulios/kafkajs#814]
**Describe the bug**
In types/index.d.ts options with topics is a required parameter:
```
fetchTopicMetadata(options: { topics: string[] }): Promise<{ topics: Array<ITopicMetadata> }>
```
In admin/index.js parameter is optional. `fetchTopicMetadata()` results in listing all the topics:
```
* If no topics are provided fetch metadata for all topics.
const fetchTopicMetadata = async ({ topics = [] } = {}) => {
```

**To Reproduce**
Using type version of KafkaJS

**Expected behavior**
Ability to call fetchTopicMetadata with no parameters in typescript.

**Observed behavior**
> index.d.ts(301, 22): An argument for 'options' was not provided.

**Environment:**
Not applicable

**Additional context**
 Using Typescript

**Comment by NamanArora** [comment]
@Nevon I would like to work upon fixing this issue. Are there are contribution guidelines/protocol that is needed to be followed?

**Comment by tulios** [comment]
@NamanArora you can create the PR and take it from there.
