### ISSUE TITLE
Disproportionate partition assignment

### ISSUE THREAD

**Issue by cpiemontese** [tulios/kafkajs#820]
Hi, I noticed a strange behavior where consumers are assigned a disproportionate amount of partitions.

I ran 12 consumers connected to ~30 topics, each with a varied number of partitions (between 1 and 12). Some consumers were assigned 1 partition and some were assigned 16. Unfortunately, I haven't been able to reproduce this issue in a controlled environment yet, but I would like to know if this could be a normal behavior of the partition assigner or if it is worth investigating further.

**Comment by tulios** [comment]
This can happen while the group is rebalancing

**Comment by cpiemontese** [comment]
Hi, this behavior happened even while the group wasn't re-balancing i.e. while everything was stable.
Since then we tried the beta version of KafkaJS because it solved another problem we were having and this doesn't seem to occur anymore.
