### ISSUE TITLE
Retry messages are not sent in the order of publication when there is no connection.

### ISSUE THREAD

**Issue by Themesaul** [tulios/kafkajs#822]
**Describe the bug**

Queues don't send messages in order

**To Reproduce**

1. Run a producer that continuously produces messages to a topic with and autonumeric key
2. Run a consumer that subscribes to that topic and logs each topic offset
3. Remove network
4. Add network

**Expected behavior**
Messages are sent in the correct order when there is no connection (the retry mechanism takes this into account)

**Observed behavior**
After the consumer has consumed all the messages, you can see that they have not arrived in the order they should, they are not even produced in order for the same key. 

**Environment:**
 - OS: Lunux
 - KafkaJS version 1.12.0
 - Kafka version last
 - NodeJS version 14

**Comment by Nevon** [comment]
Do you mean to say that the following code would potentially produce the messages in the wrong order?

```js
const sendMessage = async value => {
  await producer.send({
    topic: 'test-topic',
    messages: [{ value }],
  })
}

let value = 0
while (true) {
  await sendMessage(value)
  value++
}
```

It was a little tricky to test, as I'm running the brokers on the same machine as I'm running my producer/consumer, but what I did was:

1. Run a producer that would essentially do what I showed above.
2. While the producer was running, disconnect the kafka broker from the network.
3. Re-attach the kafka broker and wait for the producer to continue producing again.
4. Stop the producer
5. Run a consumer that just outputs all the messages.

In my experiment, all the messages were produced in the expected order. I produced across two different partitions (ensured by making the key be `key-${value % 2}`) and then I just had the value be `value-${num}-${new Date().toISOString()}` where `num` is increased by 1 after each message.

**Comment by Nevon** [comment]
I'm going to close this for now. Feel free to re-open if you can provide a way to reproduce this or if I misunderstood the problem.
