### ISSUE TITLE
admin.listGroups() is not a function

### ISSUE THREAD

**Issue by bclegaspi** [tulios/kafkajs#830]
The version I installed using npm does not have the functions such as admin.listGroups or admin.listTopics although it was the latest version(1.12)

List groups
List groups available on the broker.

await admin.listGroups()

**Comment by ankon** [comment]
The `listGroups` method was only added in the current master version (see https://github.com/tulios/kafkajs/pull/645), and hasn't been released yet.

Note that the documentation visible on the website is generated from the master version, and therefore might be out-of-sync. See https://kafka.js.org/docs/pre-releases for how to use a pre-release version built from master.

**Comment by bclegaspi** [comment]
Thank you ankon for the reply, may I ask how long before this version is released?

**Comment by ankon** [comment]
There is no specific plan for when the next version will be released, see https://github.com/tulios/kafkajs/issues/736 for the bigger context.

**Comment by bclegaspi** [comment]
Okay, thanks again, I guess I'll use the pre-release version for now.
