### ISSUE TITLE
listTopics, createPartitions methods are not present in admin client

### ISSUE THREAD

**Issue by subhamsriv** [tulios/kafkajs#834]
**Describe the bug**
listTopics, createPartitions methods are not present in type Admin.

**Observed behavior**
Type Admin should have methods listTopics, createPartitions:

![image](https://user-images.githubusercontent.com/26085961/89737455-bbd91a00-da8e-11ea-95a8-ff120786e10f.png)

Error in log: (node:16772) UnhandledPromiseRejectionWarning: TypeError: admin.listTopics is not a function

**Environment:**
 - OS: Windows
 - Version:  "kafkajs": "1.12.0"
 - NodeJS version : 12.16.3

**Comment by goriunov** [comment]
I believe types have been fixed already https://github.com/tulios/kafkajs/blob/master/types/index.d.ts, but error which you mentioned above has nothing to do with typescript types that error means that `listTopics` function does not exist on the `admin` object. Can you try running on beta version

**Comment by goriunov** [comment]
Looking at PRs 

https://github.com/tulios/kafkajs/pull/718
https://github.com/tulios/kafkajs/pull/661

listTopics and createPartitions have been added after 1.12.0 release so you have to use beta version if you want those functionalities

**Comment by subhamsriv** [comment]
Works fine with beta version. Thanks
