### ISSUE TITLE
Notification on consumer partition change

### ISSUE THREAD

**Issue by romain-gilles-ultra** [tulios/kafkajs#842]
## Context
We are developing a consumption error management system that saves the faulty message that may be due to code issues.
We want to avoid trigger reload of those messages 'manually'.

## Potential solution
We were thinking that the partition assignment could be a good candidate to identify cluster topology change. This topology change can reflect a new deployment of the application.
We would like to get notified when a new partition is assigned to a consumer.
You have this in the Java API: [ConsumerRebalanceListener](https://kafka.apache.org/26/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html).

**Comment by Nevon** [comment]
> We are developing a consumption error management system that saves the faulty message that may be due to code issues.
> We want to avoid trigger reload of those messages 'manually'.

What do you mean by this? This sounds like a regular dead letter queue, but I don't see how that relates to partition assignment.

> We would like to get notified when a new partition is assigned to a consumer.

This exists, using the [instrumentation events](https://kafka.js.org/docs/instrumentation-events#consumer) - specifically `consumer.events.GROUP_JOIN`, which includes the member assignment in the payload.

**Comment by Nevon** [comment]
> Does this listener receive an event when rebalancing occurred and this consumer now is responsible for more or fewer partitions?

The `GROUP_JOIN` event is emitted anytime the consumer has joined the group and synced, which means that partitions have been assigned across the group. It doesn't _necessarily_ mean that the assignments are different than before, although they most likely will be.
