### ISSUE TITLE
Documentation for admin.createTopics shows incorrect type for Topics parameter

### ISSUE THREAD

**Issue by SeanBarry** [tulios/kafkajs#844]
**Describe the bug**
In the documentation for the `admin.createTopics` function, the `topics` parameter type is set to `Topic[]`.

I tried to import this for type safety, but couldn't. The actual type is called `ITopicConfig`, so the documentation should be updated to:

```
await admin.createTopics({
    validateOnly: <boolean>,
    waitForLeaders: <boolean>
    timeout: <Number>,
    topics: <ITopicConfig[]>,
})
```

**To Reproduce**
N/A

**Additional context**
This is a documentation error so no reproductions are necessary.

**Comment by SeanBarry** [comment]
I'm keen to contribute to this project as we use Kafka extensively at my company and I'm currently using this library on a daily basis.

I've created a branch locally and have made this (very small) change. I don't have access rights to push the branch, is the best thing to do to create a fork for now?

**Comment by ankon** [comment]
> I've created a branch locally and have made this (very small) change. I don't have access rights to push the branch, is the best thing to do to create a fork for now?

In fact this is the _proper_ thing to do as well. You fork the project, push your changes to a branch on your fork, and then create a pull request. :)

**Comment by SeanBarry** [comment]
Thanks. I've followed that process and created a PR here: https://github.com/tulios/kafkajs/pull/845

**Comment by SeanBarry** [comment]
Thanks, I've created a tiny PR to fix this: https://github.com/tulios/kafkajs/pull/846

**Comment by Nevon** [comment]
Just for background, there are probably more cases of this in the documentation, as the documentation was written before we even had Typescript type definitions, so the types we reference in the documentation were just made up at that time. Now we should try to use the actual type names from the Typescript types, as you did.

**Comment by SeanBarry** [comment]
Good to know. I'm happy to see if I can find more examples - this just happened to be one I ran in to today while actually using the library.

Thanks for merging 👍
