### ISSUE TITLE
OAuthbearer Support

### ISSUE THREAD

**Issue by ajdanaher** [tulios/kafkajs#848]
Hi Everyone, 
Followed different threads on the topic and have a question. if you could help me?
I see that this feature (oauthbearer mechanism) available now in kafkajs in particular in master. But it is not in tagged branch yet. is this correct? 

Trying to use this wonderful library (kafkajs@1.12.0) in my application but failing if I do oauthbearer. Later in debugging I notice that the client checks for the mechanism and oauthbearer is not in the supported one. Which is already listed on kafkajs documentation at https://kafka.js.org/docs/next/configuration#a-name-sasl-a-sasl. No Issue.

when do we think this would be available for download?   Not sure where and how to use this example - https://kafka.js.org/docs/next/configuration#oauthbearer-example

Thanks in advance..

**Comment by ankon** [comment]
The feature should be available in the pre-release versions, which can you use through npm as well: https://kafka.js.org/docs/pre-releases

The documentation is versioned:
- master version documentation: https://kafka.js.org/docs/next/getting-started
- documentation for the stable version: https://kafka.js.org/docs/getting-started

**Comment by ajdanaher** [comment]
ok thanks.   i will use it from master until it is released.

**Comment by ajdanaher** [comment]
Today I tested this feature in my development env. passing token.  Good news is I could post the message on Kakfa. Tested it working from Producer side and will be testing Producer/consumer more. But I don't expect any major issue as it is connection related changes.   Thanks to the team. 

Was wondering when do we see this changes as next release?  any estimate would be appreciated.

**Comment by Nevon** [comment]
The plan is to release 1.13.0 during this month. Possibly during this week.

**Comment by ajdanaher** [comment]
Thanks.   👍
