### ISSUE TITLE
Infinite retry loop if kafka broker goes down

### ISSUE THREAD

**Issue by wickedest** [tulios/kafkajs#852]
**Describe the bug**
Once a connection is established, if the kafka broker goes down, there is no way to programmatically stop the consumer without performing a `process.exit`.

**To Reproduce**
1. Run a consumer as per the [example](https://kafka.js.org/docs/consumer-example)
2. Stop the broker
3. The consumer goes into an infinite loop of retries

**Expected behavior**
When there is a valid connection stop/disconnect work as expected.  However, if the broker disconnects, it seems to enter some kind of crash/error loop that is impossible to get out of without using `process.exit`.  I would expect that if I listen for the CRASH event, that I would have some kind of programmatic control to either a) limit the number of retries; b) stop the retry loop.

**Observed behavior**
The consumer goes into an invite loop of retries (simplified log):
```
consumer has stopped, disconnecting
Restarting the consumer in 664ms
Connecting broker
Connection error: connect ECONNREFUSED
Connecting broker
Connection error: connect ECONNREFUSED
etc.
Crash: KafkaJSNumberOfRetriesExceeded: Connection error: connect ECONNREFUSED
Stopped
consumer has stopped, disconnecting
Restarting the consumer in 10244ms
```

**Environment:**
 - OS: ubuntu 18.04
 - KafkaJS version 1.12.0
 - Kafka version 2.13-2.6.0
 - NodeJS version 12.16.3

**Additional context**

**Comment by goriunov** [comment]
From what i remember in next version of kafkajs there will be added `restartOnFailure` callback in retry where you can just return `false` or `true` to let kafkajs know if it needs to retry. You can try that out in beta version and see if that works for you.  IMHO beta version is quite stable (in some cases even better than master), we are actually running our production on kafkjs a beta version.

**Comment by wickedest** [comment]
Thanks @goriunov - that worked perfectly.
