### ISSUE TITLE
Question about MEMBER_ID_REQUIRED error

### ISSUE THREAD

**Issue by wickedest** [tulios/kafkajs#856]
**Describe the bug**
It's a question actually.  I'm developing a client using kafkajs against a local instance of kafka.  Every time the client starts and attempts to join a consumer group, it errors: `The group member needs to have a valid member id before actually entering a consumer group`.  I've done a fair bit of searching and I don't see to many references to the error (except that it's an [MEMBER_ID_REQUIRED](https://kafka.apache.org/23/protocol) protocol error), so I'm assuming I'm doing something wrong.

**To Reproduce**
Use the [consumer-example](https://kafka.js.org/docs/consumer-example).

**Expected behavior**
I am not sure if this is normal or not, but seeing these error messages is concerning.

**Observed behavior**
```
{"level":"INFO","timestamp":"2020-09-04T10:03:36.444Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"my-group"}
{"level":"ERROR","timestamp":"2020-09-04T10:03:36.457Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 4)","broker":"ubuntu:9092","clientId":"myclient","error":"The group member needs to have a valid member id before actually entering a consumer group","correlationId":1,"size":69}
{"level":"INFO","timestamp":"2020-09-04T10:03:36.470Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"my-group","memberId":"myclient-237c9b4a-c394-4a5a-b395-2d6f4a07be53","leaderId":"myclient-237c9b4a-c394-4a5a-b395-2d6f4a07be53","isLeader":true,"memberAssignment":{"quickstart-events":[0]},"groupProtocol":"RoundRobinAssigner","duration":24}
```

**Environment:**
 - OS: ubuntu 18.04
 - KafkaJS version 1.13.0-beta.65
 - Kafka version 2.13-2.6.0
 - NodeJS version 12.16.3

**Additional context**

**Comment by tulios** [comment]
Hi @wickedest , this error is from the join group v4 protocol, you are not doing anything wrong, the error is expected. We will probably not bubble up this error once we release 1.13 final, we just started working on the release.
