### ISSUE TITLE
Type SaslOption does not support mechanism: 'oauthbearer' and does not accept oauthBearerProvider function.

### ISSUE THREAD

**Issue by giubueno** [tulios/kafkajs#876]
**Describe the bug**
I am trying to use the new Oauthbearer in my Typescript project and I am receiving an error during compilation saying that SaslOption does not support 'oauthbearer' and the token generator function oauthBearerProvider cannot be set.

**To Reproduce**

```typescript
interface KafkaToken { value: string }

async function oauthBearerProvider (): Promise<KafkaToken> {
  const url = `${KAFKA_TOKEN_HOST}${KAFKA_TOKEN_PATH}`
  const form = new URLSearchParams()
  form.append('client_id', KAFKA_CLIENT_ID)
  form.append('username', KAFKA_CLIENT_ID)
  form.append('client_secret', KAFKA_SECRET)
  form.append('grant_type', KAFKA_GRANT_TYPE)

  const response = await fetch(
    url,
    {
      method: 'POST',
      headers: {
        Accept: '*/*',
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: form
    }
  )

  if (!response.ok) {
    throw new Error('Could not get a token!')
  }

  const json: Token = await response.json()

  return {
    value: json.access_token
  }
}

const config: = {
    clientId: KAFKA_CLIENT_ID,
    groupId: KAFKA_CONSUMER_GROUP,
    topic: KAFKA_TOPIC,
    brokers: [KAFKA_HOSTS],
    ssl: true,
    sasl: {
      mechanism: 'oauthbearer',
      oauthBearerProvider
    }
  }
```

**Expected behavior**
I am able to specify the oauthbearer token provider and to use the corresponding mechanism.

**Observed behavior**
I noticed that the interface [SASLOptions](https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L42) does not accept the value oauthbearer because the type [SASLMechanism](https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L40) does not have this value.

**Environment:**
 - OS: Mac OS 10.15.6
 - KafkaJS version 1.13.0
 - Kafka version [e.g. 2.3.1]
 - NodeJS version 10.19.0

**Additional context**

**Comment by tulios** [comment]
Thanks for reporting @giubueno, this should be simple to fix. I can get this done tomorrow or if you prefer you can send a PR.

**Comment by giubueno** [comment]
> Thanks for reporting @giubueno, this should be simple to fix. I can get this done tomorrow or if you prefer you can send a PR.

Or you can tell me how good this [PR](https://github.com/tulios/kafkajs/pull/877) is and I can take care of it.

**Comment by tulios** [comment]
@giubueno pre-release version `1.14.0-beta.7` is out with the fix.
Thanks for helping.
