### ISSUE TITLE
Improve TS typing of error class

### ISSUE THREAD

**Issue by lafeuil** [tulios/kafkajs#886]
The TS typing does not describe the properties of error classes. 

For example with the `KafkaJSProtocolError` class. This error class have two properties : `type` and `code`. This two properties are set in the constructor.

```javascript
class KafkaJSProtocolError extends KafkaJSError {
  constructor(e) {
    super(e, { retriable: e.retriable })
    this.type = e.type
    this.code = e.code
    this.name = 'KafkaJSProtocolError'
  }
}
```

But, in the TS typing, this properties does not appear :

```typescript
export class KafkaJSProtocolError extends KafkaJSError {
  constructor(e: Error | string)
}
```

I think this can be fix by declaring readonly property in KafkaJSProtocolError : 

```typescript
export class KafkaJSProtocolError extends KafkaJSError {
  readonly code: number;
  readonly type: string;
  constructor(e: Error | string)
} 
```

**Comment by Nevon** [comment]
Fixed by #900
