### ISSUE TITLE
Not a bug but a query - what is recommended: singleton instance of producer or create specific instance for each message producing action

### ISSUE THREAD

**Issue by sureshballa** [tulios/kafkajs#894]
Not a bug but a query - what is recommended: singleton instance of producer or create specific instance for each message producing action.

The doc here talks about initiating the producer instance but no recommendation as to should we create specific instance for each message or singleton is good enough (for each process app wide)
https://kafka.js.org/docs/producing

**Comment by Nevon** [comment]
Reusing the same producer is far preferable, as it avoids creating new connections, authenticating etc.
