### ISSUE TITLE
cant get kafkajs to read messages concurrently

### ISSUE THREAD

**Issue by yuriabaev** [tulios/kafkajs#906]
I'm trying to make kafkajs read messages concurrently,  
I'm running my topic with 2 partitions:
```
Topic:Tokens_Activity_Sandbox	PartitionCount:2	ReplicationFactor:1	Configs:segment.bytes=1073741824
	Topic: Tokens_Activity_Sandbox	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: Tokens_Activity_Sandbox	Partition: 1	Leader: 1001	Replicas: 1001	Isr: 1001
```
and made a little test client.  
 when sending 2 paralell `sleep` commands to the topic(1 for each partition), the client reads them one by one, sequencially, instead of parallely (once it goes to sleep).  

what am i doing wrong?
```javascript
const topic = 'Tokens_Activity_Sandbox';
const { Kafka } = require('kafkajs');
const util = require('util');
const sleep = util.promisify(setTimeout);
const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['192.168.0.135:9092'],
});

const groupId = 'test-group2333';
const admin = kafka.admin({
  retry: { retries: 0 },
});
const producer = kafka.producer({ allowAutoTopicCreation: false });

const consumer = kafka.consumer({
  allowAutoTopicCreation: false,
  groupId: groupId,
  retry: { retries: 1, restartOnFailure: async () => false },
});

if (process.env.CREATE === 'true') {
  (async () => {
    await admin.createTopics({
      topics: [
        {
          topic: topic,
          numPartitions: 2, // default: 1
        },
      ],
    });
  })();
}



process.on('SIGINT', async () => {
  // eslint-disable-next-line no-undef
  await consumer.disconnect();
});


const eachMessageF = async ({ topic, partition, message }) => {
  console.log('incoming message', {
    topic,
    partition,
    offset: message.offset,
    value: message.value.toString(),
  });

  if (message.value.toString() === 'sleep') {
    console.log('going to sleep');
    await sleep(5000);
    console.log('woke up from sleep');
  }
  console.log(`done processing ${message.value.toString()}`);
};

const run = async () => {
  // admin
  await admin.connect();
  await producer.connect();
  // Consuming
  await consumer.connect();
  await consumer.subscribe({ topic: topic, fromBeginning: false });
  await consumer
    .run({
      partitionsConsumedConcurrently: 2,
      eachMessage: async ({ topic, partition, message }) => {
        try {
          await eachMessageF({ topic, partition, message });
        } catch (e) {
          console.log('caught th error <3');
        }
      },
    })
    .catch((err) => {
      console.log('caught err in catch of consumer.run');
      throw err;
    });
};

run()

```

that would be the output of the running
```
incoming message {
  topic: 'Tokens_Activity_Sandbox',
  partition: 1,
  offset: '4',
  value: 'sleep'
}
going to sleep
woke up from sleep
done processing sleep
incoming message {
  topic: 'Tokens_Activity_Sandbox',
  partition: 0,
  offset: '6',
  value: 'sleep'
}
going to sleep
woke up from sleep
done processing sleep
```

**Comment by tulios** [comment]
Hi @yuriabaev, which version of kafkajs are you using?

**Comment by yuriabaev** [comment]
"kafkajs": "^1.12.0",

**Comment by Nevon** [comment]
I can't reproduce this in `master`:

```sh
info:  ┏ [Consumer] Starting
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-10-05T16:55:16.432Z",
info:  ┃ [2]   "logger": "kafkajs",
info:  ┃ [3]   "groupId": "test-group-906-1"
info:  ┗ [4] }
info:  ┏ [Runner] Consumer has joined the group
info:  ┃ [ 0] {
info:  ┃ [ 1]   "timestamp": "2020-10-05T16:55:16.703Z",
info:  ┃ [ 2]   "logger": "kafkajs",
info:  ┃ [ 3]   "groupId": "test-group-906-1",
info:  ┃ [ 4]   "memberId": "example-consumer-934f374e-b93a-42c6-af5d-80482b54ff36",
info:  ┃ [ 5]   "leaderId": "example-consumer-934f374e-b93a-42c6-af5d-80482b54ff36",
info:  ┃ [ 6]   "isLeader": true,
info:  ┃ [ 7]   "memberAssignment": {
info:  ┃ [ 8]     "topic-test-906-4": [
info:  ┃ [ 9]       0,
info:  ┃ [10]       1
info:  ┃ [11]     ]
info:  ┃ [12]   },
info:  ┃ [13]   "groupProtocol": "RoundRobinAssigner",
info:  ┃ [14]   "duration": 267
info:  ┗ [15] }
info:  ┏ Incoming message
info:  ┃ [ 0] {
info:  ┃ [ 1]   "timestamp": "1601916887096",
info:  ┃ [ 2]   "logger": "kafkajs",
info:  ┃ [ 3]   "topic": "topic-test-906-4",
info:  ┃ [ 4]   "partition": 1,
info:  ┃ [ 5]   "offset": "0",
info:  ┃ [ 6]   "headers": {
info:  ┃ [ 7]     "correlation-id": "2-1601916886681"
info:  ┃ [ 8]   },
info:  ┃ [ 9]   "key": "key-2",
info:  ┃ [10]   "value": "value-2-2020-10-05T16:54:46.681Z",
info:  ┃ [11]   "msgNumber": 1
info:  ┗ [12] }
info:  ┏ Now sleeping for 5000ms
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-10-05T16:55:16.791Z",
info:  ┃ [2]   "logger": "kafkajs"
info:  ┗ [3] }
info:  ┏ Incoming message
info:  ┃ [ 0] {
info:  ┃ [ 1]   "timestamp": "1601916886668",
info:  ┃ [ 2]   "logger": "kafkajs",
info:  ┃ [ 3]   "topic": "topic-test-906-4",
info:  ┃ [ 4]   "partition": 0,
info:  ┃ [ 5]   "offset": "0",
info:  ┃ [ 6]   "headers": {
info:  ┃ [ 7]     "correlation-id": "1-1601916886620"
info:  ┃ [ 8]   },
info:  ┃ [ 9]   "key": "key-1",
info:  ┃ [10]   "value": "value-1-2020-10-05T16:54:46.620Z",
info:  ┃ [11]   "msgNumber": 2
info:  ┗ [12] }
info:  ┏ Now sleeping for 5000ms
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-10-05T16:55:16.792Z",
info:  ┃ [2]   "logger": "kafkajs"
info:  ┗ [3] }
info:  ┏ Finished sleeping
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-10-05T16:55:21.792Z",
info:  ┃ [2]   "logger": "kafkajs"
info:  ┗ [3] }
info:  ┏ Finished sleeping
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-10-05T16:55:21.803Z",
info:  ┃ [2]   "logger": "kafkajs"
info:  ┗ [3] }
```

Nor can I reproduce it in 1.12.0:

```sh
{"level":"INFO","timestamp":"2020-10-05T16:57:11.055Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group-906-2"}
{"level":"INFO","timestamp":"2020-10-05T16:57:11.192Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"test-group-906-2","memberId":"example-consumer-d94ebc3c-e111-4a15-b980-843855303cc0","leaderId":"example-consumer-d94ebc3c-e111-4a15-b980-843855303cc0","isLeader":true,"memberAssignment":{"topic-test-906-4":[0,1]},"groupProtocol":"RoundRobinAssigner","duration":133}
{"level":"INFO","timestamp":"1601916886668","logger":"kafkajs","message":"Incoming message","topic":"topic-test-906-4","partition":0,"offset":"0","headers":{"correlation-id":"1-1601916886620"},"key":"key-1","value":"value-1-2020-10-05T16:54:46.620Z","msgNumber":1}
{"level":"INFO","timestamp":"2020-10-05T16:57:11.228Z","logger":"kafkajs","message":"Now sleeping for 5000ms"}
{"level":"INFO","timestamp":"1601916887096","logger":"kafkajs","message":"Incoming message","topic":"topic-test-906-4","partition":1,"offset":"0","headers":{"correlation-id":"2-1601916886681"},"key":"key-2","value":"value-2-2020-10-05T16:54:46.681Z","msgNumber":2}
{"level":"INFO","timestamp":"2020-10-05T16:57:11.228Z","logger":"kafkajs","message":"Now sleeping for 5000ms"}
{"level":"INFO","timestamp":"2020-10-05T16:57:16.228Z","logger":"kafkajs","message":"Finished sleeping"}
{"level":"INFO","timestamp":"2020-10-05T16:57:16.232Z","logger":"kafkajs","message":"Finished sleeping"}
```

**Comment by yuriabaev** [comment]
@Nevon can you plz share your code?

**Comment by Nevon** [comment]
It's nothing special at all. I'm just using the code from `examples/consumer.js` and adding `partitionsConsumedConcurrently: 2` and a sleep in the `eachMessage`.

```js
const fs = require('fs')
const ip = require('ip')

const sleep = require('../src/utils/sleep')
const { Kafka, logLevel } = require('../index')

const host = process.env.HOST_IP || ip.address()

const kafka = new Kafka({
  logLevel: logLevel.INFO,
  brokers: [`${host}:9094`, `${host}:9097`, `${host}:9100`],
  clientId: 'example-consumer',
  ssl: {
    servername: 'localhost',
    rejectUnauthorized: false,
    ca: [fs.readFileSync('./testHelpers/certs/cert-signed', 'utf-8')],
  },
  sasl: {
    mechanism: 'plain',
    username: 'test',
    password: 'testtest',
  },
})

const topic = 'topic-test-906-4'
const consumer = kafka.consumer({ groupId: 'test-group-906-2' })

let msgNumber = 0
const run = async () => {
  await consumer.connect()
  await consumer.subscribe({ topic, fromBeginning: true })
  await consumer.run({
    partitionsConsumedConcurrently: 2,
    eachMessage: async ({ topic, partition, message }) => {
      msgNumber++
      kafka.logger().info('Incoming message', {
        topic,
        partition,
        offset: message.offset,
        timestamp: message.timestamp,
        headers: Object.keys(message.headers).reduce(
          (headers, key) => ({
            ...headers,
            [key]: message.headers[key].toString(),
          }),
          {}
        ),
        key: message.key.toString(),
        value: message.value.toString(),
        msgNumber,
      })

      kafka.logger().info('Now sleeping for 5000ms')
      await sleep(5000)
      kafka.logger().info('Finished sleeping')
    },
  })
}

run().catch(e => console.error(`[example/consumer] ${e.message}`, e))

const errorTypes = ['unhandledRejection', 'uncaughtException']
const signalTraps = ['SIGTERM', 'SIGINT', 'SIGUSR2']

errorTypes.map(type => {
  process.on(type, async e => {
    try {
      console.log(`process.on ${type}`)
      console.error(e)
      await consumer.disconnect()
      process.exit(0)
    } catch (_) {
      process.exit(1)
    }
  })
})

signalTraps.map(type => {
  process.once(type, async () => {
    try {
      await consumer.disconnect()
    } finally {
      process.kill(process.pid, type)
    }
  })
})
```

On the producer side, all I did was create a topic with 2 partitions and publish two messages with the partitions hardcoded to be 0 and 1 respectively.

**Comment by yuriabaev** [comment]
weird, that is almost the same code as mine..
is it always working for you?

in my case out of 40 runs I've seen it running correctly only once

im sending message using kafkajs profucer :
```javascript
  await producer.send({
    topic: topic1,
    messages: [
      { value: 'sleep', partition: 0 },
      { value: 'sleep', partition: 1 },
    ],
  });
```

what can be the reason?

**Comment by Nevon** [comment]
Yes, it works consistently for me. I also tried running a single-node cluster, as it seems you are, to see if maybe this occurs when both messages are coming in the same broker fetch response, but I had the exact same result with a single-broker cluster as well.

Could you try running with the following environment variables: `KAFKAJS_LOG_LEVEL=debug KAFKAJS_DEBUG_PROTOCOL_BUFFERS=1 KAFKAJS_DEBUG_EXTENDED_PROTOCOL_BUFFERS=1`. The only thing I can think of is that maybe you're only getting a single partition back in your fetch response, which would mean that you would process the whole batch (i.e. 1 message), make a new request and receive another batch with the second message. This could happen if you configure `minBytes`, `maxBytes` and/or `maxWaitTimeInMs` incorrectly.

**Comment by yuriabaev** [comment]
thanks for your help Nevon,


1.you were right, when sending 4 messages:
```
  await producer.send({
    topic: topic1,
    messages: [
      { value: 'sleep1', partition: 1 },
      { value: 'sleep2', partition: 0 },
      { value: 'sleep3', partition: 1 },
      { value: 'sleep4', partition: 0 },
    ],
  });
```
it does read only from partition 1 two messages (sleep1,sleep3)
an then it reads messages from partition 0(sleep2,sleep4)


2.setting   `maxWaitTimeInMs` to 500 didn't help,
also, I don't understand why you think changing minBytes from 1? as  i send the value "sleep" which is larger than 1 byte
and hence, by docs, maxWaitTimeInMs shouldn't take place.

3.what I did notice is that **the feature works for me only** when I play with the order of execution between consumer and producer:

when I start the consumer and it waits for messages, and the execute the producer to send the above messages, the feature doesn't work for me

**but**,
when I execute the producer first and then start the consumer, it reads  the messages concurrently.(!!)

any idea why?
I can share my source codes,
and share the logs of running with the environment variables you suggested.

thanks again

**Comment by Nevon** [comment]
I think I understand what's happening now, and it's working exactly as intended if the consumer is configured the way I think it is.

> also, I don't understand why you think changing minBytes from 1? as i send the value "sleep" which is larger than 1 byte
and hence, by docs, maxWaitTimeInMs shouldn't take place.

Basically:

* `minBytes` = I want at least these many bytes
* `maxBytes` = I want at most this many bytes
* `maxBytesPerPartition` = I want at most this many bytes per partition
* `maxWaitTimeInMs` = If you don't have `minBytes` for me yet, wait up to `maxWaitTimeInMs` to see if we get more data, otherwise send me whatever you have.

If you have `minBytes` 1, it means that as soon as there's any data in any of the partitions that you're writing to, the broker will respond with that data. This means that as soon as a message has been written into the first partition, the broker responds to the fetch request. It's not going to wait for the second message to be written into the second partition, because you told it that as soon as there's at least 1 byte of data, you want it to respond with that data.

If you change `minBytes` back to the default value, you will see that you will start to get both messages in the same response, because the broker will wait up to `maxWaitTimeInMs` to try to accumulate at least 1mb of data. After `maxWaitTimeInMs` it will give up and send you what it has (your two messages).

> when I execute the producer first and then start the consumer, it reads the messages concurrently.(!!)

Makes perfect sense. If you have already written the data into the partitions and then start the consumer, the consumer is going to get up to `Math.min(maxBytes, maxBytesPerPartition * numPartitions)` bytes back, so in your case you will get your 2 messages back in the same response.

**Comment by yuriabaev** [comment]
you are saying that the default  is 1mb, but in the docs i see that the default is **1 Byte**

**Comment by Nevon** [comment]
Oh yes, my mistake, 1 byte is the default. The point stands, however. If you want to allocate more than that before receiving a response, you can set it to a higher value.

**Comment by yuriabaev** [comment]
Thanks for your response Nevon,

That makes me wonder:
How it works for you correctly if you used the default value **(minByte=1Byte**) just like me?

As I see it, since you had the default value (minByte=1Byte) just like me, your behavior should have been similar to mine,  i.e **getting 1 message at a time**, because each message is larger than 1Byte. 

And yet, you say you were **getting 2 messages at a time** even though you had minByte=1Byte?

What am i missing?

**Comment by Nevon** [comment]
That I'm not sure of. The behavior itself makes sense to me, but not the fact that we're not seeing the same behavior. If you run exactly the example I posted (just connecting to your Kafka cluster), do you still have the same behavior? Perhaps it's a simple matter of different Kafka versions and/or platform differences. I'm running the cluster using the docker-compose file [docker-compose.2_4.yml](https://github.com/tulios/kafkajs/blob/master/docker-compose.2_4.yml).

**Comment by vicmerlis** [comment]
@yuriabaev 
We had the same issue. `maxWaitTimeInMs = 100` solved it
