### ISSUE TITLE
Consumer keep crashing on: Crash: KafkaJSNumberOfRetriesExceeded: Converting circular structure to JSON

### ISSUE THREAD

**Issue by chengB12** [tulios/kafkajs#915]
Version: 1.14.0

error:
Crash: KafkaJSNumberOfRetriesExceeded: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle

And it causes consumer restart, and encounter same error again, causing message stalls

We start to see such error right after we upgrade kafkajs from 1.12.0 to 1.14.0

**Comment by tulios** [comment]
Hi @chengB12 can you provide a stack trace? I would also guess that this is on userland code, kafkajs doesn't perform JSON operations, so it's very unlikely that this is happening inside the client. The fact that it happened on the 1.14 update might be a coincidence, but I will watch it for a stack trace.

**Comment by tulios** [comment]
@chengB12 feel free to re-open the issue if you have more information.

**Comment by chengB12** [comment]
The problem is kafkajs itself never print out stack trace, how can I know stack trace if kafkajs not give me?

when hook on crash event, I got this as event body: {"id":213,"type":"consumer.crash","timestamp":1602516967554,"payload":{"error":{"name":"KafkaJSNumberOfRetriesExceeded","retriable":false,"originalError":{},"retryCount":0,"retryTime":301},"groupId":---"}}

**Comment by chengB12** [comment]
I also can't reopen issue, since I don't have permission

**Comment by chengB12** [comment]
confirmed it is not 1.14 update issue, we had same issue with 1.12
