### ISSUE TITLE
Crash doesn't include stacktrace

### ISSUE THREAD

**Issue by chengB12** [tulios/kafkajs#921]
**Describe the bug**
If eachBatch or eachMessage call back throw unhandled error, error log doesn't include stack trace

**To Reproduce**
Please provide either a link to a:

```typescript
  consumer.eachMessage = () => Promise.reject(new Error('Unhandled Error'))
```

**Expected behavior**
the error log shall include stack track of error thrown

**Observed behavior**
it just display:
```
2020-10-15T00:16:11.290Z - warn: Crash: KafkaJSNumberOfRetriesExceeded: Unhandled Error
```

without stack trace, it is very hard to debug where goes wrong
**Environment:**
 - OS: [windows 10]
 - KafkaJS version [e.g. 1.14.0]
 - Kafka version [e.g. 2.4.0]
 - NodeJS version [e.g. 12.18.0]

**Additional context**

**Comment by Nevon** [comment]
I think you are likely just not configuring your logger correctly. We do retain the stack through retries and it does get logged with the stack on crash:

https://github.com/tulios/kafkajs/blob/a79fc9e45f6c8cd2695e23cfb7689bb824fb86a0/src/consumer/index.js#L247-L252

Using the example consumer in `examples/consumer.js`:

```
error: ┏ [Consumer] Crash: KafkaJSNumberOfRetriesExceeded: 💣
error: ┃ [0] {
error: ┃ [1]   "timestamp": "2020-10-16T08:25:48.060Z",
error: ┃ [2]   "logger": "kafkajs",
error: ┃ [3]   "groupId": "test-group",
error: ┃ [4]   "retryCount": 5,
error: ┃ [5]   "stack": "KafkaJSNonRetriableError\n  Caused by: Error: 💣\n    at Runner.eachMessage (/Users/tommybrunn/workspace/kafkajs/examples/consumer.js:38:13)\n    at Runner.processEachMessage (/Users/tommybrunn/workspace/kafkajs/src/consumer/runner.js:185:20)\n    at onBatch (/Users/tommybrunn/workspace/kafkajs/src/consumer/runner.js:321:20)\n    at /Users/tommybrunn/workspace/kafkajs/src/consumer/runner.js:373:21\n    at invoke (/Users/tommybrunn/workspace/kafkajs/src/utils/concurrency.js:38:5)\n    at push (/Users/tommybrunn/workspace/kafkajs/src/utils/concurrency.js:51:7)\n    at /Users/tommybrunn/workspace/kafkajs/src/utils/concurrency.js:60:53\n    at new Promise (<anonymous>)\n    at /Users/tommybrunn/workspace/kafkajs/src/utils/concurrency.js:60:20\n    at /Users/tommybrunn/workspace/kafkajs/src/consumer/runner.js:363:11"
error: ┗ [6] }
```
