### ISSUE TITLE
Connection error: write after end

### ISSUE THREAD

**Issue by ismailnagib** [tulios/kafkajs#928]
**Describe the bug**

We recently upgraded from `1.12.0` to `1.14.0`. After the update, we noticed that a new error is logged in our production server:

Message:
```
Connection error: write after end
```

Stack:
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
   at writeAfterEnd (_stream_writable.js:248:12)
   at Socket.Writable.write (_stream_writable.js:296:5)
   at Object.sendRequest (/app/node_modules/kafkajs/src/network/connection.js:312:27)
   at SocketRequest.send [as sendRequest] (/app/node_modules/kafkajs/src/network/requestQueue/index.js:135:23)
   at SocketRequest.send (/app/node_modules/kafkajs/src/network/requestQueue/socketRequest.js:85:10)
   at RequestQueue.sendSocketRequest (/app/node_modules/kafkajs/src/network/requestQueue/index.js:164:19)
   at RequestQueue.push (/app/node_modules/kafkajs/src/network/requestQueue/index.js:144:12)
   at Promise (/app/node_modules/kafkajs/src/network/connection.js:307:29)
   at new Promise (<anonymous>)
   at sendRequest (/app/node_modules/kafkajs/src/network/connection.js:302:14)
```

We haven't really changed our implementation recently. Our current implementation is to call `producer.connect()` every time before we would call `producer.send()` and then call `producer.disconnect()` afterwards.

**Environment**

OS: Alpine 3.11.6
KafkaJS version: 1.14.0
Kafka version: 2.2.1
NodeJS version: 10.22.1

**Comment by ismailnagib** [comment]
Note: this has only happened once since we upgraded 4 days ago. I created the issue just in case there are maybe some implementation errors on our side that had been made apparent by the recent changes. Thank you.

**Comment by Nevon** [comment]
> Our current implementation is to call producer.connect() every time before we would call producer.send() and then call producer.disconnect() afterwards.

Is there a reason you are connecting and disconnecting all the time, rather than just connecting at startup, re-using the producer throughout the lifetime of your application, and then disconnecting at shutdown?

1.14.0 added request queue draining on disconnect. Basically, if you have requests that are waiting to be sent, `disconnect` will wait for those requests to be done before resolving. In <1.4.0 those requests would simply be lost. It's possible that this is somehow related.

**Comment by ismailnagib** [comment]
> Is there a reason you are connecting and disconnecting all the time, rather than just connecting at startup, re-using the producer throughout the lifetime of your application, and then disconnecting at shutdown?

At first, we didn't produce that many messages so it seemed like we don't need to keep the connection. But now that we've produced more messages, we can't find any reason to do that anymore so we'll fix our implementation. Thank you.

> 1.14.0 added request queue draining on disconnect. Basically, if you have requests that are waiting to be sent, disconnect will wait for those requests to be done before resolving. In <1.4.0 those requests would simply be lost. It's possible that this is somehow related.

Is there anything that we could do on our side to avoid the error from happening?

Anyway, thank you so much for this amazing package & for the response @Nevon.

**Comment by Nevon** [comment]
> Is there anything that we could do on our side to avoid the error from happening?

This error shouldn't happen in the first place, so I'm not sure what's going on. If you can manage to reliably reproduce the issue, that would be very useful.

Just make sure that you `await` `producer.connect` and `producer.disconnect`.

**Comment by ismailnagib** [comment]
After we fix our implementation, this error doesn't show up on our logs anymore. Thank you for the responses, but I'm sorry that I can't manage to reliably reproduce the issue right now so I'll close the issue after this.

> Just make sure that you await producer.connect and producer.disconnect.

Sure, already done that, thank you.
