### ISSUE TITLE
Update server, consumer and producer properties on Kafka Deployed in Kubernetes

### ISSUE THREAD

**Issue by kks010** [tulios/kafkajs#948]
Hi,

I am using your Kafka library and recently I have been facing issues with **recordtoolargeexception**, I found out the default limit is set to 1MB and it can be updated by updating the server, consumer, and producer properties of Kafka.

Here is the link for reference - https://stackoverflow.com/questions/55181375/org-apache-kafka-common-errors-recordtoolargeexception-the-request-included-a-m

But, I am unable to find it how can I update these properties as I have deployed Kafka in Azure Kubernetes using custom Helm charts.

I am stuck here, Please help if possible.
Thanks in advance!

**Comment by Nevon** [comment]
On the client side, you can configure the properties `maxBytes` and `maxBytesPerPartition`. [As the documentation says](https://kafka.js.org/docs/consuming#options):

> The maximum amount of data per-partition the server will return. This size must be at least as large as the maximum message size the server allows or else it is possible for the producer to send messages larger than the consumer can fetch. If that happens, the consumer can get stuck trying to fetch a large message on a certain partition

As for how to configure Kafka itself, that's outside the scope of this project. For support for running Kafka on Kubernetes, maybe you can reach out to the #kubernetes channel on Confluent's Slack community.

**Comment by kks010** [comment]
Hi @Nevon . Thanks for replying. 

So, I update maxBytes and maxBytesPerPartition then will I be able to reply with a size more than 1 MB to the request?

**Comment by Nevon** [comment]
That will make the client request up to that many bytes. Whether the broker will do that or not may depend on broker settings - I'm not sure. You'll have to try it out and consult the Kafka documentation if it doesn't work. From the client side, that is all you need to do.
