### ISSUE TITLE
Specify batch size for producer

### ISSUE THREAD

**Issue by vladgovor77771** [tulios/kafkajs#954]
Hello, I'm new to Kafkajs (and kafka). Here is my code:
```js
const producer = kafka.producer();
await producer.connect();
const items = await getItems(); // getting somehow 5k messages to produce 
await producer.send({
  topic: "items",
  messages: items.map(c => ({ value: JSON.stringify(c) })),
});
```
This will produce one big batch (sometimes it splits in two, don't know why).

I need to read concurrently from one group by 100 items in batch.
What should I do to send by 100 messages in batch?

What should I do if I need to read by 100 from one group and by 50 from another (also concurrently)?

**Comment by Nevon** [comment]
That's not how Kafka works. There is no connection between how you produce (how big batches etc.). and how you consume. You can produce each message individually or as a batch of 1000 messages, and you can later consume those however you want. I would suggest that you read up a bit on how Kafka works, and I think this will become a lot clearer to you.

A topic is made up of one or more partitions. Those partitions are spread across one or more brokers. When you produce messages, those messages will be assigned across the partitions. This means that if you produce 100 messages, those may all end up on the same partition or be spread across multiple partitions depending on the `key` you specify. In your example, you are not providing a key, so the messages will be spread out randomly across the available partitions.

On the consumer side, the partitions will be assigned to different instances of your consumer in the consumer group. If you have 1 instance, it will be assigned all partitions of that topic. If you have 2 instances, they will by default receive half the partitions each, and so on. When the consumer consumes messages, it asks for a number of bytes (decided by the configuration properties `maxBytes`, `minBytes` and `maxBytesPerPartition`), which will result in it receiving however many messages fit into the requested criteria.

I'm going to close this issue as it's unrelated to KafkaJS. We don't really document Kafka itself, as that's out of scope for us. My recommendation is that you read some introductory material to Kafka as you are exploring KafkaJS.
