### ISSUE TITLE
document enforceRequestTimeout

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs#955]
A thing I found very confusing and took some time to debug out.

In documentation there is **requestTimeout: 30000,**
https://kafka.js.org/docs/configuration#request-timeout

But it is not applied as there is another undocumented configuration parameter

**"enforceRequestTimeout"** which is false by default. 

So by default without even checking timeouts setting requestTimeout param has no effect at all :-)

Why not turn on timeout checks by default? Or at least mention in docs that there is another param to set

**Comment by tulios** [comment]
That's a fair point, we introduced this property some time ago because we had performance issues creating individual timers, but this was already solved. We should document the property and plan to make the default `true` in a major version bump.

**Comment by goriunovphl** [comment]
FYI we have been running our production system for quite a while with this flag on (after specified PR) and have not had any issues with performance.
