### ISSUE TITLE
Easy 2 Fix: KafkaJS default ClientID should be a UUID to enforce uniqueness

### ISSUE THREAD

**Issue by yarncraft** [tulios/kafkajs#968]
**Describe the bug**
<img width="1063" alt="Screencapture" src="https://user-images.githubusercontent.com/15328198/99879606-58729280-2c0e-11eb-959b-d7cb3ffddc1d.png">
_Confluent dataflow throws a warning for non-unique ClientIDs of the ConsumerGroup_

**Expected behavior**
The expected behavior would be that in the constructor of the network connection class, _a (unique) UUID_ is assigned to the clientID as a _default value_. This automatically enforces the uniqueness constraint.

**Observed behavior**
At the moment _'kafkajs'_ is the default clientID
https://github.com/tulios/kafkajs/blob/e2f34ffc8e8e37fc0d31ae51202f1147263cf0ed/src/network/connection.js#L45

**Environment:**
 - Confluent Standard Cluster
- Latest version of KafkaJS

**Comment by ankon** [comment]
Using a UUID would likely bring a dependency (which KafkaJS so far tries to avoid), and/or complexity for having such code.

Would it maybe suffice to _require_ the user to set the id instead of having a default?

Then again, the Kafka documentation has a known default of "" for the `client.id` configuration (https://kafka.apache.org/documentation/#client.id), and it seems that the default actually is some simple auto-increment value (`consumer-XXXX`). See also https://github.com/apache/kafka/pull/7944 for a discussion on changing that default.

**Comment by yarncraft** [comment]
An easy fix would be to generate your own unique id, _without any  additional dependencies_, using the _crypto module_:

```js
const crypto = require("crypto");
const id = crypto.randomBytes(16).toString("hex");
console.log(id);
```

This generates cryptographically strong pseudo-random data. It looks better to me given that _increments_ require 'state'.
Alternatively you could _require_ the user to set the id but then you will have introduced a breaking change :) 
What do you think?

**Comment by Nevon** [comment]
I think we need to get some clarity on the purpose of the client id before making any such decision. Generating a random value is not particularly hard (though I assume it should still be persistent across re-instantiation of the `Connection`, so we can't just generate it in the constructor), but the real question is whether or not it should be. Confluent's tooling certainly seems to want it to be unique across instances, but [the Kafka documentation ](https://kafka.apache.org/documentation/#client.id) seems to indicate that it should not be:

> The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a **logical application name** to be included in server-side request logging.

If we generate a random clientId per instance, then that defeats the documented purpose.

I would not want to change this before there has been a KIP to explain the rationale. For now, i individual users want to have unique clientIds per instance, they can set it themselves.

**Comment by yarncraft** [comment]
In my opinion, given that you know have knowledge of the unforeseen behavior your framework causes for Confluent users given the default settings, it seems logical to me that you should reconsider the static "kafkajs" clientID id. It is true the documentation says:

> The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.

I am not sure how a clientID of "kafkajs" helps on this end, but you could also settle for a combination of a serviceName + random appended string (f.e. `kafkaJS-15c99ef7-44dd-4f00-887d-19c8982214db`). 

Anyway I will proceed with manually introducing clientIDs in the meantime, this patches the problem on the Confluent side so that the data flow UI works again (see below). Thanks for the feedback.

<img width="514" alt="AfterFix" src="https://user-images.githubusercontent.com/15328198/99908013-4e20c900-2ce0-11eb-8dce-2ef58122d0ec.png">
