### ISSUE TITLE
[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Ha2ryZhang** [tulios/kafkajs#975]
**Describe the bug**
Crash: KafkaJSNumberOfRetriesExceeded: Converting circular structure to JSON

```json
{"level":"ERROR","timestamp":"2020-12-01T02:37:14.532Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'socket' -> object with constructor 'Socket'\n    --- property '_httpMessage' closes the circle","groupId":"influx_log_user_trend","retryCount":0,"stack":"KafkaJSNonRetriableError\n  Caused by: TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'socket' -> object with constructor 'Socket'\n    --- property '_httpMessage' closes the circle\n    at JSON.stringify (<anonymous>)\n    at /home/ccds/xx-xx/node_modules/kafkajs/src/loggers/console.js:5:24\n    at Object.error (/home/ccds/xx-xx/node_modules/kafkajs/src/loggers/index.js:16:3)\n    at Runner.processEachMessage (/home/ccds/xx-xx/node_modules/kafkajs/src/consumer/runner.js:188:23)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
```
and the restarting the consumer

**Environment:**
 - OS: centos 7
 - KafkaJS version 1.14.0
 - Kafka version: 2.11
 - NodeJS version 12

**Additional context**
I don’t know why the error is reported from time to time, but the reason is not found

**Comment by tulios** [comment]
@Ha2ryZhang KafkaJS doesn't make HTTP calls (`property '_httpMessage' closes the circle"`). This is very likely in your handler. You are probably logging the request object in some condition, but it fails since it has a circular structure.

**Comment by jholm117** [comment]
@tulios  Would you be open to modifying the default logger to use util.inspect in order to gracefully handle circular objects? Not super pressing as I can just pass a custom logger but it might help someone down the line.
