### ISSUE TITLE
Error class are not exported

### ISSUE THREAD

**Issue by lafeuil** [tulios/kafkajs#982]
**Describe the bug**
This bug report follows the previous issue #636. The errors are correctly described in the typescript definition but the error classes are not exported in the index of javascript file.

**To Reproduce**
When I test kafka error with an `instanceof` : 
```typescript
import { IResourceConfig, Admin, ConfigResourceTypes, KafkaJSProtocolError } from 'kafkajs';
...
try {
  await admin.alterConfigs({
    validateOnly: false,
    resources: [{
        type: ConfigResourceTypes.TOPIC,
        name: 'topic-name',
        configEntries: [{ name: 'cleanup.policy', value: 'compact' }]
    }]);
} catch (e) {
  if (e instanceof KafkaJSProtocolError && e.type === 'UNKNOWN_TOPIC_OR_PARTITION') {
    // do something
  } else {
    throw e;
  }
}
```
this throws the error : `TypeError: Right-hand side of 'instanceof' is not an object ` at `e instanceof KafkaJSProtocolError` in catch block. This is not a compile error because the typescript definition file is good but it is an execution error. When I log `KafkaJSProtocolError`, the output console is `undefined`.

**Expected behavior**
I think the root `index.js` file must export the errors from `src/errors.js` file.

**Comment by lafeuil** [comment]
I confirm if I export errors in root `index.js` that solves the issue : 
```
[...]
const errors = require('./src/errors');

module.exports = {
  [...],
  ...errors,
}
```

**Comment by DavidTimms** [comment]
This error is also causing problems for us.

I'm currently planning to use this workaround, though it is rather ugly:

```ts
import { KafkaJSError as _KafkaJSError } from 'kafkajs'

export const KafkaJSError =
  _KafkaJSError ?? require('kafkajs/src/errors').KafkaJSError
export type KafkaJSError = _KafkaJSError
```

**Comment by julienvincent** [comment]
Any update on this? Ran into this issue as well.
