### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by ccarcaci** [tulios/kafkajs#993]
Hello @tulios ,
I have a question.

Why the eachMessage callback is declared as `Promise<void>`?

`eachMessage?: (payload: EachMessagePayload) => Promise<void>`
https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L831

Shouldn't it be declared as:
`eachMessage?: (payload: EachMessagePayload) => void | Promise<void>`

Because if the user has no needs to call promisified functions the Promise<void> declaration is an overstatement.
Some linters could yell, for example eslint has a rule to catch these cases (https://eslint.org/docs/rules/require-await).

Thank you again for your remarkable work!

**Comment by Nevon** [comment]
The type could indeed be changed to `void | Promise<void>`. We will still await the function, so regardless it's going to get deferred to the next microtask even if it doesn't return a promise, but at least it would stop your linter yelling at you.

I suspect the original reasoning was that we couldn't think of a use-case for synchronous processing of messages, but certainly it's possible.

Is this a theoretical concern or something that's actually an issue for you?

**Comment by valavanisleonidas** [comment]
Hey I have a question about eachMessage too!! So I run the example from your website https://kafka.js.org/docs/getting-started and while I can publish and consume messages the console.log does not work. So when I run 

await consumer.run({
  eachMessage: async ({ topic, partition, message }) => {
    console.log({
      value: message.value.toString(),
    })
  },
})

I do not see any logs. I run using unit tests

Environment:

OS: [e.g. Mac OS 11.0.1]
KafkaJS version [e.g. 1.15.0]
Kafka version [e.g. 2.12-2.3.0]
NodeJS version [e.g. 10.16.3]


Thank you

**Comment by Nevon** [comment]
@valavanisleonidas Please keep issues on topic. For your specific issue, I would recommend StackOverflow or the KafkaJS Slack community, as it is not likely to be an issue with KafkaJS.

**Comment by ccarcaci** [comment]
> The type could indeed be changed to `void | Promise<void>`. We will still await the function, so regardless it's going to get deferred to the next microtask even if it doesn't return a promise, but at least it would stop your linter yelling at you.
> 
> I suspect the original reasoning was that we couldn't think of a use-case for synchronous processing of messages, but certainly it's possible.
> 
> Is this a theoretical concern or something that's actually an issue for you?

Hey @Nevon thank you for your promptly response.
It was just a technicality issue, that doesn't affect the library usage.

I think you're right, since the code inside the library awaits the eachMessage function it is better to leave the method signature as it is. It's ok to ignore the rule (for those who use require-await eslint rule) `// eslint-disable-next-line require-await`.

I've verified on the Mozilla doc and it says that it is perfectly compliant to use async without await.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Description
Execution will run non-blocking if no awaits are specified.

Hope this conversation could help someone with the same issue in future.
Thank you very much.

**Comment by Nevon** [comment]
Then I will go ahead and close the issue. Thanks for the well-researched reply!
